archesproject/arches

arches/app/models/resource.py

Checks if node belongs to a resource model rather than a branch. re #2678

Fixes KeyError when loading reports

---

arches/app/templates/javascript.htm
arches/app/views/graph.py

Uses minified jqueryui and reuses the datatype request in the GraphManagerView, re #2682

GraphManagerView changes to improve performance of graph manager

---

arches/app/models/concept.py
arches/app/utils/data_management/resources/exporter.py

Fixed issue where related concepts appeared more than once in RDM.
#2533

2533 related concept import

---

arches/app/datatypes/datatypes.py

fixes get node value display value

---

arches/app/media/js/views/resource/editor/form.js

Scrolls a form back to its top when a user switches menus, re #2600

Scrolls a form back to its top when a user switches menus, re #2600

---

arches/app/media/css/arches.css
arches/app/templates/views/mobile-survey-manager.htm

re 2658 UI positioning updates to people tab in MSM

---

arches/app/models/migrations/2886_geojson_sql_refactor.py

refactors geojson mv sql

---

arches/install/centos_core_setup.sh

Previous EPEL location no longer exists.

Update EPEL location

---

arches/app/media/css/arches.css
arches/app/templates/views/resource/edit-log.htm

re 2580: Update edit log header

---

arches/app/media/js/views/components/widgets/radio-boolean.js
arches/app/models/migrations/2532_boolean_datatype_display_value.py

Cleanup code, add migration for widgets
#2532

Cleanup code, add migration for widgets, re #2532

---

arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/models/migrations/2385_resource_instance_multiselect.py
arches/app/templates/views/components/datatypes/resource-instance.htm

enables resource model multiselect

---

arches/app/views/resource.py

Adds 'datatypes' fixing, missing datatype component bug. Also excludes unneeded properties from serialization in the resource editor. re #2679

Fixes missing datatype component bug 

---

arches/app/utils/forms.py

Prevents KeyError if a user does not enter an email in the user signup form, re #2453

Prevent KeyError in signup

---

arches/install/requirements.txt

remove requirement for Pillow, re #2910

---

arches/app/views/tileserver.py

Fixing tileserver url

---

arches/app/templates/javascript.htm

unlocalizes numbers serialized to JS

---

arches/install/requirements.txt

Upgrades python-memcached, re #2913

Upgrades memcached, re #2913

---

arches/app/views/auth.py
arches/settings.py

add the user who signs up via the web ui to a default group, re #2936

---

arches/app/templates/views/graph/graph-settings.htm

Changed "Form Icon" to "Icon" in resource model and branch settings.
#1197

Remove "form" in resource and branch settings from "form icon" #1197

---

arches/app/models/models.py

fix migration error, re #2940

---

arches/install/arches-templates/project_name/urls.py-tpl

Removes admin urls from project template.

Removes admin urls from project template.

---

arches/install/arches-templates/project_name/urls.py-tpl

Adds media urls to project urls

Adds media urls to project urls

---

arches/install/arches-templates/project_name/wsgi.py-tpl

Added call to settings.update_from_db() to the project template's wsgi file.

Updates system settings in the project template's wsgi.py file

---

arches/app/media/js/views/page-view.js

Moves click listener from binding on page load to binding after help ajax request, re #2960

Allow animated help GIFs to rerun

---

arches/install/arches-templates/project_name/settings_local.py-tpl

Updates the template files used in the `arches-project create` command

Updates project templates

---

arches/app/views/concept.py

Uses the default language from the d_languages table if only one language is identified as the default. If multiple languages are set as the default or if no languages are defined as default, the language in settings.LANGUAGE_CODE is used. re #1923

Selects default language and sorts languages in RDM language dropdowns

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/widgets/map.js
arches/app/templates/views/components/widgets/map.htm

Adds indication that a map widget config's accordion panel is closed or open. #2883

Adds indication that a map widget config's accordion panel opens

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/widgets/radio-boolean.js
arches/app/media/js/views/components/widgets/switch.js
arches/app/templates/views/components/widgets/switch.htm

Adds disabled state to the switch widget. re #2701

Adds disabled state of switch widget

---

arches/app/media/js/views/components/widgets/map.js

supports heatmap opacity

---

arches/app/media/js/views/map-layer-manager.js

better supports search layer management

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/widgets/radio-boolean.js
arches/app/media/js/views/components/widgets/switch.js
arches/app/templates/views/components/widgets/switch.htm

Adds support for switch widget disabled state. re #2701

Allows disabled state of switch widget.

---

arches/app/media/css/arches.css
arches/app/templates/views/components/widgets/map.htm

Allows clicks to the caret element to bubble to the accordion panel by properly nesting elements. re #2883

Syncs accordion panel clicks with caret clicks.

---

arches/app/media/css/arches.css
arches/app/templates/views/components/widgets/map.htm

Syncs accordion panel clicks with caret clicks. re #2883

Syncs accordion panel clicks with caret clicks

---

arches/app/media/js/views/components/simple-switch.js
arches/app/media/js/views/graph/card-configuration/card-component-form.js
arches/app/media/js/views/graph/report-editor/report-editor-form.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/simple-switch.htm
arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm
arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm
arches/app/templates/views/graph/report-editor/report-editor-form.htm

Replaces use of the switch widget with a new `simple-switch` component which renders a 2-way boolean switch. re #2979

Replace 3-way switch with 2 way

---

arches/app/media/js/views/components/simple-switch.js
arches/app/media/js/views/graph/card-configuration/card-component-form.js
arches/app/media/js/views/graph/report-editor/report-editor-form.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/simple-switch.htm
arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm
arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm
arches/app/templates/views/graph/report-editor/report-editor-form.htm

Replaces use of the switch widget with a new simple-switch component which renders a 2-way boolean switch. re #2979

2979 move 2-way switch to master

---

package.json
yarn.lock

fixing turf dependency

---

.yarnrc
arches/install/arches-templates/project_name/.yarnrc
package.json
yarn.lock

more fixes for yarn

---

arches/app/models/resource.py
arches/app/models/tile.py
arches/app/templates/views/edit-history.htm
arches/app/views/resource.py
arches/app/views/tile.py
arches/management/commands/packages.py

Replaces list of newly added resource instances in Recent Edits table with records of recent edits. re #2293.

2293 4.1.x recent edits table

---

arches/app/templates/views/edit-history.htm
arches/app/views/resource.py

Disables links within edit history to deleted resource instances. re #2293

Disable deleted resource links in edit history table

---

arches/app/models/tile.py
arches/app/views/resource.py

Fixes missing edit types re #2293

Fixes missing edit types re #2293

---

arches/app/templates/rdm.htm

Moves thesauri and collection tool menus into a single dropdown. re #2350

Moves thesauri and collection tool menus into a single dropdown

---

arches/app/media/css/arches.css

https://github.com/archesproject/arches/pull/2762, but for 4.1.x branch.

Add min-height to flex class to allow scrollbars in firefox #1989

---

arches/app/models/graph.py
arches/app/views/graph.py

Fixes card's 'editable' status and resolves bug preventing users from adding cards in the card manager. re #3026, #3027

Moves fixes for #3026 and #3027 from 4.1.x to master

---

arches/app/datatypes/concept_types.py
arches/app/datatypes/datatypes.py
arches/app/models/resource.py
arches/app/models/tile.py
arches/app/search/mappings.py
arches/app/views/resource.py
arches/app/views/search.py

Adds a provisional flag to the search mappings and fixes the display of deleted tiles in the recent edit history. re #2975, #2293

2975 provisional tile search

---

arches/app/views/auth.py

add 'Access-Control-Allow-Origin' for get_token endpoint, re #3050

---

docker/Readme.md

Documentation patch - suggest working default for letsencrypt, highlighting need to set production=True
- [x ] I have added necessary documentation (if appropriate)

Added some text around letsencrypt setup for production environments

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/views/resource/editor.js
arches/app/media/js/views/resource/editor/form.js
arches/app/models/forms.py
arches/app/models/tile.py
arches/app/templates/javascript.htm
arches/app/templates/views/resource/editor.htm
arches/app/templates/views/resource/editor/form.htm
arches/app/templates/views/resource/editor/provisional-tile-manager.htm
arches/app/views/resource.py
arches/app/views/search.py
arches/app/views/tile.py
arches/app/views/user.py
arches/urls.py

Adds the QA workflow to the resource editor

2974 provisional in editor

---

arches/app/models/tile.py
arches/app/templates/views/edit-history.htm
arches/app/views/tile.py

Fixes redundant edit log record when saving provisional information. re #2974

Fixes redundant edit log record when saving provisional information

---

arches/app/media/js/models/tile.js

Fixes tile save in safari and internet explorer, re #2534

Fixes tile save in safari and internet explorer, re #2534

---

docker/entrypoint.sh

Solves https://github.com/archesproject/arches/issues/3030

Docker: Respect Project when running arbitrary commands

---

arches/management/commands/packages.py

Allows user to force graph and system settings overwrites when loading package by using the -y argument re #2988.

Allows user to force defaults in load package command

---

arches/app/media/css/arches.css
arches/app/media/js/views/form.js
arches/app/media/js/views/resource/editor/form.js
arches/app/templates/views/resource/editor/form.htm

Adds border around selected provisional tile. re #2974

Adds border around selected QA tile

---

arches/install/requirements.txt

update python dependencies, re #2998, re #3039

---

arches/install/ci_install/install_arches.sh

Added -y to allow package load. re #2988

Added -y to allow package load. re #2988

---

arches/app/templates/views/graph/permission-manager/identity-list.htm

Reverting back to the previous user list design, re #2879

Reverting back to the previous user list design

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/dragDrop.js
arches/app/media/js/views/graph/graph-manager/branch-list.js
arches/app/models/graph.py
arches/app/templates/views/graph/card-manager/card-list.htm
arches/app/templates/views/graph/graph-manager/branch-list.htm
arches/app/views/graph.py

Makes new branches active by default. Displays inactive branches in the UI as disabled. re #2903

2903 remove inactive branch option

---

arches/app/media/css/arches.css
arches/app/templates/views/components/widgets/map.htm
arches/app/templates/views/search/search-results.htm

re:3093 provisional tile ui

---

arches/app/views/main.py

Fixes ALLOWED_POPUP_HOSTS setting name. re #2549

---

docs/releases/4.1.0.md

small fix in the upgrade commands listed in the 4.1.0 release notes, based on this forum post
https://groups.google.com/forum/?hl=en#!topic/archesproject/33TXJZYaGSw

add --no-binary argument to pip upgrade command

---

arches/db/system_settings/Arches_System_Settings_Model.json

Updated settings graph minus the CRM ontology. #2874

---

arches/app/datatypes/datatypes.py
arches/app/models/tile.py
arches/app/utils/data_management/resources/formats/archesfile.py
arches/app/utils/data_management/resources/formats/csvfile.py

Enables import and export of the resource instance and resource instance list datatypes to both 'csv' and 'json' formats re #2967 #3058

2967 resource inst datatype import

---

arches/app/models/project.py
arches/app/templates/pouch_demo.htm
arches/app/views/api.py
arches/app/views/mobile_survey.py
arches/app/views/pouch_demo.py
arches/app/views/tile.py
arches/install/requirements.txt
arches/management/commands/load_ontology.py
arches/settings.py
arches/urls.py

3106 integrate couch

---

arches/app/views/base.py
arches/app/views/graph.py
arches/app/views/map.py
arches/app/views/mobile_survey.py
arches/app/views/resource.py
arches/app/views/search.py

Moves map related context data out of BaseManagerView and into the new, MapBaseManagerView. re #3113

Moves map related context data out of BaseManagerView

---

arches/app/media/css/arches.css
arches/app/templates/views/graph/form-settings.htm

Moved offending element, re #3035

---

arches/app/models/concept.py
arches/app/models/graph.py
arches/app/models/mobile_survey.py
arches/app/templates/views/report-templates/default.htm
arches/app/views/base.py
arches/app/views/graph.py
arches/app/views/map.py
arches/app/views/mobile_survey.py
arches/app/views/resource.py
arches/app/views/tile.py
arches/urls.py

Reduces the number of redundant database queries.

3015 optimize queries

---

arches/management/commands/packages.py
arches/management/commands/utils.py

Allows users to import business data using a relative path. re #2947

Allows users to import business data using a relative path

---

arches/app/utils/middleware.py
arches/app/views/api.py
arches/app/views/auth.py
arches/install/requirements.txt
arches/settings.py

3050 api dev

---

arches/app/media/css/arches.css
arches/app/media/js/views/search-base-manager.js
arches/app/templates/views/list.htm
arches/app/views/search.py

Prevents scrollbars from appearing beneath the header element in list of groups/users. re #2853 
Also adds the resource models back in the resource filter search list.

2853 fix scrollbar heights

---

arches/install/ci_install/ci_ubuntu_xenial_setup.sh
arches/install/ubuntu_xenial_setup.sh
docker-compose-test.yml
docker-compose.yml
docker/settings_local.py

3103 couch db install

---

arches/app/templates/views/mobile-survey-manager/identity-list.htm
arches/app/templates/views/mobile-survey-manager/resource-list.htm

Fixes list header position in the Mobile Survey's resource and people tabs. re #2853

Fixes list header position in Mobile Survey's resource and people tabs

---

arches/app/media/js/views/graph.js
arches/app/models/graph.py
arches/app/templates/views/graph.htm
arches/app/views/graph.py
arches/management/commands/packages.py
arches/settings.py
tests/models/graph_tests.py
tests/test_settings.py

Prevents users from deleting the Node and Node/Nodetype graphs. re #907

Prevents users from deleting the Node and Node/Nodetype graphs

---

arches/app/media/js/models/mobile-survey.js
arches/app/media/js/views/mobile-survey-manager.js
arches/app/media/js/views/resource/editor/form.js
arches/app/views/mobile_survey.py

Notifies users when couchdb service is available re #3131

3131 couchdb error notification

---

arches/app/media/css/arches.css
arches/app/templates/views/graph/permission-manager.htm

Hides container scrollbar in permissions manager identity list. re #2853

Fixes permissions manager user/group list scrollbars

---

arches/app/templates/views/mobile-survey-manager.htm

Disables delete button when selected survey is active. re #3143

Disables delete button when selected survey is active.

---

arches/app/views/mobile_survey.py

Handles for errors when the server is created as well as when the database is accessed in the transaction block.  re #3131

Handles for errors other than ResourceNotFound

---

arches/app/media/css/arches.css
arches/app/templates/views/graph/graph-manager.htm

Fixes scrollbar issues in the graph manager caused by changes in the permissions manager. re #2853

Fixes unnecessary scrollbars in graph designer

---

arches/app/media/css/arches.css
arches/app/templates/views/graph/graph-manager.htm

Fixes scrollbar issues in the graph manager caused by changes in the permissions manager. re #2853

Fixes scrollbar issues in the graph manager

---

arches/app/views/mobile_survey.py

Basic loading of tiles into a couch db. Does not yet filter tiles based on properties such as survey bounds. re #3147

Loads/updates tile data on save of a survey. re #3147

---

arches/app/media/css/arches.css
arches/app/views/mobile_survey.py
arches/management/commands/mobile.py

Fixes resource instance tile filter. Fixes css issue in msm card list. Adds command to clear unwanted couch databases. re #3167

3147 save resource tiles to couch

---

.travis.yml
arches/app/views/mobile_survey.py
arches/install/ci_install/setup_couch.sh
tests/fixtures/data/mobile_survey_test_data.json
tests/fixtures/resource_graphs/Mobile Survey Test.json
tests/views/mobile_survey_tests.py

Adds testing for mobile_surveys/couch

Adds tests for mobile surveys / couchdb

---

arches/app/datatypes/datatypes.py

fix for node value save issue

---

arches/app/utils/data_management/resource_graphs/exporter.py
arches/app/utils/data_management/resources/formats/csvfile.py
arches/app/views/graph.py
arches/management/commands/packages.py
arches/settings.py

Add ability to import/export node value datatype. See comments 3059 and 3060 for instructions.
#3059, #3060 

Add ability to import and export node value datatype, re #3059, #3060

---

arches/app/models/card.py
arches/app/models/tile.py
arches/app/views/base.py
arches/app/views/resource.py
arches/app/views/search.py
arches/app/views/tileserver.py

Replaces id with object in has_perm calls.

Uses object rather than id in has_perm calls.

---

arches/app/models/tile.py

Improved syntax of Tile proxy model's user_owns_provisional method. re #2891

Refactor of Tile model's user_owns_provisional method. re #2891

---

arches/app/views/search.py

Fixes missing icons in search results, missing date nodes in time filter dropdown and missing facets in advanced search. re #3105

3105 fix search optimization bugs

---

arches/app/media/css/arches.css
arches/app/templates/change_password.htm

fixing change password buttons

---

arches/app/media/js/views/resource/editor/form.js

fixing syntax in form.js

---

arches/app/media/js/views/resource/editor/form.js

IE System settings bug

---

arches/app/utils/geo_utils.py

Fixes parsing of geom in geo_utils.convert_multipart_to_singlepart

Fixes parsing of geom in geo_utils.convert_multipart_to_singlepart

---

arches/app/views/graph.py

Moves logic in MapGraphBaseView into Views where it is used. re #3113

Removes MapGraphBaseView

---

arches/app/media/js/views/edit-history.js
arches/app/templates/views/edit-history.htm

fix sorting on date in the edit log

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/resizable-sidepanel.js
arches/app/templates/views/resource/new-editor.htm

refactoring

---

arches/app/media/js/views/components/functions/primary-descriptors.js
arches/app/templates/views/components/functions/primary-descriptors.htm

Add ability to clear nodegroup/card from primary descriptor functions.
#3227 

3227 clear primary descriptor nodegroup

---

arches/app/models/resource.py
arches/app/models/tile.py
arches/app/views/search.py
arches/management/commands/packages.py
arches/settings.py

Prevents system settings from getting indexed and allows user to specify the projection used to calculate buffers re #3244, #3248

4.1.x system settings in search and spatial analysis setting

---

arches/app/models/migrations/0003_40b4.py
arches/app/models/migrations/2891_adds_tile_provisional_json.py
arches/app/models/migrations/2891_tile_qa_schema.py

Removes command to load the system settings instance during a migration. Also removes the addition and deletion of the provisional model.

Resolves migration errors

---

arches/app/datatypes/datatypes.py
arches/app/media/js/bindings/datepicker.js
arches/app/media/js/views/search/time-filter.js
arches/app/templates/views/search/time-filter.htm
arches/app/utils/date_utils.py
arches/app/views/search.py
tests/utils/date_utils_tests.py

3261 negative dates

---

arches/app/views/search.py
arches/settings.py

implement a new setting variable to use for the SRID of the map buffer operation.
#3258 

implement buffer epsg code as new setting #3258

---

arches/app/media/css/arches.css
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-manager/new-node-form.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/new-graph-settings.htm
arches/app/templates/views/new-node-form.htm

Adds initial node editing page. re #3202

Node editing page

---

arches/management/commands/packages.py

Add ability to order business data load in a package.
Searches package_config json for 'business_data_files' array and reads files in order that they are presented in this array.
#3268 

Add ability to order business data loading packages, re #3268

---

docker/entrypoint.sh

Add CouchDB system database creation on setup.
Add wait for Elasticsearch to be up
Parameterize the Postgres user name.
#3265 
-   [X] Unit tests pass locally with my changes

3265 docker couchdb create system databases

---

arches/app/media/js/models/graph.js
arches/app/media/js/models/node.js
arches/app/media/js/viewmodels/graph-settings.js
arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph-designer.htm
arches/app/views/base.py
arches/app/views/graph.py

Fixes dirty state issues preventing users from switching nodes in the graph tree.

3202 new node editing page

---

arches/app/media/js/views/components/datatypes/concept.js
arches/app/templates/javascript.htm
arches/app/views/concept.py
arches/app/views/graph.py
arches/urls.py

Loads concept collections using ajax when a user selects a node with the concept datatype. re #3202

Fixes invalid dirty state of concept datatype nodes

---

arches/app/media/css/arches.css
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/new-node-form.htm

Enables node reset and save and improves styling. re #3202

Enables node reset/save

---

arches/app/media/js/views/components/datatypes/concept.js

Fixes loading of the correct concept collection when a concept node is loaded in the edit node form, re #3202

Fixes async concept collection loading in concept collection datatype 

---

arches/app/media/js/models/graph.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-tree.js
arches/app/models/graph.py
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-tree.htm

3201 graph tree

---

arches/app/media/js/views/graph.js
arches/app/models/graph.py
arches/app/views/graph.py

Displays error if a user tries to delete a resource model with instances. re #3282

Protected graph error message

---

arches/app/media/js/views/components/widgets/map.js
arches/app/templates/views/components/widgets/map.htm

Changes variable name for popup content from 'arches_description' to 'feature_info_content' re #2549

Custom popup property name change

---

arches/app/media/css/arches.css
arches/app/templates/views/new-node-form.htm

Adds parent node class to semantics element and formats semantics details. re #3202

Improves semantics display in node form

---

arches/app/media/js/viewmodels/domain-widget.js
arches/app/media/js/viewmodels/widget.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

new editor tree

---

arches/app/media/css/arches.css
arches/app/media/css/tree/tree.css
arches/app/media/js/views/graph/graph-tree.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-tree.htm

add button to toggle branch-list view, re #3201

---

arches/app/datatypes/concept_types.py

Remove warning from json import when trying to import null concept values.
#3308 

3308 null concept validation

---

arches/app/datatypes/datatypes.py
arches/app/media/js/bindings/time-wheel.js
arches/app/search/time_wheel.py
arches/app/utils/data_management/resources/formats/csvfile.py
arches/app/views/search.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Makes time wheel caching and configuration options available to an admin to improve time wheel performance and display. re #3306, #3343

time wheel performance

---

arches/app/datatypes/concept_types.py

Adds provisional flag for date ranges indexed from concept dates. re #3353

Fixes search result count for users without reviewer status

---

arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm

adding tree filter to new resource editor

---

arches/app/media/css/arches.css
arches/app/media/js/models/graph.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-manager/branch-list.js
arches/app/media/js/views/graph/graph-manager/node-form.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-manager/branch-list.htm
arches/app/views/graph.py
arches/urls.py

3200 branch list

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/resource/new-editor.htm

support for saving tiles in new editor

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/resource/new-editor.htm

restyles, adds support for tile delete

---

arches/install/arches-templates/project_name/settings.py-tpl
arches/management/commands/packages.py

Loads a package settings file to a project. re #3377

package settings

---

arches/management/commands/packages.py

Adds or updates package_settings when a user creates or updates a package from a project. re #3377

Exports package settings when updating or creating a package re #3377

---

arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py
arches/app/views/tile.py
arches/urls.py

applies permissions in new editor

---

README.md

fix some doc links and general update

fix some doc links and general update

---

arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

new editor sortorder

---

arches/install/arches-templates/project_name/settings_local.py-tpl

Adds ANALYSIS_COORDINATE_SYSTEM_SRID to settings_local template

4.1.x project template update

---

arches/app/media/js/views/resource/new-editor.js
arches/app/templates/navbar/new-resource-manage-menu.htm
arches/app/views/resource.py

adds manage menu to new editor

---

arches/app/media/js/views/resource/new-editor.js
arches/app/templates/javascript.htm

fix for edit history link in new editor

---

arches/app/media/css/arches.css
arches/app/media/js/views/base-manager.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/base-manager.htm
arches/app/templates/javascript.htm

re: #3222
adds support for expanded nav via click on main header icon

expanded nav

---

arches/app/media/js/views/resource/new-editor.js

sets default selection in new editor

---

arches/app/templates/views/mobile-survey-manager.htm

fix mobile surveys not showing up in the list, re #3414

---

arches/app/views/search.py

Applies permitted nodegroup filter to geo aggregation. re #2492

Applies permitted nodegroup filter to aggregation. re #2492

---

arches/app/templates/base-manager.htm

Hides link to the mobile survey manager. re #3418

Comments out link to mobile survey manager

---

arches/app/templates/base-manager.htm

using ? icon when unavailable

---

arches/app/datatypes/datatypes.py

fixes for deactivated resource layers

---

arches/app/media/js/viewmodels/node-value-select.js

fixes error w/ node value

---

arches/app/views/api.py
tests/views/api_tests.py

3309 normalize params

---

arches/settings.py
arches/urls.py

adding api url slug

---

arches/app/media/js/views/components/widgets/map.js

Moves commits from master to allow user to style click and hover layers in overlays. re #3375

3375 4.2.x overlay hover style

---

arches/settings.py
arches/urls.py

reverting api slug

---

arches/app/media/js/bindings/color-picker.js

Updates color when user resets graph settings, re #3199

Updates color when user resets graph settings

---

arches/app/media/js/viewmodels/node-value-select.js

Fixes node datatype dropdown error in card manager. re #3219

Fixes node datatype dropdown error in card manager

---

arches/app/media/js/viewmodels/node-value-select.js

Fixes node datatype dropdown error in card manager. re #3219

Fixes node datatype dropdown error in card manager. re #3219

---

arches/app/utils/data_management/resources/formats/csvfile.py

fix missing ref to GraphXMapping, re #3450

---

arches/app/media/js/views/graph.js
arches/app/models/graph.py
arches/app/templates/views/graph.htm
arches/app/views/graph.py
arches/install/arches-templates/project_name/settings_local.py-tpl
arches/management/commands/packages.py
arches/settings.py
tests/test_settings.py

Remove references to protected graphs.
#3443 

Remove references to protected graphs, re #3443

---

arches/app/datatypes/datatypes.py
arches/app/media/js/views/search/search-results.js
arches/app/models/tile.py
arches/app/templates/views/search/search-results.htm
arches/app/views/search.py

Prevents provisional edit from being applied to parent tiles that do not collect data, and prevents provisional flag from being displayed to provisional users in search. re #3472, #3473

3472 4.2.x provisional edit bug

---

arches/management/commands/mobile.py

Fixes CLI management commands for CouchDB
#3238 
-   [X] Unit tests pass locally with my changes

Fix CouchDB management commands re: 3238

---

arches/app/media/css/tree/tree.css
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/resource/new-editor.htm

Add highlight to all nodes/cards/tiles in the path of a selected node.
#3434 

3434 graph/instance tree highlight

---

arches/app/utils/data_management/resources/formats/rdffile.py
arches/app/utils/decorators.py
arches/app/utils/permission_backend.py
arches/app/views/api.py

3313 resource endpoint

---

README.md

Just noticed this syntax error.

fix url syntax

---

arches/app/media/css/arches.css
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm

driving selection via breadcrumbs in new resource editor

---

arches/app/media/css/arches.css

resource editor scrolling

---

arches/app/media/js/views/components/datatypes/resource-instance.js

Populates resource model list in card and node config form. re #3476

Fixes missing resource models in resource model list, re #3476

---

arches/app/media/js/viewmodels/node-value-select.js

Makes node-value datatype values visible in reports. re #3477

Makes node-value datatype values visible in reports. 

---

arches/app/views/api.py

support for accept header in API

---

arches/app/media/js/views/components/widgets/map.js

Fixes issues with tracking the filter state of hover and click style layers. re #3375

3375 overlay hover style

---

arches/app/templates/views/resource.htm

Fixes create resource link in Resource Manager. re #3518

Fixes create resource link in Resource Manager. re #3518

---

arches/app/templates/login.htm

Create new account link now opens in a new tab.
#2739 

Make 'Create a New Account' link open in a new tab, re #2739

---

arches/app/views/graph.py

fixes export branch error

---

.travis.yml
arches/install/ci_install/install_arches.sh

Upgrades the QA machine to use the latest stable branch (stable/4.2.x)
#3560 
*   Suggested by: @chiatt

3560 update qa 4.2

---

arches/app/media/css/tree/tree.css
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/resource/new-editor.htm

Moving the Search Filter for the Graph Designer and New Resource page closer to the tree of nodes.
#3552 
*   Designed by: @dwuthrich

3552 move graph filter

---

arches/app/templates/views/resource/new-editor.htm

Resource Editor: Remove excess whitespace
#3555 
*   Designed by: @dwuthrich

Resource Editor: Remove excess whitespace #3555

---

arches/app/views/graph.py

Fixing a regression that happened when optimizing/speeding up Arches 
#3572 
*   Found by: @dwuthrich

Graph Manager: Fix Fast Graph Switcher RE: #3572

---

arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph-designer.htm

Add the ability to quickly jump to a different graph in the Graph Designer
#3553 

Graph Designer: Update Graph Switcher RE: 3553

---

arches/app/templates/views/graph/graph-designer/graph-settings.htm

Move Description card up in Graph Settings 
#3567 
*   Designed by: @dwuthrich

Graph Designer: Move Description card up in Graph Settings #3567

---

arches/app/templates/views/graph/graph-designer/graph-tree.htm

Graph Designer: Fix delete node bug
#3585

Graph Designer: Fix delete node bug RE: #3585

---

arches/app/utils/decorators.py
arches/app/utils/permission_backend.py
arches/app/views/api.py

Adding specific permissions for concept API endpoint 
#3399 

API concept endpoint security fix RE: #3399

---

releases/4.1.1.md

Updated the link to the preferred documentation location.

update documentation link

---

arches/app/media/js/models/graph.js
arches/app/models/graph.py
tests/models/graph_tests.py

Remove commented code.
Remove commented code re #3397 
#3397 

Remove commented code, re #3397

---

arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/resource/new-editor.htm

refactors card tree in new editor

---

arches/app/views/api.py

Removes the method_decorator to allow clear 404 and 500 messages for the Concepts API endpoint
#3399 

API Concepts: Remove method_decorator to allow 404 & 500 messages #3399

---

arches/app/media/js/views/mobile-survey-manager.js
arches/app/utils/couch.py
arches/app/views/mobile_survey.py

Failures in connecting to CouchDB would not bubble up to the UI for the user to understand what was happening. This should fix that
#3131

3131 alert on couch failures

---

arches/app/views/api.py

fixes error in getting format

---

arches/app/models/graph.py

clears subtitle, description & author

---

arches/management/commands/packages.py

This just makes it easier to manage indexing operations during development.

allow indexing of only resources or only concepts

---

arches/app/media/js/views/graph-designer.js
arches/app/models/graph.py
arches/app/templates/views/graph-designer.htm
arches/app/views/graph.py
tests/models/graph_tests.py

Implement proper UI alerts for issues in saving nodes in the new Graph Designer
#3554

3554 node saving alerts

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/components/widgets/map.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm

migrates card viewmodel out of editor

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph-designer.htm
arches/app/views/graph.py

adds initial card designer tree

---

arches/app/media/js/viewmodels/card.js
arches/app/templates/views/components/cards/default.htm

makes widgets selectable in card tree

---

arches/app/media/css/arches.css
arches/app/templates/views/components/cards/default.htm

Fixes display of map widget in card component when wrapped in a flex container.

Fixes display of map widget in card component

---

arches/app/models/graph.py
arches/app/views/graph.py
arches/install/requirements.txt
arches/management/commands/resources.py

Allow the deletion of a Resource Model with instances associated with it.
#3574 

3574 delete resource instances

---

arches/app/media/js/viewmodels/graph-settings.js
arches/app/views/graph.py

Fixes issue with graph name and relatable resources not resetting back to proper their value after graph is saved. re #3199

Fixes issue with graph name and relatable resources not resetting properly

---

arches/app/models/graph.py
tests/models/graph_tests.py

Add an alert for an undefined ontology property in the new Graph Designer. 
#3611 

Add Alert for an undefined ontology property #3611

---

arches/management/commands/resources.py

Fix broken command line remove_resources #3574
#3574 
*   Found by: @ryan86

Fix broken command line remove_resources #3574

---

arches/app/media/js/models/graph.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/graph/graph-manager/graph-base.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm

3546 integrate d3graph

---

arches/app/media/css/arches.css
arches/app/media/css/tree/tree.css
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/components/datatypes/domain-value.htm
arches/app/templates/views/graph/graph-designer/graph-settings.htm
arches/app/templates/views/graph/graph-designer/node-form.htm
arches/app/templates/views/resource/new-editor.htm

Provisional edits ui updates

---

arches/app/media/js/views/graph/graph-designer/card-tree.js

fix graph designer page hangs when creating a new graph, re #3633

---

arches/app/media/js/viewmodels/card.js
arches/app/views/tileserver.py

Updates tile order  re #3583. Also allows CACHE_SEED_BOUNDS setting to take either geojson or a tuple. re #3631

Update tile order and fix CACHE_SEED_BOUNDS setting

---

arches/app/media/css/tree/tree.css
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/card-tree.htm

Migrates the HTML for the Card Tree to a template, fixes some CSS to allow the jstree header to stay centered, including the search bar.
#3636 
*   Found by: @apeters

3636 card tree template

---

arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js

expand node in tree when selecting node in d3 graph, re #3546

---

arches/app/media/css/arches.css
arches/app/media/js/views/resource/new-editor.js
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

Updates pre release manual UI testing script with section assignments

Manual UI Testing

---

releases/pre-4.3.0.md

Cruft removal and formatting edits

Manual UI testing script clean-up

---

arches/app/media/css/arches.css
arches/app/media/js/views/resource/new-editor.js
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

Reverts commits breaking search merged in at f53a495b23a7b6de466563e3568b3571576c6e8d. re #3604

Revert unintended commits

---

arches/app/media/css/arches.css

Displays left panel in resource editor above force directed graph panel. re #3568

Displays left panel in resource editor above force directed graph

---

arches/app/media/js/views/resource/new-editor.js
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

Prevents error if there are no valid properties to relate two resources. re #3606

Prevents error if there are no valid properties to relate resources

---

arches/app/media/css/arches.css
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/templates/views/resource/related-resources/related-resources-manager.htm

Adds a Splash Screen to those who can add Related Resources.
#3605 
*   Designed by: @dwuthrich

3605 related resource splash

---

arches/app/templates/views/graph-designer.htm

Add Done button to the new Graph Designer
#3663 

3663 graph designer done button

---

arches/app/models/models.py

Remove the requirement to create a Menu for a Graph before creating Resource Instances
#3644 

Remove menu requirement for resource instance #3644

---

arches/app/templates/views/graph/graph-designer/card-configuration.htm

fix broken knockout ref, re #3559

---

arches/app/views/resource.py
arches/urls.py

Fixes regression preventing users from deleting instances from the new resource editor UI. re #3679

Resource instance deletion

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/permission-designer.js
arches/app/media/js/views/graph/permission-manager.js
arches/app/media/js/views/graph/permission-manager/permission-settings-form.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm
arches/app/templates/views/graph/graph-designer/identity-list.htm
arches/app/templates/views/graph/graph-designer/permission-settings-form.htm
arches/app/views/graph.py
arches/urls.py

Adds an version of the permissions manager in the new graph designer.  re #3534

3534 permissions manager in new graph designer

---

arches/app/media/css/arches.css
arches/app/views/graph.py

Fixes errors in the old permission manager (caused by implementation of the new permission manager) until the new one fully adopted re #3534.

Fixes breaking changes in old permission manager until new one is completed

---

releases/pre-4.3.0.md

Moves changes to pre-release testing script from master to stable/4.3

43 pre release testing - moves changes to pre-release testing script from master to stable/4.3

---

.eslintrc.js
arches/app/media/js/views/graph-designer.js

lints more (and improves rules)

---

.eslintrc.js
arches/app/media/js/views/graph/function-manager/applied-function-list.js
arches/app/media/js/views/graph/function-manager/function-list.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/graph/graph-manager/branch-list.js
arches/app/media/js/views/graph/graph-manager/node-list.js
arches/app/media/js/views/graph/permission-manager/grouped-node-list.js
arches/app/media/js/views/graph/permission-manager/identity-list.js
arches/app/media/js/views/list.js
arches/app/media/js/views/mobile-survey-manager/identity-list.js
arches/app/media/js/views/mobile-survey-manager/resource-list.js
arches/app/media/js/views/provisional-history-list.js
arches/app/media/js/views/resource/editor/form-list.js
arches/app/media/js/views/resource/related-resources-node-list.js
arches/app/templates/views/graph/graph-designer/identity-list.htm
arches/app/templates/views/graph/permission-manager/grouped-node-list.htm
arches/app/templates/views/list.htm

more eslinting

---

arches/app/templates/base-manager.htm
arches/app/templates/views/system-settings.htm
arches/urls.py

Moves system settings to new designer/editor, re #3696

Moves system settings to new designer

---

arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm
arches/app/templates/views/graph/graph-designer/card-tree.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/resource/new-editor.htm

Adds missing 'trans' tags in new graph designer.

Adds missing trans tags in new designer

---

arches/app/templates/views/system-settings.htm

Updates system settings template following changes to the Card Manager re #3696

Updates system settings template following changes to the Card Manager

---

arches/management/commands/packages.py

Please see https://github.com/archesproject/arches/pull/3529
This is a cherry-pick of the same commit into a branch that was made from master.

add operation for deleting mapbox layer #3526

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/templates/views/graph-designer.htm

card preview

---

arches/app/media/css/arches.css
arches/app/templates/base-manager.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/provisional-history-list.htm
arches/app/templates/views/resource/new-editor.htm

re: 3729 Provisional Edits panel presentation updates

---

arches/app/views/api.py

Add Delete ability for resource API endpoint
#3709

Add Delete ability for Resource API Endpoint #3709

---

arches/app/models/graph.py
arches/app/views/graph.py

3725 delete invalid graph

---

.eslintrc.js
arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/tile.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/list.js
arches/app/media/js/views/resource/new-editor.js

expands tree to show highlighted items

---

arches/app/media/css/arches.css
arches/app/media/js/models/card.js
arches/app/media/js/models/report.js
arches/app/media/js/views/graph/report-editor.js
arches/app/media/js/views/graph/report-manager.js
arches/app/media/js/views/resource/report.js
arches/app/templates/views/report-templates/default.htm
arches/app/views/resource.py

3726 reports

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/tile.js
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph/graph-designer/card-tree.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/resource/new-editor.htm

improved tree filters

---

arches/app/media/js/views/graph-designer.js

Fixes card selection error when creating a new resource model.

Fixes error when creating a new resource model.

---

arches/app/templates/views/components/cards/default.htm

Fixes provisional edit error when editing a card, re #3385

Fixes provisional edit error when editing a card

---

arches/app/media/css/arches.css
arches/app/templates/views/resource/new-editor.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm
arches/app/templates/views/system-settings.htm

Fixed css issues with the related resource header. re #3607

3607 related resource instance search

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/tile.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/resource/new-editor.js

unifies tree default states

---

arches/app/media/css/arches.css
arches/app/templates/views/components/datatypes/concept.htm
arches/app/templates/views/components/widgets/datepicker.htm
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/card-configuration.htm
arches/app/templates/views/graph/graph-designer/widget-configuration.htm

re: #3736 Match styles for card and node configuration in Card Manager 

---

arches/app/utils/data_management/resource_graphs/importer.py

Removes the requirement of associated cards with a Graph import.
#3710 

3710 graph import error

---

arches/app/media/js/viewmodels/tile.js

Allows dirty state to be activated on new tiles. re #3763

Allows dirty state to be activated on new tiles.

---

arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm

Notifies a user if the card they are attempting to edit has no cards available (because the user has no write permissions to any cards). re #3769

Notifies users in the resource editor if no cards are available

---

arches/app/media/css/arches.css
arches/app/media/css/tree/tree.css
arches/app/templates/views/graph/graph-designer/widget-configuration.htm
arches/app/templates/views/resource/new-editor.htm

#3736 Match Card and Node panels in Card Manager UI

---

arches/app/media/js/models/report.js

fixes bug with report manager links

---

arches/app/media/js/bindings/slide.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph.js
arches/app/media/js/views/page-view.js
arches/app/media/js/views/resource.js
arches/app/media/js/views/resource/new-editor.js
arches/app/media/js/views/search-base-manager.js
arches/app/media/js/views/user-profile-manager.js
arches/app/templates/base-manager.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm
arches/app/templates/views/user-profile-manager.htm
arches/app/views/graph.py

Adds an observable 'helpTemplate' to the page-view view model to control which template is displayed in the help panel content. re #3712

3712 in app help

---

releases/pre-4.3.0.md

UI test result reporting and an update of the arches upgrade steps from 4.2 to 4.3

V43 testing cnh

---

arches/app/media/js/models/card.js
arches/app/media/js/models/report.js
arches/app/media/js/views/graph/report-editor.js
arches/app/media/js/views/graph/report-manager.js
arches/app/media/js/views/resource/report.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph/report-editor.htm
arches/app/templates/views/report-templates/default.htm
arches/app/templates/views/resource/report.htm
arches/app/views/graph.py
arches/app/views/resource.py

adds report card components

---

arches/app/templates/views/graph-designer.htm

Hides permissions tab when a user is editing a branch

Hides permissions tab when a user is editing a branch. re #3795

---

arches/app/templates/views/components/cards/default.htm

Adds unselectable widgets in permissions card tree. re #3793

Adds unselectable widgets in permissions card tree. re #3793

---

arches/app/media/css/arches.css
arches/app/templates/views/components/cards/default.htm

Lightens color, removes pointer and hover event. re #3793

Style changes to permissions card tree widgets

---

arches/app/media/css/arches.css
arches/app/templates/views/components/cards/default.htm

Prevent permission icons from wrapping re #3793

Prevent permission icons from wrapping

---

arches/app/media/js/viewmodels/graph-settings.js
arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph/graph-designer/graph-settings.htm
arches/app/templates/views/graph/graph-designer/node-form.htm

3778 show class and datatype in graph manager

---

arches/app/views/base.py
arches/app/views/graph.py

Removes print statements and deprecated code. re #3601

Removes print statements and deprecated code.

---

arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph/graph-designer/graph-settings.htm

Make graph.ontology computed #3778 and #3825

---

arches/app/media/js/views/graph/graph-designer/graph-tree.js

Remove Parenthesis if there is no ontology set in the Node Treet
#3783 

Change node name display in the Graph Tree #3783

---

arches/app/templates/views/components/cards/default.htm

Change icon in Card Tree to the widget datatype icon
#3791 

Change icon in Card Tree to the widget datatype icon #3791

---

arches/app/media/css/arches.css
arches/app/media/css/tree/tree.css
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/templates/views/components/cards/default.htm

Add Hover and Select state congruency between the widget in the card tree and the preview form.
#3785 

3785 card manager widget hover and select state

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/widgets/map.js
arches/app/templates/views/components/cards/default.htm

Temporarily removes the click binding handler from the widget's parent element to prevent issues with widget click events.

Widget selection state

---

arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm
arches/app/templates/views/graph/graph-designer/card-tree.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/resource/new-editor.htm
arches/app/templates/views/system-settings.htm

Remove "all" from "Expand all" and "Collapse all" labels
#3776 

Remove "all" from "Expand all" and "Collapse all" labels, re #3776

---

arches/app/media/js/views/components/cards/default.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph-designer.htm

Remove Selection and Hover state from resource editor
#3785 #3839

Remove Selection and Hover state from resource editor #3785 #3839

---

arches/app/media/js/models/card-widget.js
arches/app/templates/views/graph/graph-designer/node-form.htm

Makes required toggle switch visible when configuring a geojson node. re #3781

Required map node switch

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/permission-designer.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm
arches/app/templates/views/graph/graph-designer/permission-settings-form.htm

Adds ability to multi select cards in the permission manager as well as buttons to select all unselected cards and clear all selected cards re #3684, #3794.

3684 card multiselect

---

arches/app/media/js/views/resource/new-editor.js

Make 'Jump to Report' link in resource editor open in a new tab.
#3799 

Make 'Jump to Report' link open in new window, re #3799

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/graph-settings.js
arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/graph-settings.htm
arches/app/views/graph.py
tests/views/graph_manager_tests.py

Customize the settings page for a Branch
#3804 #3784 

3804 branch settings page

---

arches/app/media/js/views/graph-designer.js

Fixes issue with syncing graph node and card selection when a node has no matching card. re #3782

Fixes issue with syncing graph node and card selection when a node has no matching card 

---

arches/app/templates/views/graph/graph-designer/node-form.htm

Fix Truncated Datatype dropdownin new node config form
#3771 

Fix Truncated Datatype dropdown in new node config form #3771

---

arches/app/media/js/views/graph-designer.js

Prevents error when adding a node to a brand new graph. re #3782

Prevents error when adding a node to a brand new graph. re #3782

---

arches/app/media/js/models/report.js

fixes error w/ report config on template change

---

arches/app/templates/navbar/graph-manage-menu.htm

fixes function manager template

---

arches/app/media/js/views/graph/permission-manager/permission-settings-form.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/permission-settings-form.htm

Replace middle panel in permissions manager with a users dropdown
#3812 

Replace permissions manager middle panel with dropdown, re #3812

---

releases/pre-4.3.0.md

testing result updates

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js

Updates card trees (card manager and permission tree) when a user adds or deletes a card. re #3803

3803 update card tree

---

arches/app/media/js/models/report.js
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/graph-designer.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/report-templates/default.htm

supports better report preview

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm

improves default selection in editor

---

.eslintrc.js
arches/app/media/js/views/resource/new-editor.js
arches/app/media/js/views/resource/report.js
arches/app/templates/navbar/new-resource-manage-menu.htm

adds print button to resource editor

---

arches/app/media/js/reports/image.js

fixes image header report

---

arches/app/media/css/arches.css
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/permission-settings-form.htm

4.3.0 ui enhancements

---

arches/app/media/css/arches.css

re: #3925 update default map header report template

---

arches/app/media/css/arches.css

Small CSS enhancements to Card Manager widget hover/select state

---

arches/app/media/js/models/card.js
arches/app/templates/views/components/cards/default.htm

Transfer the Card Help to the new Card Designer and Resource Editor
#3903 

3903 card level help

---

arches/app/templates/base.htm

Remove Arches Version from the Base Template
#3897 

Remove Version from Base Template #3897

---

arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/graph/graph-designer/node-form.js
arches/app/models/card.py
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/graph/graph-designer/node-form.htm
arches/app/views/graph.py
arches/install/arches-templates/project_name/package.json
arches/install/arches-templates/project_name/settings_local.py-tpl

Enables datatype dropdown for parent nodes and prevents users from editing nodes that already have tiles associated with them. re #3887 and #3928
Also updates the project templates.

Removes parent datatype constraint and restricts editing nodegroups with data

---

arches/app/media/js/models/card.js

ensures config is updated w/ component

---

docker/entrypoint.sh

Detailed in #3857 - custom site install will now ignore hidden "." prefixed files when testing to see if the target folder is empty.
#3857 
*   Sponsored by: Getty Digital
*   Found by: @benosteen
*   Tested by: @benosteen

Fix for #3857, custom site install check will now ignore . files

---

arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/graph/graph-designer/node-form.js
arches/app/models/graph.py
arches/app/templates/views/graph/graph-designer/node-form.htm

If graph is a resource model: Hides switch to create a card when a node is the child of the root node. Automatically creates a card for nodes created off of root and updates the card and permission trees.

3779 disable make card

---

arches/app/media/js/views/components/widgets/map.js

Loads geometries into draw layer when a new tile geojson tile is added. re #3898

Updates draw layer when a new geojson tile is added. re #3898

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/components/cards/default.js
arches/app/templates/views/components/cards/default.htm

Permission Manager: Selecting a parent card selects all child cards
#3909
*   Found by: @ryan86

Permissions Manager: selecting parent card selects all child cards #3909

---

arches/app/media/css/arches.css
arches/app/templates/views/graph-designer.htm

Move card level help from from its own panel to middle panel
#3946
*   Found by: @dwuthrich

Move Card Help #3946

---

arches/app/media/js/views/components/cards/default.js

Expand card when children card are selected.
#3909

Permissions Manager: Expand Card when children cards are selected #3909

---

arches/app/media/css/arches.css

re:#3957 Update related resources positioning on full report

---

arches/app/templates/views/graph-designer.htm

fixes bug with report manager

---

arches/app/utils/data_management/resources/formats/rdffile.py

fix url name mismatch, re #3854

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/components/cards/default.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/templates/views/components/cards/default.htm

Select children Cards in Permission Manager when parent is selected in Card Manager 
#3909 

Permissions: Select cards when parent is selected in Card Manager #3909

---

arches/app/media/css/arches.css
arches/app/templates/views/graph/graph-designer/card-configuration.htm

Adjust Card Help #3946

---

arches/app/templates/base-manager.htm
arches/app/templates/navbar/function-manage-menu.htm

Split out Function Manager Menu to separate file for @robgaston's development
#3738 

Split out Function Manager Menu #3738

---

arches/app/media/js/viewmodels/map-controls.js
arches/app/media/js/viewmodels/widget.js
arches/app/media/js/views/components/datatypes/geojson-feature-collection.js
arches/app/media/js/views/components/widgets/datepicker.js
arches/app/media/js/views/components/widgets/number.js
arches/app/media/js/views/components/widgets/switch.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/templates/views/graph-designer.htm

Adds 'disposables' array to the WidgetViewModel and adds a dispose function to the switch, number, datepicker widgets which disposes of items in the disposable array. Also, prevents card and permission pages from rendering when nodes are changed in the graph tree. re #3906

3906 memory management

---

arches/app/media/js/views/graph.js
arches/app/templates/javascript.htm
arches/app/templates/views/graph.htm
arches/app/views/graph.py
arches/urls.py

Adding the ability to remove resource instances from the Arches Designer page
#3815 

3815 arches designer remove instances

---

arches/app/media/js/views/graph-designer.js
arches/app/templates/navbar/graph-designer-menu.htm

3738 graph manager manage menu

---

arches/app/models/tile.py

Fix Error Message to show Widget Name if set.
Fix Error Message to show multiple required values
#3885 
*   Found by: @apeters

Resource Editor: Fix Error messages #3885

---

arches/app/media/js/views/components/functions/primary-descriptors.js
arches/app/media/js/views/graph/function-manager.js

Shows dirty state if a selected function is not saved to the database. re #3970.

Function manager dirty state

---

arches/app/templates/navbar/function-manage-menu.htm
arches/app/views/graph.py

Fixes the menu in the Functions Manager
#3912

3912 functions manager fix menu

---

arches/app/media/js/viewmodels/widget.js
arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph-designer.htm

 fixes graph preview size (& center)

---

arches/app/templates/views/graph/graph-designer/graph-settings.htm

 fixes current graph name in relatable

---

arches/app/media/css/arches.css

fixes chosen multiselect remove icon

---

arches/app/media/js/views/graph.js
arches/app/views/graph.py

Find drop down fix in the Arches Designer
#3987 
*   Found by: @benosteen

Arches Designer: Fix Find #3987

---

arches/app/models/concept.py
arches/app/utils/skos.py
arches/app/views/api.py
arches/settings.py

3562 get concept as jsonld

---

arches/app/utils/skos.py

add lowercasing of language tags until the pyld module accepts mixed case, re #3562

---

arches/app/utils/permission_backend.py
arches/settings.py

allow admins to define groups that can edit resources, re #3911

---

arches/app/media/js/views/components/widgets/map.js

fixes home button for report map

---

arches/app/media/css/arches.css
arches/app/media/css/tree/tree.css
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm
arches/app/templates/views/system-settings.htm

re: #4001 Update filtered style for graph, permissions trees

---

arches/app/media/js/viewmodels/card.js
arches/app/templates/views/components/cards/default.htm
arches/app/utils/permission_backend.py
arches/app/views/resource.py

allow users to view read-only cards in the resource editor report, re #3998

---

arches/management/commands/packages.py

loads card components with package

---

arches/app/media/css/arches.css
arches/app/templates/views/report-templates/default.htm

re: #4013 Update provisional tile display in resource editor report

---

releases/pre-4.3.0.md

Adds a list of version highlights and changes

Adds list of highlights and changes list

---

arches/app/media/css/arches.css
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/page-view.js
arches/app/templates/help/cards-tab-help.htm
arches/app/templates/help/graph-tab-help.htm
arches/app/templates/help/permissions-tab-help.htm
arches/app/templates/views/graph/graph-designer/permission-settings-form.htm
arches/app/views/graph.py

Adding new in-app help content, with some extra css and js functionality.
#3902 

3902 prepare in app help for 4.3 release

---

arches/app/media/css/arches.css

re:#4017 Update related resources FDG node styling

---

arches/app/media/css/arches.css

#4020 
*   Found by: @mradamcox

Adjust .node-permissions css to fix #4020

---

releases/pre-4.3.0.md

Resets testing script

---

arches/app/media/css/arches.css

Adjust permissions-card to fix #4020

---

releases/pre-4.3.0.md

4.3 testing

---

releases/pre-4.3.0.md

Tests map config in card config manager

Tests map config in card config manager.

---

arches/app/media/js/viewmodels/graph-settings.js
arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph/graph-designer/graph-settings.htm

also fix not being able to reset graph ontologyclass back to "none"
re #4050

fix rootnode datatype not being able to be changed in a branch, re #4050

---

arches/management/commands/packages.py

Creates card component directory when a user creates a new package. re #4042

Creates card component directory when a user creates a new package.

---

arches/app/views/graph.py

Allows loading of the related resources page for users unassigned to the Graph Editor group. re #4010

Load related resource splash page for users not in the Graph Editor group

---

arches/app/views/graph.py

Allows loading of the related resources page for users unassigned to the Graph Editor group. re #4010

Allows loading of the related resources page for users unassigned to the Graph Editor group

---

arches/app/models/migrations/3724_report_manager_2.py

fix for issue with report migration - cherry picked from 4.3.x

fix for issue with report migration

---

arches/__init__.py
releases/4.3.1.md

Updates version number and adds 4.3.1 release notes.

4.3.1 release prep

---

docker/Readme.md
docker/settings_local.py

Add section to explain DJANGO_MODE=DEV etc and how to bypass Nginx.

3941 update docker readme django mode nginx

---

arches/app/models/card.py

3892 integrity error bug

---

arches/app/media/js/viewmodels/tile.js

fixes tile viewmodel dirty state for new tiles

---

arches/app/templates/base.htm
arches/app/templates/errors/error_base.htm
arches/management/commands/packages.py

support custom project/package css

---

arches/app/media/js/bindings/mapbox-gl.js
arches/app/media/js/bindings/select2-query.js
arches/app/media/js/viewmodels/card-component.js

Cherry picks from @robgaston's commits to master: 
- fixes to the card component view model. 
- adds onClear to select2 binding handler
- enhances the mapbox binding handler
- enhances the card component view model for extension

Cherry pick to 4.3.x

---

arches/app/models/mobile_survey.py
arches/app/views/api.py
arches/app/views/mobile_survey.py

4122 add metadata to msm

---

arches/app/models/mobile_survey.py

include functions in mobile survey manager config so we can render display name, re #4122

---

.github/CONTRIBUTING.md

Follows github's recommendations on the location of contribution information. 
https://github.com/archesproject/arches/wiki/Contributing

Moves contributing documentation from the wiki to the CONTRIBUTING.md

---

arches/app/utils/email_auth_backend.py
arches/app/views/auth.py
arches/settings.py
arches/urls.py

4147 enable oauth on mobile client

---

arches/app/media/js/models/card.js
arches/app/media/js/views/graph/graph-manager/graph.js

4149 js cpu issue

---

arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/views/graph.py

Updates relevant cards and widgets in the card tree when a node is edited rather than truncating and recreating the tree. re #3993, #4149

3993 refactor update card in card tree

---

arches/app/media/js/models/card.js
arches/app/media/js/models/graph.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/models/graph.py
arches/app/views/graph.py

fixes card tree syncing

---

arches/admin.py
arches/app/models/models.py
arches/app/templates/views/components/cards/default.htm

adds models to admin, fixes tree styles

---

arches/management/commands/datatype.py

Adds update to the datatype command to support dev training.

Adds update method to datatype management command.

---

arches/app/models/graph.py
arches/app/utils/data_management/resource_graphs/exporter.py

fixes graph export

---

arches/management/commands/datatype.py

Cherry pick from master:
Adds update method to datatype management command.

Cherry pick from master: update method to datatype management command.

---

README.md

update urls in README.md
#3320

update link to CONTRIBUTING.md #3320, generalize RTD link

---

arches/app/media/js/models/card.js

Sorts widgets after they are added to the card model, re #4169, #4188

Fixes widget sort order in the card tree 

---

arches/app/media/js/viewmodels/concept-select.js
arches/app/models/concept.py
arches/app/views/concept.py

makes collectors unselectable

---

arches/app/media/js/models/card.js
arches/app/media/js/models/node.js
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph/graph-designer/card-tree.js

syncs card tree w/ graph changes

---

arches/app/media/js/models/card.js
arches/install/requirements.txt

Fixes bug preventing widgets from sorting properly when loading the graph designer. re #4169

Sorts widgets after they are added to the card model. re #4169

---

arches/install/requirements.txt

Fixes urllib3 at v1.21.1 to prevent CI build errors

Fixes urllib3 at v1.21.1

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/plugins/map.js
arches/app/media/js/views/plugin.js
arches/app/models/migrations/4202_plugin_model.py
arches/app/models/models.py
arches/app/templates/base-manager.htm
arches/app/templates/views/components/plugins/map.htm
arches/app/templates/views/plugin.htm
arches/app/views/plugin.py
arches/urls.py

adds plugin page (and demo map plugin)

---

arches/app/templates/base-manager.htm
arches/app/views/base.py

adds plugin links

---

arches/app/views/auth.py

Returns user information when the mobile app requests a client id so that we can save user information with the server/app on the mobile device.

Returns user model when a client id is requested by the mobile app

---

arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/viewmodels/tile.js

Resolves knockout errors

---

arches/app/models/mobile_survey.py

add unconfigured widgets to msm config, re #4122

---

arches/app/media/css/arches.css
arches/app/media/css/tree/tree.css
arches/app/templates/base-manager.htm

re: #4220 UI 431 updates

---

arches/app/templates/base-manager.htm

fixes graph designer manage menu

---

arches/app/media/js/models/card.js

Corrects mis-ordering of widgets, re #4169., #4188

Fixes sort order bug

---

arches/admin.py
arches/app/views/base.py
arches/app/views/plugin.py

adds permissions for plugins

---

arches/app/templates/base-manager.htm

uses plugin slug in navbar if available

---

arches/app/media/js/views/resource/new-editor.js
arches/app/models/resource.py
arches/app/views/resource.py

Prevents provisional users from deleting resources with authoritative data re #4231

Prevents provisional users from deleting resources with authoritative data

---

releases/pre-4.3.2.md

Updates release notes

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js

fixes add branch recursion error

---

arches/app/media/js/models/card.js
arches/app/media/js/models/node.js
arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/card-tree.js

Fixes error when adding some branches forcing user to reload the page. re #4329.
Cherry picked from master

Fixes error when adding branches

---

arches/app/models/resource.py
releases/pre-4.3.2.md

Fixes issue preventing deletion of all instances from a resource model's manage button re #4231
Updates test script with latest results.

4.3.2 testing

---

releases/pre-4.3.2.md

432 testing

---

releases/4.3.2.md

Update data rendering section of the testing results.

---

arches/app/models/resource.py

Fixes bug preventing instance deletions from the resource model manage menu

---

arches/app/media/js/viewmodels/mobile-survey-manager.js
arches/app/media/js/views/mobile-survey-manager.js
arches/app/views/mobile_survey.py

Handles for cases when the request receives a geojson geometry rather than a feature or feature collection. re #4196

Solves bug saving MSM bounds

---

arches/app/models/mobile_survey.py
arches/app/utils/couch.py

Adds intelligent Couchdb sync
#4161 

4161 couch to postgres

---

arches/app/models/mobile_survey.py

add concept data to MSM, re #4289

---

arches/app/models/mobile_survey.py
arches/management/commands/mobile.py

4161 couch to postgres: Sync New Tiles

---

arches/app/models/mobile_survey.py

Write new Resource from Mobile to Postgres #4161

---

arches/management/commands/datatype.py

Fixes assignment of the modulename in the update command, re #4294

Fixes assignment of the modulename in the update command

---

arches/install/ubuntu_xenial_setup.sh

The xenial script was installing an old version of nodejs that didn't support the later version of yarn that we need.
#4293

#4293 update nodejs version in xenial dependency install script

---

arches/app/models/mobile_survey.py

Fixes an error in the mobile survey view when getting concepts when the collection_id is None

Fixes error getting concept collection when collection_id is None

---

.gitignore
arches/app/media/js/views/map.js
arches/app/utils/data_management/resources/formats/archesfile.py
arches/app/utils/data_management/resources/importer.py
arches/install/requirements.txt

This is a contribution of a few bugfixes/enhancements that I have incorporated into my own v3 deployments.
1) original pixel location reference method was not working properly in all browsers.
2a) some python requirements were not recorded in requirments.txt
2b) xrld is not used anywhere but was in requirements.txt
3) .egg files should be ignored
4) a few size limitations caused problems during import of large geometry
*   Sponsored by: Legion GIS
All of these commits have been in production at afrh-iris.com for a long time.

V3 updates legiongis

---

arches/app/media/js/views/components/functions/primary-descriptors.js

allows all cards in descriptor function

---

arches/app/media/css/arches.css
arches/app/templates/login.htm
arches/app/templates/registration/base.html
arches/app/templates/registration/password_reset_form.html
arches/app/templates/signup.htm

re: #4324 Simplify Log in, New Account UI

---

arches/app/views/api.py
arches/urls.py

Use a simple http sync method to sync between couch and postgres, re #4161

---

arches/app/datatypes/base.py
arches/app/datatypes/datatypes.py
arches/app/models/mobile_survey.py

Converts couch attachments to files to support the file-list datatype in mobile. re #4311

Initial work on syncing file data for a mobile survey, re #4311

---

arches/app/models/mobile_survey.py

Fixes error when no key, 'provisional_resource' exists

Check for provisional resource key. re #4311

---

arches/admin.py
arches/app/datatypes/datatypes.py
arches/app/media/js/views/components/widgets/file.js
arches/app/models/mobile_survey.py
arches/app/models/models.py
arches/app/models/tile.py
arches/app/views/tile.py

Fixes issues with saving file-list data as a provisional user and issue with files disappearing when switching between cards with file-list widgets. re #4311, #4301

212 mobile support file sync

---

arches/app/datatypes/datatypes.py

Fixes update of image properties preventing invalid activation of dirty state in card. re #212

Updates image properties during sync

---

arches/admin.py
arches/app/datatypes/datatypes.py
arches/app/media/js/views/components/widgets/file.js
arches/app/models/models.py
arches/app/models/tile.py
arches/app/views/tile.py

Fixes some issues with the invalid activation of dirty state in the file-list widget

Move file list widget fixes to 4.3.x

---

arches/app/models/mobile_survey.py

add resource instance list to metadata for mobile survey, re #4122

---

arches/app/media/js/viewmodels/tile.js
arches/app/models/mobile_survey.py
arches/app/models/tile.py

Saves mobile edits made by resource reviewers as authoritative. re #4337

Reviewer mobile edits saved authoritative

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card-component.js
arches/app/templates/views/components/cards/default.htm

adds report card expander

---

arches/app/templates/views/components/cards/default.htm

hides expander on print

---

arches/install/arches-templates/project_name/package.json

Adds missing js dependencies to the package.json in project templates.

Adds missing js dependencies to the package.json in project templates.

---

arches/app/views/mobile_survey.py

Improves error messaging if Couch is not running or inaccessible

---

arches/app/models/mobile_survey.py

allow the MSM to collect non-spatial resource instances, re #4398

---

arches/app/models/mobile_survey.py
arches/app/templates/views/mobile-survey-designer.htm
arches/app/templates/views/mobile-survey-manager.htm

Removes some cruft in serialization to improve page load performance and makes the resource instance limit available for both resource type and custom downloads. re #4357

4357 msm redesign

---

arches/app/views/api.py

make sure that only users assigned to a Mobile Survey can sync data with couch

---

arches/app/models/mobile_survey.py

Fixes date calculation error. re #4394

Fixes date calculation error. re #4394

---

arches/app/models/mobile_survey.py

fix issue with not being able to download non-spatial resources, re #4398

---

arches/app/models/mobile_survey.py

Handles both object and string enddates in survey serialization. re #4394

Handles both object and string enddates in survey serialization. 

---

arches/app/views/api.py

Thinko fix from "else if" to "elif"

else if --> elif

---

arches/app/models/models.py
arches/app/views/api.py
arches/app/views/auth.py

add card permissions to Survey endpoint, re #4423

---

arches/app/models/mobile_survey.py
arches/app/views/api.py

4424 dont save mobile survey to couch

---

arches/app/utils/data_management/resources/formats/archesfile.py

fixes tile import issue

---

arches/install/requirements.txt

fixes requests ssl error

---

arches/app/datatypes/concept_types.py

Checks if range_tile_data is true before attempting to iterate when producing RDF graph for JSON-LD serialization of a resource instance.
Closes #4414 
#

check if range_tile_data is None

---

arches/app/views/auth.py
arches/settings.py

Handles for cases in auth.py when a user does not have a related UserProfile.

cla testing

---

arches/app/views/mobile_survey.py

Fixes bug in MSM preventing card, user, and group relationships from saving on the first save of a mobile survey.  re #4432

Saves card, user, and group relationships for newly created mobile surveys

---

arches/app/views/mobile_survey.py

Temporarily disabling email notifications from the MSM because of errors if the email server is not properly configured. re #4432

4432 msm connection refused error

---

arches/app/templates/views/mobile-survey-designer.htm

Fixes issue with 'no forms added' element persisting in the msm setting page and adds the survey status panel with regardless if a survey is incomplete or not. re #4357

MSM settings panel fixes

---

arches/app/media/js/viewmodels/card-component.js
arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/tile.js
arches/app/templates/views/components/cards/default.htm

improves tree click handling

---

tests/models/graph_tests.py
tests/models/tile_model_tests.py

Small change to how resource graphs are loaded during test case setups.
#4457 

#4457 fix (iterate) reference to resource graph dirs

---

arches/app/media/css/arches.css
arches/app/media/js/views/mobile-survey-designer.js
arches/app/templates/base-manager.htm
arches/app/templates/base.htm
arches/app/templates/views/mobile-survey-designer.htm

Adds default values for user name and email in users account info. Adds data section to msm summary. Adds text description to loading element when saving a survey. re #4357

MSM improvements  

---

arches/app/models/mobile_survey.py

Skips syncing of tiles if it has no resource instance on the server. re #4463

Skips syncing of tiles that have no corresponding resource instance on the server.

---

arches/app/media/js/models/mobile-survey.js
arches/app/media/js/viewmodels/mobile-survey.js
arches/app/templates/views/mobile-survey-designer.htm

Fixes issues with user account info display and updates data download properties when user adds a card. re #4462, #4437

Fixes issues with user account info display and updates data download properties when user adds a card.

---

arches/app/views/api.py

Removes debugger breakpoint.

---

arches/app/media/css/arches.css
arches/app/templates/views/mobile-survey-designer.htm

Notifies user why some features of the MSM are immutable once a survey has been synced. re #4401

Notifies user when some features of the MSM are immutable

---

arches/app/templates/views/mobile-survey-designer.htm

Only shows active survey message when a survey is active on the server. re #4357

Only shows active survey message when a survey is active

---

arches/app/views/api.py

fix child cards not being added to the mobile survey, re #4488

---

.vscode/settings.json
arches/app/templates/base-manager.htm

Adds second search icon to left nav bar re #4456

4456 moving search button

---

arches/app/media/css/arches.css
arches/app/templates/views/mobile-survey-designer.htm
arches/app/templates/views/mobile-survey-manager.htm

re: 4506 Update MSM status message styles

---

arches/app/views/api.py

Returns a message if the survey with which a user is trying to sync has been deleted. re archesproject/arches-mobile#388

Sync returns message if a survey has been deleted

---

arches/app/views/api.py

Re-enables ProtectedResourceView inheritance for user confirmation and reports survey to mobile as deleted even if the database exists in couch, but not arches. re archesproject/arches-mobile#388

Re-enables ProtectedResourceView inheritance for user confirmation

---

arches/app/models/mobile_survey.py

only push data to couch when configured in the MSM, re #4498

---

arches/app/media/js/viewmodels/concept-select.js
arches/app/media/js/viewmodels/mobile-survey.js

re: #4522 sets closeOnSelect prop to true in select2configs (in concept-select, resource-instance-select, and group-select inputs)

explicitly sets closeOnSelect prop to false for multi select2configs

---

arches/app/media/css/arches.css
arches/app/templates/views/mobile-survey-designer.htm

re: 4531 Update MSM status icons

---

arches/app/models/mobile_survey.py

Re: #4448 fixes download limit to apply to each resource model included in survey; incorporates requested changes to correctly prioritize spatially filtered resource instances before non-spatial.

ensures that spatial instances are prioritized, DL limit applied to each resource model

---

arches/app/templates/help/graph-tab-help.htm
arches/app/templates/views/graph/graph-designer/node-form.htm

Replaces the term 'CRM Class' with 'Ontology Class'

Replaces 'CRM Class' with 'Ontology Class'

---

arches/app/views/api.py

fix an issue where parsing out the uuid of a mobile survey was incorrect

---

arches/app/models/models.py
arches/app/views/api.py
arches/app/views/mobile_survey.py

get the current status of MobileSurvey objects, re #4555

add an "expired" property to a MobileSurvey object, add an endpoint to..., re #4555

---

arches/app/models/mobile_survey.py

loads child tiles to couch

---

arches/app/datatypes/datatypes.py
tests/importer/datatype_from_rdf_tests.py

* The code now correctly looks for `@id`
* Accepts: `urn:uuid:UUID_HERE`, `http://arches.host.com/resources/UUID_HERE`, etc
* Returns the UUID if found, None otherwise
#4567

Resource Instance URIs can be any URI ending in a UUID

---

arches/app/views/api.py
arches/urls.py
tests/views/api_tests.py

allow users to download a single survey, re #4555

---

arches/app/views/api.py

refine how inactive projects are displayed, re #4555

---

arches/app/views/api.py

fixes survey permissions

---

arches/app/media/css/arches.css
arches/app/templates/views/mobile-survey-designer.htm

re: #4576 Update MSM map sources help text

---

arches/app/datatypes/concept_types.py
arches/app/utils/data_management/resources/formats/rdffile.py

Add check that rdfs:label is in the concept before trying to delete. Add check that label_node is truthy before trying to find the matching conceptvalue. 
#4421

fix no labels on inbound concept

---

arches/app/media/js/viewmodels/mobile-survey.js
arches/app/views/mobile_survey.py

Sorts cards in the MSM if cards have a sort order, re #4487

Sorts cards in the MSM if cards have a sort order, re #4487

---

arches/app/templates/help/profile-manager-help.htm
arches/app/templates/views/user-profile-manager.htm

Added a little more information in the in-app help for profile manager. Also, commented out a large section of the manager page itself that was not implemented. Specifically, there are images for the app download links but no links are yet available for the app, and there was a hidden section that mocked up how the device listing should look, but it was not linked to any list of devices, and was throwing 404 errors for a couple of images that don't exist.
#4586
-   [ ] I have added tests that prove my fix is …

4586 in app help for profile manager

---

arches/app/views/tile.py

For #4212
Add exception handling and logging to tile.post()
There were cases where no error messages were relayed to the frontend when exceptions occurred.

#4212 Add exception handling and logging to tile.post()

---

arches/app/models/resource.py

As per issue #2828 this adds a method on the resource class that provides the ability to get the value of a resource's node based on the node's name.
* Returns a list of values if the name parameter is valid and has at least one value.
* Returns an empty list (evaluating to `False`) if the name parameter is valid but the node has no values.
* Returns `False`  if the name parameter is not valid or has no match.
* Works for "string, domain, domain-list, concept, and concept-list datatypes".
```
>>> from arches.app.models.resource import Resource
>>> res = Resource.objects.get(pk="7c81a620-d746-4a6a-8dc8-0d44cd6a7a82")
>>> res.get_node_values("Style")
[u'Frame Vernacular']
>>> res.get_node_values("Structure Use")
[u'Private residence']
>>> res.get_node_values("Architect")
[]
>>> …
```

2828 add resource method for node value

---

arches/app/views/api.py

all the update of certain properties of a Survey/Project after activation, re #4555

---

arches/app/templates/views/components/cards/default.htm

re: #4582 (bug caused by #4543 ) this fixes card configuration view so that widgets are not disabled, keeps desired behavior intended by original PR in resource edit.
@robgaston @chiatt 
fyi: @dwuthrich

re-enables widgets in card configuration view

---

arches/app/media/css/arches.css
arches/app/templates/views/mobile-survey-designer.htm

re: #4601 Update Collector Designer Text size, colors

---

arches/app/media/js/viewmodels/domain-widget.js

Fixes error when loading domain widget in card config panel. re #4604

Fixes error when loading domain widget in card config panel. re #4604

---

arches/app/models/mobile_survey.py

Handles for cases when conflict data is None

---

arches/app/media/js/views/graph/graph-designer/card-tree.js

Adds new node to nodelookup so that it's available for the card component in the card config form. re #4604

Makes newly created node configs available to the card configuration

---

arches/app/datatypes/datatypes.py

Fixes previously undefined value

Fixes node datatype validation bug. re #4625

---

releases/pre-4.4.0.md

Adds the rest of Namjun's test results

Release notes

---

releases/pre-4.4.0.md

Adds more details to changes in this release

Release note improvements

---

arches/setup.py

Removes postgres version check

---

arches/app/media/js/bindings/formattedNumber.js
arches/app/media/js/views/components/widgets/number.js
arches/app/models/migrations/4352_format_config_number_widget
arches/app/templates/javascript.htm
arches/app/templates/views/components/widgets/number.htm
package.json
yarn.lock

Adds 'format' config to number widget that allows for number formatting based on the numeraljs library.
#4352 

Create config for adding commas to number widget, re #4352

---

arches/app/media/js/viewmodels/file-widget.js
arches/app/media/js/views/components/widgets/file.js
arches/management/commands/packages.py

Adds function to export widgets. re #2779, archesproject/consultations-pkg#4 and moves the file widget's view model into its own file. re #4672

4672 file widget refactor

---

arches/management/commands/packages.py

Updates widget templates in a package when a package is updated

Updates the template file with other widget data.

---

arches/app/media/css/arches.css

Improve button display in concept widget

---

arches/app/search/search.py

2691 es upgrade

---

arches/app/media/css/arches.css
arches/app/templates/views/components/plugins/workflow.htm

Updates to workflow plugin layout. re #4662

Updates to workflow plugin layout. 

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/file-widget.js

adds styling and a few minor changes to the file upload widget (from which a newer version extends), cited here: https://github.com/archesproject/consultations-pkg/pull/13

Galen file upload widget arches

---

arches/app/media/css/arches.css
arches/app/templates/views/components/plugins/workflow.htm

Adds delete button and improves layout. re #4662

Adds delete button and improves layout. re #4662

---

arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/plugins/workflow.js
arches/app/templates/views/components/plugins/workflow.htm

4668 workflow viewmodels

---

arches/app/media/js/viewmodels/tile.js
arches/app/media/js/views/resource/new-editor.js

Adds onSuccess callback to the tile view model's save method. re #4693

Adds onSuccess callback to the tile view model's save method. re #4693

---

.travis.yml
cypress.json
cypress/integration/sample_spec.js

Adding the foundation for using Cypress.io tests with Arches, and integrating it with the Arches Travis CI/CD script.
Cypress.io is an elegant way to test web applications at the browser-level, simulating user interaction, url loading, css-style selectors and so on, without the complications of selenium based tests. The tests are written in javascript, and cypress has a GUI to aid in writing tests, as well as a capacity to record video of the interactions.
#4688
-   [x] I have added tests that prove my fix is …

Adding Cypress.io testing framework to Travis CI

---

arches/app/media/css/arches.css
yarn.lock

adds css relevant to new file-widget

Galen newfilewidget css

---

arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/plugins/workflow.js
arches/app/templates/views/components/plugins/workflow.htm

update workflow and plugin architecture, re #4668

---

arches/app/models/card.py
arches/app/models/graph.py
arches/urls.py

Supports import of graphs with card constraints

---

arches/settings.py

add default setting for ELASTICSEARCH_PREFIX, re #4737

---

.travis.yml

Some travis-ci.org build issues where the deploy stage may have been attempted twice, once by each test suite. The error occurs when both tests suites end at a similar point, and one is mid-deployment when the other starts.
I've re-written the Travis-CI yml to have a separate deploy build stage that triggers once, after all the test matrices run.
#4740
(Tests run, insofar …

4740 travis deploy stage

---

arches/app/media/js/views/graph/function-manager.js
arches/app/models/tile.py

remove the need for a function to have triggering_nodegroups and a component

---

arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/widgets/map.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/plugins/workflow.htm

 minoir enhancements to map widget

---

arches/app/datatypes/datatypes.py

Allows date and domain list types to accept null values

---

arches/app/datatypes/datatypes.py

Handles for null values in number datatype validation

---

arches/app/datatypes/datatypes.py

Modifies geojson datatype to allow null values. 

---

arches/app/media/js/bindings/gallery.js

Moves gallery binding from consultations package to arches re #4751

Adds gallery binding

---

arches/app/views/map.py

Fixes undefined variable, 'resource_type'.

---

.travis.yml
arches/install/requirements.txt
arches/management/commands/es.py

4754 upgrade es to 6.7.1

---

arches/app/media/css/arches.css

removes sfp dashboard-specific css

---

docker-compose-test.yml
docker-compose.yml

Upgrading Docker files to reference Elasticsearch 6.7.1 images, to keep in line with changes done in #4754
#4753 

Update docker-compose files: #4753 

---

arches/management/commands/plugin.py

add slug and sortorder paramrters to plugin regisgtration, re #4765

---

arches/management/commands/project.py

Adds a command to register or update extensions in a project re #4762

Adds command to update extensions in a project

---

arches/management/commands/packages.py
arches/management/commands/updateproject.py

Adds flag to load_package command to include loading extensions from the project directory and lints re #4762

Adds update project to load_package command

---

arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/workflows/new-tile-step.htm
arches/app/views/api.py
arches/urls.py

new tile workflow step

---

arches/app/utils/context_processors.py

fix issue where if DEFAULT_BOUNDS were not set then the app wouldn't load

---

arches/app/templates/views/components/cards/default.htm

hides delete button when function unavailable

---

arches/app/media/css/arches.css

Fixes gray margin at top of report re #4613

Fixes gray margin at top of report re #4613

---

arches/app/media/css/arches.css

Fixes gray margin at top of report

---

arches/install/arches-templates/manage.py-tpl
arches/install/arches-templates/project_name/settings.py-tpl

Also allows users to easily create custom management commands in their projects. re #4820 #4545

Moves hash bang line to top of manage.py

---

arches/app/datatypes/datatypes.py
arches/app/media/js/bindings/dropzone.js
arches/app/models/tile.py
arches/app/views/tile.py

- Prevents IntegrityError caused by saving a file without a corresponding tile. #2963
- Validates tiles prior to saving. 
- Simplifies exception handling in the Tile view

2963 uploaded file deletion

---

arches/app/views/api.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Improves logging to collector sync and adds logging to console by default. re archesproject/arches-collector#504

Log sync errors

---

arches/app/templates/views/graph/graph-designer/card-configuration.htm

Removes cruft

---

arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Adds session cookie name to settings and project template settings. 

---

arches/app/views/api.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Adds API logging from 4.4.x and adds console logging to the logging configuration by default. re #4837

4837 mobile sync logging

---

arches/app/datatypes/datatypes.py
arches/app/models/tile.py
arches/app/templates/views/components/cards/default.htm
arches/app/views/tile.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Moves file deletion and session cookie name setting from master to 4.4.x #2963 #4541
Also, removes extra closing `ko` tag in the default card component.

Patches from master to 4 4 x

---

arches/app/templates/views/mobile-survey-designer.htm

Fixes UI error when first selecting a group from the Arches Collector Designer tree. re #4717

Prevents error when selecting groups from collector tree 

---

arches/app/datatypes/datatypes.py
arches/app/models/mobile_survey.py
arches/app/utils/middleware.py
arches/app/views/api.py
arches/app/views/mobile_survey.py
arches/management/commands/mobile.py

Improves logging during sync, re #4837

Improves logging during sync, re #4837

---

arches/app/datatypes/datatypes.py

Fixes datatype validation errors when values are `None`

---

arches/app/models/mobile_survey.py
arches/app/utils/middleware.py
arches/app/views/api.py
arches/settings.py

Adds support for a custom authentication header to support api requests from ios devices. re #4717

Support custom auth header

---

arches/app/media/js/views/components/search/map-filter.js
arches/app/media/js/views/components/search/search-results.js
arches/app/media/js/views/search.js

fix race condition when updating state, re #4771

---

arches/app/templates/views/search.htm

4771 componentize search

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/term-search.js
arches/app/views/search.py
arches/settings.py

4840 group term search

---

arches/app/media/js/viewmodels/resource-instance-select.js
arches/db/install/truncate_db.sql

Small changes to fix traditional related resource interface and support componentized search.
#4664 

4664 create related resource

---

arches/app/media/js/bindings/datepicker.js
arches/app/models/mobile_survey.py
arches/install/arches-project

Fixes error when clearing start and end dates in the collector manager and error when serializing projects that have invalid dates ('' or None). re #4484

Fixes collector manager date errors

---

arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Helps to prevent server-side errors when syncing photos from collector. archesproject/arches-collector#496

Increases max file upload size to support collector

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/term-search.js
arches/app/views/search.py

finish term search grouping and styling, re #4840

---

arches/app/search/components/provisional_filter.py

fix error with provisional filter, re #4771

---

arches/app/datatypes/datatypes.py
arches/app/models/tile.py
arches/app/views/tile.py

Ensures a files uploaded by provisional editors are saved after upload. re #2963

Handles saving of files for provisional editors. 

---

arches/app/datatypes/datatypes.py
arches/app/models/tile.py
arches/app/views/tile.py

Moves changes from 4.4.x to master that ensure that file uploads submitted by provisional editors are saved. re #2963

Fixes bug preventing provisional users from saving uploaded files

---

arches/app/media/js/viewmodels/resource-instance-select.js

fix issue with adv. search and related resource select, re #4664

---

arches/app/datatypes/datatypes.py

dates need to be not null or blank for adv. search to work, re #4872

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/templates/views/components/plugins/workflow.htm

Fixes css to allow scrolling in the workflow step body. Initializes workflow steps in the workflow step constructor and fixes error when loading the resourceinstance widget without a node config.

Modifications to support workflows

---

arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/templates/views/components/plugins/workflow.htm

Fixes latency when loading a workflow. re #4821

Fixes latency when loading a workflow. re #4821

---

arches/app/media/js/bindings/related-resources-graph.js
arches/app/media/js/views/resource/related-resources-manager.js

fix related resource select dropdown, re #4804

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/templates/views/components/plugins/workflow.htm

Changes workflow state.steps object to an array fixes issues with indicating which steps are completed when restoring a workflow from its url state. Also adds disabled state to back and next buttons. re #4821

Workflow state improvements 

---

arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/views/components/workflows/final-step.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/components/workflows/final-step.htm

Adds default final-step to workflow steps. re archesproject/consultations-prj#29

4821 workflows url params

---

arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/final-step.js
arches/app/templates/views/components/workflows/final-step.htm

Adds links to start a new workflow or edit a resource on completion of a workflow. Also filters the workflow report in the final step based on those cards available in the workflow. re archesproject/consultations-prj#29.

Final workflow step improvements

---

arches/app/media/css/index.css

includes additional updates to styling, per QA / mockup, see: https://github.com/archesproject/consultations-prj/issues/16

Galen consultation prj 16 splash screen

---

arches/app/media/js/viewmodels/workflow.js

Allows custom workflows to use default instead of having their own. re #4821

Adds default updateState method to the workflow viewmodel

---

arches/app/templates/views/components/cards/default.htm

This reverts commit 1922029eed74af5501341d0e56da62103f3762fb.

Reverts addition of node and nodegroup ids in the card designer

---

arches/db/install/truncate_db.sql

Remove trauncate_db.sql
#4664 

Remove truncate_db.sql, re #4664

---

arches/management/commands/setup_db.py

Seems like between `master` and `stable/4.4.x` this search function had been renamed and that didn't get updated in the initial cherry-pick.
#

fix name of prepare_term_index method (for cherry-pick)

---

arches/management/commands/setup_db.py

Fixes error in when loading search page. re #4928

Includes all index setup methods from search.mappings

---

arches/management/commands/setup_db.py

Includes all setup_index methods in setup_db. re #4928

Cherry picks d6db623 from master

---

arches/app/media/js/views/plugin.js

 handles for null plugin configs

---

arches/management/commands/setup_db.py

This adds better error handling to address the situation in which a postgres superuser is trying to create a new project database from a POSTGIS_TEMPLATE that doesn't actually exist.
#4944

improve handling if POSTGIS_TEMPLATE database is not present re #4944

---

arches/__init__.py
releases/4.4.2.md

Sets version to 4.4.2 and updates starts 4.4.2 release notes

Release prep for 4.4.2

---

releases/4.4.2.md

Adds results for system settings, map settings, instance etl and provisional editing.

Updates release notes with some testing results

---

releases/4.4.2.md

Adds test results for authentication

Adds test results for authentication

---

arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/map.js
arches/app/templates/views/components/map-editor.htm

fixes for map card component

---

releases/4.4.2.md

Fixes additional changes formatting and adds results for RDM and map widget

Fixes additional changes formatting and adds results for RDM and map widget

---

README.md
releases/4.4.2.md

Updates release notes with upgrade instructions and updates README with link to release notes.

Adds 4.4.2 upgrade instructions

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/map.js
arches/app/templates/views/components/map-editor.htm

improves map card component

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/tile.js
arches/app/media/js/views/components/cards/grouping.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/components/cards/grouping.htm
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/card-configuration.htm
arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm
arches/app/templates/views/graph/graph-designer/card-tree.htm
arches/app/templates/views/report-templates/default.htm
arches/app/templates/views/report-templates/tabbed.htm
arches/app/templates/views/resource/new-editor.htm
arches/grouping-card-component.json

4907 grouping card component

---

arches/app/media/js/viewmodels/file-widget.js
arches/app/media/js/viewmodels/tile.js
arches/app/media/js/views/components/widgets/file.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/templates/views/components/widgets/file.htm

Adds config for file upload limit and allows user to control workflow advancement in new-tile-step. re #4921, archesproject/consultations-prj#59

Adds config for file upload limit and allows user to control workflow advancement in new-tile-step

---

arches/app/datatypes/datatypes.py
arches/app/media/css/arches.css
arches/app/media/js/views/components/map.js
arches/app/models/migrations/4661_removes_select_workflow.py
arches/app/templates/views/components/map-popup.htm
arches/app/templates/views/components/map.htm

map card component enhancements

---

arches/app/media/css/arches.css
arches/app/templates/views/components/plugins/workflow.htm

re: #4969 workflow ui improvements

---

.eslintrc.js
arches/app/utils/activity_stream_jsonld.py
arches/app/views/resource.py
arches/urls.py
cypress/.eslintrc.js
cypress/integration/activestream.js
cypress/support/commands.js
cypress/support/index.js
tests/utils/activitystream.py

This adds a new view and associated URL handling to allow authenticated clients to get the edit logs regarding the resources managed in Arches, represented as JSON-LD using the Activity Streams 2.0 vocabulary (https://www.w3.org/TR/activitystreams-vocabulary/).
It currently uses the `/history` path, with pages of the activity stream representation available from `/history/1`, `/history/2`, and so on.
Example `/history/` Collection document:
{
"@context": "https://www.w3.org/ns/activitystreams",
"type": "OrderedCollection",
"id": "http://localhost:8000/history/", …

Edit Log as JSON-LD Activity Stream

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/map.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/map-editor.htm
arches/install/package.json
arches/install/yarn.lock

adds geojson edit tool to map card

---

arches/app/utils/data_management/resources/importer.py
arches/management/commands/packages.py

This is a cherry-pick of all the commits in https://github.com/archesproject/arches/pull/4918. Please see description in that PR.
I had to resolve some conflicts related to linting in packages.py.

Cherry-pick PR 4918 to master

---

arches/management/commands/setup_db.py

Please see https://github.com/archesproject/arches/pull/4945 for a description of the change.

Cherry pick pr 4945 to master

---

arches/app/utils/data_management/resources/importer.py

This is a cherry-pick of https://github.com/archesproject/arches/pull/4958. Please see that pull request for a full description of changes.

Cherry pick pr 4958 to master

---

arches/app/templates/views/components/map-editor.htm

 enhancements to geojson editor tool

---

arches/app/media/css/arches.css
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/components/datatypes/node-value.htm
arches/app/templates/views/components/plugins/workflow.htm
arches/app/templates/views/components/widgets/text.htm
arches/app/templates/views/components/workflows/new-multi-tile-step.htm

re:#4969 ui enhancements

---

arches/app/media/js/views/components/cards/grouping.js

Just moves the view model outside the component declaration and returns the view model. re #4907

Minor refactor of grouping card to support inheritance of its view model

---

arches/management/commands/setup_db.py

Adds an explicit check for superuser status in addition to the check for the create db ability when evaluating postgres user permissions.
#4941

add check for superuser role #4941

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/workflows/new-multi-tile-step.js
arches/app/templates/views/components/workflows/new-multi-tile-step.htm

adds a ko condition for no tiles in new-multi-tile-step template, also adds observable to pass along title of thing in list; re https://github.com/archesproject/consultations-prj/issues/27

Additional changes to new-multi-tile-step template

---

arches/management/commands/packages.py

allow for rdf and xml files to be loaded during package load, re #5017

---

arches/app/utils/skos.py

allow for incomplete concept collections to be loaded, re #5019

---

arches/management/commands/packages.py

add more print statements during package load [ci-skip]

---

arches/app/datatypes/datatypes.py

Allows null values for domain datatype

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/time-wheel.js
arches/app/media/js/views/components/search/time-filter.js
arches/app/media/js/views/search.js
arches/app/search/components/saved_searches.py
arches/app/search/components/time_filter.py
arches/app/templates/views/components/search/time-filter.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm
arches/app/templates/views/search.htm

4772 search ui update

---

arches/app/media/css/arches.css
arches/app/templates/views/components/search/search-results.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm
arches/app/templates/views/search.htm

5030 Update search button styling

---

arches/app/media/css/arches.css
arches/app/templates/views/components/search/time-filter.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm
arches/app/templates/views/search.htm

re:#5030 Update search buttons styling, related fdg CSS fixes

---

arches/app/media/css/arches.css
arches/app/templates/views/search.htm

add css class specifically for search popup buttons, re #4772 [ci-skip]

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card-component.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/report-templates/default.htm

Adds border and lines UI to default reports

cherrypicks report ui border and lines into stable/4.4.x, re #5037

---

arches/app/media/css/arches.css
arches/app/templates/views/components/search/saved-searches.htm
arches/app/templates/views/search.htm

re:#5030 improve search buttons UI

---

arches/app/media/css/arches.css
arches/app/templates/views/search.htm

re:#5030 search buttons

---

arches/app/media/css/arches.css
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/templates/views/components/search/advanced-search.htm
arches/app/templates/views/components/search/saved-searches.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm

adding default panels for some search components, re #5043

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/resource/report.js
arches/app/models/graph.py

re #5045
also see archesproject/consultations-prj#105

fix errors that were exposed after creation of the grouping card component

---

arches/app/media/js/models/report.js

Fixes error when switching between report templates. re #4684

4684 tabbed reports

---

arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/map.js
arches/app/models/migrations/4990_relax_tileserver_layer_constraints.py

apologies & thanks due to @benosteen

fixes for migration and viewmodels

---

arches/app/media/js/reports/tabbed.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/report-templates/tabbed.htm
arches/app/views/graph.py

Fixes occasional errors when sorting tabs and puts icons in a dropdown. re #4684

Tabbed report improvements

---

arches/app/media/js/reports/tabbed.js
arches/app/templates/javascript.htm
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/report-templates/tabbed.htm
arches/app/views/graph.py
arches/urls.py

Gets icons from an ajax request rather than the graph designer view.

---

arches/app/media/css/arches.css

Fixes height of reports

---

arches/app/media/css/arches.css
arches/app/templates/views/search.htm

update search panel layout to allow for term search to expand gracefully

---

arches/app/media/css/arches.css
arches/app/templates/views/search.htm

fix layout issue with other pages, re #4772 [ci-skip]

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/resource-instance-select.js

change in css class for resource-creation on-the-fly styling to show above any other cards/widgets, re https://github.com/archesproject/consultations-prj/issues/45

Consultations prj 45 create resource popup 2nd fix

---

arches/app/media/js/views/components/cards/map.js

fixes popups for editing sessions

---

arches/app/media/js/views/components/cards/map.js
arches/app/templates/views/components/map-editor.htm

cancels add new geom and disables card buttons while editing geoms

---

arches/app/media/css/arches.css
arches/app/templates/views/components/widgets/resource-instance-select.htm

re:#5078 Update inline instance form UI for workflows

---

arches/app/media/css/arches.css
arches/app/templates/views/components/search/term-filter.htm

re:#5084 attribute filter ui

---

arches/app/utils/v3migration.py
arches/app/utils/v3utils.py
arches/management/commands/v3.py
tests/fixtures/v3migration-pkg/graphs/resource_models/Historic District.json
tests/fixtures/v3migration-pkg/graphs/resource_models/Historic Resource.json
tests/v3migration/v3_migration_cli_tests.py

Cherry-pick of all the commits from PR #5050. Please see that PR for more information.
#5024 
*   Sponsored by: GCI
*   Found by: @mradamcox 
*   Tested by: @mradamcox
*   Designed by: @mradamcox

5024 cherry pick to master v3v4 groupings

---

Dockerfile

New multistage Dockerfile was missing an install step for gunicorn.
#5014 

Adding missing gunicorn install step to Dockerfile

---

arches/app/media/js/views/components/cards/map.js

refactors map card

---

arches/app/media/js/models/card-widget.js
arches/app/media/js/models/card.js
arches/app/media/js/views/components/cards/grouping.js
arches/app/templates/views/components/cards/grouping.htm

allow for sorting of widgets in a grouping card component, re #4974

---

arches/app/templates/base-manager.htm

Adds check for a property in plugin json config: "show":false ... if user adds this to their json, an icon for the plugin will not show on the nav bar
https://github.com/archesproject/consultations-prj/issues/126
-   [ x] Unit tests pass locally with my changes

adds boolean check for plugin.config.show, re #126

---

arches/app/models/migrations/4907_grouping_card_component.py

update migration to add sortedWidgetIds, re #4907

---

arches/app/search/components/resource_type_filter.py

allow the resource instance node to be work properly when multiple graphs are selected

---

arches/app/media/css/arches.css
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/map.htm

re:# 5106 Ui fixes

---

arches/app/media/js/views/components/workflows/new-multi-tile-step.js
arches/app/media/js/views/components/workflows/new-tile-step.js

changes new-tile-step and new-multi-tile-step to push any saved tiles to a workflow "state" array that can be accessed by other workflow steps, such as one using get-tile-value as referenced in the companion PR in consultations-prj.
For more info see this PR: https://github.com/archesproject/consultations-prj/pull/135
https://github.com/archesproject/consultations-prj/issues/107

Consultations prj 107 calc consultation name

---

arches/app/media/css/arches.css
arches/app/templates/views/components/map-popup.htm

re: #5106 Ui fixes

---

arches/app/media/js/views/components/cards/map.js

 fixes feature ids when editing geojson in map card

---

arches/app/media/js/views/components/workflows/new-multi-tile-step.js
arches/app/media/js/views/components/workflows/new-tile-step.js

reverts changes made on this PR (#5130 ) whereby params.requirements.tiles got instantiated in newTileStep (no longer necessary)

rm params.requirements.tiles array, re #107

---

arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/widgets/map.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/widgets/map.htm

fixes for map config

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/cards/select-feature-layers.js

re: #5106 update map card vertical menu style

---

arches/app/utils/middleware.py
arches/app/views/api.py
arches/app/views/auth.py

Adds more logging to the api and auth views as well as middleware.

Improves logging 

---

arches/app/media/js/viewmodels/card-component.js

Re-adds mistakenly deleted config array

---

arches/app/search/components/resource_type_filter.py

fix issue with strange results from the resource instance search component

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/workflow.js
arches/app/templates/views/components/plugins/workflow.htm

Allows a user to navigate to a completed step or step following a completed step by clicking on an icon. #5147
Also indicates the name of a step if a user hovers over the icon.

Implements workflow nav using step icons

---

arches/app/media/js/views/components/cards/grouping.js

Fixes UI error in the graph designer when switching between default and grouping cards 
re archesproject/consultations-prj#85

Fixes error when switching between default and grouping cards

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/templates/views/components/widgets/resource-instance-select.htm

... of the resource instance widget. re #4915

Adds close button to the create instance panel

---

arches/app/media/js/viewmodels/resource-instance-select.js

Fixes issues with the resource instance widget not updating the target tile when a new instance is create. re #5081

5081 rr errors

---

arches/app/media/js/viewmodels/resource-instance-select.js

Resolves timing issue preventing values from displaying in the resource instance widget after a user has created a new resource instance. re #5195

Resolves timing issue preventing values from displaying in the resource instance widget

---

arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/templates/views/components/widgets/resource-instance-select.htm

Displays resource model name in the new resource instance widget when creating a new instance, re #5081

Displays resource model name in the resource instance widget

---

arches/management/commands/packages.py

add the ability to load search components during package load, re #4771

---

arches/app/media/css/index.css

re:#172 general ui dates

---

arches/app/templates/views/resource/related-resources/related-resources-manager.htm

Replaces hard coded media url with the static variable

---

arches/app/utils/data_management/resource_graphs/importer.py
arches/app/utils/data_management/resources/formats/rdffile.py

Adding some DEBUG and ERROR level python logging statements for the JSON-LD import process, as a single error is not sufficient to debug why a given import fails.
#5058

5058 add logging

---

arches/app/media/css/arches.css

re:#5223 Fix css issue with FDG selected node style

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/related-resources-map.js
arches/app/media/js/views/components/cards/select-feature-layers.js
arches/app/models/migrations/4989_related_resources_map_card.py
arches/app/templates/views/components/cards/related-resources-map-popup.htm
arches/app/templates/views/components/cards/related-resources-map.htm
arches/app/templates/views/components/related-resources-map-editor.htm

adds related resources map card

---

arches/app/media/js/views/components/cards/select-feature-layers.js

fixes map card error

---

arches/app/media/js/views/components/cards/related-resources-map.js
arches/app/templates/views/components/cards/related-resources-map-popup.htm

ensures only selectable features can be related

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/map.js
arches/app/media/js/views/components/workbench.js
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/map.htm
arches/app/templates/views/components/related-resources-map-editor.htm
arches/app/templates/views/components/workbench.htm

Adds workbench template for supporting complex cards such as the new map card component re #5103

Adds workbench template for complex cards

---

arches/app/media/css/arches.css

re:#5223 Fix map popup header style

---

arches/app/templates/views/mobile-survey-manager.htm
arches/app/templates/views/resource/new-editor.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm

Cherry picks removal of hard-coded media directory paths.

Cherry pick static file fix from master

---

arches/app/media/css/arches.css
arches/app/templates/views/components/search/advanced-search.htm
arches/app/templates/views/components/workflows/new-multi-tile-step.htm

re:#204 Update styling for advanced search blocks, last workflow step

---

arches/app/media/js/viewmodels/card-component.js
arches/app/templates/views/components/cards/default.htm

Reveals ids for deeply nested nodegroups and nodes.

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/map.js
arches/app/media/js/views/components/search/map-filter.js
arches/app/media/js/views/search.js
arches/app/search/components/map_filter.py
arches/app/templates/views/components/search/map-filter.htm
arches/app/templates/views/search.htm

4984 add map component to search

---

arches/app/templates/views/components/search/map-filter.htm

fix incorrect css class, re #4984 [ci-skip]

---

arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/map.js

preserves card level basemap and overlay settings for map card

---

arches/app/media/css/arches.css

re: #5223 Update mapbox gl geocode font

---

arches/app/datatypes/concept_types.py
arches/app/datatypes/datatypes.py
arches/app/utils/data_management/resources/formats/rdffile.py
arches/app/views/api.py

Some string-based datatypes were being incorrectly turned into RDFlib Literals. A faulty catch-all exception was masking the source of the errors.
#5137

Unicode export issue fix for datatypes

---

arches/app/datatypes/datatypes.py
tests/exporter/datatype_to_rdf_tests.py

It was possible for a blank value for an integer to be exported as having a false value of 'None' in the export.
#5097 

Skip any 'None' Literal valued triples in the JSON-LD export (#5097)

---

arches/app/templates/base-manager.htm

checks if a plugin config property exists while iterating through plugins in base-manager

checks whether plugin.config exists before accessing plugin.config.show

---

arches/app/media/js/views/components/widgets/map.js

fixes map editing errors

---

arches/app/media/css/arches.css
arches/app/media/css/index.css
arches/app/templates/views/components/search/map-filter.htm
arches/app/templates/views/components/search/resource-type-filter.htm
arches/app/templates/views/search.htm

re:#5276 fix css issues

---

arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/plugins/workflow.htm

Deletes resources and tiles designated in a step's wastebin. re #5190

---

arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js

Allows a user to quit a workflow clearing the workflow instance 

---

arches/app/media/js/viewmodels/file-widget.js

It is currently not working properly, so it should be suspended until #4921 is completed or the config is removed entirely.

Temporarily removes file number constraint, re #4921

---

arches/app/media/js/viewmodels/workflow.js

The default is set to the home page.
re #5190

Allows workflows to override the destination page when a user 'quits'

---

arches/app/media/css/arches.css

re: #5276 Update workflow body background color

---

arches/app/media/js/views/components/cards/map.js

updates map card component

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/select-feature-layers.js

re:#5291 update workflow navbar

---

arches/app/media/js/viewmodels/resource-instance-select.js

Fixes error causing 'new' form panel to appear. re #5265

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/media/js/views/graph/graph-designer/node-form.js

Adds a conditional check specific to the descriptor function (to prevent viewmodels from breaking when other functions are loaded)

checks for specific descriptor function

---

arches/app/templates/views/components/workflows/new-multi-tile-step.htm

Fixes issue with missing notification banner in multi tile step

---

arches/app/models/concept.py
arches/app/models/resource.py
arches/app/utils/data_management/resources/formats/csvfile.py
arches/app/utils/skos.py
arches/management/commands/packages.py
arches/settings.py

Salinas hack trip performance improvements

---

arches/app/media/js/viewmodels/workflow.js
arches/app/templates/views/components/plugins/workflow.htm

Notifies user that they are deleting tiles or resources when quitting a workflow. re #5273

Notification banner in workflows

---

arches/app/media/css/arches.css
arches/app/media/js/reports/tabbed.js
arches/app/media/js/viewmodels/tabbed-report.js
arches/app/templates/views/report-templates/tabbed.htm

re archesproject/consultations-prj#242

intial work on tabbed report extensions

---

arches/management/commands/packages.py

add_mapbox_layer now has a try block to see it can get "name" from style json file.
If not, it will not load the layer and continue to the next layer files

5260 improve load mapbox styles

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/resource-instance-select.js

also, fixes resource instance select display value

style updates for tabbed report

---

arches/app/media/css/arches.css

re: archesproject/consultations-prj#242

consultation status styles

---

arches/app/media/js/views/components/search/map-filter.js
arches/app/media/js/views/components/search/search-results.js
arches/install/yarn.lock

5322 refactor search components

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/tabbed-report.js
arches/app/templates/views/report-templates/tabbed.htm

re: archesproject/consultations-prj#242

adds support for tab empty component

---

arches/app/media/js/models/card-widget.js

Fixes issue with values getting duplicated across sibling tiles. 

---

arches/app/media/js/models/card-widget.js

Fixes issue with values duplicating across sibling tiles. re #4304

Merges cherry pick from master. re #4304

---

arches/app/media/css/arches.css

small styling fixes related to search and border build up, re #4771

---

arches/app/media/js/bindings/ckeditor.js

Fixes bug preventing dirty state from activating in the rich text widget. re #5235

Cherry picks fix for #5235 from master
