archesproject/arches

arches/app/media/js/views/map.js

modify two functions so that firefox can interpret the pixel position correctly.

change to firefox compatible event properties

---

arches/app/models/graph.py
arches/app/views/graph.py
tests/models/graph_tests.py

re: #559
should we allow the name of the root node of a graph to ever be different from the name of the graph itself?
Currently these are distinct values (`nodes.name` and `graphs.name`), and are assigned independently in the UI… I’m wondering if perhaps we should just always keep these two values in sync (and, thus, [potentially] remove `graph.name` entirely….).

assigning graph name to node name on update

---

arches/app/models/graph.py
arches/app/models/models.py
tests/models/graph_tests.py
tests/views/graph_manager_tests.py

this is motivated to a bug found recently where is_collector was being accessed as a property causing unexpected behavior

making node.is_collector a property

---

arches/app/media/js/models/graph.js

Graph model was modifying values in the input array (updating node objects in the incoming list with `NodeModel` instances) which was transforming the source branch viewmodels.
This was causing a bug when a user added multiple cards to a given resource without refreshing the card manager page.
Changed this to not update the source array and instead create a new array of `NodeModel` instances.

fixing bug with adding multiple cards

---

arches/app/models/migrations/0001_initial.py
arches/app/models/models.py
arches/db/dml/db_data.sql

removing `widgets_x_datatypes`, instead, managing foreign keys on those tables
this includes support for a `defaultwidget` for each datatype
re: #620

refactoring widget & datatype relationships

---

arches/app/media/js/bindings/sortable.js
arches/app/media/js/models/card-widget.js
arches/app/media/js/models/card.js
arches/app/media/js/views/graph/card-configuration/card-components-tree.js
arches/app/media/js/views/graph/card-configuration/card-form-preview.js
arches/app/templates/views/graph/card-configuration/card-components-tree.htm
arches/app/templates/views/graph/card-configuration/card-form-preview.htm

re: #627 #620
enable drag and drop sorting in card preview and tree
`sortorder` values are being managed on all client side view models during sort, but widget records are not yet being saved to the db, so the `sortorder` value for widgets is not yet stored when you click 'Save'

card tree and preview sorting

---

docs/getting-started.txt

I did a fresh install on an ubuntu server to get these numbers, all in mb:
df -hm
fresh: 6711
dependencies installed: 5513
virtualenv with arches/arches_hip installed: 5338
new app with ES setup: 5302
new app package fully installed (no resources): 5288
results
1198 for all dependencies (so I'm thinking 1.5gb)
175 for code prior to installation
225 for code/db after a package has been installed (so 300 to play it safe?)

update documentation on minimum system requirements

---

arches/app/models/graph.py

Fixes graph validation bug that wouldn't allow user to save graph if the top node was not semantic. The top node only needs to be semantic if you are creating a resource.
Bug fix
#771

Fixes #771

---

arches/app/utils/data_management/resource_graphs/exporter.py
arches/app/utils/data_management/resource_graphs/importer.py
arches/app/views/graph.py
arches/db/branches/Activity Phase.json
arches/db/branches/Appellation.json
arches/db/branches/Beginning of Existence.json
arches/db/branches/Condition Assessment.json
arches/db/branches/External Resource.json
arches/db/branches/Information Carrier.json
arches/db/branches/Keyword.json
arches/db/branches/Language.json
arches/db/branches/Name.json
arches/db/branches/Publication Event.json
arches/db/branches/Resource Creation Event.json
arches/db/branches/Resource Type Classification.json
arches/db/branches/Right.json
arches/db/branches/Temporal Coverage.json
tests/fixtures/resource_graphs/archesv4_resource.json

Adds cards_x_nodes_widgets data to import/export. This commit will break import of resource models or branches that do not have a cards_x_nodes_x_widgets property in their graph object.
"cards_x_nodes_widges": [],
re #1010

Add cards_x_nodes_x_widgets data to graph export and graph import.

---

arches/app/media/css/arches-nifty.css
arches/app/media/js/widgets/map.js
arches/app/templates/views/forms/widgets/map.htm
arches/db/dml/db_data.sql

Made features that had been saved in a form editable when the form is reopened. 
Now showing resource layer instance features as an overlay in the report - not in the form where the resource instance is represented as the draw layer.
Switched the map tools from divs to lists to maintain proper spacing when the drawing tools are not included in a report. 
Added unselected icon to basemap switcher. re #723

723 geom widget

---

arches/app/media/plugins/knockout-select2.js
arches/app/templates/views/forms/widgets/select.htm

optionally bubbling click events in select binding to parent element on open of select dropdown
using this to drive select of widget in card manager on click of dropdown as select2 v3 doesn't support native events, such as click (which are supported in select2 v4)
fixes #1099

concept widget bug

---

arches/app/media/css/arches-nifty.css
arches/app/media/js/views/base-manager.js
arches/app/templates/views/graph.htm
arches/app/templates/views/graph/graph-settings.htm
arches/app/templates/views/resource.htm

Disables 'create resource' button and list options for resource models in the resource manager that do not have forms or are not-editable. Change resource model status from 'active/inactive' to 'editable/non-editable'.
Fixes #943

943 inactive resource models bug

---

arches/app/media/js/models/graph.js

Fix issue where Arches would hang when you tried to delete a node in a graph with a defined ontology.
Modify getParent function in graph.js to return passed in node if edge to find parent node does not exist.
fixes #1062

1062_ontology_node_delete_bug

---

arches/app/media/css/arches-nifty.css
arches/app/templates/base-manager.htm
arches/app/views/base.py

Disable create resource instance links in lefthand vertical arches menu. Add ‘arches-menu-item-disabled’ class to when link is disabled.
Disables 'create resource' link in the vertical resource instance menu on the lefthand side of the page when a resource either does not have forms, all forms are not visible, or the resource is inactive.
#948 #1311

948_missing_hidden_forms_bug

---

arches/app/media/js/widgets/map.js

re: #1315 
Currently, this causes the map to flicker, but this should be resolved in the next version of mapbox-gl-js:
https://github.com/mapbox/mapbox-gl-js/pull/3621

resource tile refresh

---

arches/app/media/js/widgets/map.js
arches/management/commands/packages.py

adding a command to add a layer from a mapbox style json.
For example, to add a basemap run the following:
```sh
python manage.py packages -o add_mapbox_layer -j /path/to/style.json -n my-new-basemap -b
```
To add an overlay, remove the `-b` (this feature also works for making tile server layers into basemaps using the `add_tileserver_layer` command):
```sh
python manage.py packages -o add_mapbox_layer -j /path/to/style.json -n my-new-overlay
```

Add mapbox layer command

---

tests/ui/page_elements/element_locators.py
tests/ui/page_tests.py
tests/ui/pages/form_page.py
tests/ui/pages/page_locators.py
tests/ui/pages/report_editor_page.py

This fixes #1505.
For some reason, Chrome Crashes when you use spaces in text fields while doing these tests.  The current workaround is removing theses spaces.

1505 fix ui tests

---

arches/app/media/css/arches-nifty.css
arches/app/templates/views/forms/widgets/map.htm
tests/ui/page_tests.py

…appears during ui tests. The scroll bar was masking the button preventing the overlay library from opening. Also did a little clean up in page_tests.py

Moved the button to open the overlay library out from under a scroll bar that briefly

---

arches/app/media/js/views/graph/card-configuration-manager.js
arches/app/models/card.py
arches/app/templates/views/graph/card-configuration-manager.htm
arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm
arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm
arches/app/views/graph.py
arches/app/views/resource.py

Creating a graph proxy model for every card in a report was slowing down report rendering.  To avoid creating a graph model I moved the creation of the ontology_properties list from card proxy model to the card view.  I also added ontology_properties and ontologyproperty to the card-configuration-manager view model.

1491 slow reports

---

arches/app/templates/base-manager.htm
arches/app/views/base.py

changed the nav configuration settings to show the recent edit buttons by default, and add filter in the menu to disable if user is not part of the 'edit' group.
takes care of #1573

1573 recent edits button on nav bar

---

arches/app/utils/data_management/resource_graphs/exporter.py
arches/app/views/graph.py

Concept lookup file will help with mapping value labels to valueids. Remove unnecessary keys from import/export mapping file.
The 'create mapping file' command now downloads a zip file with both the mapping file and the lookup file within it.
re #1643

Create concept lookup file that is downloaded with graph mapping file

---

arches/app/media/js/views/components/widgets/map.js

Expanding the map was causing numerous moveend events to fire and consequently too many searches overwhelming the browser. Firing search by extent handler when specific map events fire (pitch, dragend, rotateend) rather than the general moveend event. re #1717

Map Search Issues

---

arches/install/requirements_dev.txt

Just found out I'm using at least one sphinx tag (caption) that is only supported in a later version of sphinx. updating requirements_dev.txt as necessary.

update sphinx version

---

arches/app/datatypes/datatypes.py
arches/app/media/js/views/components/widgets/csv-chart.js
arches/app/media/js/views/components/widgets/file.js
arches/app/media/js/views/resource/editor/form.js

Added an isParent property to tiles in form.js so that widgets are aware of whether a tile is a parent. Also fixed a bug in the csv_chart widget that prevented files from clearing when a user would click cancel.

1738 xychart widget

---

arches/app/media/js/views/graph/datatypes/domain-value.js

Fixed missing 'remove' error when saving nodes with domain datatypes

---

arches/app/templates/help/settings-help.htm
arches/app/templates/views/graph.htm
arches/app/templates/views/graph/graph-settings.htm

Revert graph status labels to 'Active' and 'Inactive' in the graph manager.
re 1378

Revert graph/branch status labels to ‘Active’ and ‘Inactive’

---

arches/app/media/css/arches.css
arches/app/templates/views/graph/graph-base.htm

re #1313, #1654
Adjusted z-index of the Find input element in Arches Designer and resolved the issue of scrollbars scrolling past the bottom of the page in the Arches Designer panels. 
- [x ] Bugfix (non-breaking change which fixes an issue)

Obscured nav menu and arches designer scroll bar issue

---

arches/app/media/css/arches.css

Removed the min-height property from the center panel because it was preventing users from scrolling to the bottom of the panel. re #1654
- [ x] Bugfix (non-breaking change which fixes an issue)

Enabled scrolling to the bottom of the center panel.

---

arches/app/media/js/views/components/widgets/map.js

Removed the reset of the view model's value property when switching draw tools. Resetting the value no longer appeared need and it was causing the searchAggregations subscription to fire which subsequently caused the zoom level to reset to the bounds of the data. re #1959 
- [x ] Bugfix (non-breaking change which fixes an issue)

Prevented fitting to bounds when a user switches draw tools in search

---

arches/app/media/js/views/components/widgets/map.js

Zoom to search results without a search feature. Supports zooming to save searches without a map filter, re #1335

Zoom to saved search results without a map filter

---

arches/app/utils/context_processors.py
arches/app/views/tileserver.py
arches/db/system_settings/Arches_System_Settings.json
arches/db/system_settings/Arches_System_Settings_Model.json
arches/settings.py

Simplified settings by removing tile cache settings from the system_settings, made sure system_settings have precedence over settings.py settings, removed DEFAULT_MAP_CENTER and HEX_BIN_BOUNDS settings from settings.py as they are now handeled by DEFAULT_MAP_BOUNDS, re #346.

Simplification of system settings to prevent bugs and user errors

---

arches/app/media/js/views/resource/editor.js

Moved loading mask to the panel containing cards when switching menus, re #937

Limiting loading mask to card panel in resource editor when switching menus

---

arches/app/views/graph.py

Added sortorder to newly added forms so that the most recently added form has a sortorder value when forms are sorted on the client, re #2013

Fixed menu sort order after a new menu is added in the form manager

---

arches/app/models/card.py

re: #2093
some benchmarking - before this change: 
```
8562773 function calls (8357766 primitive calls) in 21.007 seconds
Ordered by: internal time, call count
List reduced from 957 to 25 due to restriction <25>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
12287    5.308    0.000    5.472    0.000 /Users/rgaston/Projects/arches4/arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/backends/utils.py:58(execute)
366557    0.568    0.000    1.020    0.000 /Users/rgaston/Projects/arches4/arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py:469(__eq__)
157441/125442    0.428    0.000    1.997    0.000 /Users/rgaston/Projects/arches4/arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py:361(compile)
32323    0.420 …
```

report performance optimization

---

arches/app/media/css/arches.css
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/templates/views/resource/related-resources/related-resources-manager.htm

Clearing relationship properties form when a user closes it.
Added a column for the selected row indicator in the related resources table.
Disabled the relationship properties form button when no rows are selected.

2108 relationship properties form

---

.travis.yml

Add postgresql-9.6-postgis-2.3 to the list of addon packages for postgres in the travis.yml file.

Fix for travis postgis 2.3 build error

---

arches/app/media/css/arches.css
arches/app/media/js/models/report.js
arches/app/templates/views/report-templates/default.htm
arches/app/templates/views/resource/report.htm
arches/app/views/resource.py

Added related resources in reports - each listed under their corresponding resource model name along with their relationship type and display name. Each related resource display name links to its own report as in v3. re #1657.
Also replaced some hard-coded references to 'en-US' with the language code defined in settings.py

1657 related resources in reports

---

arches/app/views/resource.py

Changed the required group for the ResourceReportView from 'Resource Editor' to 'Guest' so that guests are not redirected to the login page when trying to view a report. re #1635

Made reports readable by guest users

---

arches/app/templates/views/report-templates/default.htm
arches/app/views/resource.py

Allowing Resource Editors as well as Guests to access reports.
Informing users in reports when they do not have permissions to see card data.

1635 permissions reports

---

arches/app/media/js/views/components/widgets/map.js

Closing and clearing the geojson input when a user cancels or saves a card, re #1990

Clear geojson in map widget

---

arches/app/media/js/views/components/widgets/map.js

Replaced setStyle with setFilter in the highlightResource function, and replaced setStyle with setPaintProperty in the updateOpacity method.
Fixes flickering of raster tiles when changing opacity or hovering over a resource.

1995 raster flicker

---

arches/app/templates/help/system-settings-help.htm

Changes made:
Default Data Import/Export User as described above
Reformatted map zoom section into properties
Reformatted Basic Search settings to include "Number of search hints shown in dropdown".
However, looking closer at Basic Search settings led to #2262, so I have commented out the lines for "Max search results to export" with the expectation that that setting will be removed or perhaps altered.
Removed time wheel configuration entry.
Add properties for hex bin settings

2152 settings help updates

---

arches/install/arches-project
arches/install/arches-templates/project_name/settings.py-tpl

Added arches.log file and arches logs directory to the arches project template, re #2274 
Added the arches.log path to the settings.py template so that it is available in a users project rather than their virtualenv.

Added arches.log file and arches logs directory to the arches project

---

arches/install/arches-templates/project_name/system_settings/readme.txt
arches/management/commands/packages.py
docs/create-package.txt

re #2335 
- Adding .gitkeep to empty package directories created by the create_package command so that git recognizes them.
- Handling for cases when a user tries to create a package from a project without having first created a database for their project.
- Added documentation for developers that are creating projects from their development arches directory.

Adding .gitkeep to empty package directories

---

arches/app/media/js/views/components/datatypes/concept.js
arches/app/media/js/views/components/datatypes/domain-value.js
arches/app/media/js/views/components/datatypes/resource-instance.js
arches/app/media/js/views/graph/card-manager.js
arches/app/media/js/views/graph/graph-manager/node-form.js
arches/app/models/card.py
arches/app/models/graph.py
arches/app/models/models.py
arches/app/templates/help/card-manager-help.htm
arches/app/templates/help/graph-designer-help.htm
arches/app/templates/views/graph/card-manager.htm

re #2342. 
Relaxed resource model restrictions for models with instances by:
- allowing users to delete cards and nodegroups that do not have data saved against them
- allowing users to modify the configs of nodes that belong to nodegroups that do not have data saved against them
- allowing users to add new cards/branches

2342 allowable card edits

---

arches/app/views/resource.py

re #2300, Fixed bug in reports causing error when resource relationships are semantic properties

Fixed resource report bug when resource relationship is a semantic property

---

arches/app/models/resource.py

re #2112, Resolved `unexpected keyword argument 'id'` error in related resource search by checking for instance ids before performing search.

Related resource search error

---

arches/app/views/graph.py

re #1129
Changed card navigation behavior so that if a user is on a branch card configuration page and changes the graph to a resource model, the app navigates to the card manager for that resource model.
Conversely, if a user is on the card manager for a resource model and switches the graph to a branch, the app navigates to the card configuration manager for that branch.

1129 model workflow - card navigation improvements

---

arches/app/utils/data_management/resource_graphs/exporter.py
arches/management/commands/packages.py

Add ability to export multiple graphs at once
`python manage.py packages -o export_graphs -d /path/to/destination/directory -g graphid, 'branches', 'resource_models', 'all'`
#1361

Add ability to export multiple graphs at once re #1361

---

Dockerfile
docker/entrypoint.sh

This PR enables the user to run our Arches Docker image in production mode using Gunicorn.
Add Gunicorn package. 
Run gunicorn when MODE=DEV, re #2569
Before Arches container always ran the development server. Not safe for production.

Enable running Arches under Gunicorn production server

---

arches/management/commands/packages.py

Previously, `python manage.py packages -o load_package` would only accept a zip file or a url that pointed to a zip file, it was not possible to load a package that had not been zipped up. This was difficult for development.  This commit is a refactoring of the load_package command to unify the way sources are handled and allow you to use the command with an unzipped package directory stored locally.
I tested this by using the test-package-load repo as a source in all three different forms.
`python manage.py packages -o load_package -s http://github.com/archesproject/test-package-load/archive/master.zip`
`python manage.py packages -o load_package -s "C:\arches\fpan\repo\fpan\_pkg_171018_171820\source_data.zip"`
`python manage.py packages -o load_package -s …

refactor load_package to allow package source from directory

---

arches/app/media/css/arches.css

Added position: relative to the widget-wrapper class, as the asterisk widget for required fields has position: absolute, which was causing it to have a fixed position on the page.
#2576 
2 Unit tests fail, but they failed before I had made any changes. Unsure if this is to do with issues with my local system, but it's doubtful that this change would be enough to cause those tests to fail.

Asterisks scroll with page movement inside wrapper - issue #2576

---

arches/app/media/js/models/project.js
arches/app/templates/views/project-manager.htm
arches/app/views/user.py

Formatting improvements to the project manager people tab, re #2581
Within the project manager's people tab: 
1. Fixes date formatting in the group user list
2. Automatically loads the first identity when loading the project manager
3. Uses the unfiltered user list when selecting a user from the identity list (left panel) rather than a group.

2458 project summaries

---

docker/entrypoint.sh

Set workdir to arches root before running `setup_db` AND `set_dev_mode`. 
Move run_migrations to `setup_arches` command, re #2646
Workdir was not set in entrypoint.sh (Docker) before running setup_db.
When the workdir is changed, e.g. by a custom arches project, then setup_db is run from the wrong folder, leading to unpredictable behavior (e.g. django migration order gets messed up).
Additionally, Django migrations were being run on every startup (when MODE=DEV). Changed this to run only once by incorporating the `run_migrations` command in the `setup_arches` command.

Set workdir for `setup_db`, change when run_migrations is called

---

arches/app/datatypes/concept_types.py

This is a small addition to the error handling that happens during upload, specifically with regard to label-based concepts and concept-lists. A new error message has been added to indicate that a bad prefLabel has been provided, in order to distinguish this scenario from a situation in which an incorrect UUID has been provided.
This is a not a far-reaching fix, but serves to address issue #2666 
Much more could be done to unify the error messages and validation functions that occur during upload. This is just a targeted fix for a recorded issue.

#2666 add error message for invalid preflabels in a concept-list

---

arches/app/views/graph.py

Fixes #2744
Wraps the ontology prefixes in a `str()` function to avoid raw Python unicode strings, which cannot be parsed a JavaScript parser.
Fixes #2744

fixes raw unicode string in ontology prefixes for non-CRM ontologies.

---

arches/app/media/js/models/card-widget.js
arches/app/media/js/models/card.js
arches/app/models/card.py
arches/app/templates/views/resource/editor/form.htm

Adds a disabled property to the Card proxy model which is passed to the front-end card model and made available in the widget parameters. This value is set to `true` in the card proxy model if a user only has read permissions for a given nodegroup. re #2710

2710 - disabled state

---

arches/app/templates/views/components/widgets/number.htm

Adds the disabled attribute to the number widget setting the input as disabled if a user does not have write permissions for the widget's nodegroup. re #2697

Added the disabled attribute to the number input. re #2697

---

arches/app/templates/views/resource/editor.htm

Fixes issues with special characters in a displayname that would prevent displaynames passed to the browser as JSON to be invalid.

Allows displaynames to safely load in the resource editor.

---

arches/app/templates/views/graph/card-configuration/card-form-preview.htm
arches/app/templates/views/resource/editor/form.htm

Hides card's save/edit buttons when a card is disabled.  This prevents the save button from appearing when a widget has a default value.  #2710

Hides card's save/edit buttons when a card is disabled. 

---

arches/app/datatypes/datatypes.py
arches/app/media/js/views/components/widgets/number.js
arches/app/models/migrations/2591_formatted_numbers.py
arches/app/templates/views/components/widgets/number.htm

Adds configs to the number widget allowing a graph editor to define units (as a prefix or suffix), specify the increment, and set the max number of values behind the decimal place. re #2591

Number widget formatting configs

---

arches/install/arches-templates/project_name/settings.py-tpl
arches/management/commands/packages.py

Sets the index prefix to the project name when creating a new project. re #2812

Sets the index prefix to the project name when creating a new project

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/widget.js
arches/app/templates/views/components/widgets/map.htm

Adds disabled state to map widget. re #2698
Also fixes `value.subscribe` error when loading reports

2698 disable map widget

---

arches/app/views/tile.py

Ensures settings are refreshed from the db when a tile is deleted

Ensures settings are refreshed from the db when a tile is deleted

---

arches/app/views/tile.py

Removed call to update_from_db when the datatypes of tile.resourceinstance_id and settings.RESOURCE_INSTANCE_ID differ to prevent errors in the map layer manager.

Reversed allowing call to update_from_db

---

arches/app/media/js/models/graph.js

Adds ontology namespaces to newly created nodes in the graph manager making them available to the node model's "getFriendlyOntolgyName" method. re #2856

Displays user friendly ontology classes and properties in the graph manager node form

---

arches/app/utils/data_management/resources/formats/csvfile.py

This pull request adds some more explanatory error messages to the import log if an elasticsearch geometry error is encountered during business data import. Previously, an ES geometry indexing error was reported in the console and would break the import process. Now, lines like the following are added to the `resource_import.log` which is where import errors are recorded:
```
Thu Dec 21 07:10:28 2017 WARNING: 2017-12-21 09:10:28.639000: WARNING: failed to index document in resource: 48b572bc-b513-4a78-8f25-eaea4ed6bf52. Exception detail:
{
"reason": "Provided shape has duplicate consecutive coordinates at: (-82.3241091909999, 29.622251416, NaN)", 
"type": "invalid_shape_exception"
}
```
A whole lot more could be done to unify and improve the error handling during import. This is just a …

Add es import error messages

---

arches/app/templates/views/graph/graph-manager/node-form.htm

Button for adding node to resource graph now has the tooltip "add branch" rather than "add child node" to make terminology clearer to users.
#1036

Change tooltip for adding node to resource graph to "add branch" #1036

---

arches/app/views/tile.py

Ensures comparison of both instance ids are strings upon deletion of a system settings tile, re #2957

Enables deletion of saved searches

---

arches/app/media/css/arches.css

Adding a minimum height into the css of a flex box bypasses a bug in firefox that causes it to not create custom scrollbars.
#1989

Add min-height to flex class to allow scrollbars in firefox #1989

---

arches/app/models/graph.py
arches/app/views/graph.py

Fixes bug preventing cards/nodegroups from being flagged as non-editable and fixes error preventing users from adding cards to resource models in the card manager. re #3027, #3026

3026 resource model lock bug

---

arches/app/views/search.py

Prevents error when filtering provisional data from search results. However, it also prevents non-reviewers from seeing resource instances with partial results. re #2975

Temporary fix for partial results error re #2975

---

arches/app/templates/base.htm

Internet Explorer shims added to base.htm head so that Internet Explorer users can use the search page features.
#2993

Add shims to base.htm head for IE to use search page #2993

---

arches/app/templates/views/resource/editor/form.htm

Displays cancel button for provisional user's provisional child tiles re #2974

Fixes display of cancel button in resource editor for provisional users

---

arches/app/models/models.py

Sets sortorder on provisional tiles ensuring they appear at the end of a list of child tiles. re #2974

Sets sortorder on provisional tiles

---

arches/app/views/concept.py

Adds 'identifier' as a possible value type in the concept value form allowing users to specify and external reference as an identifier. re #22

Adds 'identifier' to the list of value type options in the RDM. re #22

---

arches/app/media/js/views/components/widgets/map.js
arches/app/media/js/views/map-layer-manager.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/widgets/map.htm
arches/app/views/main.py
arches/management/commands/packages.py
arches/settings.py
arches/urls.py
docs/installation.txt

Allows users to specify a property in the vector overlays with custom html (as a string or requested via ajax from a url) for display in the map popup.  Also ensures that tileserver config files will use the project database rather than the arches database. re #2549

Custom map popup content

---

arches/app/datatypes/base.py
arches/app/models/card.py
arches/app/models/tile.py
arches/app/views/base.py
arches/app/views/resource.py
arches/app/views/search.py
arches/app/views/tileserver.py

Relies uses id rather than objects when calling user.has_perm. This prevents unnecessary calls to the db. re #3071.
Also - Fixes unassigned variable in reports and when getting map sources in the base datatype - only queries for relevant tiles when 'Preview' is true.

Index permissions

---

arches/app/media/js/views/search/search-results.js
arches/app/models/graph.py
arches/app/templates/javascript.htm
arches/app/templates/navbar/resource-manage-menu.htm
arches/app/views/resource.py
arches/urls.py

Handles for errors when navigating to a resource instance report of a model that does not have an active report.
If there is not report available for a resource's model and a user tries to open a report:
- In search they will see an alert notifying them that no report is available.
- In the resource editor, the `Jump to Report` link is disabled (with text reading that no report is available)
- Navigating directly from the url, the appl will navigate to a 404 page with a message stating that the resource has no report.

3118 missing report error

---

arches/app/datatypes/concept_types.py
arches/app/utils/data_management/resources/formats/archesfile.py

Fix issue where parent tiles were trying to be saved after child tiles and throwing an error with json import.
#2882

Order list of tiles so parent tiles are imported first, re #2882

---

arches/app/media/js/views/components/widgets/map.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/widgets/map.htm
arches/app/views/main.py
arches/management/commands/packages.py
arches/settings.py
arches/urls.py

Allows users to define custom html content for map pop-ups. Also ensures that tileserver layers that read from postgres, read from the default project database. re #2549

2549 4.1.x custom popup

---

arches/app/templates/views/search/search-base-manager.htm

Abbreviates a resource name in the resource filter list with an ellipsis if the name is longer than 55 char. re #3124

Handles for long resource names in the resource instance filter

---

arches/app/templates/views/search/search-base-manager.htm

Truncates the name and addes an ellipsis if the name is longer than 55 char. re #3124

Handles for long resource model names in the resource instance filter

---

arches/app/models/mobile_survey.py
arches/app/views/search.py

Fixes error when defining search perimeter with the survey perimeter rather than a search filter perimeter. #3147 
Ensures bounds returned from the mobile survey api are JSON rather than a string.

3147 save resource tiles to couch

---

arches/app/media/js/views/components/datatypes/resource-instance.js

Makes 'createableResources' available to the resource instance datatype (rather than graphs which were removed to reduce db queries and payload). re #3221, #3105

3221 missing resource types in resource instance datatype

---

arches/app/models/resource.py
arches/app/models/tile.py

Moves logic to prevent indexing of system settings from the tile to the resource model to ensure settings are never indexed. re #3244

Ensures system settings are not indexed

---

arches/app/media/css/arches.css

Prevents resource model list from extending under nav bar when resource names are long and user is logged out. re #3124

Resource model filter list formatting

---

arches/app/media/js/viewmodels/graph-settings.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-settings.js
arches/app/media/js/views/graph/graph-tree.js
arches/app/templates/base-manager.htm
arches/app/templates/views/graph-designer.htm
arches/app/views/graph.py

Updates the root node name when a user modifies the resource model name, Prevents user for switching nodes when the graph settings are dirty. Updates the icon and resource model name in the page title when a user changes those graph properties, re #3202, #3199

Sets root node name to the graph name

---

arches/app/media/js/views/components/widgets/map.js
arches/app/templates/views/components/widgets/map.htm

Changes popup content property from 'arches_description' to 'feature_info_content', re #2549

Custom popup property name change for 4.1.x

---

arches/app/media/js/models/graph.js
arches/app/media/js/viewmodels/graph-settings.js
arches/app/media/js/views/graph-designer.js
arches/app/media/js/views/graph/graph-designer/node-form.js
arches/app/media/js/views/graph/graph-manager/node-form.js
arches/app/models/graph.py
arches/app/templates/views/graph/graph-designer/graph-settings.htm
arches/app/templates/views/graph/graph-designer/node-form.htm
arches/app/templates/views/graph/graph-manager/node-form.htm

Fixes the display of ontology options in the node form when a user changes the ontology of the graph settings. Also disables the ontology options in the graph settings form once an ontology is defined for the graph and nodes are added. re #3199, #3202

3199 graph settings

---

arches/app/media/js/views/search/search-results.js
arches/app/views/search.py

Filters points on permitted nodegroups so that the search map does not automatically zoom to data a user is not permitted to read. re #2492

Filters points on permitted nodegroups, re #2492

---

arches/app/media/js/viewmodels/node-value-select.js

Fixes reference to resourceinstanceid (broke because instances are now created after a tile is saved rather than when the resource editor page is loaded), re #3219

Populates node datatype dropdown 

---

arches/app/media/js/viewmodels/node-value-select.js

Fixes reference to resourceinstanceid (broke because instances are now created after a tile is saved), re #3219

Fixes missing options in node datatype dropdown

---

arches/app/models/migrations/2891_adds_tile_provisional_json.py

Removes reindexing of resources after addition provisional column due to a conflict between new and old versions of the graph model re #3199
Users will need to run `python manage.py es index_resources` to update their resource index with the `provisional` flag after migration.

Removes reindexing of resources after addition of the provisional column

---

arches/install/requirements_dev.txt

Now that we have the documentation in a different repo, we don't need `sphinx` in the dev requirements.txt file.

remove sphinx as all docs now elsewhere

---

arches/app/media/js/views/resource/editor/form.js

Fixes dirty state when provisional user saves an edit to a card in a card container, re #3481

Fixes dirty state of card container for prov users 

---

arches/__init__.py
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

Replaces authoritative data in a tile with a user's provisional data if a user is a provisional user and removes provisional data of other users if a user is provisional. re #3385.
This allows provisional users to see their own edits (and nobody else's) displayed in the resource editor. 
Also updates the Arches version number to 4.3.

3385 provisional in new editor

---

arches/app/templates/views/graph/graph-designer/graph-tree.htm

Move the delete node icon to the far right on the graph manager node 
#3545

Graph Manager: move delete icon node to far right RE: 3545

---

releases/4.2.0.md

The urls in the documentation links and the release date needed to be updated.

update date and urls in 4.2.0 release notes

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/new-provisional-tile.js
arches/app/templates/views/resource/new-editor.htm
arches/app/views/resource.py

Moves the provisional edit panel to the left of its card, indicates to the reviewer that a tile is entirely provisional (has no auth data saved to it), and prevents provisional users from seeing the provisional tiles of other provisional users. re #3385.

Moves provisional edit panel to the left of it's corresponding card

---

arches/app/media/js/views/resource/new-editor.js

In the resource editor - replaces the add-resource url with an instance's editor url once a tile is saved re #3569

Replaces the add-resource url with an instance's editor url once a tile is saved

---

arches/app/media/js/models/graph.js
arches/app/models/graph.py
tests/models/graph_tests.py

Remove restrictions on appending graphs to non-resource nodes
#3397 

Remove restrictions on appending graphs to non-resource nodes, re #3397

---

arches/app/models/graph.py
arches/app/views/graph.py

To give time to allow all resources to be removed, set the graph as
inactive before starting.
Allow the deletion of a Resource Model with instances associated with it.
#3574

Set graph as inactive before deletion #3574

---

arches/management/commands/whatisthis.py

UPDATE: please check comments below.
This management command will take a given uuid and return information about what that uuid refers to in your database. At present, all it does is return the name of the table that the uuid can be found in, and the contents of the corresponding row. It would be great to instantiate an actual object and return its properties as well, but that would be a lot more work, as I didn't see any standard way of linking a django model with an arches model.
This command could become the basis of a new view/url in the future as well, which would return a json response and/or help create a top-level utility which would take in any uuid and return the corresponding arches object.
Thanks @adamlodge for the kernal of sql to get this going.
input:
`python manage.py …

add new management command that finds a uuid in your db

---

arches/app/media/css/arches.css
arches/app/templates/views/resource/new-editor.htm

Disables the related resources node in the resource editor's card tree until a user saves a tile (because that's when a resource is create to relate against). re #3604

Disables related resource node in editor tree until resource instance exists

---

arches/app/media/js/viewmodels/resource-instance-select.js

Prevents resource-instance-search widget from closing when a user selects a resource instance. re #3604

Keeps resource instance search widget open during multiselect

---

arches/install/requirements.txt

Removes the `pycrypto` requirement
#3704 
Existing installs will need to run the following commands:
1. `pip uninstall pycrypto`
2. `pip install pycryptodome --force-reinstall`

Remove pycrypto #3704

---

arches/app/media/js/views/graph-designer.js

Prevents empty error panel when a user saves a node if the server response does not have a 'success' property. re #3749

Prevents empty error when saving a node.

---

arches/management/commands/packages.py

adds a command line operation to delete mapbox layers, mimicking existing operation for deleting tileserver layer. (these two could be combined in the future.)
#3526 
*   Sponsored by: Legion GIS

add operation for deleting mapbox layer #3526

---

arches/app/media/js/bindings/slide.js
arches/app/templates/base-manager.htm

Prevents the 'slide' custom knockout binding from displaying in-app help on page load. re #3712

Hides in-app help on page load

---

arches/app/models/card.py

Prevents a node's parent edge ontology property from being saved as `None` when saving a card re #3811 .

3811 missing node ontology properties

---

arches/app/models/graph.py

Allows a user to add a node to a resource model with instances. Prevents appending a node to a node that already has corresponding tile data. re #3777

Allows user to add nodes to a resource model that already has instances

---

arches/app/templates/views/components/cards/default.htm

Changes widget selection status to `true` only when status is not true. Prevents issues with click handlers within a widget. re #3785

Changes widget selection status only when status is not true

---

arches/app/templates/views/components/cards/default.htm

Passes widget configs to the widget instantiation unevaluated so that the binding between config form and widget persists. re #3796 and #3797

Map widget config bindings

---

arches/app/media/js/models/card.js

Updates a cards JSON state after widgets are added to the card so that the dirty state is not activated on load. re #3787

Prevents activation of card dirty state when a graph is loaded

---

arches/app/media/js/views/graph-designer.js

Indirectly selects the permission card that corresponds to the selected card tree card or the graph tree node. re #3782 
Also collapses trees when a card is indirectly selected. For example, if a graph node is selected its corresponding permission and card tree cards are expanded, and all other permission cards and card tree cards are collapsed. This prevents somebody from clicking on several graph nodes and then moving to the card tree to find everything expanded without ever having clicked on it anything in that tree.

Permission cards selected when a user selects a node from the graph or card tree.

---

arches/app/templates/views/graph/graph-designer/widget-configuration.htm

Removes node config from the widget manager to prevent a graph dirty state while in the card manager. re #3790

Prevent graph dirty state while configuring a widget.

---

arches/app/media/js/viewmodels/tile.js
arches/app/templates/views/components/cards/default.htm

Adds isfullyprovisional computed boolean to the tile model in order to filter fully provisional tiles from reports, re #3922 
Also, replaces some computeds with pureComputeds to improve memory management. (http://knockoutjs.com/documentation/component-binding.html#disposal-and-memory-management)

Provisional data in reports

---

arches/app/templates/views/components/cards/default.htm

Adds provisional class to the rp-card-section containing a provisional tile for provisional users. re #3922

Enables styling an entire provisional tile in the resource editor report (for provisional users)

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js
arches/app/templates/views/components/cards/default.htm

Displays authoritative data in a report when sibling tiles are fully provisional. re #3922

Displays authoritative data in a report when sibling tiles are fully provisional

---

arches/app/media/js/viewmodels/report.js

Clears 'has provisional edits' flag at the top of a report if a resource reviewer resolves all pending provisional edits. re #3922

Improves behavior of provisional edits flag in reports 

---

arches/app/views/graph.py

Gets valid properties for all ontology classes rather than just for the resource model's root node class. re #4040.
This fixes the issue of unavailable properties in the relationship dropdown and ontology classes not appearing in the Ontology Class column of the related resources table.

Gets valid properties for all ontology classes.

---

arches/app/templates/views/components/cards/default.htm

Does not display card in reports or in the resource editor card tree if its visible property is set to false. re #4061

Implements card visibility in the resource editor and reports

---

arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph/graph-designer/widget-configuration.htm

Uses css to hide the widget rather than remove it from the resource editor. This allows a default value to be saved with the tile. re #3065

Allow default values to be saved if a widget is not visible

---

arches/app/media/js/models/card.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/views/graph.py

Creates widgets within the card trees update node method rather than using parseNodes. re #3993, #4149

3993 refactor update card in card tree

---

README.md

Link from top-level README.md to the new .github/CONTRIBUTING.md.

Link to the new contribution guidelines, re #3320

---

arches/app/media/js/models/card.js
arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/viewmodels/tile.js

Cherry picks from master; a fix for the ordering of widgets in the card tree and a fix for knockout errors when saving provisional data.

Cherry pick from master to 43x

---

arches/app/utils/data_management/resources/formats/csvfile.py

Fixing issue 4308. Removing an if statement that causes an error when importing business data in csv format. The if condition is not met so the array `missing_display_nodes` is not populated. 
#
https://github.com/archesproject/arches/issues/4308

4308 Removed broken if statement from csvfile.py

---

arches/app/models/resource.py
tests/fixtures/data/csv/file_list_datatype_import.csv
tests/fixtures/data/csv/file_list_datatype_import.mapping
tests/fixtures/data/json/cardinality_test_data/file-list.json
tests/models/mapped_csv_import_tests.py

Use a default value of None for the 'request' and 'user' keyword args to Resource.save(), allowing for graceful exclusion of view code when resource import is carried out by a management command or other serverside code.
#4044 
#
*   Sponsored by: Getty Conservation Institute and Legion GIS
*   Found by: @ryan86 
*   Tested by: @beatboxchad 
*   Designed by: @beatboxchad …

4044 file list datatype upload

---

arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/viewmodels/tile.js

Prevents the dirty state from getting activated after a tile is saved and prevents tile.reset from getting called unnecessarily. re #4301, #4331

Support file sync for mobile

---

arches/app/datatypes/datatypes.py
arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/viewmodels/tile.js
arches/app/models/tile.py

Prevents unnecessary tile reset and dirty state bug in the file list widget. re #4331.

Move file list widget fixes to 4.3.x

---

arches/app/datatypes/datatypes.py
arches/app/models/tile.py

Previously the check for missing nodes before tile.data is processed into provisional data. re #4331

Runs handle request on tile.data before it's moved into provisionaledits

---

arches/app/datatypes/datatypes.py

Uses file_id generated on the mobile device rather than the file name as the attachment reference. re #4331

Reference file attachments by file id.

---

arches/install/requirements.txt
arches/install/ubuntu_setup.sh

Fix for #4378 
Provides a new ubuntu dependencies install script that works for both xenial and bionic releases. Updates include elasticsearch 5.3.3 and node 10. The _ubuntu_xenial_setup.sh_ file wasn't changed. If this script works for both releases, that release specific script could be removed.
#4378 
Thanks to @mradamcox and @chiatt for testing and finding the errors!

Fix for #4378 updated ubuntu depndencies install script

---

arches/app/media/js/viewmodels/mobile-survey.js
arches/app/models/mobile_survey.py
arches/app/models/models.py
arches/app/views/api.py
arches/app/views/mobile_survey.py

Serializes only graph properties needed by a survey when saving or a survey or requesting it from the api. re archesproject/arches-mobile#279 and #4357 
Also:  
- improves error messaging when Couch is not accessible
- allows users to delete a project even if it exists in Arches but not Couch. 
- reduces default instance count from 1000 to 100.
- prevents first resource model from being selected by default on the resource model page.

4357 msm redesign

---

arches/app/models/mobile_survey.py
arches/app/views/api.py

Prevents error when trying to call .items() on an empty string rather than a dictionary while processing provisional edits. re #4432

Prevent sync error when tile.provisionaledits is an empty string. re #4432

---

arches/app/views/api.py

Returns the stacktrace to the browser if sync fails, re #4432

Returns the stacktrace to the browser if sync fails, re #4432

---

arches/app/media/js/models/mobile-survey.js
arches/app/media/js/viewmodels/mobile-survey.js
arches/app/templates/views/mobile-survey-designer.htm
arches/app/views/mobile_survey.py

Locks critical MSM features if a survey has been synched. re #4383, #4396, #4401

Prevents users from modifying critical features of a synched survey

---

arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/resource/new-editor.htm

re: #4535 
++ enables users who lack Write permission for a given (parent-) card to still access/edit child-cards for which they *do* have Write permission
++ adds a conditional behavior to the UI so that buttons in edit/add resource interface are disabled if a user lacks Write permission for any particular card at any level, also adds a banner at the top of the UI to inform user they lack that card-specific permission

4535 galen make child cards editable below ro parent

---

arches/app/templates/views/components/cards/default.htm

…clickable and their contents viewable in editor
re: original PR #4543 and issue #4535 
fixes bug where user with RO access to a card and its associated tile(s) cannot click (and thereby view) a tile that someone else created.

fix_bug_cased_by_PR4543

---

arches/app/datatypes/datatypes.py
tests/exporter/resource_export_tests.py

Datatypes that have to_rdf() functions which create RDF Literals now do not render out the string 'None' for RDF Literals when not desirable.
#4519 

4519 dont create RDF Literals if the tile data is 'None'

---

arches/app/media/css/page_job_inner.css

For #4278 
Remove all image-block css styling: not used, plus `url()` in `line 45` pointed to non-existing file.
Removed all styling for the `.image-block` class, because it was not used anymore and was causing trouble.
`collectstatic` crashed because this css referred to a non-existing file.

#4278 Remove all image-block css styling

---

arches/app/templates/help/arches-collector-manager-help.htm

Found a few things to update regarding terminology changes, and some extra notes about survey management I wanted to include.
#4494 

add some more info on project management, reorganize, #4494

---

arches/app/models/mobile_survey.py
arches/app/models/tile.py
arches/app/templates/views/components/cards/default.htm

Fixes missing records in edit history when edits were made from mobile by passing user into tile save during sync. Also fixes missing records in edit history when edits were made from mobile re #4619, #4621

Provisional edit bug fixes

---

arches/app/datatypes/datatypes.py
arches/app/models/mobile_survey.py
arches/app/models/tile.py
arches/management/commands/mobile.py

Simplifies sync so that only the edits of the person syncing are processed and fixes issue of provisional edits not showing up in the tile after sync. re #4619

Fixes missing values in provisional edit log

---

arches/db/migration_operations/extras.py

Catching `django.db.Error`s thrown when the CreateExtension operation is run with a non-superuser postgres user. A warning is logged, but it is intended that the extension will be made available to the non-superuser postgres user through another means (eg template inclusion, or via the `public` schema.)
#4707

Catching db errors in the CreateExtension class re #4707

---

arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/plugins/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/models/migrations/4669_remove_workflow_plugin.py
arches/app/templates/views/components/plugins/workflow.htm
arches/app/templates/views/components/workflows/new-tile-step.htm
arches/app/views/api.py
arches/urls.py

 updates workflows for step components

---

arches/app/media/js/models/card.js
arches/app/media/js/viewmodels/card-constraints.js
arches/app/media/js/views/graph/graph-designer/card-tree.js
arches/app/models/card.py
arches/app/templates/views/graph/graph-designer/card-configuration.htm
arches/app/views/graph.py
arches/management/commands/packages.py

Fixes issues with properly updating dirty state of node constraints

---

arches/app/models/tile.py

Prevents unique constraint check from exiting prematurely and validating against the tile getting saved. re #4375

Fixes unique constraint bugs

---

arches/app/models/tile.py
arches/app/views/tile.py

Deletes a resource if the first attempt to save a tile to it fails. This prevents a resource from getting saved and indexed with no tile data. re #4725

Deletes a new resource if first attempt to save tile to it fails. re #4725

---

arches/app/utils/data_management/resources/exporter.py
arches/app/utils/data_management/resources/formats/archesjson.py
arches/management/commands/packages.py

Allows users to export their resources to JSONL format instead of standard JSON. To do so, users just have to use
python manage.py packages -o export_resources -d output.jsonl
instead of
python manage.py packages -o export_resources -d output.json
Related to #4855 , but only addresses v3 which is not really the point of that ticket.
This is part of a larger effort to …

v3 - support export of resources to jsonl files with multiprocessing

---

arches/app/models/mobile_survey.py
arches/app/utils/middleware.py
arches/app/views/api.py
arches/settings.py

... because iOS strips the 'HTTP_AUTHORIZATION' header in some API requests. re #4717
This allows us to download projects to iOS devices without the Guest user group being assigned to the collector project.

Adds support for alternate authorization header 

---

.travis.yml

Added an optional test stage to the Travis CI configuration that attempts to build and run the Arches test suite in a python 3.6 environment. Currently, as expected, it fails quickly but gives a test for developers a target to work towards passing.
This goes someway to addressing part of #3165 

Updated Travis CI test code to additionally test against py3.6

---

arches/app/media/js/bindings/datepicker.js
arches/app/models/mobile_survey.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Resolves date formatting and file size issues preventing arches from syncing properly with collector. re #4884

Prevents syncing errors

---

docker-compose-test.yml

It causes Elasticsearch to run in a developmental mode, causing some preflight checks to become logged warnings, rather than critical errors. This is to avoid the Elasticsearch service from closing pre-emptively on Docker Hub, as the test host DH uses may have the vm.max_map_count set too low, or a related soft error for a test instance.
#4800 

Adding env var to ES to stop bootstrap checks

---

arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/new-tile-step.js

Changes logic in new-tile-step instead. re #4821

Removes check to prevent runaway workflows on reload

---

arches/app/media/js/bindings/related-resources-graph.js
arches/app/media/js/bindings/term-search.js
arches/app/media/js/views/components/search/provisional-filter.js
arches/app/media/js/views/resource/related-resources-manager.js
arches/app/search/components/provisional_filter.py
arches/app/templates/views/resource/related-resources/related-resources-manager.htm
arches/app/views/search.py

4771 componentize search

---

arches/app/media/css/arches.css
arches/app/templates/views/components/plugins/workflow-select.htm

re: 4926 Update workflow button styling

---

arches/management/commands/setup_db.py

Makes a better check for what type of postgres user Arches is provided with. The impetus for this change is that some hosted PG solutions (like AWS RDS) don't provide users with logins that are technically "superusers". However, the logins do have "CREATE DATABASE" ability, which is all that Arches actually needs when it tries to run the create/drop database operation.
#4941 
-   [ ] I have added necessary documentation (if …

improve check for createdb privileges during setup_db re: #4941

---

releases/4.4.2.md

Adds highlights and additional changes to release notes.

Update release highlights and changes in release notes

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/map.js
arches/app/models/migrations/4670_adds_map_card.py
arches/app/templates/views/components/cards/map.htm
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/map.htm
arches/install/package.json
arches/install/yarn.lock

adds map card component

---

arches/app/utils/data_management/resources/importer.py

When testing business data import using multiprocessing, I encountered errors when trying to use an installation that had a remote postgres database backend (it was an RDS instance). The errors occurred on the first resource in each multiprocessing pool, but then the loading continued as normal. For example, if I had a machine with 4 cores, then 4 parallel processes would be made, and the first 4 resources would fail.
Adding a `django.db.connections.close_all()` call each individual load process, instead of calling it only once before the `pool` is processed, …

4858 multiprocessing improvements

---

arches/app/media/js/views/components/map.js
arches/app/templates/views/components/map-editor.htm

 refactoring, cleanup and fixes

---

arches/app/datatypes/base.py
arches/app/datatypes/concept_types.py
arches/app/datatypes/datatypes.py
arches/app/functions/primary_descriptors.py

Assigns a provisional value as descriptor when a resource instance's descriptor nodes have no authoritative data. re #3714

Uses provisional values as descriptors

---

arches/app/media/js/viewmodels/card-component.js
arches/app/media/js/views/components/cards/grouping.js
arches/app/media/js/views/components/workflows/new-multi-tile-step.js
arches/app/media/js/views/components/workflows/new-tile-step.js
arches/app/media/js/views/resource/new-editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/components/cards/grouping.htm
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/workflows/new-tile-step.htm

4907 grouping card component

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/map.js
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/map-popup.htm

refactors map card component

---

arches/install/requirements.txt

adds python-docx to requirements.txt (for use of docx library in a file_template view to handle docx templates), re https://github.com/archesproject/consultations-prj/issues/38

Galen consultation prj 38 docx

---

arches/app/views/tile.py

Prevents user from creating, updating, or deleting tile data to a resource whose model status is set to inactive. Re #4937 and followup to #4946

checks for graph.isactive in tile save()/post() and delete(), re #4937

---

arches/app/media/js/models/report.js
arches/app/models/migrations/4684_adds_config_to_tabbed_report.py

Improve performance of card configuration by only apply ko mapping to properties in a report template's default configs and fixes tabbed report reverse migration re #4684

Improves card config performance

---

arches/app/utils/v3migration.py
arches/app/utils/v3utils.py
arches/management/commands/v3.py
tests/fixtures/v3migration-pkg/graphs/resource_models/Historic District.json
tests/fixtures/v3migration-pkg/graphs/resource_models/Historic Resource.json
tests/v3migration/v3_migration_cli_tests.py

To address #5024, I have made a big refactor of the v3-v4 migration code, which does a much more thorough job of interrogating the v3 JSON structure to properly group the new v4 tiles. Where groupings were previously deduced by comparing v4 cardinality with the number of v3 data points to transfer (along with a few other tests) this refactor goes straight to v3 mergenodes and groups tiles based on those. The result is that the code more or less transforms the v3 JSON back into a list of data points structured more or less like a v3 .arches file and then iterates …

Fix data grouping problems in v3v4 migration

---

arches/app/media/js/views/components/widgets/datepicker.js

This occurred when the default date was set to date of entry even if a different date had already been saved to the tile. re archesproject/consultations-prj#106

Fixes issue with date widget always displaying current date

---

arches/app/media/js/views/components/datatypes/node-value.js

Error was occurring when the nodeid assigned to a node-value datatype config no longer existed in the resource model's nodes. re #5163

Resolves error in node datatype config

---

arches/app/templates/views/components/workbench.htm

This makes to makes it available to elements within content_management regardless of how the databind on the `workbench-card-container` element is defined. re #5103

Adds sidepanel active class outside of content_management block 

---

arches/management/commands/packages.py

The change improves the ontology loading when the package is loaded by checking -y parameter and ONTOLOGY_BASE_NAME. re#5238
The user can bypass the question asking if ontology will be loaded or not by -y parameter and check the specified ONTOLOGY_BASE_NAME to load ontology. If the name is None, ontology will not be loaded.
*   Tested by: …

Improve ontology loading during package load to check -y param #5238

---

arches/app/search/components/paging_filter.py
arches/settings.py

Limit the search result pagination to match the elastic search results limit (default is 10,000) by adding parameter in settings.py and limiting the total number for pagination to 10,000, re# 4318
paging_filter.py, settings.py
Now, only 400 pages (the number of pages that corresponds to 10,000 with 25 records per page) are shown in the page selector. The total number of records are still showing the correct total. …

Limit the search results to 10000 records & corresponding # of pages

---

arches/management/commands/packages.py
arches/management/commands/project.py

Adds logging to packages.py. Adds search component registration to package command. Removes load_ext_from_prj option from the packages command and instead loads extensions from the project and then from the package. Extensions in the project are not overwritten by the package. re #5305

Removes need to the add load extension ('-ex') argument from package command 

---

arches/app/media/js/bindings/ckeditor.js

This fixes the error of not being properly check dirty status of the rich text editor when the user moves between different cards. re #5235
Update the ckeditor.js to use editor object instead of $element.ckeditorGet()

Use editor object (ckeditor) instead of '$element.ckeditorGet()'

---

arches/app/views/graph.py

This fixes the error when deleting the resource models that has resource instances in it. re #5311
No it deletes the instances and the model altogether.
It changes the order of process when deleting resource instances. It deletes the resource instances before it change the active status

Fix error when deleting a model w/ resources re # 5311

---

arches/app/models/graph.py

Applies fix to saving graphs without an ontology by setting jsonld context to a default value when the json serializer returns None after serializing the context. re #5372

Prevents jsonld error when saving a graph

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/widgets/rich-text.js
arches/app/templates/views/components/widgets/rich-text.htm
arches/app/templates/views/report-templates/tabbed.htm
arches/app/views/search.py

Also adds developers to configure the rich text widget to display it's entire value (in a tabbed report for example) rather than the abbreviation `[rich text]` that is displayed in the card tree. re #5385, archesproject/consultations-prj#343

Adds support for customization of the main panel of a tabbed report

---

arches/app/datatypes/base.py
arches/app/datatypes/datatypes.py
arches/app/media/js/views/components/datatypes/file-list.js
arches/app/media/js/views/components/widgets/file.js
arches/app/models/migrations/4921_file_data_type.py
arches/app/models/tile.py
arches/app/templates/views/components/datatypes/file-list.htm
arches/app/templates/views/components/widgets/file.htm

-   [x ] New feature (non-breaking change which adds functionality)
-- adds validation for File datatype
-- adds a migration to insert a component and config for file datatype
-- enables graph-editor-permission-level users to enable a maximum to the number of uploadable files for a given node that uses the file widget
-- validates against such a limit during tile save
#4921 
* …

4921 file datatype

---

arches/app/datatypes/datatypes.py

changes django query in validate() to find (i.e. `__contains=`) a literal dict with the value, rather than using underscore syntax (i.e. `config__options__contains=`)
#5411 

changes domain datatype node query __contains to literal dict, re #5411

---

arches/app/utils/data_management/resources/formats/shpfile.py

Creates a shapefile for every spatial node identified for export in a resource model, fixes bugs in exporting nodes with combinations of geometry types in a single tile, and fixes bug with writing multipoint shapefile. re #5545

Shapefile export - multiple geom nodes per resource model. 

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/search/search-export.js
arches/app/templates/base-manager.htm

Previously it would default to the total number of instances - not the total in the query when the page was loaded with a query already in the search url. re #5545

Updates total in export url 

---

arches/install/ubuntu_setup_v5.sh

This pr adds a new ubuntu setup script for arches v5. Ultimately this script can replace the existing ubuntu_setup.sh file, but it's separate for the moment. The main changes in this script are:
update to postgres 12 and postgis 3
add optional system-wide elasticsearch installation (this is an improvement on the prior JDK installation which was a dependency that only served elasticsearch anyway).
#5569

add ubuntu setup script with arches 5 deps and elasticsearch #5569

---

arches/app/datatypes/datatypes.py
arches/app/models/mobile_survey.py
arches/app/models/models.py
arches/app/models/resource.py
arches/app/models/tile.py
arches/app/utils/permission_backend.py
arches/app/views/auth.py
arches/app/views/base.py
arches/app/views/resource.py
arches/app/views/search.py
arches/app/views/tile.py
arches/app/views/user.py

This is a refactor of how the app checks for whether a user is a resource reviewer. Previously, there were numerous hard-coded tests of whether a user is in the "Resource Reviewer" group. There were also some tests that used the UserProfile.is_reviewer() method. This refactor creates a new function in permission_backend and changes all references across the app to use that new function. The UserProfile.is_reviewer() method is deprecated. See full explanation in #5660.
#5660 
-   [ ] I have added tests that prove my …

refactor test for resource reviewer status #5660

---

arches/app/media/js/views/components/search/search-export.js
arches/app/models/graph.py
arches/app/search/search_export.py
arches/app/templates/views/components/search/search-export.htm
arches/app/views/search.py
arches/install/arches-templates/project_name/settings.py-tpl

Prevents user from conducting export when there are no search results. Fixes error in field name validation. Informs user that if no instances had exportable geometry nodes, no shapefiles were exported. re #5545

Improves export feedback

---

arches/app/media/js/models/node.js
arches/app/templates/views/graph/graph-designer/node-form.htm

Hides exportable input if a node has a default widget assigned to it. re #5696

Prevents user from setting non-data bearing nodes as exportable. 

---

arches/install/arches-templates/project_name/datatypes/sample_datatype.py
arches/management/commands/datatype.py

Adds issearchable property to sample datatype and error handling in case a user tries to load a datatype with that property missing. re #5557

Handles for missing 'issearchable' property in datatype configs

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/map-editor.js
arches/app/media/js/views/components/cards/map.js
arches/app/templates/views/components/map.htm

Displays provisional data when a reviewer selects a provisional users edits and widens the side panel during a provisional edit review. re #5127, #5128

Fixes display of provisional data in map component

---

arches/app/templates/base-manager.htm

Moves link to parent element to prevent user from having to double click main navbar elements. re #4359

Prevents user from having to double click navbar links

---

arches/app/search/search_export.py

Uses fieldname for shapefiles and node name for csv. re #5793, #5740

Fixes missing attribute info in shapefile export fields. re #5793, #5740

---

arches/app/search/mappings.py
arches/management/commands/packages.py

Handles for missing table error that occurs when loading a package to a project before the project's database is available, re #5876

Handles for missing table error, re #5876

---

arches/app/models/migrations/2691_ES_upgrade.py
arches/app/utils/data_management/resources/formats/csvfile.py
arches/management/commands/setup_db.py

Removes code to upgrade ES index in 2691_ES_upgrade.py migration and sets up index after database is migrated, re #5876

Sets up indexes after database is created. re #5876

---

arches/app/datatypes/datatypes.py

The es indexing of filelist when it is provisional fails, which prevents the user to add file or re-index.
The append_to_document method was updated to properly index the file list when it is provisional.
A try block was added around the code for appending, so when the tile.data is not available, it will look for provisionaledits to get info.
*   Found …

Fix es indexing of provisional edit for the filelist datatype re#5873

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/c3.js
arches/app/media/js/views/components/cards/file-viewer.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/file-workbench.htm

Prevents file viewer content from appearing on top of workbench sidepanel. Disposes of c3 charts when no longer used. Adds support for three.js file extensions. re #5881

File viewer improvements re #5881

---

arches/app/media/js/viewmodels/file-widget.js
arches/app/templates/views/components/file-workbench.htm
arches/app/templates/views/components/widgets/file.htm

If a file widget has only one file uploaded to its tile's node, the file name rather than the file count is used for the display name. re #5881

Uses file name in file widget display name with only 1 file uploaded, re #5881

---

arches/app/media/js/views/components/cards/file-viewer.js
arches/app/templates/views/components/file-workbench.htm

Prevents unintended re-rendering of file renderer components when other tile values are edited and when the edit tab is opened. re #5881

Prevent unintended re-rendering of file renderer components re #5881

---

arches/app/media/js/views/components/cards/file-viewer.js
arches/app/templates/views/components/cards/file-viewer.htm
arches/app/templates/views/components/file-workbench.htm
arches/app/views/tile.py

Prevents multiple resource instances from getting created when a user uploads multiple files in the file viewer card before a target instance is created. Fixes display of file name in card tree. Allows user to switch file renderer after it has already been assigned. re #5881

File viewer bug fixes. re #5881

---

arches/app/views/tile.py

Fixes error in casting UUID in tile view when a tiles resource instance id is already a UUID. re #5881

Fixes error in casting UUID in tile view

---

arches/app/models/migrations/4751_adds_photo_gallery_card.py

Removes the photo gallery card during migration if it already exists in the project database. re #4751

Removes the photo gallery card during migration re #4751

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/views/components/cards/file-viewer.js
arches/app/media/js/views/components/cards/map.js
arches/app/media/js/views/components/workbench.js
arches/app/templates/views/components/file-workbench.htm
arches/app/templates/views/components/iiif-annotation.htm
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/workbench.htm

Expands provisional edit tabs in workbench cards, resolves css issues with provisional banners, extends file viewer to height of large images, and fixes issue with provisional edits not loading for review.  re #6021, archesproject/arches-for-science#79

Expands provisional edit tabs in workbench cards, re archesproject/arches-for-science#79

---

arches/app/media/css/arches.css
arches/app/media/js/viewmodels/card.js

Fixes error when saving provisional edits and fixes image rotation in the file viewer for FF and future versions of Chrome. re archesproject/arches-for-science#81, archesproject/arches-for-science#82

Resolves provisional edit error in file viewer

---

arches/app/datatypes/datatypes.py

Allows same domain values to be used on different nodes and prevents error if file datatype is missing configs value.

Resolves error if same domain applied to different nodes

---

arches/app/media/js/viewmodels/card.js
arches/app/media/js/viewmodels/file-widget.js
arches/app/media/js/views/components/cards/file-viewer.js
arches/app/templates/javascript.htm
arches/settings.py

Fix applied in the file widget report and file viewer. re archesproject/arches-for-science#88

Handles for image mime (tif and psd) that are not browser supported

---

arches/app/datatypes/datatypes.py

Update the to_rdf() function for the filelist datatype, plus the v5 internal API functions of `get_rdf_uri` and `is_a_literal_in_rdf`.
Currently the variables don't resolve because they were renamed at some point.
e.g. `cidoc` --> `cidoc_nm` ; `graph` --> `g`
#6066
This does not fix another related …

Minimally fix filelist datatype

---

arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/views/components/iiif-annotation.js

Allows iiif card to update when swapping between provisional and authoritative edits. re #6049

Updates iiif drawings during provisional edit review

---

arches/app/models/tile.py

Adds a method to the tile model to update a tile value. If the tile to update does not exist, a tile and its parents are created. re #6130, archesproject/arches-esri-add-in#15

Adds a method to the tile model to update a tile value

---

arches/app/templates/javascript.htm

This allows developers to add their own urls in js files using the arches.urls object. re #6158

Adds block to urls object so project developers can add their own urls

---

arches/app/views/resource.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Fixes the issue of a missing 'creator' if the instance permissions being managed are resources that have been imported rather than created via the UI. re #2725

Resolves missing import user in resource instance permissions

---

arches/app/media/js/viewmodels/map.js
arches/app/media/js/views/components/search/search-results.js
arches/app/views/search.py

Resolves error when parsing permissions in the map popup and resizes map so that it fills the entire map element when the map tab is selected in search. re #2725

Resolves map popup error, re #2725

---

arches/app/datatypes/base.py
arches/app/datatypes/datatypes.py
arches/app/utils/data_management/resources/formats/rdffile.py

Move URI pattern tests on to datatypes so that they can be customized for externally developed datatypes, such as https://github.com/thegetty/arches-urldatatype
(Also incidentally makes the debugging output slightly better by adding in the name of the branch / datatype where things go wrong)
Tests still pass, and the code is slightly more efficient as it catches some cases that would have been ruled out in the following code that tries to recursively load the graph per branch when there are multiple possible.

move URI test to datatype as function

---

arches/app/views/api.py

Makes it possible to request resource information without including tile data if the format requested in json. re archesproject/arches-for-science#129

Makes tiles optional in resource api request

---

arches/app/models/tile.py

Prevents error when querying for function classes. re archesproject/arches-for-science#189

Prevents error when querying for function classes

---

arches/app/templates/navbar/resource-manage-menu.htm
arches/app/views/resource.py

Hides the delete button in the resource editor if a user does not have permissions to delete an instance. re #6133

Hides delete button if user not permitted to delete

---

arches/app/views/api.py

Now InstancePermission API returns a dictionary of three permissions (read, edit, delete) instead of single permission requested.
#
It will make the api more flexible to any resource instance level permission related request

Modify the InstancePermission API to return a dict of permissions

---

arches/app/utils/permission_backend.py

Prevents UUID validation error if resourceid is and empty string. 

---

arches/app/models/models.py

Change the logic of card.is_editable() to request the first tile, and if that exists, then return False. If there isn't such a tile, then return true.  This prevents the need for a full table sweep to count() the nodes.
#6319

fix logic in card.is_editable()

---

arches/app/utils/decorators.py
arches/app/utils/permission_backend.py
arches/app/views/api.py
arches/app/views/resource.py
arches/app/views/search.py
tests/permissions/permission_tests.py
tests/views/resource_tests.py

Renames instance permission methods so that their use is easier to understand. Fixes decorators so that they route a user to login if the permission check returns false. Fixes the can_user_delete _resource method so that a user cannot delete an instance with protected tiles. Updates the resource delete view so that a user gets an error message if they are not permitted to delete an instance rather than being redirected. re #2725, #5992

Fixes to resource instance deletion permissions

---

arches/app/models/graph.py

Adds logic to graph validation to check for duplicate slugs when cloning a graph or exporting a branch. Right now it sets the slug to None if a duplicate slug already exists in Arches.
#6071 #5589 

Add check to graph validation for duplicate slug value, re #6071, #5089

---

arches/app/views/api.py

Fix the error when geojson api requested with limit parameter, re #6317
Change the check the tiles (Python list of tiles) from tiles.count() to len(tiles)
The limit parameter on geojson api fails.

Fix geojson api to use the limit parameter, re #6317

---

arches/app/views/graph.py

Sets slug to None to prevent duplicate slug error when cloning a resource model. re #5589

Sets slug to none when cloning to prevent duplicate slug error. re #5589

---

arches/app/datatypes/datatypes.py

resource-instance datatype didn't generate an array when processing from rdf
#

fix resource-instance datatype from_rdf to generate an array

---

arches/app/templates/views/components/file-workbench.htm

Fixes missing parameter for chart renderer. re archesproject/arches-for-science#214

Supports chart renderer in Arches for Science 

---

arches/app/templates/views/resource.htm
arches/app/views/base.py

Use subtitle instead of description per #6382 for grid tile.
Make the background of the icon the color of the graph, in the same way as the bubble colors in the related resources visualization.
#6382

improve resource mgr view

---

arches/app/datatypes/datatypes.py

Handles for loading of proper, double-quote JSON and single quote (python dictionary strings) during csv import of resource instance values. re #6390

Supports both JSON and python literal strings during csv import of resource instance data

---

arches/app/models/graph.py

Change the way that the parent node group is evaluated for the node group, re #6308 
Fix the error when the user tries to change the separate card option, when there is a sub node that is set to have its own card.

Change the parent node group evaluation to use id, re #6308

---

arches/app/media/js/viewmodels/resource-instance-select.js

Prevents error if graph is undefined in cases where the graph is not available because it's set as inactive in the graph designer. re archesproject/arches-for-science#216

Handles for cases when a graph is not available in the graph list.

---

arches/app/datatypes/datatypes.py

During csv import of a filelist value, the private path, not the destination location is saved to the tile. On export, the human readable destination path is written to the csv file. Also ensures that the target tile is related to its corresponding file. re #6392

FileList csv import bug fixes

---

arches/app/media/js/views/components/datatypes/resource-instance.js
arches/app/templates/views/components/datatypes/resource-instance.htm
arches/app/templates/views/graph/graph-designer/node-form.htm

Prevents a user from changing the datatype configuration of a related instance node once a tile is saved to the corresponding node's nodegroup. re #5688

Prevents related instance datatype config changes after tile is saved

---

arches/app/datatypes/datatypes.py

Ensures that the node value for a tile with the filelist datatype has a value before trying to iterate over it. re #6392

Fixes error if node value for file is None, re #6392

---

arches/app/media/js/views/components/widgets/datepicker.js
arches/settings.py

Add a new time format in Javascript datetime picker to support the time in Arches, re #5256 
(YYYY-MM-DD HH:mm:ssZ, eg. 2020-08-02 17:53:30-07:00)
Also, the format was added to Python validation and ElasticSearch index format.
#

Add a time format to datepicker/es/validation to support time, re # 5256

---

arches/app/media/css/arches.css

Center draggable slider handle in Graph designer
The CSS of the draggable slider handle has borked. The handle is top-aligned to its parent when it should be center-aligned.
#6470 
UI changes seen here: https://ibb.co/vhRJNNP

center slider handle in graph designer

---

arches/app/media/js/viewmodels/graph-settings.js
arches/app/templates/views/graph/graph-designer/graph-settings.htm
arches/app/views/graph.py

Add the widget config to the top node of the branch in the graph designer, re #6310 
Now the widget can be configured when the top node is concept / domain / resource instance which will require further configurations.

Add the widget config to the top node of the branch, re #6310

---

arches/app/media/js/utils/ontology.js
arches/app/templates/views/components/datatypes/resource-instance.htm
arches/app/templates/views/components/widgets/resource-instance-select.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm

Update the related instance datatype in graph designer to add capability to reset the default value, re #6363 
Resolve the issue of not being able to remove the selection once the default is set for the related instance datatype in graph designer

The ability to reset related instance datatype in graph designer, re #6363

---

arches/app/datatypes/base.py
arches/app/datatypes/datatypes.py
arches/app/views/map.py

This adds performance improvements as discussed in ticket #6443 
When you have a lot of resources the tiles table stops performing well. Ensuring that queries include an index scan will help drastically.
All unit tests passed.

#6443 performance fix 5.0.x

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/cards/photo-gallery-card.js

My updated understanding of the function of these arrows is not to cycle through the currently selected photo, as previously thought, but rather to shift the currently viewed section of the thumbnail gallery. This functionality was borked as well, with the fix being to import the binding into the compenent.
Old UX seen here: http://recordit.co/RNnI0jnVLV.gif
New UX seen here: https://recordit.co/VhT3mnHAMQ ( NOTE: screencapture software doesn't show changed cursor )
#6504 
-   [ ] I have added tests that prove my …

Fix PhotoGallery card thumbnail arrows to respect user interaction

---

arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/media/js/views/graph/graph-designer/card-tree.js

This fixes the issue of widgets not appearing after creating new nodes. This is accomplished by having card-tree call `updateNode` regardless of any logic involving `data.updated_values.card`.
UX seen here: http://g.recordit.co/yuA8H0XMKm.gif
#6033 
UX seen here: http://g.recordit.co/yuA8H0XMKm.gif

Widgets now appear after node creation

---

arches/app/views/resource.py

Get related resource with the proper relationship type even when the relationship is in reverse (inverserelationshiptype), instead of getting all the resources with the forward relationship type, re #6328 
#6328 

Show the relationship properly in a report when inverse, re #6328

---

arches/app/media/js/views/components/cards/grouping.js

Grouping cards now respect widget addition / deletion.
UX seen here: http://g.recordit.co/2pcm7BZfMB.gif
This adds a widget subscription to the grouping card. This supersedes #6565 
A remaining bug is grouping both a node, and a newly-created node in the same card. `groupingViewModel.cardLookup` is not being updated with the correct card information. Will file a followup
#5710 #6573 #6522 
-   [ ] I have added necessary documentation …

6573 cbyrd add or remove node from grouped card breaks ui

---

arches/app/models/migrations/5967_related_resource_map_card_feature_editing.py

Fixes migration to include changes to existing card configs rather than just to the default configs. re #6574

Update migration to include changes to existing card configs. re #6574

---

arches/app/views/api.py

Currently a user can get one or all nodes in a request. This change allows a user to get features for more than one nodeid by adding a comma delimited list of nodes a nodeids parameter. 
e.g. ```/geojson?nodeids=some_geojson_nodeid,another_geojson_nodeid```
If the `nodeid` parameter is also used, the user will get features for the `nodeid` and features for the nodes in the `nodeids` parameter.

Allow a user to request multiple nodes via geojson api. re #6616

---

arches/app/templates/views/components/widgets/number.htm

Fix the number datatype report template to make the rows line up properly when a title runs more than one line, re #6639 
#6639 

Format a number in a report to line up properly, re #6639

---

arches/settings.py

Addresses import error when a user tries to install arches prior to installing some of its dependencies.

Fix Django import error during Travis build

---

arches/app/media/css/arches.css
arches/app/media/js/bindings/related-resources-graph.js
arches/app/media/js/views/search.js

force-directed graph now has better UX. The double-scroll has been removed, the user can now 'zoom out' to a scale of 0.25, and nodes no longer clump in the upper-left corner. 
An issue remains, if the user selects 'Related Resources' from the search page before the application has completely loaded, some non-breaking incorrect node behavior persists.A good rule of thumb for testing this behavior is if the `Related Resources` link changes the cursor to a pointer. If it's not yet a pointer, the app has not completely loaded and we can observe the incorrect …

6711 cbyrd update graph ux

---

arches/app/models/graph.py
arches/app/utils/data_management/resource_graphs/importer.py

Informs a user that a graph failed to load and updates error message to notify a user that that graph import may have failed due to duplicate sibling node names or duplicate node names in a card. re #6723

Inform user that graph failed to load

---

arches/app/models/graph.py

Only prevents save of a node with data if the node's name is being changed.  re #6801

Throw error on node save when name is changed

---

arches/management/commands/packages.py

Add an option to load the sample data set instead of the full data, re #6810 
When there is -dev tag, it will search the directory /sample_data under ../business_data/ and load the sample data instead of the full business data
#6810

Add sample data loading, re #6810

---

arches/management/commands/packages.py

Uses default business_data_load_order instead of business_data_load_order_dev, re #6810
So, removes business_data_load_order_dev and also changes the directory name to /dev_data
#6810 

Use default business_data_load_order instead of ..._dev #6810

---

arches/app/media/js/views/components/cards/related-resources-map.js
arches/app/templates/views/components/cards/related-resources-map-popup.htm

Allows a user to unrelate resources using the map popup and turns on only the first select able layer by default. re #6905 #6906

Related resource map improvements re #6905 #6906

---

arches/app/media/js/views/components/search/search-export.js

Geojson search endpoint URL properly formed even if a language identifier is specified in the URL. re #6908

Fixes geojson search endpoint url when localization in applied. re #6908

---

arches/app/tasks.py
arches/app/templates/email/download_ready_email_notification.htm

Changes as detailed in Arches ticket 6675 for stable/5.1.x branch
- Added search_history_obj to user.py which returns the Search Export History object for the given export
- Added code to generate the full path of the export object as email_link within user.py within the return object for export_search_results
- changed {{link}} to {{email_link}} in download_ready_email_notification.htm
Tested by running an export of over 2000 records in a local installation

Fixes to correct export email link

---

arches/app/models/models.py
arches/app/views/user.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Changes as detailed in Arches ticket 6673 for stable/5.1.x branch
- Replaces hard-coded 'from' email address in models.py with email address set in settings.DEFAULT_FROM_EMAIL
- Replaces hard-coded application name with the application name set in settings.APP_NAME
- Replaces "You're" in subject line for user update email with "Your"
- Adds DEFAULT_FROM_EMAIL to settings.py and settings.py-tpl

Files changed for app specific email config

---

arches/app/tasks.py
arches/app/templates/email/download_ready_email_notification.htm

As per bug #6675 , the e-mail template now uses email_link in the href tag so the URL where the export files are held can be accessed rather than just returning a UUID.
Passed unit tests run on local copy of code.

Add email_link for href tag in export notify email

---

arches/app/media/css/arches.css
arches/app/media/js/views/components/iiif-annotation.js
arches/app/templates/views/components/iiif-annotation.htm
arches/app/templates/views/components/iiif-viewer.htm

Disable editor/image tabs in iiif annotation when an image (canvas) is not loaded, re #6895
#6895

Disable editor/image tabs in iiif annotation when an image (canvas) is not loaded

---

arches/app/datatypes/datatypes.py

Prevent error when using get_or_create to save files that already exist.

Fix error when saving files with the same name. re #7142

---

arches/install/requirements.txt

Allows for installation of Pillow > 7.0

Fix failing Pillow install for Python 3.9

---

arches/app/views/resource.py

Fix the bug that the node-value datatype does not load the selections, #7162, archesproject/arches-her#544
#

Fix the issue with the node-value datatype does not load, #7162

---

.github/workflows/main.yml

Remove python-dev as it seems to be causing the build to fail and is probably unnecessary in latest.

Remove python-dev as it seems to be causing the build to fail

---

arches/app/media/css/arches.css
arches/app/models/migrations/6979_manifest_manager.py
arches/app/templates/views/components/plugins/manifest-manager.htm
arches/urls.py

Makes entire start page tab content a dropzone and changes tab label cursor to pointer. re #7108

Manifest manager start page improvements

---

arches/app/media/css/arches.css

Prevents the workflow step content from obscuring workflow tabs, re #7207

Fix workflow tab overlap, re #7207

---

arches/__init__.py
arches/install/arches-project

Assigns the proper branch name to package.json depending on whether the branch is a final, beta (.x branch), or alpha (master) branch, re #7210

Set proper branch to package.json when version is a beta or '.x' branch

---

arches/app/media/js/views/components/workflows/component-based-step.js
arches/app/templates/views/components/plugins/tabbed-workflow.htm

Prevents non-required steps from getting skipped due to workflow.next getting called twice - once when a user clicks `Save and Continue`, and a second time during the subscription on complete, re #7227

Prevents non-required steps from getting skipped

---

arches/app/media/js/bindings/select2-query.js
arches/app/media/js/viewmodels/resource-instance-select.js

Fix the bug that resource type selector stop working with an error, if all the graphs are not downloaded for resource instance type. archesproject/arches-her#560
by disabling the resource selector until all the graphs are downloaded.
archesproject/arches-her#560

Fix the bug while resource type selector download, arches-her#560

---

arches/app/utils/data_management/resources/formats/rdffile.py

Allow the domain node to be in a parent tile, cherry picked from 5.1.x, re #7252

Allow the domain node to be in a parent tile, re #7252

---

arches/app/media/css/arches.css

Depends on https://github.com/archesproject/arches-for-science-prj/pull/336
I generally browsed the application and found no ill effects. Removing this code is the correct move to make and we should deal with the fallout ( if any ) when it comes.

Core changes to fix thematic templating design view #7268

---

arches/app/datatypes/datatypes.py

*Recreating the PR after correctly linking my GitHub account to the commits at Adam Cox's suggestion*
There is a bug in python when calling `.astimezone()` on a Windows machine for `datetime` values before 1970 (start of epoch). [Here](https://bugs.python.org/issue36759) is the python bug post about it.
I've added a check for dates when they are being converted to first see if the date falls under the error specifications and, if so, it simply skips the timezone conversion. This isn't supposed to be a permanent fix and when python fixes the bug it will no longer …

Handle Windows .astimezone bug

---

arches/app/utils/data_management/resources/formats/csvfile.py

Fixes check for whether child tile creation is needed, re #7332
Prior to this [refactor](https://github.com/archesproject/arches/commit/250b7bc78dd8458cf0dbee5e66e8e9da39175757#diff-009b1fa3c3618e758589d21b4512631be7da49ff01e8b422e78cfa4ad78f255a), get blank tile would return a parent tile with an empty data object,`{}`. Because that was fixed, checking whether child tiles needed to be created within csv import no longer worked. This PR corrects the conditional in csvfile.py.

Fix check for whether child tile creation is needed

---

arches/app/media/js/views/components/workflows/component-based-step.js

Add component based step to track the parent tile id when necessary, archesproject/arches-her#613
Required to add `parentteilsourcestep` and `externalStepData` in the workflow definition js.
archesproject/arches-her#613

Track parent tile id for workflow component base step, arches-her#613 

---

arches/app/models/resource.py

Cherry picks from 5.2.x: Only pull back related resources that match the given graphid, re #7334

Only pull back related resources that match the given graphid, re #7334

---

arches/app/datatypes/datatypes.py

Cherry picks from 5.2.x: fix bug when the related resource node data is None, re #7364

fix bug when the related resource node data is None, re #7364

---

arches/app/utils/label_based_graph.py
tests/utils/label_based_graph_test.py

Cherry picks `update label_based_graph compact flag to handle data-collecting nodes with children #7139` from stable/5.2.x

Handle data-collecting nodes with label_based_graph compact flag, re #7139

---

arches/app/media/css/arches.scss
arches/app/templates/base.htm
arches/install/requirements.txt
arches/settings.py

re: #7395
This PR provides support for Sass preprocessing in Arches and converts the arches.css stylesheet to use Sass so that we can take advantage of the features it provides when improving these stylesheets. 
A couple of changes will need to be considered for projects taking on this change:
- there are two new python dependencies in requirements.txt that will need to be installed into your virtual environment
- the `compressor` application will need to be included in the `INSTALLED_APPS` setting (it is there in core arches settings, but may be overwritten in the project settings and therefore need to be updated)
- the `STATIC_ROOT` setting should point to the project root in development, so if this is configured for production in your project settings you will need to account for that …

adds support for Sass preprocessing

---

arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/plugins/manifest-manager.js
arches/app/media/js/views/components/workflows/component-based-step.js

moves saving observable to workflow-step.
workflow.getStepData now uses Promises.
THIS WILL BREAK the `getStepData` logic in arches-HER
#7421

Enforces workflow asynchronousity on getExternalStepData

---

arches/app/models/migrations/7442_delete_manifest_images_table.py
arches/app/models/migrations/7442_move_data_from_manifest_images_table_to_files_table.py
arches/app/models/models.py
arches/app/views/manifest_manager.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

This deletes the `ManifestImage` model and manifest_images table. It groups said functionality with `File`.
TO REPRODUCE:
1. Follow directions [here](https://arches.readthedocs.io/en/stable/managing-and-hosting-iiif/?highlight=cantaloupe#setting-up-cantaloupe) , but instead of `cantaloupe` folder use `uploadedfiles` folder
2. Navigate to project settings.py file, and change `CANTALOUPE_DIR = os.path.join(APP_ROOT, "uploadedfiles")`
3. Test as you normally would
#7442 
-   [ ] I have added tests that prove my fix is …

Merges manifest images and files tables

---

arches/app/models/tile.py

Removes 'request' argument from tile.check_for_missing_nodes because admins can control if the check is run or not using the `BYPASS_REQUIRED_VALUE_TILE_VALIDATION` setting.

Check for missing nodes from web and cli, re #7214

---

arches/app/media/js/views/base-manager.js
arches/app/media/js/views/edit-history.js

Requires the datatable binding only where it is used, re #7521

Require the datatable binding only where used

---

arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/media/js/viewmodels/workflow-step.js
arches/app/media/js/viewmodels/workflow.js
arches/app/media/js/views/components/workflows/component-based-step.js

Add locked flag in the workflow step, re: archesproject/arches-for-science#368
When other steps needs to lock a previous step to prevent for a user to change it once the resource instance is created, the `locked` flag is added so that it can be used to disable selection widget, etc.
archesproject/arches-for-science#368
* …

Add capability to flag lock in the workflow step, afs #368

---

arches/app/templates/views/mobile-survey-manager.htm
arches/app/templates/views/resource/editor.htm
arches/app/templates/views/resource/permissions/permissions-manager.htm
arches/app/templates/views/resource/related-resources/related-resources-manager.htm

we were using the `static` template tag with image paths that included leading slashes, which was causing problems for applications with certain Django configurations.
@chiatt do you understand the conditions to recreate the original poster's issue?  I was able to confirm that the new paths work, but I was not able to reproduce the original issue just by changing my Django settings.
re: #7503

Fixes image paths with leading slashes in templates

---

arches/app/templates/views/components/widgets/edtf.htm

Fix issue with required asterisk missing in action for EDTF fields.  It was hiding behind the input field. 
Move required asterisk closer to label so it won't get lost behind the input field.
* #6958 

moves "required" flag closer to label

---

arches/app/views/api.py

Prevents error when saving data to the tile API with data on request.POST or request.FILES request objects, re #7584

Prevent error when saving data to tile API with data on POST or FILES

---

arches/app/media/js/views/components/workflows/component-based-step.js

Fixes double workflow step edit bug by forcing mutation of hasunsaveddata observable
fixes #7609 

double edit bug

---

arches/app/models/tile.py

API is using the Tile proxy model to do a save; in some instances it does not create a log entry when new resource instance is created to support a new tile.  Adds functionality to save the new resource entry.
closes #7611 

Fixes edit log issue on resource creation through API

---

arches/app/media/js/viewmodels/resource-instance-select.js

Checks to see if a workflow step is disabled when determining whether or not to enable the resource instance select.  Needed for https://github.com/archesproject/arches-for-science-prj/issues/432   
closes #7619 

resource select check workflow disabled

---

arches/app/media/js/viewmodels/resource-instance-select.js
arches/app/views/api.py

Allows for the graph API caller to exclude parts of the API return - and then uses that change to exclude most of the return for the resource instance select widget in an attempt to improve performance.  Performance is noticeably better, though perhaps still not as good as it could be.  In testing, I found that most of the performance issues lie within the graph model build process
closes #7635  …

exclude parts of graph api

---

arches/app/media/css/arches.scss

-   [ X] Bugfix (non-breaking change which fixes an issue)
Adds position:relative to .calendar.picker in arches.scss to ensure that the datetimepicker widget is positioned relative to the input field rather than in the center of the viewport (a known "feature"/bug of bootstrap datetimepicker).
#7649 
-   [X ] Unit tests pass locally with my changes
*   Sponsored by: @mradamcox 
*   Found by: @kkemp85
*   Tested by: @coherit

positions datetimepicker relative to input field #7649

---

arches/app/media/js/bindings/select2-query.js
arches/app/media/js/viewmodels/resource-instance-select.js

fixes issue where the first load of the resource instance select list wouldn't be enabled in the create new resource form.  The issue is that sometimes undefined, and false || undefined is undefined, which is invalid with the select2 binding's strict disabled comparison.
resolves #7662 

resource instance list fix

---

arches/app/media/js/viewmodels/map.js
arches/app/media/js/views/base-manager.js
arches/app/media/js/views/components/search/search-results.js
arches/app/media/js/views/search.js
arches/app/templates/base-manager.htm
arches/app/templates/views/components/map-popup.htm
arches/app/templates/views/components/search/search-results.htm

Passes whether users can read and edit resources down to search components and fixes logic to display edit link in the map popup. re #7674, #7021

Pass permissions info to search components

---

arches/app/media/js/views/components/resource-report-abstract.js

Allows a resource to load in editor by preventing it from hanging if CardViewModel is not available in the resource-report-abstract component, re #7697

Allow resource to load in editor

---

arches/app/media/js/views/components/resource-report-abstract.js
arches/app/views/api.py

Adds a parameter for the bulk resource API to allow for uncompacted output, which is needed for reporting in some cases.
resolves #7700

parameter for uncompacted resource json

---

arches/app/media/js/views/components/search/map-filter.js

Prevents error when iterating over aggregated search results before they are available. re #7709

Prevent error in loading map-filter before results are available 

---

arches/app/media/js/views/components/resource-report-abstract.js

Use a synchronous require import to avoid error related to a circular import in the related-instance-select viewmodel. re #7717
For docs on synchronous require:
https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#notes-about-synchronous-require

Use synchronous require import to prevent Advanced Search error

---

arches/app/media/js/viewmodels/card-component.js
arches/app/media/js/viewmodels/card.js

Moves parent tile save behavior to card viewmodel instead of card component
resolves #7738

moves parent tile save behavior to card viewmodel

---

arches/app/media/js/viewmodels/card-component.js
arches/app/media/js/views/components/cards/grouping.js

The grouping card was using a different resourceinstanceid for each tile save. This fix ensures all tiles save to the same resource instance. re #7748

Ensure all tiles save to the same resource instance. re #7748

---

arches/app/media/js/views/components/plugins/manifest-manager.js

Add accepted files config to dropzone config in manifest manager. 
#

Restrict manifest-manager to jpeg, png, and tiff file types, re #7672

---

arches/app/utils/transaction.py

Prevents error due to missing `update` method on the Tile proxy model. Also, `save` will reindex the resource after the tile is updated., re #7779

Use save rather than update to rollback tile edits, re #7779

---

arches/app/media/css/arches.scss
arches/app/media/js/views/components/resource-report-abstract.js
arches/app/templates/views/components/resource-report-abstract.htm

Modifies resource-report-abstract to use label based graph v2 in the resource report endpoint (depends on #7774)
fixes #7775 

resource report abstract changes

---

arches/app/views/api.py

adds support for v=beta and uncompacted=true parameters to support uncompacted label based graphv2 output.
fixes #7773 

resource report endpoint changes

---

arches/app/media/js/viewmodels/workflow.js

Fixes issue where the number of steps was being incorrectly calculated at the beginning of the workflow, causing the save & complete button to always be present, even when the workflow wasn't finished.
#7791 

workflow save & complete when finished only

---

arches/app/media/js/views/components/workflows/workflow-component-abstract.js

Resolve componentBasedStep after step component indicates error is true, re #7813. Supports allowing alert messages to be displayed on outer save. QA using the instrument-info step in the upload dataset workflow on this PR: https://github.com/archesproject/arches-for-science-prj/pull/579/files

Resolve componentBasedStep after step component sets error to true

---

arches/app/search/mappings.py

Changed Elasticsearch mappings for `dates` and `date_ranges` to use `long` and `long_range` types to handle prehistoric dates that exceed integer length.
#7796 
*   Tested by: @aj-he 

7796 es mapping integer outofbounds bug

---

arches/app/datatypes/datatypes.py

Fixes error when annotation json in a csv import file is written with single rather than double quotes re #7854
This can be tested on AfS with this csv and mapping file and the following command:
[Phys_thing_test.zip](https://github.com/archesproject/arches/files/7280462/Phys_thing_test.zip)
```
python3 manage.py packages -o import_business_data -s 'Physical Thing_test.csv' -c 'Physical Thing_test.mapping' -ow 'overwrite'
```

Convert json to dict regardless of single or double quotes

---

arches/app/media/js/views/components/cards/file-viewer.js

Handles for cases when a file tile is created from import or the api and for some reason the file object has no name and extension.

Handle for file tiles with no file name in the file value object, re #7943

---

arches/app/datatypes/datatypes.py

Save years before 1000 CE from csv import by padding year string with zeros to match Python's YYYY format (eg year 200 becomes 0200 and year 12 becomes 0012). This solution does not apply to years BCE. 
#7935
Model and data for QA:
[date_testing.zip](https://github.com/archesproject/arches/files/7435436/date_testing.zip)
Command for QA:
`python3 manage.py packages -o import_business_data -s 'date_testing/Robot.csv' -c 'date_testing/Robot.mapping' -ow 'overwrite' -g 93d791e8-3781-11ec-8ea7-0242ac1a0007`

Save years before 1000 CE from csv import 

---

arches/app/media/js/views/components/workflows/workflow-component-abstract.js

Set complete to false to ensure complete subscription fires. re #7968

Ensure loading spinner does not hang after saving some workflow steps. re #7968

---

arches/app/models/tile.py

Refactors the get_blank_tile Tile proxy model method to reuse parentnodegroup_id reducing db queries
#7974

Reduce queries in Tile.get_blank_tile method

---

arches/app/templates/views/components/widgets/file.htm

As per issue: https://github.com/archesproject/arches-her/issues/686 - Simply added `target="_blank"` to file link in report. Also removed an empty `class=""`.
Ensures that a user can continue to view the report page once a file has been downloaded.
#
*   Found by: @rlwilliamss
*   Tested by: @rlwilliamss

686 - Added target blank to link

---

arches/app/search/search.py
arches/app/utils/index_database.py
arches/install/requirements.txt
arches/management/commands/es.py

Provided the capability to index resources using multiprocessing via the `es` management command. 
Provided the capability to index resources using multiprocessing via the `es` management command. This is enabled by using the two new command parameters:
- `-mp` / `--use_multiprocessing`  flag to enable multiprocessing
-  `-mxp` / `--max_subprocesses`  (optional) - explicitly sets the maximum number of processes created by the process pool. Default = ceil(cpu_count / 2)
These parameters are available on the following es management module operations:
- …

7963 multiprocessing option for ES commands

---

arches/install/requirements_dev.txt

Removes fabric because it is no longer used as a dev dependency, re #7852

Remove fabric from requirements_dev.txt

---

arches/app/models/tile.py

Ensures that the `Tile.update_node_value()` method executes `after_update_all()` on the target tile so that any functionality tied to that gets run.
addresses #8047

runs after_update_all in Tile.update_node_value

---

arches/app/media/js/views/components/resource-report-abstract.js

Fix issue where resource editor report was not loading because resourceid was not yet avaiable, re #8041 
#

Fix issue where resource editor report would not load, re #8041

---

arches/app/models/migrations/7787_relational_data_model.py

re: #7787 
This PR adds the basic functions used to generate relational schema/views for arches resource models.
the following SQL query can be used after the migration is executed to generate schema for all active resource models:
```SQL
select __arches_create_resource_model_views(graphid)
from graphs
where isresource = true
and isactive = true
and name != 'Arches System Settings';
```
The schema for any resource model should include writable (insert, update & delete) views for instances as well as all nodegroups.  These views should be queryable for read & write operations.
This feature should be considered provisional and only announced in release notes when it is considered complete.  These functions will evolve over time and the interface may change between now and feature …

adds migration for relational data model functions

---

arches/app/media/js/views/components/resource-report-abstract.js

Fixes issue with retrieving the resource report ID inside a getjson call that was causing some report data not to load
#8068 

fixes resource report abstract ID retrieval

---

arches/app/media/js/bindings/ckeditor.js

Modifies CKeditor to respect changes to the widget's disabled observable.
Needed for [AFS PR #876](https://github.com/archesproject/arches-for-science-prj/pull/876)
fixes #8077 

If the value of "disabled" changes, update the editor's readonly method

---

arches/app/datatypes/datatypes.py
arches/app/views/tile.py

To test this create a card with 2 string nodes and 1 node-value node.
The node-value node should reference one of the string nodes.
Configure the graph's resource descriptor function to utilize this card and the string node not being referenced by the node-value node.
After the graph is saved, delete the string node that is referenced by the node value node.
Create an instance of the resource and try and save the card by filling out the string value and saving.
Before the fix an unhelpful error message is displayed.
After the fix a much more helpful error message is displyed
re #8094

fix issue with node-value node mis-configuration, re #8094

---

arches/app/utils/label_based_graph.py
arches/app/utils/label_based_graph_v2.py

Prevents child nodes from associated parent tile incorrectly in the LabelBasedGraph and LabelBasedGraphV2
#8089 

Fixes incorrect label based graph tile associations re #8089

---

arches/app/utils/label_based_graph.py
arches/app/utils/label_based_graph_v2.py

Reverses changes in PR #8089 because, although they fix #8106, they cause some tiles to not appear in the label based graph.

Reverse PR 8106 due to missing tiles in some resources, re #8089

---

arches/app/models/resource.py
arches/app/tasks.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py
tests/fixtures/testing_prj/testing_prj/settings.py

Adds a celery task that will index a resource, and a setting configuration controlling it. If enabled this can dramatically improve tile save time in resources with many related_resources, if the application is leveraging complex custom indices.
#8144

8144 cbyrd add task to async update custom indices

---

arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm

Reverts archesproject/arches#8113 which should be merged into dev/6.1.x, see #8113 and #8165

Revert "render card tree on demand"

---

arches/app/media/js/views/components/iiif-viewer.js
arches/app/media/js/views/components/plugins/manifest-manager.js
arches/app/templates/views/components/iiif-viewer.htm
arches/app/templates/views/components/plugins/manifest-manager.htm

Turns off split panel tools for manifest manager in workflow
fixes #8177 

Turns off split panel tools for manifest manager in workflow

---

arches/app/media/js/views/components/datatypes/domain-value.js

Fix for domain options being modified after initial setup.  In initial setup, all the text values are observables - afterward, they're all text.  This fixes that and subscribes to changes in those values in order to mutate the options array and allow for dirty state.
fixes #8168 

mutate domain options when domain values are changed

---

arches/app/media/css/accessibility.css
arches/app/media/css/arches.scss
arches/app/templates/views/components/search/advanced-search.htm

Advanced Search - make whole area of the facet header clickable. As per issue raised... #7830 
Entire facet header now clickable instead of just the expand/collapse icon.
#
*   Found by: @rlwilliamss
*   Tested by: @rlwilliamss

7830 usability adv search facet click area

---

arches/app/frontend/webpack/webpack.common.js

fixes #8234 by stopping jquery from loading twice
fixes #8234 

jquery loads twice fix

---

arches/app/search/search_export.py

Cherry picks 6.1 fix for GeoJSON search endpoint failing when first instance has no geom.

Cherrypick GeoJSON search endpoint fix from 6.1, re #8262 

---

arches/app/models/migrations/8009_etlmodule.py

Modifies __arches_staging_to_tile(load_id uuid) so that legacyids are preserved from the staging table to the resource_instances table.

Fix legacyid from staging table, re #8294

---

arches/app/templates/views/components/related-resources-map-editor.htm

Move 'Close' button into parent flex container so it's visible
#8332

Move 'Close' button into parent flex container so it's visible, re #8332

---

arches/app/utils/data_management/resource_graphs/exporter.py

exporting mapping files doesn't work as expected in command line. This changes enables export of single resource models in command line utility. fixed:
IsADirectoryError: [Errno 21] Is a directory: '<output_dir>'
TypeError: string argument expected, got 'bytes'
Added temporary name to config file, that is a temporary workaround
Changed usage of StringIO to BytesIO in zip saving
#8310 
-   [ ] Unit tests pass locally with my changes (i get No module named 'tests.test_settings' error)
-   [x] I have added tests that prove my fix is effective or that my feature …

Fixed the error explained in issue #8310, that is:

---

arches/app/media/js/viewmodels/map-editor.js
arches/app/media/js/viewmodels/map.js

Allows a card to define its own primary descriptor template. If a card has this.popupTemplate object defined the map will use it instead of the popup defined in the map-popup-provider. 
Example of Related Resource Map card using its own popup:
https://github.com/archesproject/arches/blob/83c785d51c16071ba212eea4899db3c189a9f172/arches/app/media/js/views/components/cards/related-resources-map.js#L11-L12
https://github.com/archesproject/arches/blob/83c785d51c16071ba212eea4899db3c189a9f172/arches/app/media/js/views/components/cards/related-resources-map.js#L281 …

Allow card to override default popup, re #8389

---

arches/app/media/js/utils/map-popup-provider.js
arches/app/media/js/viewmodels/map-filter.js
arches/app/media/js/viewmodels/map.js
arches/app/media/js/views/components/search/map-filter.js
arches/app/templates/views/components/search/map-filter.htm

Modify the map popup provider so that map popups are not displayed when in a draw mode. Needed to align the name of the `drawMode` ko observable in `viewmodels/map-filter.js` and `views/components/search/map-filter.js` with the similar observable called `selectedTool` in the `viewmodels/map-editor.js` so that the tool context can be passed into the `utils/map-popup-provider.js` in both contexts.
#8364 Popup displayed when map in drawing mode
-   [ ] I have added tests that prove my fix is effective or that my …

8364 - Do not display map popup when in draw mode

---

arches/app/models/migrations/8009_etlmodule.py

Add a database trigger to use the resource id if the resource id or legacy id is already in the system, #8450
This allows a user to append tiles to the existing resource if the resource id or legacy id is known during the etl process using db functions.
#8450

Add db trigger on load_staging to get resourceid from legacyid, #8450

---

arches/app/media/js/views/components/etl_modules/branch-csv-importer.js

Call graph endpoint only when a list of graphs is need to power the template dropdown.
#8495

Call graph endpoint only when graph list needed, re #8495

---

arches/app/media/js/views/components/search/resource-type-filter.js
arches/app/search/components/resource_type_filter.py
arches/app/search/components/search_results.py
arches/app/templates/views/components/search/resource-type-filter.htm
arches/app/utils/permission_backend.py

Filters out resource instances from search results of resource models for which all nodegroups are restricted.
#8438
This also solves most of #2491 with the exception of concealing displaynames/terms from restricted instances in the search suggestions. However, applying permissions to terms should probably be treated in a different PR because it involves resource instance permissions as well as nodegroup permissions, so we can close #8438 and #2491 when this PR is approved, and address term permissions under #7316

Filter instances when all nodegroups are restricted, re #8438 

---

arches/app/search/search_export.py

Fixes sanitization of csv values in search export

fix for s #1 - sanitize csv values

---

arches/app/models/migrations/8502_loadevent_indexed_time.py
arches/app/models/migrations/8528_bulk_load_performance_functions.py

Adds functionality to disable and re-enable triggers on the tiles table to increase bulk load performance.
Adds 3 procedures/functions to:
1. Disable triggers on the tiles table
2. Re-enable triggers on the tiles table, refresh spatial views, check for tiles cardinality violations
3. Retrieve a list of tiles cardinality violations
#8528 
* …

8528 - Functions to  disable/enable tiles triggers for bulk load performance

---

arches/app/models/graph.py

Checks for ontology_id rather than performing a database query to determine if a graph has an assigned ontology.
#8671

Check for ontology id rather than ontology object, re #8671

---

arches/app/models/resource.py
arches/app/search/search.py
arches/app/views/search.py

This updates the places in code where we're using the `displaydescription` and `displayname` objects retrieved from ElasticSearch. This does NOT update the `ResourceDescriptors` class as it's not being used anywhere that I can tell && having the raw ES return could be beneficial.
In a followup ticket, we should consider refactoring `Resource.get_documents_to_index` and the Resource database model to handle i18n in the application-standard way.
#8682 #8691

updates displaydescription and displayname returns from methods leveraging the ES index #8682

---

arches/app/media/js/views/components/widgets/switch.js
arches/app/models/migrations/7783_add_graph_publications.py
arches/app/templates/views/components/widgets/switch.htm

Fixes [object object] in the subtitle of the switch widget.  There are still some mysterious issues since the widget is instantiated twice (or more) in the graph designer and the config does not propagate correctly, but this change should make it functional.  
#8762 

Fix for [object object] error in subtitle for switch widget

---

arches/urls.py

This updates the url pattern for password reset confirmations. It's an interesting rabbit hole that landed at an issue discovered as of Django 3.1:
https://code.djangoproject.com/ticket/31913
https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#adding-a-password-reset-feature 
#8716

Update url pattern for password reset confirmation

---

arches/app/media/js/viewmodels/node-value-select.js

The previous logic uses a specific pattern to pull a `resourceId` from the URL, and fire a request that ultimately hits `permission_backend.check_resource_instance_permissions` . This function attempts to fetch the ResourceInstance from the database, and if that object doesn't exist it returns falsey. However the `add-resource` and `graph_designer` views do not yet have a `ResourceInstance` entry in the database, so the function incorrectly returns falsey and that results in an error.
#8763

update node-value-select to handle for edge cases #8763

---

arches/app/models/migrations/6458_language.py

Fixes #8784 by using the system language for the migration.  The old code was using the first language in the languages table, which is not always a reliable system language - it's not necessarily the same as LANGUAGE_CODE in the django settings.  The important note here is that when a user migrates to a7 - settings.LANGUAGE_CODE is the language they're going to migrate their default strings to, and when they back out of the migration, they're going to lose everything but settings.LANGUAGE_CODE as that is what the string will revert to.  
#8784
-   [ ] Unit tests …

fix reverse migration of 6458_language #8784

---

arches/app/views/resource.py

to fix issues with popups on map and iiif widgets, we should translate resource descriptors in the resource view.  the view now always returns a string for all descriptors, either: the only one available, the user's language translation, the system language translation, or the translated string "Undefined"
fixes: #8866

translates descriptors in resource view re: #8866

---

package.json

`jquery@3.6.0` was not compatible with some of its downstream dependencies. Upgrading to `jquery@3.6.1` solved the issue.
#8885

jquery dependencies not installed in new projects re #8885

---

arches/app/templates/views/components/widgets/text.htm

Remove z-index property that was causing language dropdown to appear behind other elements, re #8854
#

Remove z-index=0 from form group for langauge dropdown, re #8854

---

arches/app/media/js/views/resource/resource-editor-data.js

Allows manage permissions link to open permissions panel. This still requires a page refresh as described here: https://github.com/archesproject/arches/issues/8907
#8906

Ensure useriscreator is properly cast to boolean, re #8906

---

arches/install/requirements.txt
releases/6.2.0.md

Use arches-django-revproxy, pypi will reject github install of django-revproxy.
#8941, #8882

Revproxy dependency replacement and django patch upgrade, re #8941, #8882

---

arches/app/views/manifest_manager.py

Set thumbnail image size to the image size if the image is smaller than the default thumbnail size (300 x 300), archesproject/arches-for-science#943
Fix the issue of the thumbnail image not loading when the image itself is small.
https://iiif.io/api/image/2.0/#size
archesproject/arches-for-science#943

Set the thumbnail image size for the small images

---

arches/app/datatypes/datatypes.py

…sed, re #8965
Removes warning in the related resources validation if a resource instance's related resource does not already exist in the database. This validation bogs down data import with postgres and ES queries and can flood the terminal output with warnings that are not useful. In cases where this validation is needed, the 'strict' flag can be passed to the validation function.
#8965

Remove related resource warning unless strict validation is used

---

arches/app/datatypes/datatypes.py

Use settings.MEDIA_URL not hard coded /files/ prefix when generating URL during file upload
#8960 
PR currently targeting dev/6.2.x branch but this should probably be merged into dev/7.0.x

8960 - Use settings.MEDIA_URL for generated URL when uploading media

---

arches/app/templates/views/graph-designer.htm

Fix the issue of the report preview/option is not working when the user change the template.
#9038

Fix the graph designer report template preview, #9038

---

arches/app/media/js/views/components/cards/grouping.js
arches/app/templates/views/components/cards/grouping.htm

Fix the issue with saving tiles of the concept list nodes in a grouping card, #9040 
Also fix the issue with previous values persistent after deleting the tile
#

The concept list in a grouping card, #9040

---

arches/app/views/auth.py

Fixes issue with password validation messages not showing up.  Needs to be cherry picked to 6.2.x.

fix issue with password validation messages not showing up #8753

---

arches/app/models/graph.py
arches/app/views/graph.py

Add functionality to create editable future graphs on copy (clone) and remove on delete.

adds functionality to create editable future graph on copy and delete

---

arches/app/media/js/views/components/widgets/rich-text.js
arches/app/media/js/views/components/widgets/text.js

Fixes issue with mutating external observables for text and rich text widgets.
Fixes #9208
#9208

9208 external widget observables

---

arches/app/models/graph.py
arches/install/requirements.txt

Add a suffix to node aliases that violate the unique node alias constraint when appending a branch. 
Also upgrades python-slugify to support Python versions >= 3.7.
#8878 - v6

Avoid node alias conflicts when appending a branch v6 #8878

---

arches/app/models/migrations/9147_get_tile_cardinality_violations_i18n.py

Fix i18n bug in __arches_get_tile_cardinality_violations - was referring to graphs.name as text, not i18n JSON string.
#9147 
I've added a diff here - copied the new function to the reverse migration section to show the diff.: …

9147 - fix i18n bug in __arches_get_tile_cardinality_violations

---

arches/app/templates/views/components/cards/file-viewer.htm

Fixes #9239 by changing referencing the parent's showGrid method rather than the tile in fileviewer

Fixes file viewer broken in 7.x

---

arches/app/media/js/viewmodels/card.js

In v6 constraints are not available on card.params. Instead, they are available directly off of params. 
#7181

Get constraints directly off of params if available. re #7181

---

arches/app/models/models.py
arches/app/views/resource.py

Ensure resource has all required properties before modifying permissions and indexing. Fixes error when instances are indexed upon the creation of a new user.
#9251

Fix error preventing new users when resource instance permissions are used

---

arches/app/media/js/views/components/cards/grouping.js
arches/app/models/graph.py
arches/app/templates/javascript.htm

Fixes grouping card for Arches v7
To test:
- Create a new Resource Model
- Create 2 non-semantic nodes
- Notice the updated placeholder text ( instead of `undefined`, "Choose a sibling card..." )
- In the card tab, change both cards to grouping cards. Have each card group the other.
- Clone the model
- In either the cloned model or original model, delete a node. The grouping card containing the deleted card/node should not error.
Notice there are no errors throughout this process.
#9267 #9159

updates grouping card for 7.x #9267

---

arches/app/utils/data_management/resources/importer.py

Removing `prevent_indexing=prevent_indexing` from `pool.map(import_one_resource, lines, prevent_indexing=prevent_indexing)` in app/utils/data_management/resources/importer.py. 
#9023 
*   Found by: @SDScandrettKint 
*   Tested by: @SDScandrettKint

9023 Fix for JSONL import multiprocessing flag

---

arches/app/media/js/views/components/cards/file-viewer.js

Fixes issue with file viewer in #9241  - the dynamic loading bit was a fix for some slowness in 6.2.x - but is no longer needed in the webpacked version of arches (and in fact causes breakage)
#9241 

file viewer fix

---

arches/app/datatypes/datatypes.py
arches/settings.py

This change is currently only really applicable to projects that implement client side uploads.  Unfortunately this core level fix seems necessary in order to prevent the datatype factory from overwriting the file that gets written.  See Arches for Science for an implementation/usage.
#9321 

overwritten file fix for #9321

---

arches/app/media/js/views/components/search/resource-type-filter.js

Added a filter in the resource-type-filter.js to check for if model is active before adding it to array. Now only active models show in resource type filter.
In version 6.0.0, only active models would show in the resource type filter, however, this feature broke upon the release of 6.1.0. Adding a filter to check if the resource model is active now shows only active models in resource type dropdown.
#9435 …

Hide inactive models in Resource Type filter

---

arches/app/templates/views/components/plugins/manifest-manager.htm

Fix missing text for dropzone element in manifest manager, re https://github.com/archesproject/arches-for-science-prj/issues/1149

Change key for dropzone text in manifest manager, re #1149

---

arches/app/datatypes/datatypes.py
arches/app/media/js/views/components/datatypes/geojson-feature-collection.js

Previously, a string could be force inputted all of the service styling and clustering config inputs. This change checks in the front end whether the number is valid i.e not an empty string or a combination of integers and strings. Additionally, the value is saved to the node config when the save button is used, rather than when the value is inputted in order to fix the double save button issue that existed previously.
#9441
-   [ ] I …

9441 Resource overlay styling and clustering input fixes

---

arches/install/requirements.txt

Removes python-docx from core requirements - it doesn't appear to be used.

removes python-docx from arches core requirements

---

arches/app/models/graph.py
arches/app/models/resource.py
arches/app/utils/index_database.py

Modified how models/Resource class obtains its serialized graph, and the graph's root ontology
#9540 
__*Proposed solution*__
1. Add an setter method to allow the graph to be set on the models/resource/Resource class
2. Remove the graph serialization logic out of …

9540 index performance fix

---

arches/app/models/graph.py

Fixes an issue where publishing a graph and then restoring causes the sort order of nodes, cards and widgets to not be honoured
#9407 
*   Found by: @chiatt @bferguso 
This only addresses the publish->restore process that was causing the order of nodes, cards and widgets to mutate. The value …

9407 - Sort cards, widgets and nodes on serialize

---

arches/app/models/migrations/9477_fix_for_spatial_view_dbf_function_edtf_displaying_null.py
arches/app/models/migrations/9477_fix_for_spatial_view_dbf_function_table_alias_error.py

Fixes #9477 
- Fixes EDTF datatype values coming through as null.
- Fixes an issue where the UUID that forms part of a table alias can sometimes cause a compile error with PGSQL. This was achieved by simply wrapping the aliases in quotes.
*   Found by: @RobOatesHistoricEngland
*   Tested by: @RobOatesHistoricEngland
*   Designed by: @aj-he @RobOatesHistoricEngland

9477 edtf and table alias fix for spatial views

---

arches/app/media/js/views/graph-designer.js
arches/app/templates/views/graph-designer.htm
arches/app/templates/views/graph/graph-designer/node-form.htm

#9591 
TO REPRODUCE:
1. In the graph designer create a node, then a child node, save the edits.
2. click 'place nodes in separate card' switch to be truthy, save the edit.
3. Interact with the `allow multiple values swtich` and the `place nodes in separate card` switch, trying various combinations
4. Notice that only one set of save/edit buttons appears

resolves issue with 2 sets of save/discard buttons appearing in some edge cases #9591

---

arches/app/utils/data_management/resource_graphs/exporter.py

The path construction for the mapping file was using an internationalized string (file_name) and a regular one (".zip"). Added language index access to file_name. Had to add the import to Django's language library to do that in a clean way. Could do with a simple str() or other less graceful ways (would also work perfectly).
Now the mapping file can be generated from the command line (UI worked fine).
# …

Use I18n for mapping file export #9680

---

arches/app/templates/email/download_ready_email_notification.htm

The download ready email template will not always have a zip file available - sometimes the zip is not generated if the files are too big to be zipped.

fix for download_ready_email_notification template

---

arches/app/templates/views/components/widgets/rich-text.htm

Fixes crowding of node name & i18n options on Rich text editor
#9678

9678 Prevent rich text widget language options crowding

---

arches/app/media/css/base-manager.css
arches/app/templates/base-manager.htm
arches/app/templates/javascript.htm

Added a skip to content link at the top of every page, that targets a hidden element just inside 'main'. This is necessary and ideal for users using screen readers as it will skip all the left navigation menu items and top links, as this could become tiresome when listening to navigate the site.
The code has been previously used and audited successfully on HE specific Arches sites such as Warden and GLHER.
For now, the css styling has been included in the base-manager.css file which contains specific items regarding the base manager template. Obviously this can …

9555 Skip to content link added upon first keyboard tab

---

arches/app/utils/permission_backend.py

fixes #9698 - where transaction reversal fails if no records exist in the transaction table for non-superusers.  The fix modifies the user_created_transaction method to return "true" if there are no transactions to be rolled back.  Since there are no transactions, this will effectively make the reverse method a no-op that returns 200, rather than causing it to fail with 403.

fix for transaction reversal 403 

---

arches/management/commands/packages.py

Adds template loading to package load command.  For this to work, the arches templating application must be installed, there must be properly named templates in the "templates" directory inside of the package, and PR https://github.com/archesproject/arches-templating/pull/10 must be merged

adds template loading to package load process

---

arches/app/datatypes/datatypes.py
arches/app/models/concept.py
arches/app/models/tile.py
arches/app/utils/data_management/resources/formats/archesfile.py
arches/app/utils/data_management/resources/formats/csvfile.py
arches/app/utils/forms.py
arches/app/views/tile.py

purges count in favor of exists (where logical) to improve performance.

purges count method in favor of exists

---

arches/app/media/css/arches.scss
arches/app/media/js/views/components/search/saved-searches.js
arches/app/media/js/views/components/search/search-export.js
arches/app/media/js/views/components/search/time-filter.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/search/saved-searches.htm
arches/app/templates/views/components/search/search-export.htm
arches/app/templates/views/components/search/time-filter.htm

A user should not need to navigate back to the search toolbar to close the popup panels. These changes add close buttons for the time-filter, saved-searches, and search export components. 
#9535

9535 Add close button for search popup panels

---

arches/app/utils/data_management/resources/formats/rdffile.py

Issue : JSON-LD concept model handling does not handle null **domain nodes** whilst there is data in the **range node** on rdffile.py edge relationship generation.
ArchesProject GitHub Giveback Issue : #9561 
Fix : Do not parse the null. Domain node as Undefined (omitted from JSON) substitution used for Unknown (NULL value).
@chiatt @aj-he : Happy to rebase to dev/7.5.x if that'd be of help!  ^_^

9561 Json-Ld fix : Omit Edge from Null Domain

---

arches/management/commands/packages.py

Graphs with forward slash in cause an error when running create_package.
If a graph name has a forward slash ("/") in the name, replace it with a dash before writing the file. The graph name will still include the forward slash but the file written will have replaced it with a dash so linux doesn't recognise it as a directory.
#9777 
*   Found by: …

Fix for graphs with forward slash ("/") in name when using create_package (dev/7.4.x)

---

arches/app/models/fields/i18n.py
tests/localization/field_tests.py

This fix allows users to have strings that start and end with double quotation marks (" ") in i18n text inputs.
Inputting a string that starts and ends with double quotation marks (e.g. "Hello, world") into any Resource Model text input box that used internationalisation would save incorrectly - e.g. as "Hello, world" rather than {"en":""\Hello, world"\"}. Strings which included double quotations not at the start and end (e.g. "Hello", world) would save correctly (e.g. {"en": ""\Hello"\, world"}. 
This change converts inputs with double quotations at the start …

Fix for allowing double quotation marks in i18n inputs (dev/7.4.x)

---

arches/app/etl_modules/base_data_editor.py
arches/app/etl_modules/base_import_module.py
arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js
arches/app/models/migrations/9670_improve_bulk_load_performance.py
arches/app/templates/javascript.htm
arches/app/templates/views/components/plugins/etl-manager.htm

Improve the performance & logic report to the front end of the bulk editor by
- not checking cardinality errors (since editor does not change the number of tiles)
- improve the cardinality checking db function
- trying catching errors after the load (before index)
#9669, #9670, #9671

Improve bulk load performance, #9670

---

arches/install/requirements.txt

`requests` lifted its upper bound of `urllib3` from <1.26 to <3 in 2.30.0, but this conflicts with `elastic-transport`'s upper bound of <2. Add this upper bound back.
Lets `pip install -r arches/install/requirements.txt` succeed.
Closes #9826

Add upper bound on urllib3 (<2) #9826

---

arches/app/media/js/viewmodels/card-component.js

Adds an event listener for the keyboard shortcut CTRL and S. When activated, the event checks for the edited tiles and their "dirty" status, and if true then runs the save tile function.
#9830
*   Found by: @SDScandrettKint 
*   Tested by: @SDScandrettKint 
*   Designed by: @SDScandrettKint

Add resource editing CTRL+S save functionality

---

arches/install/requirements.txt

Ensure pytz and tzdata are at version compatible with Celery, re #9797

---

arches/app/media/css/accessibility.scss

Improves focus indicator for accessibility mode so that elements are not resized on focus.
#9709

9709 Improve focus indicator

---

arches/app/models/concept.py
arches/app/utils/i18n.py
arches/app/views/search.py
tests/utils/i18n.py

Before, the `prefLabel` on a concept select widget control used the last label returned from the db, which may or may not correspond to the desired language.
Now, we prefer the user's selected language or the system default language when there are labels in multiple languages. (This requires sorting the best language last given how the recursive search overwrites previous values.)
closes #9848 …

Fix incorrect language labels on concept select widgets #9848

---

arches/app/datatypes/datatypes.py
tests/utils/datatype_tests.py

Before, a required string field could escape validation because an object shaped like the following didn't clean to None:
```py
{
"en": {"value": "", "direction": "ltr"},
...
}
```
Now, they clean to None and the field validation works.
Closes #9281
*   Sponsored by:
*   Found by: @chiatt 
In #9281 @chiatt suggested …

Clean empty strings to None (to enforce field validation)

---

.github/workflows/main.yml

Builds are failing with cryptic errors about path conflicts. Usually this is a symptom of unexpected entries in `sys.path`. Installing arches in "development mode" with `-e` adds the current directory to sys.path (or, at least it did in legacy mode, and that might be the source of the new problems). That's not needed for CI, and not ideal for testing purposes anyway, as tests will execute against the repo checkout, not against the installation as users will see it.
See recent failing builds …

Remove editable flag on CI

---

arches/app/models/card.py

The frontend saves cards twice, once to update the card tree, and once to update the permissions tree. If these two requests are pending, and both requests "think" a new CardXNodeXWidget must be created (on a fast architecture like an M1 Mac), then the second will fail with an IntegrityError.
https://github.com/archesproject/arches/blob/9959ce34a4485fc636bdf4e258de5f84daab96ca/arches/app/media/js/views/graph-designer.js#L294-L295
Alleviated this race condition with `get_or_create()`, so that we can be sure we don't have multiple requests each trying to insert a …

Fix race condition when saving cards in graph designer #9858

---

arches/app/search/search_engine_factory.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Update settings.py and settings.py-tpl to show how to implement Elasticsearch API key credentials. This will only work with a non-Elastic Cloud instance of Elasticsearch. #9850 is required if you need to connect to Elastic Cloud using an API key. 
Fixes #9700
*   Sponsored by: Historic England 
*   Found by: @RobOatesHistoricEngland 
*   Tested by: @RobOatesHistoricEngland …

Add support for Elasticsearch API key authentication #9700 AB#57245

---

arches/app/media/js/bindings/term-search.js

Add a 500ms delay triggering the Ajax call to perform a search so that the number of Elasticsearch requests is reduced. Elasticsearch has a minimum character count of 2 characters before a search is requested. If the user supplied an 11 character search term - a total of 10 server requests would be made. Introducing a debounce will help reduce this number substantially.
Fixes #9820 
AB#59153 …

Add search debounce of 500ms AB#59153

---

arches/app/utils/index_database.py

Within **_index_resource_batch** the function call to **index_resources_using_singleprocessing** used incorrect arguments, including superfluous **SearchEngineInstance** (refactored). 
#9953 
*   Sponsored by: HistoricEngland
*   Found by: @khodgkinson-he

Fixed function call parameters #9953

---

arches/app/media/js/views/components/resource-report-abstract.js

If the core arches views are included in a project under /arches,
this path wouldn't resolve correctly. Harden this so that it gets the resource id more reliably.
Ideally, do this in a project that includes core arches views under `/arches`.
1. Create a resource.
2. Click …

Harden link resolution of resource report

---

arches/app/models/migrations/10006_fix_escape_chars_breaking_bulk_edit.py

re #10006
To reproduce, save a string with a value that contains a backslash: eg "testing \something"
Run any of the bulk editor operations (trim, capitalize, etc...) on that field.
Notice that the bulk operation fails.

fix bulk edit operations when data contains escape chars, re #10006

---

arches/app/media/js/viewmodels/workflow-step.js

self.saving() was never set False when a workflow step promise was rejected.
Although the prior syntax looks correct to me, it seems knockout might be expecting an unwrapped callback (?)
Refs archesproject/arches-for-science-prj#1258
Perhaps easiest to test by following the testing instructions at [arches-for-science-prj#1259](https://github.com/archesproject/arches-for-science-prj/pull/1282) …

Unwrap finally callback to ensure execution

---

releases/6.2.0.md
releases/6.2.1.md

Fix the version number of `arches-django-revproxy` in release notes. Discovered installing 6.2 a couple weeks ago that the given version number doesn't exist.

[6.2.x] Fix version number of arches-django-revproxy in release note

---

arches/app/models/tile.py

Uses serialized graph in tile model.  This was already used in quite a few places here, there were only a few changes to make.

uses serialized graph in tile model

---

arches/app/views/manifest_manager.py

Reraise errors instead of swallowing them and returning None. Allows error banner to appear in UI and django debug response to appear in network tab.
Closes #9986
Before, failures in the manifest manager were almost always silent.

Let errors bubble up in `ManifestManagerView` #9986

---

arches/app/media/js/viewmodels/widget.js

`this.value` is not always an observable:
https://github.com/archesproject/arches/blob/6346ab34e10e5cf2331108947e097d8285c183cc/arches/app/media/js/viewmodels/widget.js#L33
Closes #10043, see testing instructions there

Account for `this.value` not being an observable #10043

---

arches/install/arches-admin
arches/install/arches-project

Fixes issue where on using the arches-project create command, if the arches version development stage is "alpha" or "rc" (as documented in the file), it sets the `dependencies` and `devDependencies` reference to master instead of the development branch. This causes the created project to not start correctly.
dev/7.5.x doesn not currently create a working project without then manually setting the package.json branch references.
The solution ensures that when the arches version is "alpha" and "rc", it uses the current dev branch.
fixes #10048 
-   [x] Unit tests …

Fixes issue where setting the arches version stage to "alpha" or "rc" stops package.json being created correctly #10048

---

arches/install/ubuntu_setup.sh

Changes how node is installed in the ubuntu setup script.  Also adds note that removes support for Ubuntu 18.04 - which is now [out of standard support](https://ubuntu.com/about/release-cycle).  
Tested and verified working with Ubuntu 20.04.

10009 node script deprecation

---

arches/app/templates/base-manager.htm
arches/app/views/resource.py

Adds a "View Report" button to the resource editor view, acting as a reverse to the edit resource button.
#
*   Found by: @SDScandrettKint 
*   Tested by: @SDScandrettKint 
*   Designed by: @SDScandrettKint 
Currently the only way to see the report from the resource editor view is to replace "resource" with "report" in the URL or to …

Add a "View Report" button to resource editor

---

arches/app/media/js/viewmodels/widget.js
arches/app/templates/views/components/widgets/base.htm
arches/app/templates/views/components/widgets/checkbox.htm
arches/app/templates/views/components/widgets/concept-select.htm
arches/app/templates/views/components/widgets/datepicker.htm
arches/app/templates/views/components/widgets/edtf.htm
arches/app/templates/views/components/widgets/file.htm
arches/app/templates/views/components/widgets/iiif.htm
arches/app/templates/views/components/widgets/map.htm
arches/app/templates/views/components/widgets/node-value-select.htm
arches/app/templates/views/components/widgets/number.htm
arches/app/templates/views/components/widgets/radio-boolean.htm
arches/app/templates/views/components/widgets/radio.htm
arches/app/templates/views/components/widgets/resource-instance-select.htm
arches/app/templates/views/components/widgets/rich-text.htm
arches/app/templates/views/components/widgets/select.htm
arches/app/templates/views/components/widgets/switch.htm
arches/app/templates/views/components/widgets/text.htm
arches/app/templates/views/components/widgets/urldatatype.htm

Adds the associated node alias and widget name as classes to HTML container elements to allow specific node elements to be targeted by CSS rules.
_Implementation Notes_
- Currently just added at a top level `div` for each widget/report/display_value section to not litter many HTML elements with the same classes. 
- `report` elements do not appear to have a top level `div` so applied to the `dt`, and `dd` elements.
- widget name is only available when in the `form` elements are visible. 
- `node_alias` is available for `form`, `report` and `display_value` blocks. …

10011 add node alias and widget name as class to HTML elements

---

arches/app/datatypes/base.py

When attempting to delete all files from a saved tile, TypeError was raised. Now it's fixed.
A tile value of `[]` is falsey, so it was bypassing this check, meaning get_tile_data() returned an implicit None after logging "Tile has no authoritative or provisional data".
Closes #10057
Refs #9704 (for initializing k/v pairs in tile data to None)

Fix TypeError when deleting all files from tile #10057

---

arches/app/datatypes/datatypes.py

Fixes #10109 which would temporarily switch the file storage to avoid writing zero byte files to the cloud to prevent duplication - this is no longer necessary.  Also outputs the file's path - which can sometimes be changed by the file storage backend.

removes the switching of file storage

---

arches/app/datatypes/datatypes.py
arches/app/media/js/viewmodels/file-widget.js

I originally sought a backend solution for this similar to what @jacobtylerwalls was thinking in the ticket. There appears to be no great way to differentiate `File` objects with posted file data. Turns out the `formData` was not getting cleared after a tile save and was therefore submitting polluted data on multiple uploads.
This also includes a small performance improvement since I was already touching the backend.
#10127 
#10058

fixes exponential files upload bug #10127

---

releases/7.0.0.md

Forwardport of #10025 (different files involved)

[7.4.x] Fix version number of arches-django-revproxy in release note

---

arches/app/media/js/views/components/widgets/rich-text.js
arches/app/media/js/views/components/widgets/text.js

Before, using the language picker in the text/rich text widgets would not actually save language/direction to the tile, as only the key in the I18n object was the language before changing (likely to be English).
Closes #10122
- Manipulate language, direction, save
- Check tile data
LMK if I should …

Fix language selection in text widgets #10122

---

arches/app/models/resource.py

Prevents the provisional flag from getting assigned to resources that have no tiles. Also, fixes logic to assign the provisional flag to resources that have tiles, but none with authoritative data.
#10130
To QA:
1. Using a provisional editor, create a resource with one provisional tile. Confirm in search that it has the provisional flag.
2. Using an authoritative editor, create a second, authoritative tile. Confirm it still has a provisional flag.
3. Delete all tiles from the resource instance. Confirm in search that it has no provisional flag.

Properly assign provisional flag during index, re #10130

---

arches/app/media/css/arches.scss

The spinner is usually put on `.loading-mask::before`. For layout reasons, `.search-result-details` and `.file-viewer` are putting it on `.loading-mask::after`. Need to suppress the other spinner.
Try the workflow from #10159, specifically interacting with the footer of the Update Project Collection workflow in AFS, e.g. the last two pages. Add network throttle if needed.
Closes #10159
I'm open to other ways of doing this.

Remove duplicative spinner in `.search-result-details` #10159

---

arches/app/media/js/viewmodels/concept-select.js

`select2` can't cope with async requests each trying to initialize the widget.
Closes #10162
You might see another TypeError from clicking on Project Selection, but it traces from CKEDITOR, and there's discussion [here](https://github.com/ckeditor/ckeditor4/issues/5460).

Fix race condition in concept select widget #10162

---

arches/install/arches-templates/project_name/settings.py-tpl

RENDERERS is [documented](https://github.com/archesproject/arches-docs/blob/bd3d919661e2f210f755a500abfa9641ef4970d0/docs/developing/reference/import-export.txt#L170), and relied upon in several places in arches, so it's not optional. Add it to the settings.py template.
*   Found by: @ekansa in archesproject/arches-for-science#1373

Add `RENDERERS` to settings.py template

---

arches/management/commands/packages.py

Before, on running `manage.py packages -o load_package`, JSON files for further card components, reports, or plugins beyond the first would overwrite the previous one in place.
Noticed this in DISCO, where [here](https://github.com/archesproject/disco/blob/main/disco/card_components) I would have expected a folder containing two card components (instead, one card component only, called "card_components".
Will open a separate cleanup PR to DISCO.
Closes #10160

Place JSON configs for card components etc in correct place #10160

---

arches/app/datatypes/datatypes.py

Fixes an issue that occurs when using more than on EDTF node per card as criteria in advanced search. 
#10112 
*   Sponsored by: @aj-he 
*   Tested by: @aj-he @apeters 
*   Designed by: @aj-he

Fixes multiple EDTF nodes in single card used in advanced search returning too many records

---

arches/app/media/js/viewmodels/card-component.js
arches/app/media/js/viewmodels/widget.js
arches/app/media/js/views/resource/editor.js
arches/app/templates/views/components/cards/default.htm
arches/app/templates/views/components/cards/grouping.htm
arches/app/templates/views/components/file-workbench.htm
arches/app/templates/views/components/iiif-annotation.htm
arches/app/templates/views/components/map-editor.htm
arches/app/templates/views/components/photo-workbench.htm
arches/app/templates/views/components/related-resources-map-editor.htm

- Adds the graph slug as a class to widget HTML nodes.
- Adds graph slug, widget name, node alias and static string `card_component` to widget parent HTML tag to allow more flexible formatting of page via CSS
#10119 

10119 add graph slug as class

---

arches/app/datatypes/datatypes.py
arches/install/arches-templates/project_name/settings.py-tpl
tests/models/tile_model_tests.py

Updates 7.4 with bug fixes in 6.2.x

Update 74x with 62x

---

arches/app/media/js/viewmodels/resource-instance-select.js

If a document has >1 resource instance select widgets, they may both try to initialize select2 widgets, which manage references to the DOM and cannot handle parallel init'ing.
Fixes #10210
Sourced to a36a9465c94a29831c499a7be89610658a225519.
Ensure that icons still appear in the resource instance …

Fix race condition in resource-instance-select.js #10210

---

arches/app/media/js/bindings/clipboard.js
arches/app/media/js/views/graph/graph-designer/graph-tree.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/search/search-export.htm
arches/app/templates/views/graph/graph-designer/graph-tree.htm

Adds a button to copy node UUIDs to clipboard in the graph designer tree.
Adds a button that shows up in the graph designer node tree once 'show IDs is clicked' that allows the current node UUID to be copied to the clipboard. This provides a quicker way of obtaining a node UUID than the previous method of using inspect element.
When show IDs is off:
When show IDs is on:
#
* …

Add a button to copy node UUIDs to clipboard in graph designer tree

---

arches/install/arches-templates/project_name/webpack/webpack.config.dev.js
arches/webpack/webpack.config.dev.js

Removes full-screen overlay for frontend errors when running webpack development server.
#10224

Removes full-screen overlay for frontend errors when running webpack development server. #10224

---

arches/app/media/js/views/components/plugins/manifest-manager.js
arches/app/views/manifest_manager.py

sets the default canvas name to 'blank' - corrects issue where it can occasionally be 'undefined'.

default canvas names should be blank - not 'undefined' #10204

---

releases/7.0.0.md
releases/7.1.0.md
releases/7.1.1.md
releases/7.2.0.md

`{{ block.super }}` is necessary to avoid losing all of the strings defined in core arches.
Noticed upgrading an arches project to 7.5 and including a new string.

Add missing `{{ block.super }}` to javascript.htm instructions

---

arches/app/templates/views/report-templates/default.htm

The default report will hide the tile separator lines when the card is invisible. #10219 
Fix the issue with showing only the separator with no contents in the card that participate in the other grouping card.
#10219 

Hide the separator line for invisible card, #10219

---

arches/app/etl_modules/base_excel_exporter.py
arches/app/etl_modules/branch_excel_exporter.py
arches/app/etl_modules/tile_excel_exporter.py
arches/app/templates/javascript.htm
arches/app/templates/views/components/etl_modules/branch-excel-exporter.htm
arches/app/templates/views/components/etl_modules/tile-excel-exporter.htm

Display the export status during the etl process before the export is done, #10238
#10238

Display the export status during etl, #10238

---

arches/app/datatypes/datatypes.py
arches/app/utils/data_management/resources/importer.py
arches/install/arches-app-templates/setup.py
arches/install/arches-project
arches/management/commands/datatype.py
arches/management/commands/fn.py
arches/management/commands/packages.py
arches/management/commands/search.py
arches/management/commands/utils.py
setup.py
tests/base_test.py
tests/exporter/datatype_to_rdf_tests.py
tests/exporter/jsonld_export_tests.py
tests/exporter/resource_export_tests.py
tests/importer/datatype_from_rdf_tests.py
tests/importer/jsonld_import_tests.py
tests/models/mapped_archesjson_import_tests.py
tests/models/mapped_csv_import_tests.py
tests/models/resource_test.py
tests/utils/activitystream.py
tests/views/api_tests.py
tests/views/search_tests.py

- Fix incompatibility with Python 3.11 (remove deprecated/removed "universal" mode in `open()`) (See [forum post](https://community.archesproject.org/t/getting-error-valueerror-invalid-mode-ru-when-run-python-manage-py-setup-db/2127/2))
- Add classifiers showing Python 3.11 support
- Resolve DeprecationWarnings for `imp` module (deprecated in 3.4, removed in 3.12)
Closes #9832
Closes #8083

Support Python 3.11

---

arches/app/search/search_export.py

In the example below, I am attempting to nest:
**Discovery
└─> Location Data
____└─>Geometry**
However as **Geometry Card** is processed before it's parent **Location Data Card** is added, it can never be appended..
To address this I have introduced a loop whilst sub-cards have been added to the main card list, to check if they have sub-cards in turn.
#10199 
This is likely an historical remnant of when Arches only allowed sub-cards nested two levels deep.

Handle multiple Subcard levels in Search Export.  #10199

---

arches/app/media/js/viewmodels/resource-instance-select.js

This change allows the resource instance select search string to be an absolute path without location origin sections of the url (`https://<hostname>:<port>`
#9224 
Did not include omission of the context root as that is likely specific to our implementation and would …

9224 - Do not require hostname in resource instance search string

---

arches/management/commands/packages.py

The sample function file and the [docs](https://arches.readthedocs.io/en/stable/developing/extending/extensions/functions/#creating-a-function) both suggest
placing function.py files loose under /extensions/functions, e.g.
extensions/functions/foo.py.
The globbing pattern here was skipping over them, expecting
them instead at extensions/functions/foo/foo.py, like [card components and friends](https://github.com/archesproject/arches-for-science/tree/e2679e74ea14619c03e1b613db3cd9b40808d6cb/arches_for_science/pkg/extensions/card_components).
The intent here is to …

Fix function registration

---

arches/app/models/concept.py
arches/app/views/concept.py

Previously a second db query was performed to identify exact matches and place them at the top of a concept widget result set. This allowed concepts to appear that existed outside of a nodes collection. This fix identifies exact matches limited within a nodes collection. 
#10307, #10306

Prevent concept widget from allowing selection of concepts outside collection

---

arches/app/datatypes/datatypes.py
arches/app/media/js/views/search.js
arches/app/views/search.py

Fixes failing query and error message
#10250

Fix edtf advanced search error message

---

arches/app/templates/login.htm
arches/app/views/api.py
arches/app/views/auth.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/install/requirements.txt
arches/settings.py
releases/6.2.6.md

Add rate limiting to auth views. Expose `RATE_LIMIT` as a setting. See [accepted possibilities](https://django-ratelimit.readthedocs.io/en/stable/rates.html#rates-chapter), e.g. `12/5m`, or a python callable.

Rate-limit login views

---

arches/app/models/migrations/0001_initial.py

Fixes intermittent failures when migrating a fresh database like this:
```
django.db.utils.IntegrityError: null value in column "name" of relation "django_content_type" violates not-null constraint
DETAIL:  Failing row contains (1, null, models, bulkindexqueue).
```
The migration now depended on removes that `name` field, so that would make sense that it prevents the given error.
Closes #10302
*   Tested by: @jacobtylerwalls 
cc/ @aarongundel as we looked at this …

Add contenttypes dependency to initial migration #10302

---

arches/app/functions/primary_descriptors.py
arches/app/models/resource.py
arches/app/views/api.py

See use case in #10299: when overriding this function, it may be useful to know _which_ kind of descriptor is being resolved.
Closes #10299

Make primary descriptor fn aware of which description it's calculating #10299

---

arches/app/media/js/bindings/time-wheel.js
arches/app/templates/views/components/search/time-filter.htm

The double-click handler on the time wheel was not functional.
Closes #10293
The UI still distinguishes between a click and a double-click. Is that desired? Additional code could be removed in that case.

Remove double-click handler from time wheel #10293

---

arches/app/media/css/components/_index.scss

Fixes #10332
75px seemed to do the trick for the word "Delete", but I opted for 80 just to add some headroom for other languages (without reinventing the whole ~map~ wheel here).

Fix alignment of delete button in map widget #10332

---

arches/install/requirements.txt
releases/7.5.0.md

- Upgrade to latest Django patch release (from this morning)
- Upgrade to latest 2.x psycopg2 patch release
- Revert to upstream `django-revproxy`, with declared support for Django 4.2
Closes #10117
Uninstalling the arches fork of django-revproxy (`arches-django-revproxy`) is smart, but not strictly needed:
```py
>>> from revproxy import __version__
>>> __version__
'0.10.0'
```
And after installing `django-revproxy`:
```py
>>> from revproxy import __version__
>>> __version__
'0.12.0'
```

Bump Django to 4.2.8 and django-revproxy to 0.12.0 #10117

---

arches/install/requirements_dev.txt
releases/7.5.0.md
tests/exporter/datatype_to_rdf_tests.py
tests/importer/datatype_from_rdf_tests.py
tests/utils/activitystream.py

`mock` was just a backport of the unittest.mock module, which has been available in the stdlib since Python 3.3.
Noticed this when trying to run tests after forgetting to install the dev dependencies.
Other dev dependencies are already being removed in 7.5, so it seemed a good time to propose one more cleanup.

Remove `mock` from dev dependencies

---

arches/app/tasks.py
arches/app/views/search.py

Hey @csmith-he :wave: Thanks for the additional details on #9180--very helpful!
***
I opened this draft just to demo my idea at https://github.com/archesproject/arches/pull/10237#discussion_r1384194720.
Really, it's a lot like your solution in #10237, but it just programmatically deletes the file (and thus nothing left behind to clean up.)
From the traceback you posted, the failure on `wb.save()` suggests to me that the file was opened with `delete=True`, which I would [expect to fail on Windows](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) with PermissionError if reopened (as wb.save() tries to do).
***
I'd be grateful if you'd be willing to see if this diff solves your use case. Or if it doesn't, if it perhaps produces a different traceback.

Add Windows compatibility to tile excel export #9180

---

arches/apps.py

Adds a system check (warning) if your configuration is not using a cache backend that supports rate-limiting the auth views.
Refs #10323
```
arches % python3 manage.py check
System check identified some issues:
WARNINGS:
?: (arches.W001) Cache backend does not support rate-limiting
HINT: Your cache: django.core.cache.backends.locmem.LocMemCache
Supported caches: ('django.core.cache.backends.memcached.PyLibMCCache', 'django.core.cache.backends.memcached.PyMemcacheCache', 'django.core.cache.backends.redis.RedisCache')
```
Other manage.py commands also surface checks, e.g. `runserver` and `migrate`. The check can be silenced with `SILENCED_SYSTEM_CHECKS`.
@chiatt I'll defer to you on what you think the release note should be, if any.

Add system check for cache backends capable of rate-limiting

---

arches/app/models/models.py
tests/models/resource_test.py
tests/models/tile_model_tests.py

`update_or_create()` will break on Django 4.2 for models with custom save methods that set model fields unless we account for this by updating the `update_fields` argument. See [release notes](https://docs.djangoproject.com/en/4.2/releases/4.2/#setting-update-fields-in-model-save-may-now-be-required).
Added two tests (for the more important models of the three affected) that fail on the target branch.
I'm fairly certain we're okay with the proxy model save methods; just need to look at the ones that actually accept `**kwargs`.
Closes #10352
-   [x] Unit tests …

Update `update_fields` in custom save() methods #10352

---

arches/install/requirements.txt
releases/7.5.0.md

Adds Python 3.11 compatibility

Bump celery to 5.3.6

---

arches/app/utils/data_management/resource_graphs/importer.py
arches/app/utils/thumbnail_factory.py

There's nothing wrong with importing graphs into an environment without ontologies in their db. Demote this UI error to a logged warning.
Closes #9649

Demote no-ontologies UI error to a logged warning #9649

---

arches/app/models/migrations/10150_add_default_value_file_list.py
arches/app/templates/views/user-profile-manager.htm
arches/management/commands/updateproject.py
releases/7.5.0.md

Using a proxy model in a migration can create drift. Better to accomplish this with a `publish` command inside the `updateproject` command.
Follow-up to #9333

Avoid publishing graphs in migrations

---

arches/app/search/time_wheel.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py
releases/7.5.1.md

-   [x] Performance improvement
Adds a default cache timeout to the CACHE_BY_USER setting so that the timewheel config can be cached for all users.
#10457

Adds v5 timewheel cache default

---

arches/app/media/css/arches.scss

Prevent card help or graph publication modals from appearing behind the map workbench buttons.
Fixes #10432
*   Found by: @JPdelaRosa83
The git history shows this change (200 -> 1000) was made for RTL, so a quick check that all is good in RTL at 500 would be wise. (Looked OK to me.)

Stop map buttons from appearing over modals and help #10432

---

.github/workflows/main.yml
pyproject.toml
releases/7.6.0.md
setup.py

Require Python 3.10+ in Arches 7.6 (LTS)
Python 3.12 support should be declared once more (all?) Arches dependencies declare their support, although it may be functionally okay already.
This enables using Python 3.10 features like:
- `match`/`case` statements
- `zip(strict=True)` for added safety against iterating jagged arrays
Closes #9111

Require Python 3.10+

---

arches/app/media/css/arches.scss
arches/app/templates/views/components/file-workbench.htm
arches/app/templates/views/components/photo-workbench.htm

Before, for the file viewer and image gallery cards, the card level help was only accessible from the "edit" tab, which in the case of the file viewer card, is only accessible after uploading one file.
Now, the help is surfaced outside the side tabs in the main file widget area.
Closes #10318
*   Sponsored by: Auckland
*   Found by: @JPdelaRosa83
*   Tested by: …

Surface card help panel in main file widget area #10318

---

arches/app/media/js/views/components/widgets/rich-text.js
arches/app/media/js/views/components/widgets/text.js

Previously, for a string node allowing multiple values, leaving
no value for the first node entry, clicking the "+" to get a second
entry box, switching the language, and then typing in the text
entry caused a perpetual restoration of the original blank value.
Also include a backport of #10140.
Fixes #10468
*   Sponsored by: Auckland
*   Found by: @JPdelaRosa83
There is probably a deeper cause either with change listeners not being deregistered or with mutating objects that might be better as immutable, but those would be bigger …

Fix text entry after switching language in rich-text widget #10468

---

arches/app/datatypes/datatypes.py
arches/app/utils/string_utils.py
arches/app/views/resource.py
arches/install/requirements.txt
releases/7.6.0.md
tests/utils/datatype_tests.py

Depends on archesproject/arches#10456
On python 3.12, Arches had an undeclared dependency on a util (`strtobool()`) from older versions of `setuptools` which still vendored distutils, since `distutils` is no longer in the stdlib. Instead just reimplement the functionality to avoid pulling in setuptools or anything else as a dep.
~Bumps `mapbox-vector-tile` to a version that doesn't pull in `setuptools` as a dependency (and a version that explicitly supports python 3.11).~ EDIT: removes it altogether.
Closes #10460
- …

Replace `strtobool()` #10460

---

arches/app/models/tile.py
tests/models/tile_model_tests.py

In the if block in this diff, the usual code path is to fetch from the Nodes table because `node` was a `SimpleNamespace` object from the serialized graph. Then, the cardxnodewidgets was never fetched, so we defaulted to the node name, even if a widget label was available.
Then, this uncovered #9280 again, so I fixed that also.
Closes #10486
Closes #9280

Use widget label in TileValidationError #10486

---

arches/app/media/js/views/components/workflows/workflow-component-abstract.js

Fixes arches for science workflow issue where default step value of undefined is not equal to resource instance select empty value of null.

update workflow component abstract to default to null value

---

arches/app/search/search_export.py
arches/app/utils/data_management/resources/formats/csvfile.py

Fixes warnings for "invalid escape sequence" (DeprecationWarning on 3.11; SyntaxWarning on 3.12+). Since these sequences are regex syntax, marking them as raw strings dismisses the warnings.
[See blog post for deep dive](https://adamj.eu/tech/2022/11/04/why-does-python-deprecationwarning-invalid-escape-sequence/)

Fix "invalid escape sequence" warnings

---

arches/app/models/resource.py
arches/app/views/api.py

There are some examples where a list of tiles gets checked against a user's permissions. The issue (#9484)  is that we only care about whether the user has permission for the nodegroup, but we're checking all tiles and thus we're checking tile.nodegroup permissions even after we already know whether the user has permission for that nodegroup.
The two changes made in this PR are in the Resource proxy model to more efficiently leverage the permission backend in the `load_tiles` method, as well as in the Resource Report API to achieve the same for tiles and cards …

9484 report tile perm optimize

---

arches/management/commands/packages.py

Replaces the default `python manage.py packages` command with a helpful prompt to use --help to learn more about the command rather than resetting the database.  
Could replace `setup` with another of the commands, but a non-harming message seemed better even though it isn't in the choices list.  If the default value could call --help that would be better, but I'm not sure if that is possible
#10103  …

Remove setup as default from `python manage.py packages` to prevent fatal mistakes

---

arches/app/media/js/viewmodels/file-widget.js
arches/app/media/js/views/components/cards/photo-gallery-card.js

Fix file URL handling to be consistent in file widget and photo gallery card.
Don't add prefix if it already starts with it
#10584 
*   Sponsored by: Self Funded 

10584 - Make file URL formatting consistent

---

arches/app/datatypes/base.py
releases/7.5.1.md

@chiatt [points out](https://github.com/archesproject/arches/pull/10572#discussion_r1486902445) that a tile can have only None saved to it after saved data is deleted, so this shouldn't emit a logged exception.
Then, remove release note duplicated from 7.5.0 in 7.5.1.
4b02d35d097230f273d34e8aac86204efe5d2057 changed the if/else logic so that tiles with only falsy values reach the else catchall and log an exception (7.5.0)
e4a519e531a tightened that up to "only None values" to exempt falsy values like `[]` in the file-list datatype. (7.5.0)

Avoid logging exceptions for tiles with only None values

---

releases/7.5.0.md

Came up in an Arches implementation upgrading to 7.5.

Update 7.5 breaking changes with `<select>` admonition

---

.eslintrc.js
arches/app/src/declarations.d.ts
arches/install/arches-app-templates/.eslintrc.js
arches/install/arches-app-templates/tsconfig.json
arches/install/arches-templates/project_name/.eslintrc.js
arches/install/arches-templates/project_name/tsconfig.json
tsconfig.json

I found these small adjustments to be necessary when dev'ing #10569.
- [Declare primevue submodules](https://github.com/archesproject/arches/commit/bcd6f8e6c3a5d5e38ed30b97d5e4fbd3106304e5): was getting:
```
arches/app/src/plugins/ControlledListManager.vue:4:19 - error TS2307: Cannot find module 'primevue/toast' or its corresponding type declarations.
4 import Toast from "primevue/toast";
~~~~~~~~~~~~~~~~
```
- [Turn off typescript in vue templates (for now)](https://github.com/archesproject/arches/commit/92123cdf9d85576f3c0ffaf5e74cf2cb7bd63313): We weren't …

Adjustments to eslint / typescript configs

---

arches/app/media/js/utils/create-vue-application.js
releases/7.6.0.md

Add ~toast (error message) and tooltip~all services and directives from PrimeVue to the `createVueApplication()` util so that they're available out of the 🎁 .
Closes #10621

Add primevue services to vue app wrapper #10621

---

tests/models/resource_test.py

The recursion error described in #9198 for 7.2 was fixed in 7.4 by de4b9d2, which isolated the resource descriptor getting from resource descriptor calculating. The resource-instance datatype calls `displayname()`, but in 7.4 that just fetches--it doesn't recalculate. Before, that call to displayname() would recalculate, but the caller was already trying to recalculate.
Added a regression test that fails on 7.2:
```py
======================================================================
FAIL: test_self_referring_resource_instance_descriptor (tests.models.resource_test.ResourceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/jwalls/prj/arches/tests/models/resource_test.py", line 317, in …
```

Add regression test for #9198

---

arches/app/datatypes/url.py

fix bug with creating json-ld with url datatypes, re #9190

---

arches/app/views/api.py

I suggested a pattern when reviewing #10546 that I just now discovered doesn't work for null sortorders on CardXNodeXWidget records.
Would appreciate a review @whatisgalen if you are available, thanks!
To test, ensure you can view a resource report for a resource with a null sortorder on a cardxnodexwidget row.
Was seeing:
```py
File "/web_root/arches/arches/app/views/api.py", line 1158, in get
for widgets in [sorted(card.cardxnodexwidget_set.all(), key=attrgetter("sortorder")) for card in permitted_cards] …
```

Harden ResourceReport.get() against null sortorder

---

arches/app/datatypes/base.py
arches/app/media/js/viewmodels/file-widget.js
arches/app/media/js/views/components/cards/photo-gallery-card.js
arches/app/models/graph.py
arches/install/requirements.txt
releases/7.5.1.md
releases/7.5.2.md
tests/views/workflow_tests.py

Update Dev/7.6.x with latest commits from dev/7.5.x

Update Dev/7.6.x with latest commits from dev/7.5.x

---

arches/app/media/js/views/components/cards/photo-gallery-card.js
arches/app/templates/javascript.htm
arches/app/templates/views/components/photo-workbench.htm

Upload Photographs widget changed to display max-photo-size-warning containing dynamic "maximum size of any single file" value corresponding to the Max File Size as set on the widget manager / db.
#10653

Emend Photo Card max-photo-size-warning.

---

arches/install/requirements_dev.txt
releases/7.6.0.md

Resolves RemovedInDjango51Warning re: get_storage_class:
```py
2024-03-13 12:23:44 /web_root/ENV/lib/python3.11/site-packages/silk/models.py:28: RemovedInDjango51Warning: django.core.files.storage.get_storage_class is deprecated in favor of using django.core.files.storage.storages.
2024-03-13 12:23:44   silk_storage = get_storage_class(SilkyConfig().SILKY_STORAGE_CLASS)()
```

Bump django-silk to 5.1.0

---

package.json
releases/7.6.0.md
yarn.lock

Allows using `nodeicon` slot in `<Tree>`, see [release notes](https://github.com/primefaces/primevue/releases/tag/3.50.0).
Currently using this to ease implementation of the LetterCircle icon in 7b24d5f4bbabbfc3aae4ebd7fd9f72c7f6f55b07.

Bump primevue to 3.50.0

---

arches/install/arches-app-templates/gettext.config.js
arches/install/arches-templates/project_name/gettext.config.js
gettext.config.js

Follow-up to 01ffc0e5214940455c8418eeff8c1277ef0bde91
I guess we may hold this if we decide not to allow typescript functions to take `$gettext` callbacks, but I'm currently doing it, and figure would be nice to support:
https://github.com/archesproject/arches/blob/c677d557791c678cad03b51bc969964cc506f086/arches/app/src/components/ControlledListManager/api.ts#L38-L42

Include .ts files in gettext extraction

---

arches/install/requirements.txt
releases/7.5.2.md

Closes #10650
There is no 4.3 of Django. 4.2 is the LTS; 5.0 is the current supported version; 5.1 comes out in August. We can probably loosen the upper bound to <5.2.0 in August when 5.1 comes out (in Arches dev/8.0.x).

Relax upper bound on Django patch releases #10650

---

arches/app/utils/decorators.py
arches/app/views/workflow_history.py
tests/views/workflow_tests.py

Allows raising a 403 Forbidden for API-style requests, instead of a 302 redirect to nowhere.
More info about the use case in the linked issue.
Closes #10658

Add raise_exception arg to @group_required #10658

---

arches/app/models/fields/i18n.py
tests/localization/field_tests.py

Before, there was silent data loss when using `bulk_update()` on I18n_JSON fields such as node, datatype, widget, plugin configs.
Now, we at least allow bulk_updates to homogenous values. Heterogenous values (not yet supported) throw an error to prevent a silent failure.
The situation may improve in Django 5.1 if someone submits a PR with the patch identified in [this ticket](https://code.djangoproject.com/ticket/35167). Maybe that someone is one of us? :D
Closes #10618 
Opened a followup #10619 for the issue demo'd in the skipped test.
-   [x] Unit tests pass …

Fix bulk_update() on I18n_JSON fields for homogenous values #10618

---

arches/app/models/resource.py
arches/app/models/tile.py
arches/app/views/resource.py
arches/app/views/tile.py
releases/7.6.0.md

Update the active stream view not to returns "Update" (such as tile create) when the tiles are created with the resource creation.
#9768, #9769

Update activity stream, #9768, #9769

---

arches/settings.py

Add `ARCHES_APPLICATIONS` to core settings so that the test suite can be run on core arches after running `setup_db`. We weren't seeing this failure on CI because (AFAICT) it uses a postgres service that bootstraps a database called "arches". It's reasonable to expect an individual contributor to do this via `setup_db` instead.
Closes #10714

Add `ARCHES_APPLICATIONS` to core settings #10714

---

package.json
yarn.lock

Addresses peer dependency warning:
```sh
[3/4] 🔗  Linking dependencies...
warning " > vue3-gettext@3.0.0-beta.4" has unmet peer dependency "@vue/compiler-sfc@>=3.0.0".
```
Prevents consumers of arches applications (e.g. DISCO) from ending up with different versions of the package.
I don't have the console output to paste anymore, but the **before** version showed multiple conflicting copies of `@vue/compiler-sfc` (one from arches; another from arches-for-science).
Now, the **after** version is just:
```
root@d46eada8944b:/web_root/disco/disco# yarn list …
```

Selectively resolve @vue/compiler-sfc

---

arches/app/models/graph.py

#10750
-   [x] Unit tests pass with my changes

persist function_x_graph id, re #10750

---

arches/app/templates/javascript.htm
package.json
releases/7.5.2.md

Updated path to Slick image slider so it can be used in the application. The existing path was causing webpack build errors. Added a shim for Slick's jQuery dependency.
#10778
CSS files in core Arches need to be referenced by the project to be able to use the plugin.

10778 - Fixed Slick image slider path, added shim for jQuery

---

arches/app/datatypes/url.py
arches/app/media/css/tree.scss
arches/app/media/js/viewmodels/node-value-select.js
arches/app/media/js/views/components/widgets/text.js
arches/app/media/js/views/components/widgets/urldatatype.js
tests/utils/datatype_tests.py

The main bug linked shows that some datatypes do not persist card data that is entered but not saved, a feature that almost all datatypes have.  This bug is present for three datatypes: String, URL and Node Value.
This PR fixes all three (details on each fix below).
Main issue: #10027 
URL datatype issues: #10592, #8451
*   Found by: …

 Fix for cards losing their values when in "dirty" state & adding back highlight - 7.5.x 

---

arches/app/utils/index_database.py

Follow-up to f2861f22a34e7bb096bbc95bfcf9188d70611ccf.
Missed that `resources` might already have been evaluated before `optimize_resource_iteration()` returns a new queryset. Not a problem, just a missed opportunity for that first call to `len(resources)` to become `resources.count()` since it won't be used again later.

Use count() for indexing progress bar re #10453

---

arches/app/utils/activity_stream_jsonld.py
releases/7.6.0.md
tests/utils/activitystream.py

Configure ActivityStreams objects to return resource id's rather than resource url.
#10665

Use resource id rather than url in ActivityStreams #10665

---

arches/app/datatypes/base.py
releases/7.5.3.md
tests/utils/datatype_tests.py

Return blank tiles (holding only None values) from `get_tile_data()` rather than returning an implicit None. For example, return `{node_id: None}` rather than `None`.
Datatypes often drill into the result of `get_type_data()` expecting a dict, and do not check for `None`. (Perhaps they should, since there is still a code path that could return None after logging an exception. Or, we could elevate that logged exception to a runtime exception, but that's outside the scope here.)
Tiles might hold only None if a tile is added for a resource and then edited to remove …

Return blank tiles from get_tile_data() #10829

---

arches/app/media/js/viewmodels/provisional-tile.js
arches/app/media/js/viewmodels/tile.js

Fixes the display and updating of provisional edits in the default card
#10633, #10360

Fix display and update of provisional edits

---

.coveragerc

Without the `--source` option, coverage.py doesn't discover python files that aren't exercised in your tests. For instance, the entire etl_modules directory was untested, and so wasn't included in the coverage denominator. (Also, that directory needed an `__init__.py` to be discovered.)
[Docs](https://coverage.readthedocs.io/en/7.5.0/source.html)
See [example coverage artifact](https://github.com/archesproject/arches/actions/runs/8923012808) without etl_modules coverage listed.
```sh
coverage run manage.py test tests --settings=tests.test_settings && coverage …
```

Measure coverage on untested files re #10738

---

arches/app/utils/index_database.py
tests/models/resource_test.py

Follow-up to https://github.com/archesproject/arches/commit/f2861f22a34e7bb096bbc95bfcf9188d70611ccf.
@bferguso loosened the type annotation of `index_resources_using_singleprocessing` to take an iterable of resources, so in f2861f22a34e7bb096bbc95bfcf9188d70611ccf I made sure to handle that. But in doing so I hit the footgun described in #10877. I found a workaround that gave up on n+1 queries at the graph level, but the better fix is to just clean the fields to ensure graph ids are UUIDs.
For more information, see #10877.

Remove workaround in optimize_resource_iteration() that caused N+1 queries

---

arches/app/utils/data_management/resources/formats/archesfile.py

When a json file is used for the `import_business_data` command, the "sortorder" values are not being used and all tiles are resetting to all be "sortorder: 0".
1. Initial Manual Data Entry
*Note the order and the resource name at the top*
[Initial_Export.json which is used for all `import_business_data` commands](https://github.com/archesproject/arches/files/15204092/Initial_Export.json)
1. After using `export_business_data` followed by `import_business_data`
*Note the same areas as last step are now in an incorrect order (this is not a consistent order but is random each time)*
[Reimported_Export.json](https://github.com/archesproject/arches/files/15204094/Reimported_Export.json)
1. After adding the fix and running `import_business_data` on the same data file as the previous step
*This …

Fix "sortorder" values are not being preserved during a JSON import

---

arches/app/datatypes/base.py
releases/7.6.0.md
tests/utils/datatype_tests.py

Allows minzoom and maxzoom properties to be added to the map source of a resource so that geometry requests can be limited to a specific range. 
Currently zoom properties must be added using sql:
```
update nodes set config = config || '{"minzoom": 10}' where nodeid = 'some geojson node id';
```
The ability to modify these properties in the UI will be addressed here: #10931
#10929
-   [ ] I have added necessary documentation (if …

Allow min & maxzoom to be applied to a resource map source

---

arches/app/models/migrations/10709_refresh_geos_by_transaction.py

Removes references to postgres users so that Arches can be installed using postgres without the postgres user
#10944

Remove references to postgres user in migration

---

arches/app/etl_modules/import_single_csv.py
arches/settings.py

Moves hard-coded file size threshold out of the import single csv module python file and into the ETL module's config
#10381 
*   Sponsored by: @scholiumtech
*   Found by: @whatisgalen 
*   Designed by: @whatisgalen

10381 Move csv-import-module celery file size threshold into etl module config

---

tests/views/api_tests.py

Fixes test failure in #10948 due to graph names/slugs (I tried slugifying first...) no longer being strictly unique on v8 (unique only to themselves and their partners-in-history):
```py
ERROR: setUpClass (tests.views.api_tests.APITests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/work/arches/arches/tests/views/api_tests.py", line 69, in setUpClass
cls.data_type_graph = Graph.objects.get(name="Data Type Testing Model")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

Adjust APITests setup to work on both v7.6 and v8

---

arches/install/arches-templates/tsconfig.json
tsconfig.json

In fca355c we fixed the root cause for why we couldn't get type-checking in vue templates, so reenabling that functionality (that was temporarily turned off in 92123cd).
See example output with templates checked:
```ts
...
arches/app/src/components/ControlledListManager/TreeRow.vue:237:27 - error TS18048: '__VLS_ctx.node.key' is possibly 'undefined'.
237                     v-if="node.key in selectedKeys"
~~~~~~~~
arches/app/src/components/ControlledListManager/TreeRow.vue:246:27 - error TS18048: '__VLS_ctx.node.key' is possibly 'undefined'.
246                     v-if="node.key in selectedKeys"
~~~~~~~~
arches/app/src/components/ControlledListManager/TreeRow.vue:256:42 - error TS18048: '__VLS_ctx.node.key' is possibly 'undefined'.
256                 v-if="!node.data.name && node.key in …
```

Reenable type-checking in vue templates

---

arches/app/media/js/utils/create-vue-application.js
arches/app/media/js/views/plugin-standalone.js
arches/app/templates/base.htm
arches/app/templates/views/plugin-standalone.htm
package.json
releases/7.6.0.md
yarn.lock

10838 cbyrd upgrade primevue

---

arches/app/media/css/arches.scss
arches/app/templates/views/components/search/saved-searches.htm
arches/app/templates/views/components/search/search-export.htm
arches/app/templates/views/components/search/time-filter.htm

Fixes search panel height/scrolling/overflow issue when viewing on devices with smaller screen heights. I wasn't sure if this should be for 7.5 or 7.6, so for now I targeted 7.5.
Closes #11019 
*   Tested by: @phudson-he 

Fix for search panel height scrolling issues

---

arches/app/models/tile.py
releases/7.6.0.md

Fix the issue with a geojson geometry not being refreshed when the node value is updated, #11029
Make sure nodegroup_id is always a string (it is sometimes uuid) when comparing to serialized graph
Closes #
[Developer …

Fix after_update_all when node value is updated, #11029

---

arches/app/media/css/arches.scss
releases/7.5.3.md

Fixes an issue where buttons are mis-aligned when editing photo meta-data in a workflow
Closes #11051 
*   Tested by: @phudson-he 

Fix mis-aligned buttons in photo editing workflow step

---

tests/exporter/resource_export_tests.py

In this test we had indeterminate sorting of lists holding dictionaries. To sort a list of dictionaries consistently, we need to define a sort key. We had a sort key for the innermost array of tiles (tileid), but not the outer array of resources.
With this diff applied:
```diff
diff --git a/tests/exporter/resource_export_tests.py b/tests/exporter/resource_export_tests.py
index 764829e9f5..51799cab88 100644
--- a/tests/exporter/resource_export_tests.py
+++ b/tests/exporter/resource_export_tests.py
@@ -95,6 +95,7 @@ class BusinessDataExportTests(ArchesTestCase): …
```

Fix flaky test_json_export()

---

arches/app/search/components/sort_results.py

See recent GitHub actions logs with this warning emitted:
```py
/home/runner/work/arches/arches/arches/app/search/components/sort_results.py:25: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if sort_param is not None and sort_param is not "":
```
Could possibly be simplified even further to `if sort_param:`, but would rather keep this scoped smaller / easier to review.

Fix SyntaxWarning

---

arches/install/arches-templates/project_name/settings.py-tpl
arches/settings.py

Follow-up to 02b0ff5, which was under dev at the same time as a9d8e74, which replaced `timeout` with `request_timeout`.
See deprecation warning when `runserver`'ing with es 8.11.1:
```py
2024-03-18 15:21:38 /web_root/arches/arches/app/search/search.py:41: DeprecationWarning: The 'timeout' parameter is deprecated in favor of 'request_timeout'
```
[ES 8 migration guide](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/migration.html)

Replace deprecated es `timeout` param in settings.py

---

arches/app/media/js/views/components/search/advanced-search.js
releases/7.6.0.md

Ensures advanced search facets have widget labels when the search is restored #11046
Closes #11046

Ensure search facets have widget label on restore #11046

---

arches/app/etl_modules/jsonld_importer.py
arches/app/utils/file_validator.py
arches/apps.py
arches/install/arches-templates/project_name/settings.py-tpl
arches/install/requirements.txt
arches/settings.py
releases/7.6.0.md
tests/models/tile_model_tests.py
tests/test_settings.py
tests/utils/test_file_validator.py

There are several useful safety checks guarded behind the FILE_TYPE_CHECKING setting, not all of which have to do with the file type, strictly speaking.
The main reason this was off by default was the lack of a "lenient" option to allow through files whose extensions cannot be determined.
Add this lenient mode, default new projects to it, and deprecate the old true/false values.
Closes #10862 …

Add lenient file-type checking mode #10862

---

arches/app/media/js/viewmodels/widget.js
arches/app/media/js/views/components/widgets/text.js
releases/7.6.0.md

Persists unsaved value in widget if a user switches between cards in the card tree.
Closes #11092

Persist dirty state of string widget #11092

---

.github/workflows/main.yml
arches/install/arches-templates/.github/workflows/main.yml
arches/install/arches-templates/.prettierrc
arches/install/arches-templates/project_name/install/requirements_dev.txt
arches/install/arches-templates/tests/base_test.py-tpl

Noticed in arches-lingo:
- these constants in base_test.py are only used in core.
- without specifying tab width, prettier defaulted to two spaces. we missed this in core because we use an .editorconfig
- separate formatting steps

Fine-tune project template tooling

---

arches/app/templates/views/components/cards/default.htm

Fixes #11109 
Original hotfix and explanation found at https://github.com/archesproject/arches-her/pull/1203
-   X] Bugfix (non-breaking change which fixes an issue)
*   Tested by: @csmith-he 
Raising a pull request against dev/7.5.x to get hotfixes applied …

11109 Editor Tree Error Fix

---

arches/app/media/js/models/card-widget.js

The card-widget looks to see if widgets have been loaded into the workflow; if not, widgets are required so they load in the workflow
#11111 
*   Tested by: @csmith-he 
*   Designed by: @chrabyrd …

#11111 Adds workaround to load widgets into workflow if missing.

---

arches/app/datatypes/datatypes.py

Supports both line and polygon geometries and changes `split_geom` to return feature collections rather than geometries.
A file with a large polygon and line for testing: [biggeojson_w_line.json](https://github.com/user-attachments/files/16072755/biggeojson_w_line.json)

11080 handle lines

---

arches/app/media/css/arches.scss

The search listing footers were a fixed height, and these changes ensure that if any extra height is required, it will render correctly and not break the container.
Closes #11078 
*   Tested by: …

Remove fixed height from search listing footers

---

arches/app/search/search_export.py
releases/7.5.3.md

Puts an isinstance check on the geometry field value to make sure the following code is only run on values that whole valid geometry
#11139 
-   [X] I added a changelog in arches/releases
*   Sponsored by: HistoricEngland
*   Found by: @csmith-he 
*   Tested by: @csmith-he
Required for Arches for HERs

11139 Check value is geometry before proceeding with export to geojson

---

arches/app/utils/betterJSONSerializer.py
releases/7.6.0.md
tests/utils/test_betterJSONSerializer.py

Follow-up to 9334ae1.
**Before**
Attempting to edit an internationalized field like `Plugin.name` (string) or `DDataType.defaultconfig` (json) would throw errors in the Django admin ("Enter a valid JSON"). Also, it's possible that if a user worked around this by hand-escaping the JSON, there was a possibility of data loss since not all saved language values (for strings) were populated into the form.
**After**
Now, these issues are fixed. Some testing notes below.
Closes #10597
- …

Fix i18n text/json field serialization in Django admin #10597

---

arches/app/media/css/components/_buttons.scss

On the search page, if there are many items to select when using the QA Type or Resource Type dropdowns, users are unable to scroll to the bottom. This fix will ensure users can scroll down to view all of the content if needed.
Closes #11077 
*   Sponsored …

Scrolling fix for many items in search qa/resource filter dropdowns

---

arches/app/models/system_settings.py
releases/7.6.0.md
tests/models/system_settings_tests.py

Protects against silent failure shown in issue
Closes #11118
A 'real life' scenario for testing:
Edit the `if __name__ ...` block of settings.py in core arches to include this …

Reraise ImproperlyConfigured in SystemSettings #11118

---

arches/install/arches-templates/project_name/apps.py-tpl
arches/install/arches_admin.py
arches/install/arches_project.py
arches/management/commands/updateproject.py

Remove underscores from the templated class name for the AppConfig subclass in apps.py provided with 7.6.
Closes #11195
*   Found by: @chrabyrd 
Removed the `verbose_name` …

Remove underscores from AppConfig class name #11195

---

arches/install/arches-templates/project_name/webpack/webpack-utils/build-filepath-lookup.js
releases/7.5.4.md

Before 7.5.3, the webpack config special-cased a specific common dotfile created on mac systems (`.DS_Store`) that results from moving files using the Finder. Without that special case, node throws a TypeError (see issue). That special case was removed in bc0d79c.
Now, the special case is restored, but generalized to any dotfile, e.g. `.gitkeep` ([example](https://github.com/archesproject/arches-templating/pull/18#discussion_r1681727121)).
Closes #11094
-   [ ] I submitted a PR …

Ignore dotfiles in webpack file discovery #11094

---

.github/PULL_REQUEST_TEMPLATE.md

dev/8.0.x is now the target for new features, so update the PR template to reflect this.
(Technically 7.5 also has two more months of main support, but it may take almost that much time to merge this up to master anyway.)

Bump versions in PR template

---

.git-blame-ignore-revs
arches/app/datatypes/base.py
arches/app/datatypes/datatypes.py
arches/app/models/graph.py
arches/app/models/models.py
arches/app/models/utils.py
arches/app/src/arches/types.ts
releases/7.6.0.md

As described in https://github.com/archesproject/arches/pull/11209#issue-2417288140, there were a few useful changes mixed in with the controlled list work that we should preserve in core, ranging from trivial typo fixes to a new hook for datatype validation.
Adding this to 7.6 preserves the ability for the (separately maintained) Controlled List Manager & Reference Datatype to be compatible with 7.6 if it chooses. See #11201.

Pick out useful changes from controlled list work

---

arches/install/arches-templates/tests/base_test.py-tpl
tests/base_test.py

Allows running a subset of tests that don't use the database (or 0 tests in a new project).
Closes #11204
- Create a project
- Change the sample test to inherit from `django.test.SimpleTestCase`
- Run tests

Allow running tests without PG on unmigrated db #11204

---

tests/fixtures/testing_prj/testing_prj/settings.py

Follow-up to a1ecddc.
This setting already exists when imported from arches, so prefer extending to overwriting.
Was getting this check at the project level:
```sh
?: (guardian.W001) Guardian authentication backend is not hooked. You can add this in settings as eg: `AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', 'guardian.backends.ObjectPermissionBackend')`.
```

Sync app template treatment of ignored system checks setting

---

.git-blame-ignore-revs
arches/app/views/api.py
tests/views/api_tests.py

Before, the API resource report would crash on cards with null sortorders.
Closes #10949
-   [ ] I added a changelog in arches/releases (no --> unreleased bug)
*   Sponsored by: Getty Conservation Institut

Gracefully handle null card sortorders in resource report #10949

---

arches/management/commands/packages.py
releases/7.6.0.md

Follow-up to 4d2f4f5. Unreleased bugfix in 7.6. Projects no longer have a setup.install.

Deprecate `-o install` operation

---

arches/app/models/migrations/0001_initial.py
releases/8.0.0.md

Before, longer model names might fail (due to indeterminate inter-app ordering of migrations) if the initial migration for Arches ran before the migration from the Django admin app that lifts the length of the permission name field.
Closes #11317

Ensure longer model names can be used #11317

---

arches/app/views/plugin.py
arches/urls.py
releases/8.0.0.md
tests/views/plugin_tests.py

Before, plugin routes couldn't be more expressive than just /plugins/slug or /plugins/pluginid. Further, if an arches application tried to add more expressive routes to its plugins itself, the core arches PluginView would just drop the full route when redirecting post-auth.
Now, these issues are solved in a backward-compatible way. Needed for archesproject/arches-references#19
Closes #11320
-   [x] Unit tests pass locally …

Support more expressive plugin URLs #11320

---

arches/apps.py
tests/utils/test_checks.py

Improve the compatibility check from #11114 by softening it to a warning in debug mode. This allows people to continue to develop projects while their arches compatibility is in flux (perhaps with a URL reference to a branch).
Also clarify/standardize the message prefixes with application names, so that they appear like:
```
arches-references: (arches.W001) Cache backend does not support rate-limiting
```
instead of:
```
?: (arches.W001) Cache backend does not support rate-limiting
```

Soften compatibility check to warning in debug mode re #11114

---

.pre-commit-config.yaml
arches/install/arches-templates/.pre-commit-config.yaml
arches/install/arches-templates/pyproject.toml
arches/install/arches-templates/tests/search_indexes/__init__.py
pyproject.toml

Before, the ts pre-commit hook had trouble finding files for two reasons:
- [types_or](https://pre-commit.com/#config-types_or) was needed instead of types
- pre-commit provides a list of staged files to check, which [causes typescript to ignore your .tsconfig.json](https://github.com/microsoft/TypeScript/issues/27379) (!)
This second issue was worked around by using bash to bail out of the pre-commit context that provides a list of staged files only.
Now, also add the [check-hooks-apply](https://pre-commit.com/#meta-check_hooks_apply) meta hook to ensure the …

Fix typescript pre-commit hook file inclusion #11249

---

arches/app/datatypes/core/__init__.py
arches/app/datatypes/core/non_localized_string.py
arches/app/datatypes/core/util.py
arches/app/datatypes/datatypes.py
tests/utils/datatype_tests.py
tests/utils/non_localized_string_tests.py

There's an issue with the null/empty search performance for non-localized string nodes in very large datasets.  Performance is dramatically slower because of the base painless script.  This bypasses that problem only for this datatype. 
Also extracting nonlocalized string (similar to geojson feature collection datatype).

Update nonlocalized string search to correct the null search performance issue

---

arches/apps.py

Validate proper values for FILE_TYPE_CHECKING with an exception in Arches 8.0 as promised.

Promote DeprecationWarning to ValueError for FILE_TYPE_CHECKING booleans

---

arches/settings.py

Refs archesproject/arches-lingo#59
Follow-up to f8076a3.
This should be set True in production, but the development server doesn't run over HTTPS, so this is too aggressive for our default dev settings.
[Reference](https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-secure)

Omit `SESSION_COOKIE_SECURE` in development

---

arches/app/etl_modules/branch_excel_importer.py

Address deprecation warnings in test suite:
```py
/home/runner/work/arches/arches/arches/app/etl_modules/branch_excel_importer.py:227: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
[2259](https://github.com/archesproject/arches/actions/runs/10406926722/job/28821082656?pr=11101#step:6:2275)
graphid = workbook.get_sheet_by_name("metadata")["B1"].value
[2260](https://github.com/archesproject/arches/actions/runs/10406926722/job/28821082656?pr=11101#step:6:2276)
./home/runner/work/arches/arches/arches/app/etl_modules/branch_excel_importer.py:227: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
[2261](https://github.com/archesproject/arches/actions/runs/10406926722/job/28821082656?pr=11101#step:6:2277)
graphid = …
```

Replace deprecated workbook method

---

arches/app/templates/views/components/widgets/file.htm
releases/7.5.4.md

Allowed document formats text indicates all formats are acceptable if no specific format is defined - uses the allFormatsAccepted value in translatons
#11120 
-   [X] I added a changelog in arches/releases
*   Found by: @csmith-he 
*   Tested by: @csmith-he 
* …

#11120 - File Widget: Indicate clearly All formats are allowed if no specific format is defined

---

arches/app/search/components/advanced_search.py
arches/app/search/components/base_search_view.py
arches/app/search/components/map_filter.py
arches/app/search/components/resource_type_filter.py
arches/app/search/components/standard_search_view.py
arches/app/search/components/term_filter.py
arches/app/search/components/time_filter.py

… re #11390
Closes #11390
| Form …

pass search-filter querystring directly to filter's `append_dsl` method

---

arches/app/models/models.py

userid can be of NoneType, which will return a TypeError.  pass on this to invoke the DEFAULT_RESOURCE_IMPORT_USER setting.

also catch type error for userid being None

---

tests/permissions/permission_tests.py
tests/views/search_tests.py

Fix noisy output from recently merged test:
```py
.......Not Acceptable: /search/resources..........
```
While re-running tests, noticed a relatively slow test (unrelated) with a straightforward fix.

Fix noisy test

---

arches/install/arches-templates/tsconfig.json
tsconfig.json

Without this change, notice failure in archesproject/arches-lingo#86 in the ts linter:
```ts
arches_lingo/src/arches_lingo/utils.spec.ts:12:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
12 describe("Build scheme hierarchy", () => {
~~~~~~~~
arches_lingo/src/arches_lingo/utils.spec.ts:13:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
13     it("Should shape schemes into TreeNodes", () => {
~~
arches_lingo/src/arches_lingo/utils.spec.ts:21:9 - error TS2304: Cannot find name 'expect'.
21         expect(schemeNode.label).toEqual("Test …
```

Add vitest globals to tsconfig

---

arches/app/src/arches/types.ts

Helpful typescript interfaces for vue development will be fleshed out further in archesproject/arches-vue-utils rather than core.

Remove types.ts

---

arches/management/commands/updateproject.py
releases/7.6.0.md

Update release notes with .gitignore changes rather than overwrite .gitignore
Closes #11452

Remove overwrite of project's gitignore

---

arches/app/models/resource.py
tests/views/api_tests.py

Remove extra `get_relations` ORM queries

---

arches/app/permissions/arches_permission_base.py

There are some issues with indexing performance using default deny for large datasets.  These seem to be tied to the number of resources, but in all cases there is a 10x difference between default allow and default deny performance.  This change attempts to improve that discrepancy, which is largely a result of querying for object permissions for users and groups - a set of four groups of queries that must occur for each object.  Default Allow has a much faster implementation here.  This PR (instead of starting with the user and getting their permissions on a given object) gets all of the permissions that exist for a particular object and uses that (complete) set of permissions.

performance improvements for indexing with default deny

---

arches/app/etl_modules/base_import_module.py
tests/bulkdata/base_importer_tests.py
tests/bulkdata/jsonld_import_tests.py

Fixes this failure when uploading a file to the JSON-LD bulk importer:
```py
File "/Users/jwalls/prj/arches/arches/app/etl_modules/jsonld_importer.py", line 81, in read
self.prepare_temp_dir(request)
File "/Users/jwalls/prj/arches/arches/app/etl_modules/base_import_module.py", line 237, in prepare_temp_dir
self.temp_dir = os.path.join(settings.UPLOADED_FILES_DIR, "tmp", self.loadid)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 90, in join
File "<frozen genericpath>", line 164, in _check_arg_types
TypeError: join() …
```

Fix failure to launch JSON-LD bulk importer #11470

---

arches/app/etl_modules/jsonld_importer.py
arches/app/views/etl_manager.py
tests/bulkdata/jsonld_import_tests.py

When uploading a JSON-LD zip referencing a graph that does not exist, the error was no longer surfaced to the user. Now this is fixed.
Closes #11454
-   [n/a -- unreleased] I added a changelog in arches/releases
-   [n/a] I submitted a PR to arches-docs (if appropriate)

Surface nonexistent model error in JSON-LD importer #11454

---

arches/app/models/fields/i18n.py
arches/app/models/graph.py
releases/7.6.0.md
tests/views/graph_manager_tests.py

Forbid potentially malicious node and plugin config keys. No known SQL injection vulnerability exists, see test case which (after fiddling with the payload quite a bit) always fails on target branch with ProgrammingError, due to its being used in two places. …

Forbid malicious keys in node configs

---

arches/app/search/components/advanced_search.py
arches/app/search/components/resource_type_filter.py
arches/app/search/components/time_filter.py
tests/views/search_tests.py

[Avoid JSONDecodeError for querystring fallback](https://github.com/archesproject/arches/commit/79df33611e191456501af20b3022eb62d0a87403)
follow-up to 46f8d0f.
[Suppress logged error from test re #11443](https://github.com/archesproject/arches/commit/4d652874926eadb8f42a5b46366d510d6bcd9ce7)

Avoid JSONDecodeError in querystring fallbacks, fix noisy test re #11443

---

arches/app/media/js/models/card-widget.js
arches/app/media/js/views/components/widgets/rich-text.js
arches/app/media/js/views/components/widgets/text.js
arches/app/templates/views/components/widgets/rich-text.htm
arches/app/templates/views/components/widgets/text.htm
releases/7.6.0.md

When a fresh string node is created in the graph designer, the Discard Card Edits button was malfunctioning. Now, the situation is improved, although there are still some related bugs.
More specifically:
These issues are fixed for a new widget that has
*just* been created in the graph designer.
- after discarding edits to fields like widget name,
there is no dirty state (good).
- dirty state is correctly picked up for initial
edits to placeholder.
This issue remains:
- after dismissing card edits, the placeholder
field is not editable (dirty state not detected) …

Fix text widget dirty state calculation w/r/t localized placeholder #10873

---

arches/app/media/js/views/graph-designer.js
arches/app/models/card.py
releases/7.6.0.md

Replaced `get_or_create` because it was taking widget_id as an argument. This worked well for newly created records, but if a record already existed and the widget was being changed to a different widget, this would create a second cardsxnodesxwidget record for the node.
This change reintroduces #9858, however, that error was due in part to making two immediate calls to the CardView endpoint to update the card and permissions trees [here](https://github.com/archesproject/arches/blob/96051bb2d3fc1edd45b24071c53e2004a6313070/arches/app/media/js/views/graph-designer. …

Fix error preventing widget changes

---

arches/app/media/js/viewmodels/map.js

Prevent the marker popup from failing when clicking a search result while using the default deny permission framework. Hard-coded permission types are still in the map.js viewmodel. This could be avoided with an instance permission endpoint as described [here](https://github.com/archesproject/arches/issues/11502)
Closes #11501
-   [ ] I added tests that prove my fix is …

Prevent failed popup when clicking search result marker in default deny

---

arches/management/commands/updateproject.py

Copy sample_index.py to project during updateproject
Closes #11509

Copy sample_index.py to project during updateproject

---

arches/app/templates/javascript.htm
arches/app/templates/views/components/plugins/etl-manager.htm
arches/management/commands/permissions.py
tests/commands/test_permissions.py

Indicates to user that they have no permissions to any bulk modules if they do not find any etl modules on the Bulk Data Manager page. This is because permissions were not enforced in 7.5, however, that issue is fixed in 7.6, so users accustomed to seeing modules may now find that that they can't see any in 7.6. Additionally, this PR adds a management command to allow an admin to grant or revoke permissions to etl modules in bulk.
Closes #11450
-   [ ] I submitted a PR to …

Indicate if user has no etl module permissions

---

arches/install/arches-templates/project_name/settings.py-tpl
arches/install/arches-templates/tests/test_settings.py-tpl
arches/settings.py
arches/settings_docker.py
docker/settings_local.py
releases/8.0.0.md
tests/fixtures/testing_prj/testing_prj/settings.py

Speed up indexing with cursor_tuple_fraction pg option #11382

---

arches/app/permissions/arches_permission_base.py
releases/7.6.1.md

Prevent map layer manager error when getting default perms
Closes #11522 

Fix maplayer manager error

---

arches/app/views/api/__init__.py
releases/8.0.0.md

Before, the concepts api would respond to error conditions with an empty body. This might frustrate a vue frontend that expects to be able to parse the response body as json.
Closes #11519
*   Sponsored by: CA Dept of Parks and Rec
*   Found by: …

Return JSON response in GET calls to api/concepts #11519

---

arches/app/templates/base-manager.htm
arches/app/templates/index.htm
arches/install/arches-templates/project_name/templates/index.htm
releases/7.6.2.md

The language switcher component assumes there is a CSRF token set already, but we weren't setting it before login. This PR now sets the csrf token when we render the language switcher.
To reproduce the problem without this patch:
- delete cookies
- enable multiple languages, rebuild frontend
- load the arches homepage
- navigate to search (it's an unrelated bug that the switcher is not rendering on the index page, see console errors)
- switch the language
- result: csrf error
Closes #11528
-   [x] I added a changelog in …

Fix language switcher CSRF error when interacting before login #11528

---

arches/app/datatypes/datatypes.py
arches/app/models/graph.py
arches/app/models/models.py
arches/app/models/resource.py
arches/app/models/tile.py
arches/app/permissions/arches_permission_base.py
arches/app/search/components/search_results.py
arches/app/search/components/time_filter.py
arches/app/search/search_export.py
arches/app/utils/index_database.py
arches/app/views/api/__init__.py
arches/app/views/etl_manager.py
arches/app/views/graph.py
arches/app/views/resource.py
tests/utils/datatypes/datatype_tests.py

I had some of these changes lying around for months, so I batched them up and @chiatt offered to review before we undertake further performance improvements.
Descriptions in commit messages. Probably easier to review commit by commit.

Reduce queries
