archesproject/arches

arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/db/dml/db_data.sql
These are the latest changes to the Data Model as discussed between @apeters and @adamlodge on or around March 11th
=> Model Upgrade

arches/app/models/resource_graphs.py, arches/app/views/graph.py, arches/urls.py
=> getting graph from top level node id

arches/app/media/css/arches-nifty.css, arches/app/media/js/graph-manager.js, arches/app/media/js/views/graph-manager/graph.js
=> 352 graph view

arches/app/media/css/arches-nifty.css, arches/app/media/js/graph-manager.js, arches/app/media/js/views/graph-manager/graph.js
=> fixes to the management of selected/edited node state

arches/management/commands/packages.py
python manage.py packages -o import_json -s 'path to json file'
=> Add management command for importing arches.json.

arches/app/media/css/arches-nifty.css, arches/app/media/js/graph-manager.js, arches/app/media/js/models/node.js, arches/app/media/js/views/graph-manager/node-form.js, arches/app/templates/graph-manager.htm, arches/app/templates/views/graph-manager/node-form.htm
merging work in before completion to make NodeModel js class available for other work
=> 353 node form

appspec.yml, arches/install/update_docs.sh
integrating docbox deploy into dev CI
=> Docbox setup

arches/app/media/js/views/map.js
Pull @mradamcox's changes for firefox into Arches Stable V3
=> change to firefox compatible event properties

arches/app/media/js/graph-settings.js, arches/app/models/graph.py
some small fixes for graph metadata work
=> 421 graph metadata form

arches/app/templates/base-nifty.htm, arches/app/templates/views/graph-list-item.htm
=> Graph manager fixes

arches/app/media/js/views/graph-manager/node-form.js
=> adding jsdoc comments

arches/app/media/js/graph-settings.js, arches/app/media/js/models/graph.js, arches/app/templates/graph-settings.htm, arches/app/views/graph.py
=> adding graph root class dropdown

arches/app/media/js/models/graph.js, arches/app/media/js/views/graph-manager/node-form.js
selecting parent node instead
re: #476
=> not hiding node form after delete

arches/app/views/graph.py
=> excluding current graph from branch list

arches/app/views/graph.py
=> Node form fixes

arches/app/models/migrations/0001_initial.py
=> use generated UUID as stored CRM UUID

arches/app/models/graph.py, arches/app/views/graph.py, arches/settings.py
setting default graph ontology and root node ontologyclass to None
setting ontologyclass on root node to none when graph ontology is set to None
re: #485
=> ensure ontology and ontologyclass are in sync

arches/app/media/js/views/graph-manager/branch-list.js, arches/app/views/graph.py
=> allow append graphs with ontology to those without

arches/app/media/css/arches-nifty.css, arches/app/media/js/viewmodels/alert.js, arches/app/media/js/views/page-view.js, arches/app/templates/base-nifty.htm, arches/app/templates/graph-base.htm, arches/app/templates/javascript.htm
=> adding global alert, using for confirm nav

arches/app/media/css/arches-nifty.css, arches/app/media/js/graph-manager.js, arches/app/media/js/views/graph-manager/graph-base.js
=> Graph styling enhancements

arches/app/media/js/graph-settings.js, arches/app/media/js/views/graph-manager/node-form.js, arches/app/templates/graph-settings.htm, arches/app/templates/views/graph-manager/node-form.htm
=> enforce root node of "Resource" must be semantic

arches/app/media/js/graph-settings.js, arches/app/media/js/views/graph-manager/node-form.js, arches/app/models/graph.py, arches/app/templates/views/graph-manager/node-form.htm, tests/models/graph_tests.py
=> ensure root node of resource is not be a collector

.github/ISSUE_TEMPLATE.md
To streamline issue creation while we are doing heavy development on V4, User Stories has been moved to the top and cleaned up
=> Update Issue Template for Heavy V4 Development

arches/app/media/js/views/graph-manager/node-form.js, arches/app/templates/views/graph-manager/node-form.htm
=> fixing bug in resource top node query

arches/app/media/css/arches-nifty.css, arches/app/media/js/models/graph.js, arches/app/media/js/views/graph-manager/node-form.js, arches/app/templates/views/graph-manager/node-form.htm
=> enforcing node grouping rules in node form

arches/app/models/graph.py, arches/app/models/models.py, arches/app/views/graph.py
=> fixing collector management bug

arches/app/media/js/views/graph-manager/branch-list.js, arches/app/media/js/views/graph-manager/node-form.js, arches/app/templates/views/graph-manager/branch-info.htm
=> disable append when node form is dirty

arches/app/media/js/graph-manager.js, arches/app/media/js/views/graph-manager/graph-base.js, arches/app/media/js/views/graph-manager/node-list.js, arches/app/templates/javascript.htm
=> panning graph to node on select in node list

arches/app/media/js/views/graph-manager/graph-base.js
=> ensuring zoom to node works across scales

arches/app/media/css/arches-nifty.css, arches/app/media/js/graph-manager.js, arches/app/media/js/views/graph-manager/graph-base.js, arches/app/templates/graph-base.htm, arches/app/templates/graph-list.htm, arches/app/views/graph.py
=> Graph UI enhancements

arches/app/templates/views/graph-manager/node-form.htm
re: #552
This is sort of hard to test with a resource given how parent groups currently
cascade - I'd recommend testing w/ a new graph probably.
Also, we need to open a ticket for fixing the way the root card's group cascades
down to child nodes nodegroups as a parent group.
=> updating labels for collector switch

arches/app/media/js/models/graph.js, arches/app/media/js/views/graph-manager/node-form.js
=> preventing overly nested node groups

tests/fixtures/resource_graphs/archesv4_resource.json
=> specifying ontology for heritage resource

arches/app/models/graph.py, tests/models/graph_tests.py
=> Group node management

arches/app/templates/graph-settings.htm
=> using search_contains for root class dropdown

arches/app/media/js/graph-settings.js, arches/app/templates/graph-settings.htm
=> removing resource/graph radio buttons

arches/app/media/js/bindings/scrollTo.js, arches/app/media/js/views/page-view.js, arches/app/templates/graph-list.htm
=> scrolling to alert on graph delete

arches/app/media/js/models/graph.js, arches/app/media/js/views/graph-manager/node-form.js, arches/app/templates/views/graph-manager/node-form.htm
=> Make card switch

arches/app/media/js/views/graph/graph-manager/node-form.js
=> fixing logic to enable root node make card switch

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/graph-base.htm
=> fixing broken alert panel on graph manager

arches/app/templates/views/graph/graph-manager/branch-info.htm
=> fixing bug in branch-info.htm

arches/app/models/graph.py, arches/app/models/models.py, tests/models/graph_tests.py
=> fixing bug in delete_node logic

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/graph/graph-list.js, arches/app/templates/base-nifty.htm, arches/app/templates/views/graph/graph-list.htm, arches/app/templates/views/graph/graph-manager/node-form.htm
=> graph list redesign

arches/app/media/js/bindings/dragDrop.js, arches/app/media/js/views/graph/card-manager.js, arches/app/templates/views/graph/card-manager.htm
=> drag and drop to add cards

arches/app/templates/views/graph/card-manager.htm
=> label updates

arches/app/media/js/views/graph/card-manager.js, arches/app/media/js/views/graph/graph-manager/node-list.js, arches/app/media/js/views/list.js, arches/app/templates/views/graph/card-manager.htm, arches/app/templates/views/graph/graph-manager/card-list.htm
=> using list view for card list

arches/app/media/js/views/graph/card-manager.js
=> fixing bug with card list hide button

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/graph/card-manager.js
=> showing alert message on request fail

arches/app/media/js/views/graph/card-manager.js, arches/app/templates/views/graph/card-manager.htm, arches/app/templates/views/graph/card-manager/card-list.htm
=> adding jump to dd and open card method

arches/app/media/js/bindings/chosen.js
=> using contains search by default in chosen widgets

arches/app/media/js/views/graph/card-configuration.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/views/graph/card-configuration/card-components-tree.js, arches/app/media/js/views/graph/card-configuration/card-form-preview.js, arches/app/templates/views/graph/card-configuration.htm
=> stubbing out card configuration views

arches/app/templates/views/graph/graph-base.htm
=> fixing manage panel bug

arches/app/templates/views/graph/graph-settings.htm
=> fixing issue with active radio buttons

arches/app/models/graph.py, arches/app/views/graph.py, tests/views/graph_manager_tests.py
Code cleanup and changes to graph import validation.
Documented code and made changes to validation methods.
=> Code cleanup and import validation changes

arches/app/templates/views/graph/card-configuration.htm, arches/app/views/graph.py
re: #620
we should probably move the logic that gathers this data out of
the view and into a new `Card` proxy model, as with the `Graph`
model.  For now, I'm adding it here to push forward w/ development
of this read-only component
=> passing data required for card tree to client

arches/app/media/js/models/card.js, arches/app/media/js/views/graph/card-configuration.js, arches/app/views/graph.py
=> adding basic client card model

arches/app/media/js/views/graph/card-configuration.js, arches/app/models/card.py
=> add Card proxy model, re #642

arches/app/media/js/models/card.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/views/graph/card-configuration/card-form-preview.js, arches/app/models/card.py, arches/app/templates/views/graph/card-configuration/card-component-form.htm, arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> 621 card container editor

arches/app/media/js/models/card-widget.js, arches/app/media/js/models/card.js, arches/app/models/card.py, arches/app/templates/views/graph/card-configuration.htm, arches/app/templates/views/graph/card-configuration/card-components-tree.htm, arches/app/views/graph.py
=> initial modeling of card widgets for client

arches/app/media/js/models/card-widget.js, arches/app/media/js/models/card.js, arches/app/templates/javascript.htm, arches/app/templates/views/graph/card-configuration/card-components-tree.htm
re: #620
previously was showing nodes, now showing `cards_x_nodes_x_widgets`
as `CardWidgetModel` instances.
=> 620 card components tree

arches/app/templates/views/graph/card-configuration/card-component-forms.htm
=> showing widget form by duck typing CardWidgetModel

arches/app/templates/views/graph/card-configuration/card-components-tree.htm
=> better template syntax and naming for card tree

arches/app/media/js/models/card-widget.js, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/templates/javascript.htm, arches/app/templates/views/graph/card-configuration/card-components-tree.htm, arches/db/ddl/arches4ddl.SQL, arches/db/dml/db_data.sql, tests/fixtures/resource_graphs/archesv4_resource.json
=> more card tree template refactoring

arches/app/media/js/models/card-widget.js, arches/app/media/js/views/graph/card-configuration.js, arches/app/media/js/views/graph/card-configuration/card-form-preview.js, arches/app/media/js/widgets/datepicker.js, arches/app/media/js/widgets/select.js, arches/app/media/js/widgets/switch.js, arches/app/media/js/widgets/text.js, arches/app/models/models.py, arches/app/templates/javascript.htm, arches/app/templates/views/graph/card-configuration/card-form-preview.htm, arches/db/dml/db_data.sql
=> 627 card preview

arches/app/media/js/views/graph/card-configuration/card-form-preview.js, arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> keeping selected card tab in preview synced

arches/app/templates/views/graph/card-configuration.htm, arches/app/templates/views/graph/card-configuration/card-components-tree.htm
=> style fix for card tree

arches/app/media/js/models/card-widget.js, arches/app/templates/views/graph/card-configuration/card-components-tree.htm
=> using datatype icons for nodes in tree

arches/app/media/js/models/card.js
=> fixing widget sort order

arches/app/media/js/models/card.js, arches/app/media/js/views/graph/graph-settings.js, arches/app/models/card.py, arches/app/models/graph.py, arches/app/templates/views/graph/card-configuration/card-form-preview.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/graph/graph-base.htm, arches/app/templates/views/graph/graph-list-item.htm, arches/app/templates/views/graph/graph-settings.htm, arches/app/views/graph.py, tests/models/graph_tests.py
=> 623 card editor

arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> enabling selection of widgets via preview

arches/app/models/card.py, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/db/dml/db_data.sql, tests/models/tile_model_tests.py
=> move cardinality property from card model to node group model, re #674

arches/app/media/css/arches-nifty.css
=> more card preview styling

arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> fixing item preview for non container root card

arches/app/media/js/models/card-widget.js, arches/app/media/js/models/card.js, arches/app/media/js/views/graph/card-configuration/card-components-tree.js, arches/app/media/js/views/graph/card-configuration/card-form-preview.js
=> documenting card form preview js files

arches/app/media/css/arches-nifty.css, arches/app/media/js/bindings/summernote.js, arches/app/media/js/views/graph/card-configuration.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/views/graph/card-configuration/card-form-preview.js, arches/app/templates/javascript.htm, arches/app/templates/views/graph/card-configuration/card-form-preview.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm
=> 625 card help

arches/app/templates/javascript.htm
=> fixing tooltips

arches/app/media/js/bindings/summernote.js
=> minor enhancement to summernote ko binding

arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm
=> improve the way the help form visibility is managed, re #625

arches/app/media/js/models/card-widget.js, arches/app/media/js/models/card.js, arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/models/card.py, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py
=> support for saving cards_x_nodes_x_widgets records

arches/app/media/js/models/card-widget.js, arches/app/media/js/viewmodels/widget.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/widgets/datepicker.js, arches/app/media/js/widgets/select.js, arches/app/media/js/widgets/switch.js, arches/app/media/js/widgets/text.js, arches/app/templates/views/forms/widgets/datepicker.htm, arches/app/templates/views/forms/widgets/select.htm, arches/app/templates/views/forms/widgets/switch.htm, arches/app/templates/views/forms/widgets/text.htm, arches/app/templates/views/graph/card-configuration/card-form-preview.htm, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm
=> adding widget level config forms

arches/app/media/js/viewmodels/widget.js, arches/app/media/js/widgets/text.js
=> a little cleanup and docs

arches/app/media/js/viewmodels/widget.js, arches/app/media/js/widgets/text.js, arches/app/templates/views/forms/widgets/text.htm, arches/db/dml/db_data.sql
@ryan86 @jmunowitch see this PR as an example for widget dev
=> adding an example of another widget config value (width)

arches/app/media/js/viewmodels/widget.js, arches/app/media/js/widgets/text.js, arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> enhancing widget viewmodel and preview

arches/app/media/js/models/card-widget.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/models/models.py, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm
=> adding ability to switch widgets

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/card-configuration/card-components-tree.htm, arches/app/templates/views/graph/card-configuration/card-form-preview.htm, arches/app/templates/views/graph/card-configuration/component-forms/permissions-form.htm, arches/app/templates/views/graph/graph-list.htm
=> Card Designer UI and label fixes

arches/app/media/js/views/graph/card-configuration/card-component-form.js
=> minor fix for widget select input

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> Add Titles for card and card container tiles

arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/widgets/rich-text.js, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm
=> 626 widget config form

arches/app/media/js/models/card.js, arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/models/card.py, arches/app/templates/views/graph/card-configuration-manager.htm, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm, arches/app/views/graph.py
=> support for managing validations in widget form

arches/app/templates/views/graph/graph-base.htm, arches/app/views/graph.py
=> bug fixes for card designer

arches/app/models/models.py, arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm, arches/app/templates/views/graph/graph-base.htm, arches/app/templates/views/graph/graph-settings.htm, arches/app/views/graph.py, tests/views/graph_manager_tests.py
=> removing card container form 'advanced' tab

arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/permissions-form.htm
=> 624 manage permissions

.travis.yml, arches/install/requirements_dev.txt, tests/test_settings.py, tests/ui/login_tests.py, tests/ui/page_tests.py, tests/ui/pages/base_page.py, tests/ui/pages/graph_page.py, tests/ui/pages/login_page.py
To run the ui tests users will have to do the following:
- pip install -U selenium
- add browsers you wish to test to test_settings.LOCAL_BROWSERS ('Firefox' should work out of the box)
To use Chrome follow the instructions here https://sites.google.com/a/chromium.org/chromedriver/ and then
- copy the chromedriver executable to /usr/bin and it should just work (make sure to add "Chrome" to test_settings.LOCAL_BROWSERS)
=> Selenium and sauce lab tests

arches/app/media/js/views/graph/graph-manager.js
=> fixing graph manager alert behavior

arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/views/graph/graph-manager/node-form.js
=> filtering list of validations

arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm, arches/app/templates/views/graph/graph-manager/node-form.htm, arches/app/templates/views/graph/graph-settings.htm
=> Card graph bugs

arches/app/media/js/models/node.js, arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/views/graph/graph-manager.js, arches/app/media/js/views/graph/graph-manager/node-form.js, arches/app/models/card.py, arches/app/models/graph.py, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/models/tile.py, arches/app/templates/views/graph/card-configuration-manager.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm, arches/app/templates/views/graph/graph-manager.htm, arches/app/templates/views/graph/graph-manager/node-form.htm, arches/app/views/graph.py, arches/db/dml/db_data.sql, tests/ui/pages/graph_page.py
=> 672 functions

arches/app/models/migrations/0001_initial.py, arches/app/models/models.py
=> add db fields to support form management, re #759

arches/app/media/js/views/graph/form-manager.js, arches/app/templates/views/graph/form-manager.htm, arches/app/views/graph.py
=> cleanup form manager list and dropdown

arches/install/requirements.txt
Solves https://github.com/archesproject/arches/issues/728
=> Pinning pip to known working versions of libraries for V3

arches/app/models/concept.py, arches/app/utils/data_management/resources/formats/archesfile.py, arches/app/utils/data_management/resources/formats/shpfile.py, arches/management/commands/package_utils/authority_files.py, arches/management/commands/packages.py, tests/importer/concept_import_tests.py
Add functionality to load v3 authority files.
#309
=> Authority file load

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/graph/form-configuration.js, arches/app/media/js/views/graph/form-manager.js, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/templates/views/graph/form-configuration.htm, arches/app/templates/views/graph/form-manager.htm, arches/app/templates/views/graph/form-manager/card-list.htm, arches/app/views/graph.py
=> add cards to forms

arches/app/media/js/models/form.js, arches/app/media/js/views/graph/form-configuration.js, arches/app/media/js/views/graph/form-settings.js, arches/app/templates/views/graph/form-configuration.htm, arches/app/templates/views/graph/form-settings.htm
cleanup of form model and settings view
=> 753 add cards

arches/app/templates/views/graph/graph-list-item.htm
=> 776 ui updates and fixes

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/form-settings.htm
=> Form editor

arches/app/media/js/models/card.js, arches/app/media/js/models/graph.js, arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/templates/views/graph/card-configuration-manager.htm
=> Discard edit bugs

arches/app/models/migrations/0001_initial.py
Adds check to node table to make sure datatype in nodes table is a valid datatype from d_data_types
Fixes #747
=> Add check for d_data_type value in nodes table.

arches/app/media/js/views/graph/form-manager.js, arches/app/templates/views/graph/form-manager.htm, arches/app/views/graph.py, arches/urls.py
=> adding support for form delete feature

arches/app/media/js/widgets/number.js, arches/app/templates/views/forms/widgets/number.htm, arches/db/dml/db_data.sql
Create first version of number widget.
#722
=> First cut at number widget.

arches/app/templates/views/resource.htm
=> 765 resource manager

arches/app/media/js/widgets/switch.js, arches/app/templates/views/forms/widgets/switch.htm
Added subtitle to configuration form, re #725
=> Added subtitle to configuration form, re #725

arches/app/media/css/arches-nifty.css, arches/app/media/js/models/card-widget.js, arches/app/media/js/models/card.js, arches/app/media/js/models/report.js, arches/app/media/js/viewmodels/report.js, arches/app/media/js/viewmodels/widget.js, arches/app/media/js/views/graph/report-editor.js, arches/app/templates/views/forms/widgets/datepicker.htm, arches/app/templates/views/forms/widgets/number.htm, arches/app/templates/views/forms/widgets/radio-boolean.htm, arches/app/templates/views/forms/widgets/rich-text.htm, arches/app/templates/views/forms/widgets/select.htm, arches/app/templates/views/forms/widgets/switch.htm, arches/app/templates/views/forms/widgets/text.htm, arches/app/templates/views/graph/report-editor/report-editor-form.htm, arches/app/templates/views/report-templates/default.htm, arches/app/templates/views/report-templates/image.htm, arches/app/templates/views/report-templates/map.htm, arches/app/templates/views/report-templates/partials/card-report.htm
=> functional report preview in editor

arches/app/templates/views/graph/report-editor/report-editor-form.htm, arches/app/templates/views/graph/report-manager.htm, arches/app/views/graph.py
=> adding active switch for reports

arches/app/templates/views/forms/widgets/number.htm, arches/app/templates/views/forms/widgets/text.htm
Minor changes to the string and number widgets, #721, #722
=> enabled string and number widget inputs, re #721, #722

arches/app/media/js/resource-report.js, arches/app/views/resource.py
=> fix for reports

arches/app/media/js/bindings/ajax-chosen.js, arches/app/media/js/widgets/geometry.js, arches/app/media/plugins/chosen.ajaxaddition.jquery.js, arches/app/templates/views/forms/widgets/geometry.htm, arches/db/dml/db_data.sql, arches/settings.py
Changed geocoder widget to chosen-ajax and removed references to geometry widget in ajax-chosen binding, re #723
=> 723 geom widget

arches/app/media/css/arches-nifty.css, arches/app/templates/views/report-templates/default.htm
=> basic print style for resource report

arches/app/templates/views/graph.htm
=> setting up manage links in graph list page

arches/app/media/js/widgets/geometry.js, arches/app/templates/views/forms/widgets/geometry.htm
=> enabling layer reorder buttons in geom widget

arches/app/media/js/bindings/nouislider.js
preventing values from updating twice during slide
=> improving nouislider binding handler

arches/app/media/js/bindings/chosen.js, arches/app/media/js/models/report.js, arches/app/media/js/views/graph/form-configuration.js, arches/app/templates/views/graph/form-configuration.htm
=> Resource designer bugs

arches/app/media/js/views/graph.js, arches/app/templates/base-manager.htm, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/graph-base.htm, arches/app/templates/views/graph/graph-settings.htm, arches/app/templates/views/resource.htm, arches/app/templates/views/resource/resource-base.htm, arches/app/views/graph.py, tests/test_settings.py, tests/ui/pages/graph_page.py
=> label cleanup

arches/app/templates/views/resource/editor/form.htm
=> passing node into widgets in forms

arches/app/views/resource.py
Added map layers and sources to resource ResourceEditorView so that layers show up correctly in form. re #723
=> added map layers and sources to resource ResourceEditorView

arches/app/models/graph.py
Fixes error message when importing an arches json graph with cards. re #809
=> Fixes error message when importing an arches json graph with cards.

arches/app/media/css/arches-nifty.css, arches/app/templates/base-manager.htm, arches/app/templates/views/resource/editor.htm, arches/app/templates/views/resource/editor/form-list.htm, arches/app/templates/views/resource/editor/form.htm
=> UI enhancements (default header, small resource editor tweaks)

arches/app/media/js/models/card.js, arches/app/media/js/models/graph.js, arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/media/js/views/graph/card-manager.js, arches/app/templates/javascript.htm, arches/app/templates/views/graph/card-configuration-manager.htm, arches/app/templates/views/graph/card-manager.htm, bower.json
=> wiring up card list in card manager

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/datepicker.htm
Initial date widget with a very basic config.
=> 720 default widget date initial version

arches/app/media/css/arches-nifty.css, arches/app/templates/base-manager.htm, arches/app/templates/views/report-templates/default.htm, arches/app/templates/views/resource/resource-base.htm
=> UI enhancements

arches/app/templates/views/graph/graph-base.htm
caused issues w/ escaping string data
re: #956
=> ensuring json data is not wrapped in string

arches/app/media/js/widgets/geometry.js, arches/app/templates/javascript.htm, bower.json
=> zooming to feature collection extent in map widget

arches/app/templates/views/graph/graph-settings.htm
=> fix graph settings tab label

arches/app/media/js/views/resource/editor/form.js
Fixes issue where the selected value of a concept widget was not displayed if the selected concept came from a nested list of concepts.
Fixes #939
=> 939 concept widget bug

arches/db/dml/db_data.sql, arches/install/install_arches.sh
Remove import_json command from dev machine install so Heritage Resource graph will no longer be installed by default on the dev machine. Also create metadata for default node and node type branches.
=> Remove import_json command from dev machine install.

tests/fixtures/resource_graphs/archesv4_resource.json
Fixed duplicate legacyoid issue if you tried to import concepts from arches json and other authority files.
=> Resolve duplicate legacyoid issue

arches/app/media/js/views/graph.js, arches/app/templates/base-manager.htm
=> linking to branches/resource models in nav

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/datepicker.htm, arches/app/templates/views/forms/widgets/geometry.htm, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/card-manager/card-list.htm, arches/app/templates/views/graph/form-configuration.htm, arches/app/templates/views/resource.htm
=> Small UI enhancements

arches/app/media/css/arches-nifty.css
=> ongoing UI enhancements

arches/db/dml/db_data.sql
removed geometry widget and datatype from db, re #723
=> removed geometry widget and datatype from db, re #723

arches/app/media/js/views/graph/report-manager.js, arches/app/templates/views/graph/report-manager.htm, tests/fixtures/resource_graphs/archesv4_resource.json
=> displaying template name in report manager

arches/app/media/js/models/report.js, arches/app/media/js/views/graph/report-manager.js, arches/app/templates/views/graph/report-manager.htm, arches/app/views/graph.py
=> showing template and list of forms in report manager

arches/app/media/js/viewmodels/concept-widget.js, arches/app/media/js/widgets/concept-radio.js, arches/app/media/js/widgets/concept-select.js, arches/app/templates/views/forms/widgets/concept-radio.htm, arches/app/templates/views/forms/widgets/concept-select.htm, arches/app/templates/views/graph/report-manager.htm, arches/db/dml/db_data.sql
=> concept radio widget

arches/app/media/js/viewmodels/concept-widget.js, arches/app/media/js/widgets/concept-list-select.js, arches/app/media/plugins/knockout-select2.js, arches/app/templates/views/forms/widgets/concept-radio.htm, arches/app/templates/views/forms/widgets/concept-select.htm, arches/db/dml/db_data.sql
=> adding concept multiselect widget

arches/app/media/js/viewmodels/concept-widget.js, arches/app/media/js/widgets/concept-checkbox.js, arches/app/templates/views/forms/widgets/concept-checkbox.htm, arches/app/templates/views/forms/widgets/concept-radio.htm, arches/db/dml/db_data.sql
=> concept checkbox widget

arches/app/media/plugins/knockout-select2.js, arches/app/templates/views/forms/widgets/concept-checkbox.htm
=> a little cleanup

arches/app/models/graph.py
=> preserving cardinality on copy/append graph

arches/app/models/graph.py, arches/app/templates/javascript.htm, bower.json
=> preserving card labels on branch append

arches/app/media/js/models/graph.js
=> only select the root node if the root node is available, re #1118

arches/app/media/js/rdm.js, arches/app/templates/rdm.htm, arches/app/views/concept.py, arches/urls.py
=> get RDM page working again, re #946

arches/app/utils/data_management/arches_file_exporter.py, arches/app/views/graph.py
Adds a metadata object to arches.json graph export that includes information about the operating system and arches version. Also removes 'export' from graph export file name.
re #1096
=> Add metadata to export data. 

arches/app/media/js/views/resource/editor/form.js, arches/app/media/js/widgets/file.js, arches/app/templates/views/forms/widgets/file.htm, arches/app/views/tile.py
=> enhancements for file widget 

arches/app/media/css/arches-nifty.css, arches/app/media/js/reports/image.js, arches/app/media/js/viewmodels/report.js, arches/app/media/js/widgets/file.js, arches/app/templates/views/report-templates/image.htm, arches/db/dml/db_data.sql
=> image report template

tests/ui/page_tests.py, tests/ui/pages/map_widget_page.py, tests/ui/pages/page_locators.py
Added more checks to the map widget test, re #1074
=> added more checks to the map widget test, re #1074

arches/app/media/js/bindings/dropzone.js, arches/app/media/js/widgets/file.js, arches/app/templates/views/forms/widgets/file.htm
=> fix for multiple dropzone widgets on single page

arches/app/media/js/views/functions/primary-name.js, arches/app/templates/views/functions/primary-name.htm
=> update primary name card selection logic, re #997

arches/app/media/js/views/resource/editor.js
=> fix bug where the active form may not be the first form in the list of forms

arches/app/media/js/bindings/datepicker.js, arches/app/templates/views/forms/widgets/datepicker.htm
=> fixes for datepicker widget

arches/app/media/css/arches-nifty.css, arches/app/templates/base-manager.htm
=> Report Template UI enhancements

arches/app/media/js/models/card.js
=> fixing bug with node order in cards

arches/install/install_arches.sh, arches/management/commands/packages.py, arches/settings.py
enhancing import command to support importing multiple json files, and support using paths to folders containing json files in `RESOURCE_GRAPH_LOCATIONS` setting.  This allows users to import the default branches & resource models by running:
`python manage.py packages -o import_json`
=> Import json enhancement

arches/app/views/resource.py
=> only showing forms that are active and visible

arches/app/media/css/arches-nifty.css, arches/app/media/js/viewmodels/geocoder.js, arches/app/media/js/widgets/map.js, arches/app/media/js/widgets/map/map-styles.js, arches/app/templates/views/forms/widgets/map.htm, arches/db/dml/db_data.sql, tests/fixtures/sample_branches/places_export.json
Added config to toggle map controls off in a report, re #1209
=> 1209 report configs

arches/app/media/js/models/form.js, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/templates/views/graph/form-manager.htm, arches/app/templates/views/graph/form-settings.htm, arches/app/views/graph.py, arches/app/views/resource.py, arches/db/graphs/resource_models/architectural_resource.json
=> removing form status field

arches/app/media/js/views/resource/editor.js, arches/app/templates/javascript.htm, arches/app/templates/views/resource/resource-base.htm, arches/app/views/resource.py
=> wire up delete of resource instance, re #896, also addresses re #1190

arches/app/media/css/arches-nifty.css, arches/app/media/js/viewmodels/geocoder.js, arches/app/templates/views/forms/widgets/map.htm, arches/app/utils/geocoders.py
=> updated geocoder

arches/app/media/css/arches-nifty.css, arches/app/media/js/viewmodels/geocoder.js, arches/app/templates/views/forms/widgets/map.htm
=> geocoder enhancements

tests/importer/concept_import_tests.py, tests/test_settings.py, tests/ui/pages/base_page.py, tests/ui/pages/card_page.py, tests/ui/pages/form_page.py, tests/ui/pages/graph_page.py, tests/ui/pages/login_page.py, tests/ui/pages/map_widget_page.py, tests/ui/pages/node_page.py, tests/ui/pages/page_locators.py, tests/ui/pages/report_editor_page.py, tests/ui/pages/report_manager_page.py, tests/ui/pages/resource_editor_page.py, tests/ui/pages/resource_manager_page.py
=> 1240 ui tests

arches/app/media/js/widgets/text.js, arches/app/templates/views/forms/widgets/text.htm, arches/db/dml/db_data.sql, arches/db/graphs/resource_models/architectural_resource.json
Added max length config to default text widget re #1216
=> 1216 text configs

arches/app/models/graph.py, arches/app/utils/data_management/arches_file_importer.py, arches/app/utils/data_management/resource_graphs/importer.py, arches/management/commands/packages.py, tests/models/graph_tests.py
Fix issue where nodegroup attribute data was not being imported with branch/resource model.
re #1237
=> 1237 cardinality import bug

arches/app/media/js/widgets/map.js
=> resizing map in card-form-preview

arches/app/templates/views/resource.htm, arches/app/views/resource.py
Disables 'Create Resource' button in resource editor when a resource model does not have any forms. Also provides a contextual warning explaining when 'Create Resource' button is disabled.
Fixes #948
=> 948 missing forms bug

arches/app/media/js/bindings/input-mask.js, arches/app/media/js/widgets/text.js, arches/app/templates/javascript.htm, arches/app/templates/views/forms/widgets/text.htm, arches/db/dml/db_data.sql, arches/db/graphs/resource_models/architectural_resource.json, bower.json
=> added text widget input mask config re #1216

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/resource/editor/form.js, arches/app/media/js/widgets/map.js, arches/app/media/js/widgets/map/map-styles.js
Added event listener to clear selected geometries in the map widget when a user saves a tile. Added styles to selected draw points. Increased z-index and width of editing notification alert box. re #1090, #1253
=> 1090 draw tools

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm
Fixed editing notification width so that it is 10px from map controls button when controls are dismissed. re #1253
=> Fixed editing notification width so that it is 10px from map controls.

.gitignore, arches/app/views/tileserver.py
=> adding disk caching for tileserver

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm, arches/app/templates/views/resource.htm
=> Small UI enhancements to map widget

arches/app/templates/views/graph/graph-settings.htm
=> Removed Appearance tab from branch model settings, re #1264, #1194

arches/app/media/css/arches-nifty.css, arches/app/media/js/widgets/map.js, arches/app/templates/views/forms/widgets/map.htm, arches/app/views/tileserver.py, arches/db/dml/db_data.sql
also info popup on hover of resource layer
re: #1210
=> adding resource vector tile layer

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/card-configuration/card-components-tree.htm
=> Update card tree UI in card manager

arches/app/media/js/widgets/map.js, arches/db/dml/db_data.sql
=> using relative paths to tileserver layers

.travis.yml
Update Travis build infrastructure to Trusty #1271
=> Travis trusty update

arches/app/media/js/views/base-manager.js, arches/app/media/js/views/graph/graph-settings.js, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/graph-base.htm, arches/app/templates/views/graph/graph-settings.htm
Changed name and icon to observables in graph settings and navbar 'Add New Resource' list, re #942
=> 942 update resource model name

arches/install/requirements.txt
=> adding missing dependencies

arches/app/models/graph.py
Add missing attributes(including sortorder) to cards in graph model so they are imported with resource graph.
Fixes #1300
=> Add missing card attributes to graph model.

arches/app/media/js/views/resource/editor/form.js
=> small fix for updating cards inline, re #1240

arches/app/views/tileserver.py, arches/db/dml/db_data.sql
=> unifying resource vector tile source

arches/app/utils/data_management/resources/importer.py
Small fix for business data import save.
Change save method to update_or_create.
Solved issue with business data save on import.
=> Fix issue with business data save.

arches/app/media/js/views/resource/editor/form.js, arches/app/media/js/widgets/map.js
Fixed edit cancellation for geojson-feature-collection tiles. re #1277
=> 1277 cancel geom edit

arches/app/media/js/widgets/map.js, arches/app/templates/views/forms/widgets/map.htm
Also added geojson in report to visually verify cardinality, re #1334
=> Preventing map zoom and pan when other maps on a page are panned or zoomed

arches/management/commands/packages.py
=> using absolute path to mapnik xml files

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/resource/editor/form.htm
=> UI enhancements to help panel, report template

arches/app/templates/search.htm, arches/app/templates/views/resource/resource-base.htm
=> wiring search link in resource page header

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/search.js, arches/app/models/tile.py, arches/app/templates/views/search.htm, arches/app/templates/views/search/term-filter.htm
=> 1323 tile indexing

arches/app/templates/views/graph.htm, arches/app/templates/views/graph/card-configuration-manager.htm, arches/app/templates/views/graph/form-configuration.htm, arches/app/templates/views/graph/graph-base.htm, arches/app/templates/views/graph/graph-manager.htm, arches/app/templates/views/graph/report-editor.htm, arches/app/templates/views/resource/resource-base.htm
ensuring links w/ navigation click events have href properly defined so that links can be opened in a new tab.
re: #1376
=> allowing navigation links to open in new tab

arches/app/media/css/arches-nifty.css
=> Select2 multi-select styling enhancements

arches/app/templates/base-manager.htm
allows for right click & open in a new tab
re: #1376
=> wiring up hrefs for nav bar links

arches/app/functions/base.py, arches/app/functions/required-nodes.py, arches/app/media/css/arches-nifty.css, arches/app/media/js/views/components/functions/required-nodes.js, arches/app/media/js/views/list.js, arches/app/models/tile.py, arches/app/templates/views/components/functions/required-nodes.htm, arches/app/utils/data_management/resources/importer.py, arches/db/dml/db_data.sql
Updated function ui to allow a user to select multiple node groups and nodes within a single function. re #1193
=> 1193 required nodes

arches/app/media/js/widgets/map.js, arches/app/models/forms.py
=> dirty state bug

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/card-configuration/card-components-tree.htm, arches/app/templates/views/graph/report-editor/report-editor-tree.htm
=> update report node list, card node list

arches/app/functions/resource_functions.py
=> added resourceinstanceid in tile model query, re #1307

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/card-configuration/card-components-tree.htm, arches/app/templates/views/graph/report-editor/report-editor-tree.htm
=> addition small UI enhancements to node tree in cards, reports

arches/app/models/models.py, arches/app/views/resource.py
=> handling forms w/o cards

arches/app/media/js/widgets/map.js, arches/app/templates/views/graph/card-configuration/card-components-tree.htm
=> using node name in card tree view

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/search.js, arches/app/media/js/views/search/base-filter.js, arches/app/media/js/views/search/search-results.js, arches/app/models/graph.py, arches/app/models/resource.py, arches/app/models/tile.py, arches/app/search/mappings.py, arches/app/templates/views/search.htm, arches/app/templates/views/search/search-results.htm, arches/app/utils/betterJSONSerializer.py, arches/app/utils/data_management/resources/importer.py, arches/app/views/search.py, arches/management/commands/packages.py, tests/models/tile_model_tests.py
=> 1325 search results

arches/app/media/css/arches-nifty.css
=> UI: Map Overlay Library enhancements

arches/app/media/css/arches-nifty.css, arches/app/templates/base-manager.htm
=> Add search to default navbar, hover enhancement on basemap widget

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/page-view.js, arches/app/templates/views/resource/resource-base.htm
=> stub out button/panel for recent edits in navbar

arches/app/media/js/views/search.js, arches/app/media/js/views/search/time-filter.js, arches/app/templates/views/search.htm
=> cleanup for filter switching

.gitignore, arches/app/media/js/widgets/map.js, tests/settings_local.py
Added default css class for map context so that map shows up in card manager, re #1413. Removed the tests/settings_local.py and added it to .gitignore.
=> 1413 map not in card manager

arches/app/media/js/bindings/term-search.js, arches/app/media/js/views/search/term-filter.js
=> 1331 term filter

arches/app/media/css/arches-nifty.css
=> Search results UI enhancements

arches/app/media/css/arches-nifty.css, arches/app/templates/views/search.htm
=> fix map position in search UI, update full-screen css for editable maps

arches/app/media/css/arches-nifty.css
=> add CSS to disable full screen button in map widget in Card Manager

arches/app/media/js/bindings/term-search.js, arches/app/media/js/views/search.js, arches/app/media/js/views/search/base-filter.js, arches/app/media/js/views/search/resource-type-filter.js, arches/app/media/js/views/search/term-filter.js, arches/app/search/mappings.py, arches/app/views/search.py
=> 1439 resource type filter

arches/app/media/css/arches-nifty.css
=> Slight CSS tweaks to expanded map classes

arches/app/models/tile.py, arches/app/search/mappings.py
=> manage term index better when updating terms, re #1323

arches/app/media/css/arches-nifty.css
=> Allow scroll of map list in basemap and overlay list

arches/app/media/js/widgets/map.js
=> fix for opacity slider issue with raster layers

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/search.js, arches/app/media/js/views/search/map-filter.js, arches/app/media/js/widgets/map.js, arches/app/templates/views/forms/widgets/map.htm, arches/app/templates/views/search.htm, arches/app/templates/views/search/map-filter.htm
=> sliding in/out search results

arches/app/media/js/models/card-widget.js, arches/app/media/js/models/card.js, arches/app/media/js/viewmodels/widget.js, arches/app/media/js/views/search/map-filter.js, arches/app/media/js/widgets/map.js, arches/app/templates/views/forms/widgets/map.htm, arches/app/templates/views/resource/editor/form.htm
=> adding support for expanded edit map

arches/app/media/js/widgets/map.js
=> minor refactor

arches/app/media/js/views/search/map-filter.js
temporary patch for missing params variable, re #1330
=> temporary patch for missing params variable, re #1330

arches/app/media/js/widgets/map.js
=> smoothing out map resize

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm
=> UI clean-up, remove full screen button from map tools in card manager

arches/app/media/js/views/resource/editor/form-list.js
Forms were included in the form list for every card. Filtered the form list by formid to get a unique list of forms for the resource editor ui. re #1414
=> 1414 duplicates in form list

arches/app/media/js/bindings/time-wheel.js, arches/app/media/js/views/search/time-filter.js, arches/app/media/js/views/search/time-wheel-config.js, arches/app/templates/views/search/time-filter.htm
=> integrating time wheel w/ time filters

arches/app/media/css/arches-nifty.css, arches/app/media/js/widgets/map.js
=> UI tweaks, set default buffer distance for geospatial search to 100ft

arches/app/media/js/views/search/search-results.js, arches/app/media/js/widgets/map.js, arches/app/media/js/widgets/map/map-styles.js, arches/app/templates/views/forms/widgets/map.htm, arches/app/templates/views/search/search-results.htm, arches/app/views/search.py, arches/app/views/tileserver.py, arches/db/dml/db_data.sql
- Changed search results on map from reading paged results to reading all results.
- Added map feature highlighting when mousing over a search result in the search result list.
- Added all resources layer to search map by default and styled all resource layer grey.
- Added outline property to all resources view in order to style polygon outlines differently that line geometries.
- Fixed bug with map search results not updating when resource type filter was changed.
=> 1330 map search

arches/app/media/js/bindings/term-search.js, arches/app/media/js/views/search.js, arches/app/media/js/views/search/search-results.js, arches/app/media/js/views/search/term-filter.js, arches/app/media/js/views/search/time-filter.js, arches/app/templates/views/search/term-filter.htm, arches/app/templates/views/search/time-filter.htm, arches/app/views/search.py, arches/install/requirements.txt
=> 1431 integrate timefilter with search

arches/app/templates/views/graph/graph-settings.htm
=> fixes issue w/ relatable resource model checkboxes

arches/app/media/css/arches-nifty.css
=> Improve display of checkbox arrays (better text handling)

arches/app/media/js/views/concept-graph.js, arches/app/templates/views/rdm/modals/import-scheme-form.htm, arches/app/utils/skos.py, arches/app/views/concept.py
=> 1436 skos import updates

arches/app/models/migrations/0001_initial.py, arches/management/commands/load_ontology.py, arches/settings.py
=> Azaroth42 master

arches/db/dml/db_data.sql
=> sync core concept value ids with the core skos file, re #1436

arches/app/utils/data_management/resource_graphs/exporter.py
=> order nodes in import/export mapping file by node name, #1490

arches/app/media/css/arches-nifty.css, arches/app/templates/views/report-templates/default.htm
=> UI enhancements for Report template (with @media screen enhancements)

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm
=> small ui tweaks on map overlay

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
Added close button to relation properties form.
Dynamically resizing the dropdown's container so that a user can alway scroll to the bottom of the form.
=> 1329 relation properties form

arches/app/media/css/arches-nifty.css, arches/app/views/resource.py
Added deletion of a resource instances index, related resources and related resources indexes to the delete method of the resource view.
=> 1580 delete resource index

arches/app/views/tileserver.py
Catching empty tile request error in tileserver handle_request method
=> Catching empty vector tile request error

arches/app/media/css/arches-nifty.css, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> Related resources table UI enhancements

arches/app/views/search.py
=> fix search pagination, re #1589

arches/app/media/css/arches-nifty.css
=> Update link style in related resources graph

arches/app/media/js/bindings/time-wheel.js, arches/app/media/js/views/search/time-filter.js, arches/app/search/elasticsearch_dsl_builder.py, arches/app/templates/views/search/time-filter.htm, arches/app/views/search.py, arches/urls.py
=> 1430 integrate timewheel with dynamic config

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/models/resource.py, arches/app/utils/data_management/resources/csv_file_importer.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/remover.py, arches/db/dml/db_data.sql, arches/management/commands/packages.py, tests/fixtures/data/csv/heritage_resource_model.mapping
- Moved value transformation for import and export to datatype methods.  Created at base concept datatype class from which concept and concept list datatypes inherit.  
- Fixed an issue with the heritage resource mapping file preventing measurement units from loading correctly in the ui.
- Added a command line tool to clear existing resources (helpful for testing import)
=> 1541 datatype objects

arches/app/templates/views/resource.htm
This should take care of the specific issue, but similar changes may be necessary once new landing pages have been created from existing mockups.
#1571
=> remove unnecessary title bar

arches/install/install_arches.sh, arches/management/commands/packages.py
=> fixing typo in tileserver commands

arches/app/views/tileserver.py
=> unifying resource geom schema for tileserver

arches/app/media/css/arches-nifty.css, arches/app/media/js/views/graph/function-manager.js
Increased space for chosen drop downs in descriptors function and removed cruft.
=> Increased space for chosen dropdowns and removed log statement. re #1542

arches/app/templates/navbar/graph-manage-menu.htm, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/form-configuration.htm, arches/app/templates/views/graph/form-manager.htm, arches/app/templates/views/graph/form-settings.htm, arches/app/views/graph.py
This pull request includes changes to satisfy a number of tickets that documented small UI improvements, generally located (or stemming from) the upper left Manage... menu.
#1389 #1121 #1477 #1612 #1613 
- [ x ] Bugfix (non-breaking change which fixes an issue)
=> Multiple UI Updates

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm
=> Initial UI enhancements to map popup

arches/app/media/css/arches-nifty.css, arches/app/templates/views/forms/widgets/map.htm
=> Small UI enhancement in map popup

arches/app/datatypes/concept_types.py, arches/app/utils/data_management/resources/formats/csvfile.py
=> replaced tabs with spaces

arches/app/media/css/arches-nifty.css, arches/app/templates/base-manager.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> UI fixes for recently added resources panel, related resources panel

arches/app/media/js/rdm.js, arches/app/media/js/views/rdm/concept-tree.js, arches/app/models/concept.py
=> fix recursive error in RDM left tree panel, re #1304

arches/app/media/css/arches-nifty.css, arches/app/templates/views/search/time-filter.htm
=> UI fix for search description, time wheel sequence font

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/media/css/arches-nifty.css, arches/app/media/js/bindings/codemirror.js, arches/app/media/js/models/node.js, arches/app/media/js/views/graph/datatypes/geojson-feature-collection.js, arches/app/media/js/views/map-layer-manager.js, arches/app/templates/javascript.htm, arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm, arches/app/templates/views/map-layer-manager.htm, arches/app/views/map.py, arches/app/views/tileserver.py, arches/db/dml/db_data.sql, arches/db/graphs/branches/Place 1.json, arches/db/graphs/branches/Place 2.json, arches/db/graphs/branches/Place 3.json, arches/db/graphs/resource_models/Activity Resource Model.json, arches/db/graphs/resource_models/Actor Resource Model.json, arches/db/graphs/resource_models/Heritage Resource Group Resource Model.json, arches/db/graphs/resource_models/Heritage Resource Model.json, arches/db/graphs/resource_models/Historical Event Resource Model.json, arches/db/graphs/resource_models/Information Resource Model.json, arches/settings.py, bower.json, tests/fixtures/data/example_target_graph.json, tests/fixtures/sample_branches/places_export.json
=> resource map layer manager

arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm
=> cleaning up map layer manager instructions

arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/formats/format.py
Adding translation of messages using ugettext and writing error messages out to a log file, re #1499, #1653
=> 1499 import validation

arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/views/tileserver.py, arches/management/commands/packages.py, arches/tileserver/all_resources.json, arches/urls.py
=> reworking tilesever add feature for vectiles

arches/app/media/js/views/graph/datatypes/geojson-feature-collection.js, arches/app/media/js/views/map-layer-manager.js, arches/app/templates/javascript.htm, arches/app/templates/views/map-layer-manager.htm
=> stubbing out list of basemaps & overlays 

arches/app/media/css/arches-nifty.css, arches/app/templates/base-manager.htm, arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm, arches/app/templates/views/map-layer-manager.htm
=> Initial Map Manager UI update

arches/app/media/js/views/map-layer-manager.js, arches/app/media/js/widgets/map.js, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/templates/javascript.htm, arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm, arches/app/templates/views/map-layer-manager.htm, arches/app/views/map.py, arches/db/dml/db_data.sql, arches/urls.py
=> adding support for managing overlays & basemaps to layer manager

arches/app/templates/views/map-layer-manager.htm, arches/db/dml/db_data.sql, arches/tileserver/3d-buildings-mapbox.json
=> some cleanup

arches/app/media/css/arches-nifty.css, arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm, arches/app/templates/views/map-layer-manager.htm
=> Map Layer Manager UI enhancements

arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm
=> fixing errors on map layer manager page

.travis.yml, arches/app/datatypes/datatypes.py, arches/app/models/resource.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/search/mappings.py, arches/app/search/search.py, arches/app/views/concept.py, arches/app/views/search.py, arches/install/requirements.txt, arches/install/ubuntu_trusty_setup.sh, arches/install/ubuntu_xenial_setup.sh, arches/management/commands/es.py, arches/management/commands/packages.py, arches/settings.py, arches/setup.py, tests/fixtures/resource_graphs/Search Test Model.json, tests/views/search_tests.py
=> 1629 search with date concepts

arches/install/ubuntu_xenial_setup.sh
Enabled es installation and commented out user prompts to allow travis to run script
=> added es install and commented out user prompts

arches/install/ubuntu_xenial_setup.sh
Removed ES install ... 5.2 debian install is not yet available
=> Removed ES install ... 5.2 debian install is not yet available

arches/app/media/css/arches-nifty.css, arches/app/templates/views/map-layer-manager.htm
=> Fixes for UI lists, Map Layer Manager category selection UI

arches/setup.py, virtualenv/virtualenv.py
See https://github.com/archesproject/arches/issues/1702
=> Updating virtualenv versions and install for setuptools

arches/app/media/js/models/node.js, arches/app/media/js/views/graph/card-configuration/component-forms/permissions-list.js, arches/app/media/js/views/graph/datatypes/geojson-feature-collection.js, arches/app/media/js/views/map-layer-manager.js, arches/app/templates/base-manager.htm, arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm, arches/app/templates/views/map-layer-manager.htm, arches/app/views/map.py
=> map layer manager: displaying permissions and list rework

arches/app/media/js/views/map-layer-manager.js
=> making layer list filter case insensitive

arches/app/views/search.py, tests/search/search_tests.py, tests/views/search_tests.py
=> improve results from date based searches, re #1629

arches/app/datatypes/datatypes.py
=> ensuring resource layer icons are used on ma

arches/app/datatypes/datatypes.py, arches/app/media/js/views/search-base-manager.js, arches/app/media/js/views/search/map-filter.js, arches/app/media/js/views/search/search-results.js, arches/app/media/js/widgets/map.js, arches/app/models/resource.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/search/mappings.py, arches/app/templates/javascript.htm, arches/app/templates/views/search/map-filter.htm, arches/app/views/search.py, arches/db/dml/db_data.sql, bower.json
=> initial work on hex binning results on map

arches/app/datatypes/datatypes.py, arches/app/media/js/widgets/map.js
=> cleanup initial map search results work

arches/app/media/js/views/map-layer-manager.js, arches/app/media/js/widgets/map.js, arches/app/templates/javascript.htm, arches/app/utils/context_processors.py, arches/app/views/search.py, arches/db/dml/db_data.sql, arches/settings.py
=> better hex bin styles, configuration

arches/settings.py
=> some comments

arches/app/utils/data_management/resources/formats/csvfile.py
Use ResourceIDs from csv business data if they are valid UUIDs, otherwise create UUIDs for each resource.
=> Use ResourceIDs from csv file if they are UUIDs

arches/app/media/js/views/map-layer-manager.js, arches/app/media/js/widgets/map.js, arches/app/templates/javascript.htm, arches/app/templates/views/forms/widgets/map.htm, arches/app/utils/context_processors.py, arches/db/dml/db_data.sql, arches/settings.py
=> edits to map search results

arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm
Updating widget paths to component directories in map widget files.
=> fixed path in map widget files

arches/install/arches-templates/project_name/datatypes/sample_datatype.py, arches/management/commands/datatype.py, arches/management/commands/fn.py, arches/setup.py
Added commands to manage datatypes and a sample datatype to the arches project templates
=> 1662 function config

arches/app/models/migrations/0001_initial.py, arches/app/templates/base-manager.htm, arches/app/views/concept.py, arches/app/views/graph.py, arches/app/views/map.py, arches/app/views/resource.py, arches/app/views/tile.py, arches/templatetags/template_tags.py, tests/views/auth_tests.py
=> 618 role based page access

arches/app/media/js/views/resource/editor/form.js
=> fix n-1 cardinality save bug, re #1353

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/importer.py, arches/app/views/tile.py, arches/db/dml/db_data.sql
Alter refresh_mv_geojson_geoms trigger to resolve postgres memory issue when importing. refresh_mv_geojson_geoms now runs manually after import and after each tile save and delete in the tile view.
Postgres memory issue when importing larger(>~1900 resources) datasets.
=> Alter mv trigger on import

arches/app/media/js/viewmodels/geocoder.js
Removing geocode layer when there is no text in the geocode input #1716
=> Clearing geocode layer when gecode text field is emptied, re #1716

arches/app/media/css/arches.css, arches/app/media/js/bindings/related-resources-graph.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> Related Resources Node listing UI

arches/app/media/js/views/graph/datatypes/geojson-feature-collection.js, arches/app/media/js/views/map-layer-manager.js, arches/app/templates/views/map-layer-manager.htm
in map layer map layer manager
re: #1709
=> managing selected layer when changing tabs

arches/app/models/graph.py, arches/app/utils/data_management/resource_graphs/importer.py, arches/db/dml/db_data.sql, arches/db/graphs/branches/Settings System Defaults.json, arches/db/graphs/resource_models/Arches System Settings.json, tests/fixtures/data/json/example_target.json, tests/fixtures/resource_graphs/Search Test Model.json
Add default configs to nodes, reports, functions, and widgets on import if they are missing.
#1790
=> Add default configs on import.

arches/db/dml/db_data.sql
=> Default extrusion height for hex bins to 1, opacity to 0.5

arches/app/utils/data_management/resource_graphs/importer.py
Temporary fix to support config strings until configs are stored as json.
=> Returning config in string format when a string is provided

arches/app/media/js/models/graph.js, arches/app/media/js/views/graph/graph-manager.js, arches/app/media/js/views/graph/graph-manager/node-form.js, arches/app/media/js/views/resource/editor/form.js, arches/app/models/graph.py, arches/app/views/graph.py, tests/models/graph_tests.py
=> show specific error messages related to the graph, re #831

arches/app/media/css/arches.css, arches/app/templates/views/map-layer-manager.htm
=> Make overly opacity slider easier to access, highlight search listing

arches/app/media/js/views/components/widgets/map.js, arches/app/media/js/views/search/search-results.js
=> flying to buffered search result features

arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/models/card.py, arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm, arches/app/views/graph.py
=> 1811 ontologyproperty bug

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm, arches/db/dml/db_data.sql
=> only showing popups for visible features

arches/app/templates/views/graph/report-editor/report-editor-form.htm, arches/app/templates/views/graph/report-editor/report-editor-tree.htm, arches/app/templates/views/report-templates/default.htm
=> removing report footer

arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm
=> only show the ontology property for the outer most card, re #1633

arches/app/datatypes/concept_types.py, arches/app/media/css/arches.css, arches/app/media/js/views/base-manager.js, arches/app/media/js/views/resource.js, arches/app/models/concept.py, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/templates/base-manager.htm, arches/app/templates/views/resource.htm, arches/app/views/base.py, arches/app/views/concept.py, arches/app/views/resource.py, arches/app/views/resources.py, arches/db/dml/db_data.sql
=> recently added resources bugs & enhancements

arches/app/media/css/arches.css, arches/app/templates/views/resource.htm
=> fixing style for recent resources datatable

arches/app/media/js/models/node.js
=> tightening up node config logic

arches/app/utils/data_management/resources/formats/format.py, arches/app/utils/data_management/resources/importer.py, arches/management/commands/packages.py
Provides a warning when pointing to a business data file at an invalid path. Removes references to relation_config file.
#1653
=> 1653_import_warnings

arches/app/templates/base-manager.htm
=> fixing report link in recent edits

arches/app/templates/views/components/widgets/map.htm
=> adding 'selected' class to active basemap

arches/app/views/search.py
=> order time wheel bins by start date, re #1733

arches/app/views/search.py
=> fix broken method reference, re #1847

arches/app/utils/data_management/resources/formats/csvfile.py
=> fix bulk import, re #1850

arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm
=> prevent extremely large buffers from being specified, re #1777

arches/app/views/search.py
=> code refactor, re #1777

arches/app/utils/data_management/resources/formats/format.py, arches/app/utils/data_management/resources/importer.py, arches/install/install_arches.sh, arches/management/commands/packages.py
Add import_business_data_relations command and modify handling of null dates in relations files.
=> Add import_business_data_relations command

arches/app/media/css/arches.css, arches/app/templates/views/graph/graph-manager/node-form.htm
=> Node configuration panel sizing improvements

arches/app/templates/views/resource/editor.htm, arches/app/views/resource.py
add display name of resource to Resource Editor page
#1721 
See #1721 for more discussion on this.
=> 1721 display name

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm
=> Map popup improvements

arches/app/media/js/bindings/summernote.js, arches/app/media/js/views/components/widgets/rich-text.js
Moved regex to clean script tags into the value subscription function.  re #1837
=> Clearing script tags in value subscription, re #1837

arches/app/media/css/arches.css
=> Improved display of map layers, overlays

arches/app/media/css/arches.css, arches/app/media/js/bindings/time-wheel.js, arches/app/media/js/views/search/time-filter.js, arches/app/templates/views/search/time-filter.htm
=> time wheel highlighting issues

arches/app/media/js/views/search/time-filter.js, arches/app/templates/views/search/time-filter.htm
=> fixing to field min date issue

arches/app/templates/base-manager.htm
system settings page was causing error.
=> remove link to system settings page

arches/app/media/js/views/search/time-filter.js
=> keeping date ranges sensible

arches/app/media/js/views/search/time-filter.js
=> fixing time filter date formats

arches/app/media/css/arches.css, arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/views/list.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/templates/views/components/widgets/map.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
Wired up node list panel in related resources manager.
=> 1713 fdg node list

arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/media/js/views/resource/related-resources-node-list.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
Inherits from list view, to add additional observables loaded and total to each item, re #1713
Fixes display of total and loaded counts in the related resources node list.
=> Added related-resources-node-list.js

arches/app/views/resource.py
=> type drop down in related resources time filter

arches/app/media/css/arches.css
=> small tweak to time wheel position

arches/admin.py, arches/app/models/migrations/0001_initial.py, arches/app/models/models.py, arches/app/views/graph.py, arches/app/views/map.py, arches/app/views/resource.py, arches/app/views/search.py, arches/app/views/tileserver.py, arches/management/commands/packages.py
adding map related model (Map Layers, Map Sources, Tileserver Layers) to admin interface
=> Admin map models

arches/app/media/css/arches.css
=> CSS Fix for selected-cards in a left panel list

arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/templates/base-manager.htm, arches/management/commands/packages.py
Added command `manage.py packages -o update_project_templates` which updates the necessary files.  Updated settings.py-tpl file with additional settings a user may need to update. re #1890
=> 1890 template script

arches/app/media/css/arches.css
Set vertical scrolling to `auto` in elements where the scroll bar was showing up unnecessarily. re #1346
=> 1346 scroll bars

arches/app/media/js/views/search/map-filter.js, arches/app/templates/javascript.htm, arches/app/utils/context_processors.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py
This can be set in the Map Layer Manager, re #1890
=> Removed default basemap setting

arches/app/templates/help/map-manager-help.htm, arches/app/views/map.py
=> Map layer help

arches/app/media/js/views/search/map-filter.js
=> Removed reference to view model that is no longer defined

arches/app/templates/help/card-designer-help.htm, arches/app/templates/help/graph-designer-help.htm
simple updates to graph designer and card designer help
=> Help updates

arches/db/dml/db_data.sql
... until flickering iss…ue is resolved, re #1905, #1765
=> Commented out 'stamen-terrain' source and layers.

arches/app/media/js/views/components/widgets/iiif.js
=> removing circle draw tool for iiif widget

arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/app/views/search.py
Force directed graph now updates when a user selects a resource from search results re #1800.
=> 1800 Related Resources d3 graph 

arches/app/datatypes/datatypes.py, arches/app/media/css/arches.css, arches/app/media/js/bindings/nvd3-line.js, arches/app/media/js/views/components/widgets/csv-chart.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/csv-chart.htm, arches/db/dml/db_data.sql, bower.json
Added a widget for loading and charting csv files
- [ x] New feature (non-breaking change which adds functionality)
=> 1738 xychart widget

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/csv-chart.js, arches/app/templates/views/components/widgets/csv-chart.htm
Moved widget elements into href tabs and made 'visualization' link disabled if no files have been uploaded.
=> Moved widget elements into href tabs, re #1738

arches/app/utils/data_management/resources/formats/archesfile.py, arches/app/utils/data_management/resources/formats/format.py, arches/app/utils/data_management/resources/importer.py
Fixes #1907 relation import for json files.
1907
=> 1907 json relations import bug

arches/admin.py, arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/iiif.js, arches/app/models/models.py, arches/app/templates/views/components/widgets/iiif.htm
=> iiif widget drawing name editing

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/widgets/iiif.js, arches/app/models/resource.py, arches/app/templates/javascript.htm, arches/db/dml/db_data.sql
indexing data, highlighting features on click
=> More work on IIIF widget

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/csv-chart.htm
=> UI enhancements for cdv-chart widget

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/iiif.js, arches/app/templates/views/components/widgets/iiif.htm
=> iiif widget full screen feature 

arches/app/datatypes/datatypes.py, arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/iiif.js, arches/app/templates/views/components/widgets/iiif.htm, arches/db/dml/db_data.sql
=> adding support for drawing type in iiif widget

arches/app/media/js/bindings/ckeditor.js, arches/app/media/js/views/components/widgets/rich-text.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/rich-text.htm, arches/install/arches-templates/project_name/bower.json, bower.json
=> 1898 fix summernote issues

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/iiif.htm
=> small UI tweaks for IIIF widget and csv_chart widget

arches/app/media/css/arches.css
=> z-index fix for iiif widget

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/widget.js, arches/app/media/js/views/components/widgets/iiif.js
=> iiif widget enhancements

arches/app/media/css/arches.css
=> Update search results listing CSS

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm
=> UI for map popup footer

arches/app/models/concept.py, arches/app/models/resource.py, arches/app/search/search.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/index_database.py, arches/db/dml/db_data.sql, arches/management/commands/es.py, arches/management/commands/packages.py
=> 1776 database indexing

arches/app/functions/base.py, arches/app/media/js/views/components/functions/primary-descriptors.js, arches/app/models/models.py, arches/app/models/tile.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/functions/primary-descriptors.htm, arches/app/templates/views/graph/function-manager.htm, arches/app/views/admin.py, arches/app/views/graph.py, arches/urls.py
=> 1726 reindex after function update

arches/app/media/css/arches.css, arches/app/media/js/views/resource/editor.js, arches/app/templates/views/resource/editor.htm
Moved the loading mask to the card panel when a card is being saved or deleted. re #937
=> 937 loading mask

appspec.yml, arches/install/ci_install/update_docs.sh
removing CI build references that were used for docbox installation
=> remove CI references to docbox install

arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/archesfile.py, arches/app/utils/data_management/resources/formats/archesjson.py, arches/app/utils/data_management/resources/formats/csvfile.py
Removes relations from json export. Refactor relation export code. Fix issue with concept datatype export.
re 1970
re 1432
=> 1970 remove relations from json

arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm, arches/app/templates/views/resource/editor/form.htm
Added visible switch to both the card configuration and the card container configuration forms.  
Added view logic in the resource editor to:
- Hide card containers when their visibility property is false
- Hide cards within a container (but not the container) if their visibility is false and their container's is true
- Hide cards if their visibility is is false and they do not belong in a container
=> 1618 card container visibility

arches/app/media/css/arches.css, arches/app/templates/views/components/functions/primary-descriptors.htm, arches/app/templates/views/graph/function-manager.htm
=> UI enhancements to primary description function

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/widgets/map.js
=> map enhancements

arches/app/media/js/views/components/widgets/map.js, arches/db/dml/db_data.sql
=> highlighting search hex bins on hover

arches/app/media/js/views/components/widgets/map.js, arches/app/views/resource.py
=> ensuring map link in popup works for overlays

arches/app/templates/views/concept-graph.htm
re #178 
Set the nodetype to 'Concept' in the force concept graph delete request
- [ x] Bugfix (non-breaking change which fixes an issue)
=> Fixed deletion of concepts from the RDM force directed graph

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/functions/primary_descriptors.py
=> 1971 fix primary decs function

arches/app/media/css/arches.css
=> Fix borders on resource model grin in Arches Designer

arches/app/media/css/arches.css, arches/app/media/js/views/search/search-results.js, arches/app/templates/views/search/search-results.htm
=> adding search result "selected" class

arches/app/media/js/views/components/widgets/map.js
=> clearing map highlight when popup dismissed

arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/format.py, arches/management/commands/packages.py
Fix error where empty dates or notes returned None in export and errored on import.
=> Fix relation export error

arches/app/media/js/views/graph/datatypes/geojson-feature-collection.js, arches/app/views/map.py
in map layer map layer manager
re: #1961
=> zooming to resource layer bounds

arches/app/datatypes/datatypes.py
Fixed domain indexing so that the domain text value gets indexed rather than the domain id. 
- [x ] Bugfix (non-breaking change which fixes an issue)
=> 1943 save domains

arches/app/media/css/arches.css, arches/app/templates/views/graph/graph-base.htm
=> Fix for content height that applies to both search and designer.

arches/app/media/css/arches.css, arches/app/templates/views/resource/editor/form.htm
=> Move Card, Card Container cardinality grid to top of form for better editor UX

arches/app/media/css/arches.css, arches/app/templates/views/resource/editor/form.htm
=> Ensure delete icon is positioned properly for card container level saved records

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/views/search.py
=> basics for advanced search backend

arches/app/templates/views/resource/editor.htm, arches/app/views/resource.py
=> fix for saved search error, re #1335

arches/app/datatypes/datatypes.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/templates/views/graph/datatypes/string.htm, arches/app/views/search.py
=> refactoring string adv search

arches/app/datatypes/datatypes.py, arches/app/media/js/views/graph/datatypes/boolean.js, arches/app/models/migrations/0002.py, arches/app/templates/views/graph/datatypes/boolean.htm, arches/app/templates/views/graph/datatypes/string.htm
=> adding boolean support for adv search

arches/app/datatypes/datatypes.py, arches/app/media/js/views/graph/datatypes/number.js, arches/app/models/migrations/0002.py, arches/app/templates/views/graph/datatypes/number.htm
Added number datatype to advanced search
=> Added number datatype to advanced search

arches/app/media/js/models/node.js, arches/app/models/graph.py, arches/app/models/migrations/0002.py, arches/app/models/models.py, arches/app/templates/views/graph/graph-manager/node-form.htm, arches/app/views/resource.py, arches/app/views/search.py
=> adding searchable flag to node model

arches/app/datatypes/datatypes.py, arches/app/media/js/views/graph/datatypes/domain-value.js, arches/app/models/migrations/0002.py, arches/app/templates/views/graph/datatypes/domain-value.htm, arches/app/templates/views/search/advanced-search.htm
Added domain-value datatype for advanced search.  #2030
=> domain-value datatype for adv. search

arches/app/media/css/arches.css, arches/app/templates/views/search/search-base-manager.htm
=> Improve search toggle buttons appearance

arches/app/datatypes/concept_types.py, arches/app/media/css/arches.css, arches/app/media/js/views/graph/datatypes/concept.js, arches/app/media/js/views/graph/datatypes/domain-value.js, arches/app/models/migrations/0002.py, arches/app/templates/views/graph/datatypes/concept.htm, arches/app/templates/views/graph/datatypes/domain-value.htm, arches/app/templates/views/search/advanced-search.htm
Added concept datatype to advanced search
=> 2031 adv search concept datatype

arches/app/datatypes/datatypes.py, arches/app/views/search.py
=> delegating creation of `nested` query to datatypes

arches/app/datatypes/concept_types.py
Added nested query to the adv. search concept datatype
=> Added nested query to concept datatype, re #2031

arches/app/media/js/views/graph/datatypes/concept.js
=> Fixed missing concepts when a concept facet was removed and re-added

arches/app/media/css/arches.css, arches/app/templates/views/resource/editor/form.htm
css edits to allowing map to fully expand, re #2060
=> css edits to allow map to fully expand, re #2060

arches/app/templates/views/resource/editor/form.htm
Removed relative class preventing map from expanding in n-n cardinality cards, re #2060
=> Fixed full map expansion in n-n cards

arches/app/media/css/arches.css
=> better map full screen css

arches/app/media/css/arches.css
=> CSS enhancements for saved search, advanced search styling

arches/app/views/search.py, arches/settings.py
Switched default geocoder to Bing because Mapzen SSL handshake fails with urllib2 and fixed geocoder provider key in search geocode method, re #2069
=> Fix for geocoder requests

arches/app/datatypes/datatypes.py, arches/app/media/js/bindings/time-wheel.js, arches/app/search/elasticsearch_dsl_builder.py, arches/app/search/mappings.py, arches/app/utils/date_utils.py, arches/app/views/search.py, tests/views/search_tests.py
=> 1987 sync time wheel counts

arches/app/templates/views/rdm/concept-report.htm
re #1917
Fix for special characters not working in the rdm.
re #1917
=> Fix for special characters not working in the rdm

arches/app/media/js/views/graph/permission-manager.js, arches/app/templates/help/permissions-help.htm, arches/app/templates/navbar/graph-manage-menu.htm, arches/app/templates/views/graph/permission-manager.htm, arches/app/templates/views/graph/permission-manager/node-list.htm, arches/app/templates/views/graph/permission-manager/permission-settings-form.htm, arches/app/templates/views/graph/permission-manager/users-and-groups-list.htm, arches/app/views/graph.py, arches/urls.py
=> stub out permission manager page and sub-views, re #1112

arches/app/media/js/views/graph/permission-manager.js, arches/app/media/js/views/graph/permission-manager/users-and-groups-list.js, arches/app/templates/navbar/graph-manage-menu.htm, arches/app/templates/views/graph/permission-manager.htm, arches/app/templates/views/graph/permission-manager/users-and-groups-list.htm, arches/app/views/graph.py
=> 1113 users and groups list

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm
=> Add Leaflet style map digitizing tools to map widget

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/models/resource.py
Added get_search_terms methods to domain value and domain value list datatypes to index a domain's label when it's saved to a tile.
=> 2083 domain value index

arches/app/media/css/arches.css
=> Properly size Select2 multiselect

arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm, arches/app/templates/views/graph/datatypes/geojson-feature-collection.htm, arches/app/templates/views/map-layer-manager.htm
also using double click to add drawings from layer
re: #2005
=> adjusting default tabs in map layer manager

arches/app/media/css/arches.css
=> Fix height issue on Select2 multi-select

arches/app/media/css/arches.css, arches/app/media/js/views/graph/permission-manager/grouped-node-list.js, arches/app/templates/views/graph/permission-manager/grouped-node-list.htm, arches/app/views/graph.py
=> add the ability to expand or collapse specific nodes, re #1115

arches/app/media/css/arches.css, arches/app/media/js/views/graph/permission-manager.js, arches/app/media/js/views/graph/permission-manager/grouped-node-list.js, arches/app/templates/views/graph/permission-manager/grouped-node-list.htm
=> 1115 permission settings form

arches/app/media/js/views/components/widgets/map.js
=> adding support for urls for adding feature drawing

arches/app/media/js/views/components/widgets/file.js, arches/app/media/js/views/resource/editor/form.js
Fixed issue causing save and cancel buttons to persist in cards with a 1-n cardinality after a user pressed save or cancel. re #2007
=> 2007 file upload save btns

arches/app/media/js/views/graph/permission-manager.js, arches/app/utils/permission_backend.py, arches/app/views/graph.py, arches/settings.py
=> add Permissions middleware, re #1636

arches/app/templates/navbar/graph-manage-menu.htm, arches/app/templates/views/graph.htm
=> Added manage permission link

arches/app/models/card.py, arches/app/models/forms.py, arches/app/views/resource.py
=> initial attempt at a working card permission filter, re #1636

.gitignore, arches/app/utils/profile.py, arches/app/utils/profile_stats.py, arches/settings.py
=> adding profiling scripts

arches/app/models/card.py, arches/app/views/resource.py
Filtering cards and forms for which a user does not have permissions, re #1635
=> 1635 permissions reports

arches/app/templates/views/graph/card-configuration/component-forms/card-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/card-container-configuration.htm, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm
=> remove unneeded tabbed ui for cards, re #1636

docs/installation.txt
fixing error pointed out in forum.
=> correct placement of elasticsearch in installation process

arches/app/media/js/reports/map.js, arches/app/templates/views/report-templates/map.htm, arches/app/views/resource.py
Preventing map header from showing in map template if a user does not have permissions for geom nodes, re #1635
=> Report Permissions

arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/formats/format.py
Change error log to append instead of overwrite.
Archive log file when it reaches a size greater than 5mb.
Add error to log file about business data not being imported.
Add datetime stamp to each line of log file.
#2089
=> 2089 overwritten error log

arches/app/media/css/arches.css, arches/app/templates/views/graph/permission-manager.htm, arches/app/templates/views/graph/permission-manager/grouped-node-list.htm, arches/app/templates/views/graph/permission-manager/identity-list.htm, arches/app/templates/views/graph/permission-manager/permission-settings-form.htm, arches/app/templates/views/list.htm
=> Permissions ui

docs/installation.txt
=> add note about setting gdal library on windows installations

arches/app/templates/views/components/widgets/select.htm
Allow ability to clear select widget once you've selected an option.
re #2020
=> Allow deselect on concept select dropdown.

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm
Added search buffer and search by extent to leaflet-like map tools and removed previous versions from the map control panel, re #1996
=> Added search buffer and search by extent to map controls

arches/app/templates/base-manager.htm, arches/app/views/graph.py, arches/app/views/map.py, arches/app/views/resource.py, arches/app/views/search.py, arches/install/arches-templates/project_name/templates/base-manager.htm
=> re-add references to map_layers in graph, map and resource.py

arches/app/views/graph.py
Remove superusers from permission manager view
re #2143
- [] New feature (non-breaking change which adds functionality)
=> Remove superusers from permission manager view

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm, arches/app/templates/views/search/search-base-manager.htm
=> Pre4 ui cleanup

arches/app/media/css/arches.css
=> Add box shadow to map panel

arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm
=> Add report link to search popup

arches/app/media/js/reports/map.js, arches/app/templates/views/report-templates/map.htm, arches/app/views/graph.py
Added map layers back into report header.
Fixed error preventing report template from loading in the report editor.
re #2171
=> Report template loading error

arches/app/views/map.py
Fixed missing basemaps in Map Manager
=> Re-added map_layers to map layer manager view, re #2177

arches/app/models/migrations/0002_40b4.py, arches/app/models/migrations/0003_40b4.py, arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/archesjson.py, arches/management/commands/packages.py, arches/settings.py
Change default path to path to settings.SYSTEM_SETTINGS_LOCAL_PATH
Modify command to overwrite existing system_settings_local file
Modify migrations to use settings.SYSTEM_SETTINGS_LOCAL_PATH property
re #2166
=> Change name of command to 'save_system_settings'

arches/app/media/css/arches.css, arches/app/templates/views/report-templates/default.htm
Formatted related resources in reports to follow the presentation of data in cards, re #1657.
=> Related resource formatting

arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/models/migrations/0003_40b4.py
Add advanced search capabilities for concept-list and domain-list datatypes
re #2082
=> 2082 adv search cards

arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm
- Fixed pitch control so it properly indicates state.
- Clearing properly formatted geojson from the geojson input once the feature has been added to the map.
- Zooming to the geojson feature once it's added to the map.
- Notifying user that their geojson is invalid in the notification bar.
=> 1996 map draw tools

docs/installation.txt
tiny fixes to readthedocs content
=> small fixes

arches/app/templates/help/system-settings-help.htm, arches/app/views/resource.py, docs/initial-configuration.txt, docs/overview.txt
complete draft of docs for the new system settings UI. Added to readthedocs content as well.
=> add documentation for system settings

docs/installation.txt
=> fix link url

arches/app/media/js/views/components/geocoders/base-geocoder.js, arches/app/media/js/views/components/geocoders/mapbox.js, arches/app/media/js/views/components/geocoders/mapzen.js, arches/app/media/js/views/components/widgets/map.js, arches/app/models/migrations/0003_40b4.py, arches/app/models/models.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/map.htm, arches/app/utils/context_processors.py, arches/settings.py
Added mapzen gecoder to the list of available geocoders in the card manager.
=> 2069 re-adding mapzen geocoder 

arches/app/media/js/bindings/datepicker.js
Save/Cancel buttons now disappear when clearing a date widget.
re #1866
=> Save/Cancel buttons now disappear when clearing a date widget.

arches/app/templates/base-manager.htm, arches/app/templates/index.htm
=> Remove unused buttons from vertical menu, bold text on landing page

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/iiif.htm, arches/app/templates/views/components/widgets/map.htm
=> Map widget update

arches/app/media/js/views/components/widgets/map.js, arches/app/views/map.py
=> fix index property name mapping issue, re #1637

arches/app/media/css/arches.css, arches/app/media/js/views/resource/editor/form.js
Toggling border class to change border color of open cards in a card container, re #2003
=> User selected record highlighting

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/widgets/map.js, arches/app/media/js/views/search/search-results.js, arches/app/search/elasticsearch_dsl_builder.py, arches/app/search/mappings.py, arches/app/views/search.py
=> filter search result geometries based on user permissions, re #1637

arches/app/media/js/views/components/widgets/map.js
Removed immediate clearing of input.
=> 1990 clear geojson

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm
Added link in geojsonInput to allow clearing of invalid geojson, re #1861
=> Added link in geojsonInput to allow clearing of invalid geojson

arches/app/views/search.py
=> apply permissions to advanced search, re #1637

arches/app/media/css/arches.css
=> Fix for wide forms in the resource editor

arches/app/templates/errors/404.htm, arches/app/templates/errors/500.htm
=> Update 404/500 pages

arches/app/datatypes/datatypes.py, arches/app/views/base.py, arches/app/views/search.py, arches/app/views/tileserver.py
=> 1637 search permissions

arches/app/templates/views/graph/card-configuration/card-form-preview.htm
=> Remove unused div from card preview

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/map.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/map.htm, arches/app/views/search.py, bower.json
=> map buffer units

arches/app/media/plugins/knockout-select2.js
Fix save and cancel buttons when clearing a select dropdown.
re #2020
=> Fix save and cancel buttons when clearing a select dropdown.

arches/app/media/js/views/components/widgets/map.js
=> Remove padding when restoring extent search, re #2233

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/map.js, arches/app/media/js/views/search-base-manager.js, arches/app/media/js/views/search/map-filter.js, arches/app/media/js/views/search/search-results.js, arches/app/templates/views/search/map-filter.htm, arches/app/views/search.py
Switching to using buffer geometry from the server.
Resolves disagreement between the server buffer geometry and the search buffer geometry displayed on the map.
=> 2233 search extent

arches/app/views/search.py
link to help template that needed to happen in a new branch to avoid conflict.
=> link to search help template

arches/app/media/js/views/base-manager.js, arches/app/media/js/views/edit-history.js, arches/app/templates/base-manager.htm, arches/app/templates/views/edit-history.htm, arches/app/views/base.py, arches/app/views/resource.py, arches/install/arches-templates/project_name/templates/base-manager.htm, arches/urls.py
=> 1990 move edit history link

arches/app/views/map.py
=> Fixed missing bounds dict key

arches/app/media/js/views/graph/permission-manager/grouped-node-list.js
Fix for clear button not working in permission manager.
re #2126
=> Fix for clear button not working

arches/app/media/js/views/search/map-filter.js, arches/install/arches-templates/project_name/bower.json, arches/install/arches-templates/project_name/templates/base-manager.htm, arches/install/arches-templates/project_name/templates/index.htm, arches/install/arches-templates/project_name/templates/login.htm
Trans tags added and bower.json updates.
=> Project template update

arches/app/templates/help/function-help.htm
added brief note to the function docs.
=> #2268 add note to function docs about using restricted cards in resource descriptors

arches/install/arches-templates/project_name/templates/index.htm, arches/install/arches-templates/project_name/templates/login.htm
=> Trans tags in index.htm and login.htm

arches/app/templates/help/rdm-help.htm, arches/app/views/concept.py
Adding basic RDM explanation to in-app help for now. Planning to put in something more substantive before the v4 publication.
=> #2265 initial draft and integration of RDM in-app help.

arches/app/media/js/bindings/related-resources-graph.js, arches/app/models/resource.py
=> resource relations count

arches/install/arches-templates/project_name/settings_local.py-tpl, arches/management/commands/packages.py
Replaced dictionaries and arrays commented with ''' in settings_local.py-tpl with #
=> Updated commented project template settings with '#' 

arches/app/media/js/models/node.js, arches/app/media/js/views/map-layer-manager.js, arches/app/models/graph.py, arches/app/templates/javascript.htm, arches/app/views/graph.py, arches/urls.py
only in the context of the map layer manager
re: #2280
=> allow edit to node.config with instances re: #2280

arches/app/media/css/arches.css, arches/app/templates/index.htm
=> Update splash page content

arches/app/templates/index.htm
=> redirect to home page instead of graph designer, re #2284

arches/app/utils/data_management/resources/formats/format.py, arches/install/arches-project, arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/settings_local.py-tpl, arches/install/arches-templates/project_name/templates/index.htm, arches/management/commands/packages.py, arches/settings.py
-  Whitelisted the new setting in update_project_templates.
- Added it to the settings.py-tpl file.  
- Updated the update_project_templates command so that it removes the users cwd from paths saved to any settings.
- Removed `authority_file_errors.txt` from project directory
=> Added RESOURCE_IMPORT_LOG to settings

arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/settings_local.py-tpl, arches/install/arches-templates/project_name/templates/index.htm, arches/management/commands/packages.py
Updated templates with TILE_CACHE_CONFIG settings and changes to index.htm
=> Updated project templates with TILE_CACHE_CONFIG setting, re #1662

MANIFEST.in, arches/install/arches-templates/project_name/settings_local.py-tpl, arches/management/commands/packages.py
=> 2302 fix update project template command

arches/app/datatypes/datatypes.py, arches/settings.py
we should consider adding this to the layer settings
=> reducing default vector simplification

docs/installation.txt
=> remove beta references

arches/app/media/js/views/components/widgets/resource-instance-select.js
=> resource instance datatype reports

docs/installation.txt
=> add note about no binary pip installation

arches/install/requirements.txt, arches/management/commands/load_ontology.py
=> 2306 new ontology loader

arches/app/datatypes/datatypes.py, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/views/components/widgets/resource-instance-multiselect.js, arches/app/models/migrations/0004_4_0_1.py, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> resource instance select

arches/app/datatypes/datatypes.py, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/views/components/datatypes/resource-instance.js, arches/app/models/migrations/0004_4_0_1.py, arches/app/templates/views/components/datatypes/resource-instance.htm
=> resource instance datatype search implementation

arches/app/datatypes/concept_types.py, tests/views/search_tests.py
=> Fixing concept string search

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/xy-input.js, arches/app/media/js/views/components/widgets/map.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/map.htm, arches/app/utils/context_processors.py, arches/settings.py
re #2323
Allowing users to enter xy coordinates (coordinate system of their choosing) to generate points in the resource editor.  The same UI is available in search to create search locations.
=> 2323 xy input

arches/app/media/css/arches.css, arches/app/media/js/views/components/datatypes/resource-instance.js, arches/app/templates/views/components/datatypes/resource-instance.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> cleanup for resource instance adv search

arches/app/media/css/arches.css
=> Clean up positioning of map widget tools, support scroll of overlay grid

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/map.htm
=> Update xy tool CSS

arches/app/media/css/arches.css
=> Small UI enhancements to card-container help panel, map tools positions

arches/app/media/css/app.css, arches/app/media/js/views/components/geocoders/mapbox.js, arches/app/media/js/views/components/geocoders/mapzen.js, arches/app/utils/data_management/sparql_providers/aat_provider.py
This is a replacement for PR #2041 
Removed "http:" part of "http://" links.
=> #2037 Some .htm templates call http links

arches/app/datatypes/datatypes.py, arches/app/models/migrations/0005_4_0_1.py, arches/app/models/models.py, arches/app/utils/data_management/resource_graphs/importer.py, arches/management/commands/datatype.py, arches/management/commands/fn.py, arches/management/commands/packages.py, arches/management/commands/widget.py
- Added parameter to verify if a user wants to overwrite graphs on package loading.
- Added command to build a valid package folder structure.
- Added loading of tile server layers and default name and icon values for mapbox styles and tile server layers.
- Prevented users from loading duplicate functions, datatypes, widgets, and geocoders.
- Added stage and overwrite options for concepts to the load_package command
=> 2335 load package

arches/management/commands/packages.py
Fixed glob pattern for tile server xml files, re #2335,
=> fixed glob pattern for tile server layers.

arches/app/utils/data_management/resources/exporter.py
re #2300, Fixed failing resource relationship export and minor refactor
=> Fixed semantic resource relationship export

arches/app/media/js/views/components/widgets/map.js, arches/app/templates/views/components/widgets/map.htm
Allowed the map configs to update in the report manager when a user pans, tilts, or zooms the map. re #2341
=> 2341 report manager configs

arches/app/media/js/views/rdm/concept-report.js
=> 29 rdm file delete bug

arches/app/media/js/models/graph.js
=> fix ontologies not rendering correctly, re #2307 [ci skip]

arches/app/media/js/rdm.js, arches/app/media/js/views/rdm/concept-report.js, arches/app/templates/views/rdm/concept-report.htm, arches/app/views/concept.py
=> refactor delete of concept to use AlertViewModel, re #291

arches/app/utils/data_management/resources/formats/archesfile.py
Modify json import to overwrite tiles or reosurces that have the same tileid or resource id respectively.
#2394
=> Modify json import to overwrite existing tiles on import. re #2394

arches/app/media/js/views/resource/editor.js, arches/app/models/resource.py, arches/app/templates/javascript.htm, arches/app/templates/navbar/resource-manage-menu.htm, arches/app/views/resource.py, arches/urls.py
=> adding the ability to copy a resource instance, re #2346

arches/app/media/css/arches.css
=> Fix cursor on hover of disabled "Add Card" button in Card Manager

arches/app/utils/decorators.py
whether there are resource graphs in the system, re #2316
=> allow a super user to access the system settings page regardless of 

arches/app/media/css/arches.css, arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/media/js/views/resource/related-resources-node-list.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/management/commands/packages.py
re #2112, Added both a selected and hovered state so that the selected state of a node will persist when hovering over nodes and list entries.
=> Related resources force directed graph persistent node selection

arches/app/media/css/arches.css, arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
re #2110, Replaced d3 tips with a popup panel in the related resources force directed graph.
=> 2110 Related Resources Info Panel

arches/app/datatypes/datatypes.py, arches/app/models/migrations/0007_4_0_1.py, arches/app/templates/views/components/datatypes/geojson-feature-collection.htm, arches/settings.py
=> node level vec tile simplification

arches/app/templates/views/components/widgets/rich-text.htm
=> display value for rich text widget

arches/app/templates/views/components/datatypes/concept.htm, arches/app/templates/views/components/datatypes/date.htm, arches/app/templates/views/components/datatypes/domain-value.htm, arches/app/templates/views/components/datatypes/number.htm, arches/app/templates/views/components/datatypes/resource-instance.htm, arches/app/templates/views/components/datatypes/string.htm
=> better adv search form sizing

arches/app/templates/views/rdm/modals/value-form.htm
Add labels for RDM modal dropdowns
re #177 
- [] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
=> Add labels for RDM modal dropdowns, re #177

arches/app/datatypes/datatypes.py, arches/app/media/js/models/node.js
=> handling for legacy nodes

arches/app/media/css/arches.css, arches/app/templates/views/graph/card-manager.htm
re #2342, Added logic to change remove card text and a class to style locked cards differently than unlocked cards
=> Locked card style

arches/app/media/js/models/concept.js, arches/app/media/js/views/rdm/concept-report.js, arches/app/models/concept.py, arches/app/templates/javascript.htm, arches/app/templates/views/rdm/concept-report.htm, arches/app/views/concept.py, arches/urls.py
=> initial work on making a collection from a given concept, re #2200

arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/importer.py
Add shapefile import. You can now import a zipped or non zipped shapefile. Generally the process is the same as importing a csv. 
- In the mapping file 'file_field_name' for your geometry node should be 'geom'
- Shapefile should be in wgs84
- Geoms may need to be simplified to avoid 'mapping_parser_exception' from elasticsearch
#1543
=> 1543 shapefile import

docs/create-package.txt
=> re #2335, fixed typo in create package docs

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resource_graphs/exporter.py, arches/app/utils/data_management/resources/formats/csvfile.py
Add ability to import business data using prefLabels from collections rather than labelids.
re #2426
=> 2426 label based concept import

arches/app/media/css/arches.css, arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/bindings/scrollTo.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/media/js/views/resource/related-resources-node-list.js, arches/app/models/resource.py, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/management/commands/developer.py, arches/management/commands/packages.py
- Moved report and edit links from the node info panel to the node list entry.
- Added transition to expand node list entry when selected.
- Added scrolling to node list entry when node is selected from force directed graph.
- Modified panel so that it appears near the relevant nodes when a user hovers over an edge.
- Moved the live reload command into it's own developer command.
- Added ability to load additional relationships from the node list entry
=> 2112 related resources fdg list enhancements

arches/app/media/css/arches.css, arches/app/templates/change_password.htm, arches/app/templates/index.htm, arches/app/views/main.py, arches/install/arches-templates/project_name/templates/index.htm, arches/urls.py
Added a page to allow an authenticated user to change her/his password
=> 282 change password page

arches/app/media/js/bindings/term-search.js, arches/app/media/js/rdm.js, arches/app/media/js/views/concept-search.js, arches/app/media/js/views/rdm/modals/add-collection-form.js, arches/app/media/js/views/rdm/modals/add-scheme-form.js, arches/app/media/js/views/rdm/modals/import-scheme-form.js, arches/app/media/js/views/rdm/modals/manage-parent-form.js, arches/app/models/concept.py, arches/app/templates/views/rdm/modals/manage-parent-form.htm, arches/app/utils/skos.py, arches/app/views/concept.py, arches/app/views/resource.py, arches/app/views/search.py
=> 2199 manage top concepts

arches/app/models/concept.py
=> forgot to add default value for method parameter, re #2199

arches/app/models/migrations/0005_4_0_1.py
=> index base Arches concept, re #2199

arches/app/templates/help/map-manager-help.htm, arches/app/templates/help/settings-help.htm
previous changes were only concerned with image links, target='_blank' now added to non-image links.
#2388
=> #2388 fix non-image links

arches/app/media/js/rdm.js, arches/app/media/js/views/rdm/modals/import-scheme-form.js, arches/app/views/concept.py
=> add a loading spinner when importing skos files, re #1583

arches/app/media/js/views/components/datatypes/concept.js, arches/app/media/js/views/components/datatypes/domain-value.js, arches/app/media/js/views/components/datatypes/resource-instance.js
re #2342, Skipping check if card is editable in card configuration. This is a just stop-gap measure to avoid an error.
=> re #2342, Skipping check if card is editable in card configuration

arches/app/media/js/views/components/datatypes/concept.js, arches/app/media/js/views/components/datatypes/domain-value.js, arches/app/media/js/views/components/datatypes/resource-instance.js
re #2342, Checking if cards are editable in the card configuration manager.
=> re #2342, Checking if cards are editable

arches/app/models/migrations/0005_4_0_1.py, arches/app/templates/views/rdm/concept-report.htm, arches/app/utils/data_management/sparql_providers/aat_provider.py, arches/app/utils/skos.py
=> 245 rdm uri import

arches/app/views/concept.py
=> only showing prefLabels

arches/app/media/js/rdm.js, arches/app/media/js/views/rdm/modals/delete-scheme-form.js, arches/app/templates/javascript.htm
=> add feedback when deleting a concept scheme, re #1583

arches/app/media/css/arches.css, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> Pre 401 ui fixes

arches/app/templates/help/system-settings-help.htm
=> fix quotes in target= and trans tags

arches/app/templates/views/components/widgets/map.htm
re #363, Fix for loading map in search when node obj is undefined
=> re #363, Required node modifications

arches/app/media/css/arches.css, arches/app/media/js/views/graph/card-configuration-manager.js, arches/app/media/js/views/graph/card-configuration/card-component-form.js, arches/app/media/js/views/graph/graph-manager/node-form.js, arches/app/templates/views/components/widgets/checkbox.htm, arches/app/templates/views/components/widgets/concept-select.htm, arches/app/templates/views/components/widgets/csv-chart.htm, arches/app/templates/views/components/widgets/datepicker.htm, arches/app/templates/views/components/widgets/file.htm, arches/app/templates/views/components/widgets/iiif.htm, arches/app/templates/views/components/widgets/number.htm, arches/app/templates/views/components/widgets/radio-boolean.htm, arches/app/templates/views/components/widgets/radio.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/components/widgets/rich-text.htm, arches/app/templates/views/components/widgets/select.htm, arches/app/templates/views/components/widgets/text.htm, arches/app/templates/views/graph/card-configuration/component-forms/widget-configuration.htm, arches/app/templates/views/graph/graph-manager/node-form.htm
- Ensuring that there is always a node defined before adding the `isrequired` switch
- Disabling `isrequired` switch if data is already saved against its card
=> 363 required fields

arches/app/media/css/arches.css
=> fdg edge styling update

arches/app/media/css/arches.css, arches/app/media/js/bindings/related-resources-graph.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/app/views/resource.py
- Added all relationship types to list of relationships when two resources have multiple relationship types.
- Fixed issue with broken loading links (due to ko subscriptions not getting cleaned up).
=> 2112 fdg list

arches/app/media/css/arches.css, arches/app/templates/views/graph/permission-manager/permission-settings-form.htm
=> fdg model icon CSS update, permissions manager CSS updates

arches/app/media/css/arches.css, arches/app/templates/views/graph/permission-manager/permission-settings-form.htm
=> Permissions manager title improvements

arches/app/models/concept.py, arches/app/views/concept.py
=> 244 use correct lable in dropdowns

arches/app/media/css/index.css, arches/app/templates/index.htm, arches/install/arches-templates/project_name/templates/index.htm
re #282, Moved logout and change password links into a dropdown.
=> re #282, Moved logout and change password links into a dropdown.

docs/import-export.txt, docs/initial-configuration.txt
Sparked by forum post about system settings directions.
a few small fixes to initial configuration and system settings docs
=> a few general docs updates

arches/management/commands/packages.py, arches/management/commands/utils.py
Added a user input prompt to confirm the remove_resource procedure. Added a `-y` `--yes` flag to allow command to run without user input.
=> add user confirmation input to command, add -y/--yes to force

arches/app/media/js/views/graph/graph-page-view.js, arches/app/views/graph.py
re #1129 
Redirecting users to the most suitable graph page when switching between pages in the graph designer.
Graph Designer:
Settings:
Cards:
Menus:
Reports
Functions:
Permissions:
=> Graph editing workflow - redirecting users to the most suitable page 

arches/management/commands/export.py
re #1498, Added an export command to export a shapefile from a resource instance view.
=> 1498 shp export

arches/management/commands/export.py
re #1498, Checking for existing rows before attempting export and a little tidying.
=> shp export refinements

arches/management/commands/export.py
=> re #1498, Removed unnecessary braces in string formatting.

arches/app/models/concept.py
=> fix sort order in tree view and left panel, re #2018

arches/install/requirements.txt
Specified python  dependency versions in requirements.txt
=> Specified versions in requirements.txt

arches/app/templates/rdm.htm
See https://github.com/archesproject/arches/issues/2482
=> Add Title into the RDM template

arches/app/models/concept.py
=> speed up sorted hierarchical paged dropdown, re #244

docs/managing-map-layers.txt
add documentation to readthedocs re: geospatial config and layers
#2319
=> 2319 add documentation to readthedocs re: geospatial config and layers

arches/app/media/css/arches.css
=> Update min-width, allow x-scroll to better support small screens

arches/app/media/js/models/node.js
=> fixing issue w/ node config

arches/app/media/js/viewmodels/xy-input.js, arches/app/templates/views/components/widgets/map.htm, arches/settings.py
re #2523, #2520 Fixed issue with proj4 coor transformation issue and set default values for xy coords and srid.
=> 2523 xy input proj4 error

arches/app/views/tileserver.py
=> fix for handling tileserver layers outside request

arches/app/media/css/arches.css
=> fixing search map height

arches/app/media/js/views/components/widgets/map.js
=> fixing map offset issue

arches/app/media/css/index.css, arches/app/templates/index.htm
re #282, 
- Added click binding to `Welcome User` to reveal logout button in cases where caret is hidden off screen.
- Fixed placement of logout and change password links when a user's screen width is near 1000px.
- Added trans tag to logout
=> 282 change password

arches/app/media/css/arches.css
=> fixing navbar z-indexing

arches/app/models/migrations/0009_4_0_1.py
Added forward function to migration to move required nodes from required nodes function to node `isrequired` property.
=> re #363, Added required nodes forward function

arches/install/arches-templates/project_name/templates/index.htm
=> Updated project template with changes to index.htm

arches/app/models/migrations/0009_4_0_1.py
re #363, Setting `isrequired` back to default value (false) in migration reversal.
=> re #363, Setting isrequired values back to default

arches/management/commands/packages.py
Added logic at the end of setup_db to overwrite system settings if a user has a system settings local file.
=> Fixed automatic loading of system settings local

docker-compose.yml, docker/Readme.md, docker/entrypoint.sh
New custom arches apps are now created alongside arches root instead of within.
Also update Readme and cleanup in docker-compose.yml (remove unused volume, rename volume).
=> Docker: Change folder structure

docker/entrypoint.sh
Removed the `exec` part of the command and added `exit 0`  so command is properly completed.
Virtual env was not active when running arbitrary commands.
=> Docker: Run arbitrary commands within virtual env

arches/app/templates/views/search/search-base-manager.htm, arches/app/templates/views/search/search-results.htm
Hiding related resources to users that are not logged in
=> Hiding related resources to users that are not logged in

arches/app/models/concept.py, arches/app/models/migrations/0009_4_0_1.py, arches/app/templates/views/search/search-base-manager.htm, arches/app/templates/views/search/search-results.htm
=> 2554 rdm export bug

arches/app/utils/password_validation.py, arches/management/commands/packages.py, arches/settings.py
Added password validators to settings.py including custom validators for requiring upper and lower case characters, numeric characters and special characters
=> 2454 password validators

docker-compose.yml, docker/Readme.md, docker/entrypoint.sh
=> 2565 minor docker fixes

arches/app/media/css/arches.css, arches/app/media/js/models/project.js, arches/app/media/js/views/project-manager.js, arches/app/models/migrations/0010_4_0_2.py, arches/app/models/models.py, arches/app/templates/base-manager.htm, arches/app/templates/help/project-manager-help.htm, arches/app/templates/javascript.htm, arches/app/templates/views/project-manager.htm, arches/app/views/project.py, arches/urls.py
=> project manager page basics

arches/app/media/css/arches.css, arches/app/templates/help/profile-manager-help.htm, arches/app/templates/views/user-profile-manager.htm, arches/app/views/users.py
Added help page and some ui fixes for user profile manager page
=> 2567 move change password

arches/app/models/migrations/0001_initial.py, arches/app/models/migrations/0003_40b4.py, arches/app/models/migrations/0005_4_0_1.py, arches/app/utils/data_management/resources/importer.py, arches/db/dml/db_data.sql, arches/install/requirements.txt, arches/management/commands/load_ontology.py, arches/urls.py, tests/importer/ontology_import_tests.py
=> 2355 upgrade django to 1.11.6

arches/app/media/css/arches.css, arches/app/templates/views/graph/permission-manager/permission-settings-form.htm
=> re #2395 UX Improvements in listing widget, forms, graph manager

arches/app/media/css/arches.css, arches/app/templates/base.htm, arches/app/templates/javascript.htm, arches/app/templates/signup.htm, arches/app/utils/context_processors.py, arches/app/views/base.py, arches/app/views/main.py, arches/app/views/users.py, arches/management/commands/packages.py, arches/settings.py
=> 2453 signup page

arches/app/media/css/arches.css
=> Update CSS to better display nodes in related resources fdg

arches/app/models/system_settings.py, arches/app/templates/base.htm, arches/app/templates/email/general_notification.htm, arches/app/templates/errors/error_base.htm, arches/app/templates/login.htm, arches/app/templates/signup.htm, arches/app/templates/views/project-manager.htm, arches/app/views/main.py, arches/app/views/project.py
=> 2582 project summary tab

arches/app/media/js/models/project.js, arches/app/templates/views/project-manager.htm
First attempt at group user filter in project's people tab. re #2581
=> Adds user filter to a projects group user list. re #2581

arches/app/media/css/arches.css, arches/app/templates/views/list.htm, arches/app/templates/views/project-manager.htm
Layout improvements to the people tab in the project manager re #2581
Fix for the list.htm page
=> 2458 project summaries

arches/app/media/js/models/project.js, arches/app/media/js/views/project-manager/identity-list.js, arches/app/templates/views/project-manager.htm
=> add groups and names listing to manage tab of the project page, re #2582

arches/app/templates/signup.htm, arches/app/utils/forms.py, arches/app/views/main.py, arches/install/requirements.txt, arches/management/commands/packages.py, arches/settings.py
=> add support for using Captcha in the signup form, re #2453

arches/app/media/css/arches.css, arches/app/media/js/models/project.js, arches/app/templates/help/project-manager-help.htm, arches/app/templates/views/project-manager.htm
Modified user activation rules so that a user can be unapproved in an approved group. re #2581 
Added help documentation to explain rules.
=> 2581 project users

Dockerfile, docker-compose-test.yml, docker-compose.yml, docker/entrypoint.sh, docker/settings_local.py
Solve https://github.com/archesproject/arches/issues/2628
=> 2628 docker enhancements

docs/additional-configuration.txt
Improved html link appearance. re #2454
=> Password validation doc improvements

arches/app/media/css/arches.css
=> re #2639 Improve button display

arches/app/media/js/bindings/datepicker.js, arches/app/media/js/models/project.js, arches/app/media/js/views/project-manager.js, arches/app/models/migrations/0011_4_0_2.py, arches/app/models/models.py, arches/app/templates/base.htm, arches/app/templates/views/project-manager.htm, arches/app/utils/context_processors.py, arches/app/views/project.py
=> project manager settings page

arches/app/media/js/viewmodels/project-manager.js
The project model updates the properties of this list. re #2581
=> Removed update of identity items in list view

arches/app/media/js/viewmodels/project-manager.js, arches/app/media/js/views/project-manager.js, arches/app/templates/javascript.htm, arches/app/templates/views/project-manager.htm, arches/app/views/project.py
Allows users to delete mobile projects in the mobile project manager. re #2459
=> Added ability for user to delete a mobile project

arches/app/media/css/arches.css, arches/app/templates/views/project-manager.htm
=> re: #2658 #2659 mpm "people" tab UI improvements, add tab for defining instance data download

arches/app/media/css/arches.css, arches/app/media/js/models/project.js, arches/app/media/js/viewmodels/project-manager.js, arches/app/media/js/views/project-manager/resource-list.js, arches/app/templates/views/graph.htm, arches/app/templates/views/project-manager.htm, arches/app/templates/views/project-manager/resource-list.htm, arches/app/views/project.py
Initial addition of resources in the resources tab re #2580. Also fixes #2662.
=> 2580 mpm resources tab

arches/app/utils/data_management/resources/formats/csvfile.py
Fix for importing concept preflabels with commas in them during business data import
We've followed standard csv convention where values with commas in them must be quoted and quotes within quotes must be escaped. Thus a concept list containing one label with a comma in it and another label without a comma would look like this:
`"""label, with comma"", label without comma"`
#2665
=> Fix for commas in preflabls during label based business data import

docker/Readme.md
=> Docker Readme updates

arches/app/utils/data_management/resources/formats/csvfile.py, tests/fixtures/data/csv/required_child_node_import.csv, tests/fixtures/data/csv/required_child_node_import.mapping, tests/fixtures/data/csv/required_node_import.csv, tests/fixtures/data/csv/required_node_import.mapping, tests/fixtures/data/json/cardinality_test_data/target.json, tests/models/mapped_csv_import_tests.py
Fix required node validation and add tests.
#2732
=> 2732 required node validation

arches/app/templates/views/graph/graph-manager/node-form.htm
Change the "Searchable" label and description in node settings to clarify functionality for users.
#2226
=> Change "Searchable" label and description in graph designer #2226

arches/management/commands/packages.py
Removes duplicate system settings overwrite prompt in importer
=> Removes unnecessary prompts in package loader

arches/app/media/css/arches.css, arches/app/media/js/views/project-manager.js, arches/app/templates/views/project-manager.htm
Adds delete button to each project listed in the project manager. re #2654
=> Adds delete button to each project

docs/index.txt, docs/initial-configuration.txt, docs/installation.txt, docs/projects-and-packages.txt, docs/requirements-and-dependencies.txt
This is a re-working of the installation instructions in an effort to consolidate some existing documentation. It works in conjunction with a change to the wiki "developer installation" as well. The main change in that regard is to point developers toward using projects. Also, this is a step toward incorporating the package paradigm into the default installation process, to make people more familiar with it.
=> Doc improvements

arches/app/media/js/models/project.js, arches/app/media/js/viewmodels/project-manager.js, arches/app/media/js/views/user-profile-manager.js, arches/app/models/project.py, arches/app/templates/javascript.htm, arches/app/templates/views/user-profile-manager.htm, arches/app/views/project.py, arches/app/views/user.py, arches/urls.py
Adds adds a Mobile Project proxy model to move duplicate code regarding protects from the user (profile) and project django views to a common location. Also uses ajax to pull down a project's resource information to improve performance of the user profile page. re #2458.
=> Adds a mobile project proxy model

arches/urls.py
Fixes the project resources url #2458
=> Project resources url correction re #2458

arches/management/commands/fn.py, arches/management/commands/widget.py
Generates a custom uuid for functions and widgets if one is not provided or if it is invalid. re #2637
=> Generates a uuid for custom widgets and functions

arches/app/media/css/arches.css, arches/app/media/js/views/mobile-survey-manager/resource-list.js, arches/app/templates/views/mobile-survey-manager.htm, arches/app/templates/views/mobile-survey-manager/resource-list.htm
Changes appearance of the resource list in the mobile survey manager so that resources are displayed in an accordion-like list rather than a list and side panel. re #2580
=> MSM Resource List

arches/app/media/js/viewmodels/widget.js, arches/app/media/js/views/components/widgets/text.js, arches/app/models/migrations/2704_string_widget_default_value.py, arches/app/templates/views/components/widgets/text.htm
Add ability to set default value for string widget
#2704
=> 2704 string widget default value

arches/management/commands/packages.py
Adds command to export package configs. Also adds loading of preliminary sql files.
=> Adds command to export package configs and loading of preliminary sql files.

arches/app/media/css/arches.css, arches/app/templates/views/mobile-survey-manager.htm
=> re: #2770 mpm resources tab ui

arches/app/templates/views/resource/editor/form.htm
=> Added disabled state to cards within containers, re #2710

arches/app/models/card.py, arches/app/templates/views/graph/card-configuration/card-form-preview.htm, arches/app/views/graph.py
Adds disabled state to card preview and enables widgets even if a user does not have delete permissions.
=> 2710 node disabled state

arches/app/media/js/models/mobile-survey.js, arches/app/views/mobile_survey.py
Fixes bug when saving approved groups to a mobile survey. re #2581
=> Mobile Survey - Approved groups bug fix

arches/app/media/js/views/components/widgets/datepicker.js, arches/app/models/migrations/2707_datepicker_widget_default_value.py, arches/app/templates/views/components/widgets/datepicker.htm
Add ability to set default value for date widget
#2707
=> 2707 date widget default value

arches/app/templates/views/components/widgets/radio-boolean.htm
=> 2701 disabled boolean widget

arches/management/commands/packages.py, arches/management/commands/resources.py
Moves remove_resource command out of packages.py, re #2428
=> Moves remove_resource command out of packages.py, re #2428

arches/app/views/graph.py
Applies disabled state to cards belonging to card containers within the card preview. #2710
=> Applies disabled state to cards belonging to card containers

arches/app/search/search.py, arches/app/utils/index_database.py
=> 2751 es index updates

arches/app/media/js/models/mobile-survey.js, arches/app/media/js/views/mobile-survey-manager/resource-list.js, arches/app/templates/base-manager.htm, arches/app/templates/help/mobile-survey-manager-help.htm, arches/app/views/mobile_survey.py, arches/app/views/user.py
Changes references to project to mobile survey in the django views. re #2760
=> Mobile Project > Survey

arches/app/templates/views/components/widgets/datepicker.htm
=> add the ability to disable the date widget, re #2696

arches/app/templates/views/components/widgets/file.htm
=> add the ability to disable the file upload widget, re #2700

arches/app/media/css/arches.css, arches/app/media/js/models/mobile-survey.js, arches/app/media/js/viewmodels/mobile-survey-manager.js, arches/app/media/js/views/mobile-survey-manager/identity-list.js, arches/app/templates/views/mobile-survey-manager.htm, arches/app/templates/views/mobile-survey-manager/identity-list.htm, arches/app/templates/views/mobile-survey-manager/resource-list.htm
Refactor of the users/groups UI to the accordion layout in the mockup. re #2581
=> 2581 survey users

arches/app/media/js/bindings/select2-query.js, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/datatypes/resource-instance.htm
Disables the resource instance widget when it's card is disabled. re #2699
=> Disables resource instance widget

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/number.htm
Formatting number widget for report with prefix and suffix. re #2591
=> Formatting number widget for report with prefix and suffix

arches/app/datatypes/datatypes.py
Resolve issue where domain datatype validation was not working as intended.
re #2817
=> Fix issue with domain datatype validation, re #2817

arches/app/media/js/viewmodels/domain-widget.js, arches/app/media/plugins/knockout-select2.js, arches/app/templates/views/components/widgets/checkbox.htm, arches/app/templates/views/components/widgets/radio.htm, arches/app/templates/views/components/widgets/select.htm
Adds disabled state to domain widgets: select, checkbox, and radio re #2694
=> 2694 disabled domain lists

arches/app/templates/views/components/widgets/concept-select.htm
Allows for disabling concept-select widget. re #2695
=> Allows for disabling concept-select widget. re #2695

arches/app/templates/views/components/datatypes/domain-value.htm
Add ability to reorder added domain values in domain value widget.
#2806
=> Add ability to reorder values in domain widget, re #2806

arches/app/media/css/arches.css
Makes text in disabled select2 multi a visible color, re #2695
=> Makes text in disabled select2 multi a visible color

arches/app/media/js/views/components/widgets/radio-boolean.js, arches/app/media/js/views/components/widgets/switch.js, arches/app/models/migrations/2713_null_boolean_state.py, arches/app/templates/views/components/widgets/radio-boolean.htm
Makes boolean value `null` by default rather than displaying `false`. re #2713
=> Makes boolean value `null` by default rather than displaying `false`

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/switch.js, arches/app/templates/views/components/widgets/switch.htm
Adds null state to switch widget. #2713
=> Adds null state to switch widget. 

arches/app/templates/help/graph-designer-help.htm, arches/app/templates/views/graph/graph-manager/node-form.htm
Remove sub-card terminology from graph manager and graph manager help.
#2225
=> Change sub-card terminology, re #2225

arches/app/templates/javascript.htm
Add ability to have single quote in concept label
#2830
=> Add ability to have single quotes in concept labels, re #2830

arches/app/media/js/bindings/time-wheel.js
=> Change label in time wheel config, re #2372

arches/app/media/css/arches.css, arches/app/templates/views/mobile-survey-manager.htm
=> re: 2852 MSM UI Enhancements

.travis.yml, arches/install/ci_install/ci_ubuntu_xenial_setup.sh
Added `filter_secrets:false` to the travis.yml file.
=> Travis updates

arches/app/media/css/arches.css, arches/app/media/js/models/mobile-survey.js, arches/app/media/js/views/mobile-survey-manager.js
Changes 'project' to 'mobile survey' in mobile survey front-end model. re #2760
=> Changes 'project' to 'mobile_survey' in mobile survey model. re #2760

arches/app/media/js/viewmodels/mobile-survey-manager.js, arches/app/media/js/views/mobile-survey-manager.js, arches/app/media/js/views/mobile-survey-manager/resource-list.js, arches/app/media/js/views/user-profile-manager.js, arches/app/templates/base-manager.htm, arches/app/templates/views/mobile-survey-manager.htm, arches/app/templates/views/mobile-survey-manager/project-summary.htm, arches/app/templates/views/user-profile-manager.htm
Renames 'mobile projects', 'mobile surveys' in javascript and htm templates. re #2760
=> Replaces 'mobile project' with 'mobile survey' in js and htm files. re #2760
