archesproject/arches

arches/app/media/js/viewmodels/graph-settings.js, arches/app/media/js/viewmodels/report.js, arches/app/media/js/views/components/widgets/map.js, arches/app/media/js/views/graph-designer.js, arches/app/media/js/views/graph/graph-designer/node-form.js
=> Resolves lag in tabbed report configs and error when switching report header

arches/app/media/css/tree/tree.css, arches/app/media/js/models/card.js, arches/app/media/js/viewmodels/card.js, arches/app/media/js/viewmodels/tile.js, arches/app/media/js/views/graph/graph-designer/card-tree.js, arches/app/templates/views/components/cards/default.htm
-   [x ] New feature (non-breaking change which adds functionality)
indicates in the UI if there are unsaved edits to a tile or card (in resource editor)
#5254 
=> 5254 resource editor tree display dirty tile

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/file-widget.js, arches/app/templates/views/components/widgets/file.htm
Moves what was called the "newfilewidget" into core arches, changing the viewmodel and template but keeping the naming convention `file-widget` and `file.js` and widget id.
https://github.com/archesproject/consultations-prj/issues/314
=> 314 replace file widget with newfilewidget

arches/app/media/css/arches.css, arches/app/templates/views/components/map-popup.htm
=> re:#5344 popup report styles

arches/setup.py
- removes `run_virtual_environment()` method and call from setup.py
- comments out main logic in `confirm_system_requirements()` with todo to replace post python 3 upgrade
=> 2939 virtualenv requirement

arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/install/arches-templates/project_name/datatypes/sample_datatype.py
refactors `except` syntax to conform to python 3 standards, using 2to3
#5340 
=> refactors except using 2to3, re #5340

arches/app/models/concept.py, arches/app/utils/__init__.py, arches/app/utils/data_management/resources/importer.py, arches/app/utils/pagination.py, arches/app/views/api.py, arches/app/views/concept.py, arches/app/views/tileserver.py
-   [x ] New feature (non-breaking change which adds functionality)
2to3 refactor using commands `maxint`,`zip`, and `xrange`
#5349 
=> 5349 2to3 maxint zip xrange

arches/app/models/migrations/0001_initial.py, arches/app/models/migrations/0010_4_1_0.py, arches/app/search/components/term_filter.py, arches/app/views/api.py, arches/app/views/mobile_survey.py, arches/app/views/resource.py, arches/app/views/search.py, arches/app/views/user.py, arches/management/commands/es.py, arches/management/commands/packages.py
-   [x ] New feature (non-breaking change which adds functionality)
2to3 commands `numliterals` and `set_literal`
#5351 
=> 5351 2to3 literals

arches/app/models/graph.py, arches/app/models/tile.py, arches/app/utils/password_validation.py
=> 2to3 command filter, re #5355

arches/admin.py, arches/app/utils/data_management/resources/formats/archesfile.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/formats/rdffile.py, arches/app/utils/data_management/resources/importer.py, arches/app/utils/data_management/sparql_providers/aat_provider.py, tests/ui/page_elements/map_widget.py, tests/ui/page_elements/string_widget.py, tests/ui/pages/base_page.py, tests/ui/pages/base_widget_page.py, tests/ui/pages/card_designer_page.py, tests/ui/pages/card_page.py, tests/ui/pages/form_page.py, tests/ui/pages/graph_page.py, tests/ui/pages/login_page.py, tests/ui/pages/node_page.py, tests/ui/pages/report_editor_page.py, tests/ui/pages/report_manager_page.py, tests/ui/pages/resource_editor_page.py, tests/ui/pages/resource_manager_page.py
=> Uses relative imports for sibling modules

arches/app/media/js/views/components/cards/map.js, arches/app/media/js/views/components/cards/related-resources-map.js
=> zooms to related resources data on select from dropdown

arches/app/utils/betterJSONSerializer.py
adds an `isinstance` check for byte strings, decodes before handling data via `json.load()` in JSONSerializer
#5372 
=> decodes bytestring input in betterJSONSerializer, re #5372

arches/app/media/css/arches.css, arches/app/media/js/views/components/cards/map.js, arches/app/media/js/views/components/search/map-filter.js
=> re:#5371 ui updates

arches/app/models/graph.py, arches/app/utils/data_management/resources/formats/archesfile.py
Fixes sorting errors when saving tiles on resource model import. re #5372
=> Tile sorting error when importing a resource model

arches/app/utils/skos.py
Fixes bug calling e.message in python 3. re #5372
=> Fixes error message. 

arches/app/utils/index_database.py, arches/app/utils/skos.py, arches/app/views/concept.py
create a concept scheme to hold orphaned concepts, re #5384
=> warn when importing a skos file if orphaned concepts would be created,

arches/app/models/concept.py
=> fix the RDM to work in py3, re #5389

arches/settings.py
=> fix import of settings_local, re #5396

arches/app/datatypes/base.py, arches/app/models/migrations/5394_postgis_mvt_api.py, arches/app/views/api.py, arches/urls.py
=> adds postgis mvt api

arches/app/datatypes/base.py
=> adds commented future url for mvt sources

arches/app/views/api.py
=> supports clustering in postgis mvt api

arches/app/utils/data_management/resources/formats/archesfile.py
=> fix for resource impport failing, re #5410

arches/app/datatypes/datatypes.py
additional refactoring for domain list data type
#5411 
=> also refactors domain list data type __contains query, re #5411

arches/app/views/mobile_survey.py
=> removes list() from query in get_history(), re #5424

arches/app/datatypes/base.py
=> Removes tile caching methods from the base datatype.

arches/app/utils/arches_crypto.py
=> fix create user issue, re #5423

arches/install/arches-project
=> Fixes print statement

arches/app/datatypes/datatypes.py
Fixed distutils import statement for Python 3.
=> Fixes distutils error when saving boolean data

arches/app/datatypes/datatypes.py, arches/app/models/migrations/0010_4_1_0.py, arches/app/models/models.py, arches/management/commands/packages.py, tests/exporter/resource_export_tests.py
=> 5441 fix data import

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/workflow.htm
enables a workflow step to be "required" depending on the value of that field on the workflow config for each step
https://github.com/archesproject/consultations-prj/issues/385
https://github.com/archesproject/consultations-prj/issues/384
-   [x ] Unit tests pass locally with my changes
=> Consultations prj 384 step requirement

arches/app/search/components/paging_filter.py
=> somehow ES 7.x style response format got merged into master, #5450

arches/app/media/js/views/graph/function-manager.js
=> fixes issue w/ saving functions where component is null

arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/settings_local.py-tpl, arches/settings.py
=> fix incorrect LOCALE_PATH setting, re #5461

.travis.yml, arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/settings_local.py-tpl, arches/install/init-unix.sql, arches/settings.py, docker/settings_local.py
=> rename postgis template to "template_postgis", re #5454

arches/app/search/components/paging_filter.py
=> Fixes error in paging filter

arches/management/commands/packages.py
=> need to encode output of JSONSerializer, re #5485

arches/app/media/js/models/node.js, arches/app/media/js/views/graph/graph-designer/node-form.js, arches/app/models/graph.py, arches/app/models/migrations/5473_exportable_nodegroup_node_fieldname.py, arches/app/models/mobile_survey.py, arches/app/models/models.py, arches/app/templates/javascript.htm, arches/app/templates/views/graph/graph-designer/node-form.htm, arches/app/views/graph.py, arches/urls.py
1. This adds a migration to add the following columns to the database: 
-- Nodegroup: exportable (boolean)
-- Node: fieldname (text)
2. The Nodegroup and Node models in `models.py` have been altered accordingly
3. The graph designer now has a switch for each node to set "Exportable" and if true, a string input for "fieldname". Note that at this time, changes via those widgets will not trigger a dirty state.
4. Adds NodeGroupView in `views/graph.py`, with a nodegroup url in `urls.py` and `javascript.htm`
#5473 
-   [ …
=> 5473 node exportable

arches/app/media/js/views/search.js, arches/app/search/elasticsearch_dsl_builder.py, arches/app/views/search.py
=> fix for search results count being limited to 10000 records, re #5404

arches/app/views/graph.py
removes unnecessary print statement
=> rm unneeded print statement in graph.py

arches/install/requirements.txt, arches/management/commands/es.py, arches/management/commands/packages.py, arches/setup.py
=> 5488 remove es install

arches/app/views/api.py, arches/app/views/auth.py, arches/management/commands/mobile.py
=> Updates sync to support tech upgrades

arches/app/views/api.py, arches/settings.py
=> extends geojson API to include related tile data

arches/app/models/migrations/5473_exportable_nodegroup_node_fieldname.py, arches/app/models/models.py
uses proper migration pattern for schema change
#5473 
=> edits migration to use django command rather than sql command, re #5473

arches/app/views/api.py
=> Changes call to collector back to mobile

arches/app/models/migrations/5473_exportable_nodegroup_node_fieldname.py, arches/app/models/models.py
=> sets null=True on NodeGroup exportable field, re #5521

arches/celery.py, arches/install/arches-templates/project_name/celery.py-tpl
=> Cleans up cruft. 

arches/app/datatypes/datatypes.py
=> removes geom view auto-update

arches/install/centos_core_setup.sh, arches/install/ci_install/arches_stop.sh, arches/install/ci_install/ci_ubuntu_xenial_setup.sh, arches/install/ubuntu_setup.sh
=> remove other instances of template_postgis_20 from shell scripts, re #5454

arches/management/commands/celery.py
=> Adds a management command to start celery worker

arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/views/graph.py
Fixes errors when exporting mapping files and exporting resource instances in csv format. re #5535
=> CSV export bug fixes

arches/app/models/resource.py, arches/app/utils/data_management/resources/formats/csvfile.py
Fixes descriptor indexing during standard package load (without -bulk) and when a user reindexes resources using the UI of the descriptor function config. re #5538
=> Fixes descriptor indexing

arches/app/datatypes/datatypes.py, arches/app/models/resource.py, arches/app/utils/data_management/resources/formats/csvfile.py
Removes STREAMLINE_IMPORT setting and removes cruft. re #5538
=> Descriptor indexing fixes

arches/app/views/api.py, arches/management/commands/mobile.py
Improves logging during collector sync process
=> Improve sync logging

tests/exporter/jsonld_export_tests.py, tests/importer/jsonld_import_tests.py
Fix name of import class to not collide with export class
#
=> Fix class name for Import tests

.vscode/settings.json, README.md, arches/__init__.py, arches/app/views/api.py, releases/4.4.3.md
Adds release notes and updates version number
=> 443 release prep

.stickler.yml
=> Raises max line length to 140

.stickler.yml, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/search/search.py, arches/app/utils/context_processors.py, arches/app/utils/data_management/resource_graphs/exporter.py, arches/app/utils/data_management/resources/formats/archesfile.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/formats/format.py, arches/app/utils/data_management/resources/importer.py, arches/app/utils/date_utils.py, arches/app/utils/geo_utils.py, arches/app/utils/module_importer.py, arches/app/utils/response.py, arches/app/views/auth.py, arches/app/views/concept.py, arches/app/views/resource.py, arches/app/views/tile.py, arches/install/arches-templates/project_name/datatypes/sample_datatype.py, arches/management/commands/packages.py, arches/management/commands/resources.py, tests/base_test.py, tests/models/graph_tests.py, tests/run_tests.py
changes all occurences of `!= None` and `== None` with `is not None` and `is None` respectively
#5555 
This is mostly needed to be in compliance with linter
=> 5555 is none

.stickler.yml
re-enables stickler property review: fail_on_comments to true
#
=> re-enables stickler property review: fail_on_comments to true

arches/app/tasks.py, arches/app/views/user_tasks.py
replaces print statements in task-related code with logger statements
refactors JSONResponse in user_tasks view
#5533 
in regards to PR #5550
=> 5533 updates to task pr

arches/app/media/js/views/components/search/search-export.js, arches/app/media/js/views/search.js, arches/app/search/search_export.py, arches/app/templates/views/components/search/search-export.htm, arches/app/utils/context_processors.py, arches/app/utils/data_management/resources/exporter.py, arches/app/views/search.py
Allows user to download csv if the total number of search results is below the search export limit. If the search export limit is exceeded, a zip file with results is saved to the file system. re #5545
=> Limits search export to SEARCH_EXPORT_ITEMS_PER_PAGE setting

arches/app/tasks.py
Creates a notification if a task utilizes the `update_user_task_record` or `log_error` follow-up tasks
#5563 
=> 5563 celery task notification

arches/app/datatypes/datatypes.py, arches/app/models/migrations/5475_update_geom_mv.py, arches/app/views/api.py, arches/settings.py
=> reintroduces geom materialized view

arches/app/media/js/views/components/search/search-export.js
Fixes issue with search export url not updating consistently. re #5545
=> Ensures search export url is updated when a user changes query

arches/app/datatypes/datatypes.py, arches/app/media/css/arches.css, arches/app/search/search.py, arches/app/search/search_export.py, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/app/views/resource.py, arches/app/views/search.py
Handles error when search limit is exceeded, improves error handling in datatypes, and fixes paginator error in related resources. re #5545
=> Fixes search export document limit error

tests/fixtures/jsonld_base/models/string_to_path_basic.json, tests/importer/jsonld_import_tests.py
Adds a very simple test that currently fails.
=> add simple failing test for string_to_path

arches/app/media/js/rdm.js, arches/app/media/js/viewmodels/alert-json.js, arches/app/media/js/views/graph/card-manager.js, arches/app/media/js/views/rdm/concept-report.js
=> Some js file linting

tests/fixtures/jsonld_base/models/test_2_complex_object.json, tests/importer/jsonld_import_tests.py
=> another complex test

arches/app/models/migrations/3713_unload_ontolgy.py
Wrap the reverse migration in a try block to avoid error using migrate using management command
#
=> Update the unload-ontology migration

arches/app/utils/data_management/resources/formats/rdffile.py, tests/importer/jsonld_import_tests.py
Test if we're a resource-instance as further disambiguation
=> add resource-instance test to rdffile

arches/app/media/css/arches.css, arches/app/models/models.py, arches/app/templates/navbar/graph-designer-menu.htm, arches/app/templates/views/components/search/search-export.htm, arches/app/templates/views/components/search/time-filter.htm, arches/app/templates/views/graph-designer.htm, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/graph-designer/node-form.htm
=> Ui updates

tests/fixtures/jsonld_base/models/nest_test.json, tests/importer/jsonld_import_tests.py
=> Rob more tests

arches/app/datatypes/datatypes.py, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/install/requirements.txt
Adds pyshp to requirements.txt and fixes error when saving None to a boolean node. re #5545
=> Adds pyshp to requirements.txt

arches/app/media/css/arches.css, arches/app/media/css/tree/tree.css, arches/app/templates/views/graph/graph-designer/node-form.htm
=> Ui styling updates

arches/app/search/search_export.py
=> Changes search import statement to prevent error on ubuntu. 

arches/app/media/js/views/mobile-survey-manager.js
=> Fixes missing jquery import in arches collector manager

arches/app/media/js/views/graph/graph-designer/graph-tree.js, arches/app/templates/views/graph/graph-designer/graph-tree.htm
=> add display of node ids in the graph designer, re #5108

arches/app/utils/data_management/resources/importer.py, arches/install/requirements.txt
=> Upgrades django and fixes file path parsing for relative paths in importer

arches/install/supervisor_celery_setup/my_proj_name-celerybeat.conf, arches/install/supervisor_celery_setup/my_proj_name-celeryd.conf, arches/install/supervisor_celery_setup/my_proj_name-supervisor.conf
=> adds config files for supervisord / celery setup, re #5667

arches/app/utils/data_management/resources/formats/rdffile.py, tests/importer/jsonld_import_tests.py
* Add `xsd:string` checking for literal types  (L427)
* Add check for `graphid` to prevent attempting to iterate over None (L296)
* Reimplement `validate_concept_in_collection()` to check URIs from identifier, per original algorithm  rather than label.
=> Fix validate_concept_in_collection

tests/exporter/datatype_to_rdf_tests.py, tests/views/auth_tests.py
=> band-aid fix for now for breaking tests (I commented them), re #5671

arches/app/datatypes/datatypes.py, arches/app/models/models.py, arches/app/search/search_export.py
adds `get_display_value` methods for datatypes: FileList and EDTF
#5617 
=> 5617 human readable vals to export

arches/app/media/css/arches.css, arches/app/templates/base-manager.htm, arches/app/templates/views/notifications-list.htm, arches/app/templates/views/user-profile-manager.htm
=> re: #5679 Ui notification styling

arches/app/templates/views/report-templates/default.htm
=> hides related resources cards in report by checking length, re #5217

arches/app/datatypes/datatypes.py, arches/app/search/search_export.py, arches/app/utils/data_management/resources/formats/shpfile.py, arches/app/utils/response.py
=> Fixes issues with shape export when column names do not match available data 

arches/app/search/search_export.py, arches/app/utils/data_management/resources/formats/shpfile.py
=> Fixes resource id and multiple shape type export in shapefile export

arches/app/models/graph.py
=> validates fieldname regardless of datatype, re #5641

arches/app/utils/response.py, arches/app/views/mobile_survey.py
Informs user that CouchDB is not available. re #5654
=> Provides feedback if a collector project fails to save

arches/app/datatypes/datatypes.py, arches/app/tasks.py
=> adds a task to handle refresh of materialized view, re #5602

arches/app/media/js/views/components/search/map-filter.js, arches/app/templates/javascript.htm, arches/install/package.json, arches/install/yarn.lock
=> Removes mathjs. 

arches/app/media/css/arches.css, arches/app/media/js/views/components/search/time-filter.js, arches/app/search/time_wheel.py, arches/app/templates/views/components/search/time-filter.htm
=> Adds loading indicator for time wheel

arches/app/media/js/views/components/search/search-export.js, arches/app/media/js/views/notifications-list.js, arches/app/models/models.py, arches/app/tasks.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/search/search-export.htm, arches/app/templates/views/notifications-list.htm, arches/app/views/notifications.py, arches/app/views/search.py
adds name field to searchExport, checks on frontend for celery and total search results against settings maximum before enabling email address field in search export, re #5651 
#
=> 5651 search export email field

arches/app/search/components/map_filter.py, arches/app/views/auth.py, arches/app/views/search.py
Fixes server error when pulling collector projects to a device. re #5508
=> 5508 collector sync error

arches/app/media/js/views/notifications-list.js, arches/app/utils/skos.py
changes time formatting for notification timestamp
#5695 
=> 5695 notification panel date fmt

arches/app/templates/views/components/search/search-export.htm, releases/5.x.md
Cleans up release testing markdown and removes geojson from search export options. re #5564
=> Cleans up release testing markdown

arches/app/models/migrations/5712_update_sys_setting.py, arches/app/utils/task_management.py, arches/app/views/resource.py
Handles for BrokenPipeError if celery check fails. Reattempts connection 3 times if connection fails. Also fixes KeyError when loading the edit history page. re #5728, #5738
=> 5712 export models

arches/app/media/css/arches.css, arches/app/templates/views/graph-designer.htm, arches/app/templates/views/graph/graph-designer/widget-configuration.htm, arches/app/templates/views/notifications-list.htm, arches/app/views/search.py
=> re: #5724 Designer ui updates

arches/app/utils/index_database.py
=> fix reindex of concepts when there are orphaned concepts in the db, re #5384

arches/app/media/js/viewmodels/map.js, arches/app/media/js/views/components/cards/map.js, arches/app/media/js/views/components/widgets/map.js, arches/app/models/migrations/5608_adds_map_card_configs.py, arches/app/templates/views/components/cards/map.htm, arches/app/templates/views/components/widgets/map.htm
=> adds support for map card and widget position configs

arches/app/models/concept.py, arches/app/utils/skos.py, arches/management/commands/packages.py
=> 5487 data import speedup

releases/5.x.md
=> further testing, fixes formatting for search export table

arches/app/media/css/arches.css, arches/app/media/css/tree/tree.css, arches/app/templates/views/graph/graph-designer/graph-tree.htm
=> re: #5760 Ui updates

arches/app/media/js/viewmodels/card-component.js, arches/app/media/js/views/components/cards/grouping.js, arches/app/media/js/views/components/workflows/new-multi-tile-step.js, arches/app/templates/views/components/cards/default.htm, releases/5.x.md
Fixes TileValidationError when shown in UI banner in resource editor
#5758 
=> 5758 tile validation banner error

arches/app/models/graph.py
=> includes duplicate fieldname in validation error of fieldname, re #5742

arches/app/utils/forms.py
- adds error handling/logging for exceptions triggered by initiating ReCaptchaField in auth process
- changes named kwarg ("attrs") to unnamed arg in ReCaptchaField
#5746 
=> 5746 captcha error signup

arches/app/models/graph.py, arches/app/templates/views/graph/graph-designer/node-form.htm
=> Minor capitalization changes in field name validation 

arches/app/models/resource.py, arches/management/commands/es.py
=> restore code that was removed due to a bad merge, re #4935

arches/app/datatypes/datatypes.py, arches/app/views/tile.py
Fixes issue with incorrect tile validation error messages. re #4375
Also fixes error when getting display value for the edtf datatype and lints.
=> Fixes unique constraint error message

arches/app/media/js/views/graph/graph-designer/card-tree.js, arches/app/models/graph.py, arches/app/templates/views/components/widgets/node-value-select.htm, arches/app/views/graph.py
Replaces default card name with node name when a user first updates a new node. re #4175
=> 4175 default card name

arches/app/media/js/viewmodels/node-value-select.js, arches/app/views/resource.py
Enables filtering of the node widget dropdown. re #5771
=> Node widget filtering

arches/management/commands/packages.py
=> Adds ontologies directory to newly created packages

README.md, releases/5.x.md
=> Updates release doc with upgrade info and updates Readme with version. 

arches/app/templates/views/graph/graph-designer/graph-tree.htm
Makes tool tips visible in top nodes of graph tree in graph desingner. re #5786
=> Makes tool tips visible in top nodes of graph tree

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/map.js, arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/templates/index.htm
Moves new index page to project template and fixes error in collector designer map re #5611 and #5790
=> 5611 moves new index pg to proj template

arches/app/media/css/arches.css
=> re: #5219Fix "no data" text position in reports

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/widgets/number.js
Fixes issue with numbers widget resetting formatted numbers to 0.0. re #4352
=> Fixes number formatting in number widget. re #4352

releases/5.0.0.md
testing done for provisional edits, graph designer
#
=> Galen stable/5.0.x

arches/management/commands/load_ontology.py
=> fixes syntax error with ontology load, re #5809

arches/app/media/js/views/graph-designer.js, arches/app/views/graph.py
=> ModelInactiveError not showing correctly

releases/5.0.0.md
=> additional testing for v5.0

arches/app/datatypes/datatypes.py
=> fix issue with the equality query in Adv. search against a numeric field

arches/app/datatypes/datatypes.py
=> checks for null filename in file-datatype tile, search export, re #5828

arches/app/media/css/arches.css
=> re: #5219 wrap long report labels

arches/app/views/main.py, releases/5.0.0.md
=> further testing for v5.0

arches/app/media/css/arches.css
=> re: #257 Ui updates

arches/app/media/js/viewmodels/concept-select.js, arches/app/media/js/views/components/datatypes/domain-value.js, arches/app/templates/views/components/datatypes/concept.htm
fixes advanced search filters that use concept-select and domain-val widgets to be clearable, have an empty option, respectively
#2848 
=> 2848 adv search concept filter

arches/app/media/js/viewmodels/concept-select.js, arches/app/media/js/views/components/datatypes/domain-value.js, arches/app/templates/views/components/datatypes/concept.htm
cherrypicking commits: 5dd0f4d360e7b1b5c7f79cbe65a49963c72f8ef5 and 9f76dacdd07be584df16cc69bf2b5fb837a45101 for fixes re #2848 
#
=> 2848 cherrypick adv search filters

.travis.yml
=> updates postgres to v12.0, postgis to v3.0, rm py2 tests

arches/app/templates/views/map-layer-manager.htm
=> adds condition for empty layer list in map layer manager, re #5756

.travis.yml, arches/app/templates/views/map-layer-manager.htm
=> 5756 cherrypick map layer mgr ui

arches/app/utils/data_management/resources/formats/rdffile.py, tests/importer/jsonld_import_tests.py
=> 4575 json ld context cache

.gitignore, arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/models/graph.py, arches/app/search/mappings.py, arches/app/search/search.py, arches/app/tasks.py, arches/app/views/graph.py
=> 5859 es node mapping

arches/app/search/mappings.py
=> increase the default limit for the number of fields in our resource index

Dockerfile, arches/install/init-unix.sql, arches/settings.py, docker-compose.yml, docker/entrypoint.sh, docker/settings_local.py
- Updated the Dockerfile for the new install requirements
- Altered settings.py to work around wsgi/gunicorn deployment not loading arches as a package (python3 relative imports do not work)
- Updated docker-compose.yml to allow for PROD or DEV deployments (does not include Rabbit MQ at this stage)
#5849
=> 5849 update docker for v5

arches/app/utils/data_management/resources/formats/rdffile.py, arches/settings.py, tests/importer/jsonld_import_tests.py
=> add cache invalidation to the JSON-LD context caching, re #4575

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/file.htm, arches/app/templates/views/graph-designer.htm
=> re:#5887 Ui enhancements to card designer

arches/app/media/js/bindings/c3.js
Fixes bug in chart loading. re #5881
=> Fixes bug in chart loading. re #5881

arches/app/media/js/bindings/c3.js
Removes chart disposal. re #5881
=> Removes chart disposal. re #5881

arches/app/media/css/arches.css, arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/views/components/file-workbench.htm
Formats file viewer side panel. re #5881
=> Formats file viewer side panel. re #5881

arches/templatetags/template_tags.py
https://github.com/archesproject/arches-her/issues/279
=> fixes mismatch in def name, re arches-her #279

arches/app/media/js/viewmodels/tile.js, arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/views/components/file-workbench.htm
Keeps the edit tab open when deleting tiles from the file viewer and adds a clear button to the file filter. re #5881
=> File viewer UI improvements

arches/app/media/css/arches.css, arches/app/templates/views/components/file-workbench.htm
=> re: afs #21 Afs ui updates

arches/app/media/css/arches.css, arches/app/templates/views/components/file-workbench.htm
Removes c3 css import and adds file count to the file manager. re #5881
=> File viewer file count

arches/app/media/js/bindings/scroll-to-file.js, arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/cards/file-renderers/imagereader.htm, arches/app/templates/views/components/file-workbench.htm, arches/settings.py
Persists filter when switching between tiles, allows user to select file renderer when there are multiple candidate renderers,  supports multiple side panel tabs for file renderers #5881
=> File viewer improvements re #5881

arches/app/datatypes/datatypes.py, arches/app/functions/primary_descriptors.py, arches/app/models/mobile_survey.py, arches/app/views/api.py, arches/settings.py, arches/urls.py
=> 5920 image endpoint

arches/app/media/js/views/components/cards/file-viewer.js, arches/app/views/api.py
Fixes incorrect assignment of resource instance id in the file viewer, and fixes import placement of tasks in the collector sync method.  re #5881, #5932
=> Undefined tasks sync error

arches/app/models/mobile_survey.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/install/requirements.txt, arches/settings.py
=> 5935 2way sync

arches/install/arches-templates/project_name/celery.py-tpl
Added Windows celery fix from #5916 to the arches project template.
Please could this also be merged into master for arches-her work.
=> 5947 bug arches project template celery fix for windows

arches/celery.py, arches/install/arches-templates/project_name/celery.py-tpl, arches/management/commands/es.py
Picks commits from @AJ-HistoricEngland 5.0.x PRs. re #5916, #5917
=> Resolves celery bug on windows and ES param bug, re  #5916 #5917 

arches/management/commands/es.py
Adds missing comma in es command
=> Adds missing comma in es command

arches/app/media/css/arches.css, arches/app/templates/views/components/cards/map.htm, arches/app/templates/views/components/cards/related-resources-map.htm, arches/app/templates/views/components/file-workbench.htm
=> re:#5952  Ui updates

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/photo-gallery.js, arches/app/media/js/views/components/cards/photo-gallery-card.js, arches/app/models/migrations/4751_adds_photo_gallery_card.py, arches/app/templates/views/components/cards/photo-gallery-card.htm, arches/app/templates/views/components/photo-workbench.htm
Moves photo gallery card from arches-her to core arches. re #4751
=> Adds photo gallery card. re #4751

arches/app/views/search.py
=> fixes typo, re #5956

arches/app/templates/javascript.htm
Updates path to dropzone in javascript.htm
=> Updates path to dropzone package.

arches/app/media/js/bindings/related-resources-graph.js
Fixes bug preventing related resources from loading. re #5609
=> Fixes bug preventing related resources from loading. re #5609

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/card-multi-select.js, arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/views/components/cards/file-viewer.htm, arches/app/templates/views/components/file-workbench.htm
re archesproject/arches-for-science-prj#45
=> Initial multi-tile select implementation

arches/app/models/graph.py, arches/app/views/graph.py
Saves only the modified node during when updating only one node in a graph. #5979
=> graph save performance

arches/app/media/css/arches.css
https://github.com/archesproject/arches-for-science-prj/issues/44
=> adds class for chart header in fileviewer, re afs #44

arches/app/media/css/arches.css, arches/app/templates/views/components/file-workbench.htm
=> re:# Ui enhancements

arches/app/media/js/views/components/cards/iiif-card.js, arches/app/media/js/views/components/iiif-annotation.js
=> improves manifest/canvas management in iiif card

arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/views/components/file-workbench.htm
Also changes 'select filtered' to 'select all' on selection button. re #5881
=> Makes only qualified loaders selectable in the file loader dropdown

arches/app/media/css/arches.css, arches/app/templates/views/components/file-workbench.htm
=> re: #5952 Ui enhancements

arches/management/commands/packages.py
Removes cruft and reduces length of load package function, re #5894
=> Minor refactor to business data import in load package command. re #5894

arches/app/templates/views/components/file-workbench.htm, arches/app/templates/views/components/widgets/file.htm
Fixes type in upload panel. re #6007
=> Fixes type in upload panel. re #6007

arches/app/media/css/arches.css, arches/app/media/js/bindings/color-picker.js
Fixes file viewer sidebar height with large images, removes duplicate css and lints the color-picker binding handler. re #86
=> Fixes file viewer sidebar height with large images

arches/app/datatypes/datatypes.py
=> add get_search_terms method for FileList datatype, re #5801

arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/views/components/file-workbench.htm, arches/app/templates/views/components/widgets/file.htm
Updates file type config text, re #6013
=> Updates file type config text, re #6013

arches/app/templates/views/components/map-widget-editor.htm
Adds missing space between the card and edit header in the map widget.
=> Adds missing space between the card and edit header in the map widget.

arches/app/media/js/views/components/cards/file-viewer.js
Throttles tile save requests submitted via dropzone. re #6047
=> Allow for a longer pause between file saves. re #6047

arches/app/media/css/arches.css
=> iiif gallery enhancements

arches/app/media/css/arches.css, arches/app/media/js/views/components/cards/file-viewer.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/file-workbench.htm, arches/app/utils/zip.py, arches/app/views/tile.py, arches/urls.py
Zips selected files and downloads zip, re #6048
=> Allows users to download selected files from file viewer, re #6048

arches/app/media/js/viewmodels/node-value-select.js
=> Fixes filtering bug in node to node dropdown.

arches/app/media/js/viewmodels/card.js
Fixes persistent dirty flag on cards when widgets have default values. re #6052
=> Fixes persistent dirty flag on cards, re #6052

arches/app/media/js/views/components/iiif-viewer.js, arches/app/views/api.py
=> uses contains to query manifests

arches/app/media/js/views/components/iiif-viewer.js, arches/app/views/api.py
=> adds paging to iiif manifest selection

arches/app/media/js/views/components/iiif-viewer.js, arches/app/views/api.py
=> filters on description and label

arches/app/media/js/views/components/iiif-viewer.js, arches/app/templates/views/components/iiif-viewer.htm
=> expands gallery by default, collapses on canvas click

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-viewer.htm
=> adds manifest details information to iiif component

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-viewer.htm
=> improves details styles

arches/app/media/js/views/components/iiif-viewer.js
=> fixes issue with iiif canvas not resizing properly

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/card-component.js, arches/app/templates/views/components/iiif-annotation.htm
=> adds button to add new annotation to card

arches/app/media/js/views/components/cards/iiif-card.js
=> resets iiif card state after delete of last tile

arches/app/media/js/viewmodels/card-component.js, arches/app/media/js/views/components/cards/iiif-card.js, arches/app/media/js/views/components/iiif-viewer.js
=> maintains iiif state on save of new tile

arches/app/media/css/arches.css, arches/app/media/js/views/components/iiif-viewer.js, arches/app/templates/javascript.htm, arches/install/package.json, arches/install/yarn.lock
=> adds fullscreen control to iiif component

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/iiif.js, arches/app/templates/views/components/widgets/iiif.htm
=> adds report view for iiif annotations

arches/app/media/css/arches.css
=> improves iiif report styles

arches/app/media/js/views/components/widgets/iiif.js
=> zooms iiif report to annotations

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-annotation.htm, arches/app/templates/views/resource/editor.htm
=> adds add new button to card header

arches/app/media/js/views/components/iiif-viewer.js
=> selects canvas on manifest update

arches/app/media/js/views/components/cards/iiif-card.js, arches/app/media/js/views/components/iiif-viewer.js
=> preserves iiif gallery state

arches/app/datatypes/datatypes.py
Fixes error preventing provisional users from saving iiif annotations. re #6049
=> Fixes error preventing provisional users from saving iiif annotations

arches/app/media/css/arches.css, arches/app/templates/views/search.htm
#5044 
archesproject/v5_demo#7
=> 5044 saved search css

arches/app/media/css/arches.css, arches/app/templates/views/graph/graph-designer/node-form.htm, arches/app/templates/views/resource/permissions/permissions-manager.htm
=> re: #6126 Ui enhancements

arches/app/media/css/arches.css, arches/app/media/js/models/graph.js, arches/app/templates/views/graph/graph-designer/graph-settings.htm, arches/app/templates/views/graph/graph-designer/node-form.htm
=> 2347 node designer ui

arches/app/models/resource.py, arches/app/models/tile.py, arches/app/search/mappings.py, arches/app/utils/permission_backend.py, arches/app/views/resource.py, arches/app/views/search.py
Filters search results by user instance access. re #2725
=> Enforce instance permissions in search #2725

arches/app/media/css/arches.css, arches/app/media/js/views/resource/editor.js, arches/app/media/js/views/resource/permissions-manager.js, arches/app/templates/javascript.htm, arches/app/templates/views/resource/editor.htm, arches/app/templates/views/resource/permissions/permissions-manager.htm, arches/app/utils/permission_backend.py, arches/app/views/resource.py, arches/urls.py
Adds ability to return an instances permissions back to normal access re #6122
=> Allows reset to normal resource instance access permissions re #6122 

arches/app/media/js/views/resource/permissions-manager.js
Clears resource instance permissions for a user when 'no access' is selected. re #6123
=> Clears permissions when 'no access' is selected. re #6123

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/resource/editor.htm
=> re:#6136 Ui fixes

arches/app/media/js/views/resource/permissions-manager.js, arches/app/models/resource.py, arches/app/templates/views/resource/editor.htm, arches/app/templates/views/resource/permissions/permissions-manager.htm, arches/app/utils/permission_backend.py, arches/app/views/resource.py, tests/permissions/permission_tests.py
Updates resource index after all users have been restricted or permitted access to resources. re #6122, #6134
=> Reindexes resource after access changes for all users re #6122, #6314

arches/app/media/js/views/resource/permissions-manager.js, arches/app/templates/views/resource/editor.htm, arches/app/templates/views/resource/permissions/permissions-manager.htm, arches/app/views/resource.py
Makes superuser the creator for instances that have no creator, re #2725 
Also makes resource permission labels translatable.
=> Makes superuser the creator for instances that have no creator, re #2725

arches/app/media/js/views/components/search/search-results.js, arches/app/media/js/views/resource/permissions-manager.js, arches/app/media/js/views/search.js, arches/app/templates/views/components/search/search-results.htm, arches/app/views/resource.py, arches/app/views/search.py
Improves management of instance permission dirty state and ensures instance creators have instance access. re #2725
=> Resource permission UI dirty state

arches/app/models/tile.py
Resolves issue with updating tile values when a tile's node is directly off the model root. Also corrects bug with function methods not getting called. re #6103
=> Tile value update bug.

arches/app/media/css/arches.css, arches/app/views/resource.py
=> Fixes issues with indexed instances missing graphids and descriptors

arches/app/media/css/arches.css
migrates workflow-specific css to core arches
#
=> migrates css from arches-her to core arches for workflows

arches/app/templates/views/components/map-popup.htm, arches/app/utils/permission_backend.py, arches/app/views/api.py, arches/app/views/resource.py, tests/views/api_tests.py
=> 6111 api resource inst perm

arches/app/media/js/models/card-widget.js, arches/app/media/js/viewmodels/map.js
Resolves minor errors in card designer and adds min and max zoom levels to the map viewmodel so that system settings zoom settings apply where the map viewmodel is used. re #6038
=> Min and max zoom settings, re #6038

arches/app/media/js/views/components/search/search-result-details.js, arches/app/media/js/views/components/search/search-results.js, arches/app/templates/views/components/search/search-result-details.htm, arches/app/views/resource.py
=> refactors and optimizes details search component

arches/app/media/js/views/components/search/search-result-details.js
=> fix for search details report

arches/app/media/js/views/components/search/search-result-details.js, arches/app/media/js/views/components/search/search-results.js, arches/app/views/resource.py
=> optimizes search details component

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-viewer.htm
=> re:#6165 Iiif filter ui

arches/app/functions/base.py, arches/app/models/tile.py
=> 6172 post save tile

arches/app/media/js/views/components/workflows/new-tile-step.js
=> add check for hiddenNodes on card load, re #6187

arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/new-tile-step.js, arches/app/utils/data_management/resource_graphs/exporter.py
Renames getStateProperties to defineStateProperties in workflow steps re #6192
=> Renames getStateProperties to defineStateProperties in workflow steps

arches/app/media/css/arches.css, arches/app/templates/views/components/photo-workbench.htm, arches/app/templates/views/components/workbench.htm
=> re:#6194 photo workbench ui fix

arches/app/templates/views/components/workbench.htm
=> re: #6194 Height fix

arches/app/media/js/utils/resource.js, arches/app/search/elasticsearch_dsl_builder.py, arches/app/search/search.py, arches/app/views/search.py
=> add utility to lookup resource data from elastic search, re #6198

arches/app/media/js/views/components/workflows/new-tile-step.js
https://github.com/archesproject/arches-for-science-prj/issues/147
=> Afs 147 phys wkflw

arches/app/media/js/utils/resource.js
=> 6198 resource lookup utility

arches/app/media/js/views/components/workflows/new-tile-step.js
Fixes the creation of a new instance with every step in a workflowe #6210
=> Fixes the creation of a new instance with every step in a workflow.

arches/app/media/js/views/components/workflows/new-tile-step.js
Ensures resourceid gets set on workflow step refresh. re #6217
=> Ensures resourceid gets set on workflow step refresh. re #6217

arches/app/media/css/arches.css
=> re: #6215 Update inline editor position

arches/app/media/js/views/components/workflows/new-tile-step.js
=> Uses resource id off the state if params.resourceid is not available

arches/app/models/graph.py, arches/app/views/api.py, arches/app/views/graph.py, arches/settings.py
Removes caching of valid ontology classes that could be the cause of #6221
=> Removes caching that could be causing #6221

arches/app/media/css/arches.css, arches/app/templates/views/components/cards/default.htm, arches/app/templates/views/components/search/search-results.htm
=> #6229 search provisional ui

arches/app/models/mobile_survey.py, arches/app/views/api.py
=> 6255 collector sync silent fail

arches/install/requirements.txt
upgrade latest django 2, celery, and celery-results-backend
#
=> Dependency upgrade

arches/app/media/js/models/node.js, arches/app/templates/views/graph/graph-designer/node-form.htm
Adds node description to the node configuration UI in graph settings. re #5165
=> Adds node description to the node configuration UI in graph settings

arches/app/datatypes/datatypes.py, arches/app/models/models.py, tests/fixtures/jsonld_base/models/4564-referenced.json, tests/importer/jsonld_import_tests.py
=> fixes for 6182

arches/app/views/resource.py
=> 6279 require user to be in the ResourceEditor group to access the resource editor page

arches/app/media/js/viewmodels/resource-instance-select.js
=> fix card preview bug with new resource-instance datatype, re #6182

arches/app/datatypes/datatypes.py
Prevents none from getting added to the tiledata array. re #6284
=> Prevents none from getting added to the tiledata array. re #6284

arches/app/views/api.py
Instance Permission API now respond with true/false based on the permission parameter in the api request ("view_resourceinstance", "change_resourceinstance","delete_resourceinstance")
#
=> Instance Permission API returns only true/false 

arches/app/datatypes/datatypes.py
Handles for cases when node value is None in append_to_document method, re #6284
=> Handles for cases when node value is None, re #6284

arches/app/media/js/views/components/datatypes/resource-instance.js, arches/app/templates/views/components/datatypes/resource-instance.htm
=> fix resource-instance config to use root node, re #6182

arches/app/functions/base.py, arches/app/models/tile.py, arches/install/arches-templates/project_name/functions/sample_function.py, arches/install/arches-templates/project_name/media/js/views/components/functions/sample-function.js, arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/templates/views/components/functions/sample-function.htm
Removes cruft and outdated code from the project template.
=> Project template cleanup

arches/app/views/auth.py, arches/urls.py
=> add endpoint for server settings, re #6294

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/views/api.py
Add create/append functionality to nodeValue endpoint
#
=> Add create/append functionality to nodeValue API endpoint

arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> fix issue with report and the new resource-instance datatype, re #6182

arches/app/models/migrations/6190_adds_group_map_settings_model.py
=> Fixes table name in GroupMapSettings migration.

arches/app/views/search.py
Fixes search query to filter no access instances. re #6314
=> Fixes bug in search permissions

arches/app/views/graph.py
=> fix nodegroup editing bug in update node, re #6312

arches/app/media/css/arches.css
Fixes position of advanced search clear button. re #6336
=> Fixes position of advanced search clear button. re #6336

arches/app/models/mobile_survey.py
=> add graphid to resource instance options so we can add default ontology properties

arches/app/datatypes/datatypes.py
Change logic for API append, to match geojson format
=> Change logic for API append, to match geojson

arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/formats/csvfile.py
=> fixes csv import and export for new RI datatypes, re #6364

arches/app/media/js/models/node.js, arches/app/models/graph.py, arches/app/templates/views/graph/graph-designer/graph-settings.htm, arches/app/views/graph.py
Replacement PR for #6305.  
Instead of putting branch id in a separate field, just make sure to copy the description around between nodes and put it in there.
Also exposes the slug property to admins for graphs.
#6299 #6300
=> Copy description of branch, expose model slug to admin

arches/app/media/css/arches.css, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/templates/views/components/datatypes/resource-instance.htm, arches/app/templates/views/components/search/advanced-search.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm, arches/app/templates/views/search.htm
=> re: #6333 Resource Instance ui fixes

arches/app/models/graph.py, arches/app/templates/views/graph/graph-designer/graph-settings.htm
Ensures error is thrown in the graph designer if slug is a duplicate. re #6071
=> Ensures graph validation error is thrown when slug is a duplicate

arches/app/media/js/views/components/search/advanced-search.js, arches/app/media/js/views/graph/graph-manager/branch-list.js, arches/app/views/base.py
Sort `createable_resources` by model name, to improve UI of "create new resource" left hand menu, and `/resource` card list.
Sort models in advanced search facet list by name, and sort cards per model by name.
#5433 
Improves #6332 (though would still be much better if it was same order as card list)
=> Alpha-sort models, cards in lists

tests/views/command_line_tests.py
=> standardize variable name, re #5923

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/install/arches-templates/project_name/media/js/views/components/functions/sample-function.js
Removes unused code, re #6185, #6094, #6113
=> Removes unused code

arches/app/datatypes/concept_types.py
=> fix concept referenced in primary descriptor being deleted, re #5957

arches/app/views/graph.py
Sets slug to None when exporting branch. re #6071
=> Sets slug to None when exporting branch. re #6071

arches/app/search/search_export.py
re #6380
the `create_zip_file` method takes 2 arguments
=> fix search export, re #6380

tests/importer/datatype_from_rdf_tests.py
=> fix broken build, re #6386

arches/install/arches-templates/project_name/templates/index.htm
Fix the typo in one of the the image links for landing page
#
=> Fix a typo in img link in the project template

arches/app/datatypes/datatypes.py
Supports reimport of exported csv files when csv contains resource instance relationship tile values re #6390
=> Supports reimport of exported csv files re #6390

arches/app/views/api.py
=> use consistent return object during sync operation, re #6395

arches/app/views/api.py
when requesting a single resourceinstance json via the API, if args: `?format=json&disambiguate=true` are supplies, the json response will contain a disambiguated dictionary of node names with the respective tile values, along with the serialized resource instance data where its resourceinstanceid is the key.
#6030 
* …
=> 6030 node names api

arches/app/templates/views/map-layer-manager.htm
Moves no overlays message into trans tags, re #5756
=> Moves no overlays message into trans tags, re #5756

arches/management/commands/packages.py
Adds command to export all models and branches, re #6406
=> Adds command to export all models and branches, re #6406

arches/app/search/search_export.py, arches/app/utils/data_management/resources/formats/rdffile.py
=> Deletes cruft

arches/app/media/css/arches.css
=> #6405 ui fixes

arches/app/views/api.py
=> fix resource api endpoint to not wrap object in a keyed dictionary

arches/app/models/tile.py, arches/app/templates/javascript.htm
=> add endpoint for update node value, wrap all of tile.save in a transaction

arches/app/media/css/arches.css, arches/app/templates/views/components/datatypes/resource-instance.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> #6420 ri ui fixes

arches/app/utils/data_management/resources/formats/rdffile.py, tests/importer/jsonld_import_tests.py
Fixes and tests for fix when POSTing JSON-LD data
#6407
=> re #6407 update tests, fix rdffile jsonld reader

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/cards/file-renderers/pdfreader.js, arches/app/templates/views/components/cards/file-renderers/imagereader.htm, arches/app/templates/views/components/cards/file-renderers/pdfreader.htm, arches/settings.py
Adds a pdf reader as a core file viewer loader re #6240
=> Adds pdf reader re #6240

arches/app/media/css/arches.css, arches/app/media/js/views/resource/editor.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/media/js/views/search.js, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> 6182 related resources ui

arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> show editor link instead of report link in resource instance ui

arches/app/media/css/arches.css, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> #6434 ui fixes

arches/app/datatypes/datatypes.py, arches/app/models/concept.py, arches/app/models/migrations/0005_4_0_1.py, arches/app/models/mobile_survey.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/models/tile.py, arches/app/search/mappings.py, arches/app/search/time_wheel.py, arches/app/utils/data_management/resources/remover.py, arches/app/utils/index_database.py, arches/app/utils/permission_backend.py, arches/app/views/concept.py, arches/app/views/map.py, arches/app/views/resource.py, arches/app/views/search.py, tests/base_test.py, tests/models/resource_test.py, tests/models/tile_model_tests.py, tests/permissions/permission_tests.py, tests/views/resource_tests.py, tests/views/search_tests.py
=> 6432 fix unit tests

arches/app/datatypes/datatypes.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py
Add support for the time and timezone to date data type, re #5669 #6043  
Expand the datetime data type to support time and timezone including validation and es indexing
Also, accepting the collector datetime as it is
=> date timezone import, re #5669 #6043

arches/app/models/graph.py
Read the cssclass onto the model
#6441
=> re 6441 load cssclass

arches/management/commands/packages.py
Updates the export_business_data command to export data for all resource models. #6464
Also removes some cruft and prevents and error when saving a filelist node that has a None value. re #6392
=> Export data for all resource models

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/cards/file-viewer.js
Improves identification of file type in file viewer and sets default renderer on import. re #6240
=> Improves identification of file type in file viewer and sets default renderer on import

arches/app/models/card.py, arches/app/models/graph.py, arches/app/views/api.py, arches/app/views/user.py
Update get_cards logic when serializing to exclude is_editable properly when it is called.
Slight improvement on performance when report view is created
=> 6319 card editable reportview

arches/app/datatypes/datatypes.py
=> Change es mapping for number datatype, re #6335

arches/app/datatypes/datatypes.py, arches/app/media/js/viewmodels/file-widget.js, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/views/components/cards/related-resources-map.js, arches/app/media/js/views/resource/related-resources-manager.js, arches/app/views/api.py, arches/urls.py
Updates the related resource map card to support datatype changes. re #6444
Also prevents and error in the FileList widget if a file does not have an extension.
=> Updates the related resource map card to support datatype changes. re #6444

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/models/resource.py, arches/app/models/tile.py
Deletes the indexed relationship in ElasticSearch if a resource instance or tile participating in the relationship is deleted. re #6453, #6421
=> Deletes indexed relationship when corresponding resource tile/instance is deleted

arches/app/templates/index.htm, arches/app/templates/views/resource/report.htm, arches/app/views/main.py, arches/app/views/resource.py, arches/install/arches-templates/project_name/templates/index.htm
Update the report footer to use dynamic Arches version number
The footer is currently displaying Arches 4 statically. This update changes the version number to be dynamic.
#6446 
UI changes seen here: https://ibb.co/MZz14m7
Do we need to add tests for non-logic changes?
=> update footer to use dynamic arches version

arches/app/media/js/viewmodels/card.js, arches/app/media/js/viewmodels/tile.js, arches/app/media/js/viewmodels/widget.js, arches/app/templates/views/components/cards/default-card-report.htm
=> adds support for copying tile data

arches/management/commands/packages.py
Replace the unsafe characters in a business data export filename, re #6378 
Special characters except (' ', '.', '_', '-') will be replaced by hyphen (-).
ie. Actor/Actress or Actor\Actress --> Actor-Actress
This resolves the error when trying to export business data from a model whose name has special characters.
* …
=> Replace special chars in a model name when exporting data, re #6378

arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/views/components/cards/related-resources-map.js, arches/app/templates/views/components/cards/related-resources-map-popup.htm, arches/app/templates/views/components/cards/related-resources-map.htm, arches/app/templates/views/components/related-resources-map-editor.htm
Adds support for the geometry editing in the related resource map card. re #6444, #5967
=> Adds support for the geometry editing in the related resource map card. re #6444

arches/app/datatypes/datatypes.py
=> fix save error with resource instance datatype when the graph doesn't specify and ontology

arches/app/views/graph.py
Minor fix for failing test, re #6310
=> Fixes failing test

arches/app/datatypes/datatypes.py
Resolves errors when saving and deleting tiles with related instance nodes. re #6507
=> Resolves errors when saving and deleting tiles with related instance nodes.

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/number.htm
Add the None where number value is missing, re #6511 
#6511 
Fix the node label and value do not match in some cases
=> The node label and value mismatch, re #6511 

arches/app/models/models.py, arches/app/models/resource.py, arches/app/utils/index_database.py, arches/app/views/concept.py
use SearchEngineInstance not Factory.create()
Towards #6518 
=> 6518 reduce se instances

arches/management/commands/packages.py
Actually show the errors that occur during loading.
#6418 
=> re 6418 report graph load errors

arches/app/utils/data_management/resources/formats/rdffile.py
Trivially split write_resources into build_json and write_resources, to give access to the JSON for other internal purposes without writing out a record.
#6433 
=> re 6433 Split write_resources

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/views/map.py
Cherry picked from https://github.com/archesproject/arches/pull/6515 from @AJ-HistoricEngland
=> performance fix added index scan via nodegroupid

arches/app/search/mappings.py
Increases the indexing limits for nested documents and fields
#6527
=> re 6527 increase index limits

arches/app/models/graph.py, tests/models/graph_tests.py
Allow an ontology that has multiple range classes to be valid
#6456
=> re #6456 allow multiple range classes

arches/app/media/js/viewmodels/card-component.js, arches/app/media/js/viewmodels/report.js, arches/app/media/js/viewmodels/widget.js, arches/app/templates/views/components/cards/default-card-report.htm, arches/app/templates/views/components/widgets/base.htm, arches/app/templates/views/report-templates/default.htm, arches/app/templates/views/report-templates/tabbed.htm
=> Allow user to hide 'None' values and keys in reports, re #5214

arches/app/templates/views/report-templates/default.htm
Add a block around the title bar so it can be overridden in projects, per discussion with @chiatt on slack
#
=> re @chiatt make report title bar a block

arches/app/media/js/viewmodels/report.js
Re discussion in slack, lacking a way to configure the default, flip the "hide empty nodes" switch in the default report template to true
#
=> re @chiatt flip default to hide empty

arches/app/datatypes/datatypes.py, arches/app/functions/primary_descriptors.py, arches/app/models/tile.py
Introduce a DataTypeFactoty as a class variable to be able to reuse the factory throughout the tile.
Expect to see some improvement such as loading a package.
=> Improve datatype factory used in tile, re #6289

arches/app/templates/views/components/cards/default-card-report.htm, arches/app/templates/views/report-templates/default.htm
Hide subcards when they have no data
Further towards #5214 
=> re 5214 hide empty sub-cards

arches/app/templates/views/mobile-survey-designer.htm
=> fixes survey map widget bug

arches/app/templates/views/report-templates/default.htm
Fixes template error when rendering reports without related resources #6567
=> Fixes bug when rendering reports without related resources #6567

arches/app/templates/views/components/cards/default-card-report.htm
Fixes issue with missing tile values in a card report in cards with cardinality n. re #6570
=> Fix issue with missing data in card reports. re #6570

arches/app/media/js/models/card.js, arches/app/media/js/views/graph/graph-designer/graph-tree.js
This changes card model behavior to remove orphaned widgets.
#6524 
Correct delete / display behavior occurs for collector and non-collector nodes. The grouping card appears to be borked on master again ( argh! ) so I want to fix that before further developing this branch. It is important to test the delete/display behavior for grouping cards.
=> Deleting non-collector nodes now deletes widget, need to test for side effects

arches/app/templates/views/components/iiif-viewer.htm
=> includes title of canvas on hover, re #6239

arches/app/templates/views/components/cards/default-card-report.htm
Fixes knockout error in card when hideEmptyNodes is not observable re #6570
=> Fixes knockout error in card when hideEmptyNodes is not observable.

arches/management/commands/mobile.py
Iterates through datatypes after mobile sync and calls `after_update_all` to refresh geojson materialized view.
#6578 
=> Mobile sync mv refresh fix

arches/app/templates/views/components/workflows/final-step.htm, arches/app/templates/views/components/workflows/new-multi-tile-step.htm
=> add missing i18n tags

arches/app/media/css/arches.css
=> re: #6584 Small ui fixes

arches/app/utils/context_processors.py
re #6591 for instructions on how to reproduce
=> fix bug with adding a user without a group

arches/app/media/css/arches.css, arches/app/media/css/main.css, arches/app/templates/rdm.htm
=> re: #6593 ui fixes

arches/app/templates/login.htm, arches/app/templates/registration/password_reset_form.html, arches/app/templates/signup.htm
Remove or fix the links to arches-project webpage in password-reset, password-create, login webpages, re #5745 
#5745
=> remove not working arches links, re #5745

arches/app/views/auth.py, arches/urls.py
=> fix password reset form bugs, re #6595

arches/app/models/models.py, arches/app/models/resource.py
=> 6398 instance permissions

arches/app/templates/views/components/widgets/base.htm
The report now shows grouped widgets.
UI before: https://ibb.co/zndvpyn
UI after: https://ibb.co/ZBFJcZr
#6589 
UI before: https://ibb.co/zndvpyn
UI after: https://ibb.co/ZBFJcZr
=> grouping cards now display child widgets

arches/app/media/js/views/components/search/search-results.js
This adds existence logic to two methods, allowing the component to be reused in afs
#
=> Adjust search-results component

arches/app/media/css/arches.css, arches/app/media/js/views/components/search/term-filter.js, arches/app/media/js/views/search.js, arches/app/templates/views/search.htm
Add a reset button to clear all the filters applied in search template, re #6542 
#6542 
=> Add a reset button to clear all search filters, re #6542

arches/app/media/js/views/components/search/advanced-search.js, arches/app/media/js/views/search.js, arches/app/templates/views/search.htm
Add a button to clear all the filters applied, re #6542 
Also, the clear() methods for some filters implemented.
#6542 
=> clear all search filters, re #6542

arches/app/media/js/bindings/term-search.js, arches/app/media/js/views/components/search/advanced-search.js
Add a tag to search page indicating advanced search is applied, re #6541 
#6541 
=> Add "advanced search" tag in the search, re #6541

arches/app/datatypes/base.py
in the rare case that on tile save, more than one provisional edit exists for a given user *and* no authoritative data exists, an exception will be raised and logged that the provisional tile was invalid
fixes #5032 
=> 5032 prov edit

arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> update resource instance component, re #6632

arches/app/media/js/views/components/search/base-filter.js, arches/app/media/js/views/components/search/provisional-filter.js, arches/app/media/js/views/components/search/related-resources-filter.js, arches/app/media/js/views/components/search/resource-type-filter.js, arches/app/media/js/views/components/search/search-result-details.js, arches/app/media/js/views/components/search/search-results.js, arches/app/templates/views/components/search/search-results.htm
Allows a developer to identify those components that are required for a search component to load properly. re #6637
=> Ensures required filters load for search component re #6637

arches/app/media/js/views/search.js
Removes hard-coded filter names from filtersApplied computed. re #6542
=> Removes hard-coded filter names from filtersApplied computed. re #6542

arches/app/media/js/views/components/notification.js, arches/app/media/js/views/notifications-list.js, arches/app/tasks.py, arches/app/templates/views/components/notification.htm, arches/app/templates/views/notifications-list.htm, arches/app/views/notifications.py, arches/management/commands/packages.py
- Decouples notification component from notifications-list
- Messages are now formed in the backend and passed front
UI seen here: https://ibb.co/X3pMWDP
#6184 
=> Create notification component

arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/viewmodels/map.js, arches/app/templates/views/components/map-popup.htm
fixes map card viewmodel and template to support generic overlays
=> allows for selection of non-arches layers in map card re: #6647

arches/app/media/js/viewmodels/report.js, arches/app/media/js/views/resource/report.js, arches/app/templates/views/resource/report.htm, arches/app/views/resource.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py
Add a setting whether hide the empty node in the report or not in the settings.py, re #6622 
#6622 
=> Add setting to hide empty node in report, re #6622

arches/app/media/js/viewmodels/map.js, arches/app/media/js/views/search.js, arches/app/templates/views/components/map-popup.htm, arches/app/templates/views/search.htm
Moves permission logic from template to view model and handles for error when permissions are not a JSON string. re #6659
=> Moves permission logic from template to view model re #6659

arches/app/search/base_index.py, arches/app/search/components/search_results.py, arches/management/commands/packages.py
Removes check for absolute path when loading related resources because relative paths are supported.
=> Removes check for absolute paths when loading related resources

arches/app/media/js/viewmodels/concept-select.js, arches/app/models/concept.py
=> use localized concepts in the dropdown, re #6679

arches/app/media/js/views/graph-designer.js, arches/app/templates/navbar/graph-designer-menu.htm
=> add mapping file link, re #6683

arches/app/datatypes/datatypes.py, arches/app/tasks.py, arches/management/commands/add_test_users.py, arches/management/commands/packages.py
Adds test users to package load when dev flag is used, allows package developers to include 'post sql' which runs after the package is loaded, and refreshes the materialized view after the package load is complete.
=> Adds test users to package load when dev flag is used

arches/app/templates/views/components/widgets/base.htm, arches/app/templates/views/components/widgets/number.htm, arches/settings.py
It resolves the issue of consider 0 as null value in number report template, re #6685 
The fix will show zero in report instead of None and does not hide as null value when Hide_Null_Value = True
#6685 
=> Showing zero in report properly, re #6685

arches/app/datatypes/datatypes.py, arches/settings.py
=> Add get_display_value function to date datatype, re #6696

arches/app/media/js/views/components/widgets/number.js, arches/app/templates/views/components/widgets/base.htm, arches/app/templates/views/components/widgets/number.htm
Fix the bug that the report does not show the numbers formatted as strings, re #6685 
#6685 
=> Return number value as string for report, re #6685

arches/app/datatypes/datatypes.py
When an integer is entered to the number data type node, the type will remain the same, re #6693 
instead of being transformed into float
#6693 
=> Add the logic to retain integer type, re #6693

arches/app/templates/base-manager.htm
=> remove hardcoded plugin name, re #6705

tests/fixtures/data/csv/required_child_node_import.mapping, tests/fixtures/data/csv/resource_export_test.mapping, tests/fixtures/data/json/cardinality_test_data/target.json
Fix duplicate node names in the test package, re #6700
#6700 
=> Fix duplicate node name in test package, re #6700

arches/app/datatypes/datatypes.py
Checks if the value is an empty string for number node before transforming it into number while saving or importing numbers, re #6693 
#6693 
=> Check if empty sting before transforming into numbers, re #6693

arches/app/models/migrations/6481_add_resourceinstance_graphid.py, arches/app/models/models.py
=> Fixes migration 6481

arches/app/media/js/viewmodels/map.js
=> 6713 cbyrd map component track center long and lat

arches/management/commands/es.py
adds reindex_database ES command
#6720 
=> add reindex_database es command #6720

arches/app/models/migrations/5967_make_target_layer_configurable.py
=> Fixes migration dependency

arches/app/media/js/viewmodels/resource-instance-select.js
Default ontologies are now loaded in the resource editor
#6731 
=> default ontologies now load in resource editor #6731

docker-compose-test.yml, docker-compose.yml, docker/Readme.md, docker/entrypoint.sh
Removed obsolete `DJANGO_REMOTE_DEBUG` variable from compose files and entrypoint.
Update Readme accordingly.
#5179 
-   [x] I have added necessary documentation (if appropriate)
=> #5179 Remove obsolete DJANGO_REMOTE_DEBUG variable && Update Readme

arches/app/datatypes/datatypes.py
Fix issue with import of domain-value-list datatype from csv.
#
=> Add transform_value_for_tile function to domain-list datatype.

arches/app/views/api.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/management/commands/kibana.py, arches/management/commands/packages.py, arches/settings.py, arches/urls.py
fixes #6735 
To test this you should first update your Elasticsearch to version 7.9, then you should install Kibana version 7.9
Then, you'll need to edit the config/kibana.yml by adding these configs:
server.basePath: "/kibana"
server.rewriteBasePath: true
Then start Kibana
Then install the USDSSC package.  After the package loads you should be able to see the kibana dashboard in the site.
=> working load of Kibana objects during package load, re #6735

arches/app/media/js/views/resource/permissions-manager.js, arches/app/utils/permission_backend.py, arches/app/views/resource.py
Interface to manually set resource instance permissions now shows correct permissions for each user/class.
#6777 
=> update available permission options 

arches/app/utils/permission_backend.py
Added a check to get_editable_resource_types so that unprivileged users no longer pass.
#6781 
=> hide edit button for unprivileged users

releases/5.1.0.md
Adds note regarding unique node name constraints
=> Adds notes about unique name constraints

arches/app/templates/views/graph/graph-designer/node-form.htm
Limits shapefile field names to 10 characters. re #6812
=> Limits shapefile name to 10 characters. re #6812

arches/management/commands/kibana.py
=> fix override flag when loading kibana objects, re #6817

arches/app/models/resource.py
=> fixes tile save when multiple custom indexes are specified, re #6840

.travis.yml
=> Travis CI: Test on Python 3.9

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/install/requirements.txt
Refactors creation of most datatype error messages with a function on the base datatype and adds localization support for datatype error messages. re #6842
=> Cleans up / localizes datatype validation error messages. re #6842

arches/app/media/js/models/report.js
Fix the bug the related resource info button not working, re #6762 
The check for a necessary property was added.
#6762 
=> Fix the related resource info button, re #6762

arches/app/media/js/models/report.js
related resource reports now correctly reference instances of the same resource. Also the changes made resolve #6762 
#6847 #6762 
=> Related Resources report now references instances of self resource model

arches/app/templates/views/components/search/advanced-search.htm, arches/app/templates/views/components/search/saved-searches.htm
Fix the hard coded image locations to %static tag, re #6816 
#6816 
=> Fix hard coded image files, re #6816 

arches/app/media/js/viewmodels/mobile-survey.js, arches/app/templates/views/mobile-survey-designer.htm
fix i18n errors in collector_designer. To verify, successfully complete the flow to create a new collector project.
#6853 
=> fix i18n errors in collector_designer view

arches/app/datatypes/datatypes.py, arches/app/functions/primary_descriptors.py
=> 6869 primarydescriptors function updates

arches/app/media/js/viewmodels/resource-instance-select.js
=> add improvement to ri  widget, re #6864

arches/app/views/api.py
reverts default resource API return to json-ld format.
#6868 
=> revert default resource api return to json-ld #6868

arches/app/models/resource.py, arches/app/tasks.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/importer.py, arches/management/commands/packages.py
=> 6809 defer index on package load

arches/settings.py
Removes settings local error messages. re #6880
=> Removes settings local error messages. re #6880

arches/app/media/js/viewmodels/resource-instance-select.js
=> add observable to ri viewmodel, re #6882

arches/app/templates/views/report-templates/tabbed.htm
Hide the empty card (as hideEmptyNode) in the tabbed report as in the default report, re #6869
#6869 
=> Hide the empty card in the tabbed report, re #6569

arches/app/views/resource.py
Shows the resource instance name again in the report header, re #6876 
By adding the displayname back to the context.
#6876 
=> Showing Resource Instance Name in the Report, re #6876

arches/app/datatypes/datatypes.py
=> fix indexing of related resources displayname bug, re #6888

arches/app/media/js/views/components/cards/select-related-feature-layers.js
Applies minzoom to all related resource map selection layers, re  #6893
=> Applies minzoom to all related resource map selection layers, re  #6893

arches/app/media/css/arches.css
Fix the bug that the widget config panel in the graph designer does not scroll all the way to the bottom, re #6877
#6877 
=> The widget config panel in the graph designer, re #6877

arches/app/templates/views/components/datatypes/resource-instance.htm
The width of the ontology selector ui is increased to fix the ui bug, re #6575 
#6575 
=> The fix for the related resource ontology selector ui, re#6575

arches/app/media/css/arches.css
Hide the button from dropzone in the file upload widget, re #6887 
#6887
=> Remove extra button in the file widget, re #6887

arches/app/media/js/views/components/widgets/number.js, arches/app/templates/views/components/widgets/number.htm
Create the string display value for number value for data binding for the report, re #6750 
The value will remain as number datatype.
To properly show 0 in the report and evaluate the dirty state.
#6750 
=> Create number string value for the report, re #6750

arches/app/templates/views/graph-designer.htm
Users can now create a new Resource Model error-free
#6899 
=> fix create new resource model in editor

arches/app/search/components/map_filter.py
Buffers map filter geom with postgis rather than the geo api and replaces print statement with log statement, re #6913, #6850
=> Buffers map filter geom with postgis rather than the geo api, re #6913

arches/app/models/migrations/6838_add_manifest_json.py
=> Fixes migration dependency order

arches/app/media/js/viewmodels/card-component.js
=> 6897 show card without extra click

arches/app/media/css/arches.css, arches/app/media/js/views/components/widgets/edtf.js, arches/app/templates/views/components/widgets/edtf.htm
Adds panel with common edtf date formats to edtf data entry widgets.
#
=> 6896 edtf formats panel

arches/app/search/base_index.py, arches/app/search/search.py, arches/app/utils/index_database.py, arches/management/commands/es.py
=> add better feed back during data indexing operations, seperate indexing of resources from custom indexes

arches/app/search/base_index.py, arches/app/utils/index_database.py, arches/app/views/admin.py, arches/management/commands/es.py
=> add a command paramter to hide status bar output during indexing operations

arches/app/models/tile.py, arches/app/views/api.py
Provide constraint violation details so that user can identify the problematic tiles/card re #6650
=> Supplement cardinality constraint error feedback with card/tile details

arches/app/media/js/views/components/search/search-export.js
Update 5.2.x with geojson endpoint bug fix from master.
=> Update 5.2.x with geojson endpoint bug fix from master.

arches/app/media/js/viewmodels/concept-select.js, arches/app/templates/views/components/widgets/concept-select.htm
The concept-select widget now loads/selects data without UI buginess.
#6963 
=> Concept-select widget proper data handling

arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/viewmodels/map.js, arches/app/media/js/views/components/search/map-filter.js
Changes to the map.js and map-editor.js viewmodels and the map-filter.js view to put the cursor into crosshair mode when drawing geometry as this allows for a more accurate placement of vertices.
Cursor wasn't changing to crosshairs when in draw mode
-   [X] Unit tests pass locally with my changes (Only unit tests that failed were to do with v3 to v4 migration and the mobile survey.)
-   [X] Manual testing in local installation to confirm expected behaviour …
=> 6930 Crosshairs code added

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/workflow.htm
Workflows can now accept a `tabbedWorkflow` param, which changes the UI to use tabbed workflows. Currently we're just splitting logic in the workflow template but if this becomes more complex we should properly break out the components.
Button logic and 'Guidance box' logic will be included in followup tickets.
#6969 
=> tabbed workflows

arches/app/media/css/arches.css, arches/app/media/css/index.css
=> re: #6943 UI fixes

arches/app/datatypes/datatypes.py, arches/app/templates/views/components/datatypes/boolean.htm
=> fix bugs with EDTF and boolean datatypes when used in Adv. search

arches/app/media/css/arches.css, arches/app/templates/views/components/widgets/checkbox.htm, arches/app/templates/views/components/widgets/radio.htm, arches/settings.py
Fixes width of radio and checkbox widgets, re #6977, #6725
=> Fixes width of radio and checkbox widgets 

arches/app/models/graph.py
=> fix bug with nodes not getting mappings in es, re #6993

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/models/tile.py
=> 6923 tile delete indexing

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/search/components/advanced_search.py, arches/app/search/search.py, arches/app/templates/views/components/datatypes/boolean.htm, arches/app/templates/views/components/datatypes/concept.htm, arches/app/templates/views/components/datatypes/date.htm, arches/app/templates/views/components/datatypes/domain-value.htm, arches/app/templates/views/components/datatypes/edtf.htm, arches/app/templates/views/components/datatypes/number.htm, arches/app/templates/views/components/datatypes/resource-instance.htm, arches/app/templates/views/components/datatypes/string.htm
=> 6772 search for null

arches/app/models/resource.py, arches/app/utils/label_based_graph.py, tests/utils/label_based_graph_test.py
Minimize DB calls in LabelBasedGraph thru caching
#6921 
Data shown is all Resources in AFRH, total load time ~1.5 minutes on master and ~1.4 minutes on PR
The biggest win here is the `Tuples out` fetched v. returned. It directly translates to rows fetched v. returned and having a large delta between the two is indicative of unnecessary DB calls. ( Reference: …
=> optimize LabelBasedGraph to minimize DB calls through caching #6921

arches/app/media/js/views/components/widgets/number.js
Fixes false dirty state in number widget, re #6982
=> Fixes false dirty state in number widget, re #6982

arches/app/search/search_export.py
Prevents error when collection geometries during search export. re #7013
=> Prevents error when collection geometries during search export. re #7013

arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm, arches/app/templates/views/components/plugins/workflow.htm
moves logic from workflow template into tabbed-workflow template
#7001 
=> create tabbed workflow template #7001

arches/app/media/js/viewmodels/workflow-step.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm, arches/app/templates/views/components/plugins/workflow-step.htm
This pulls workflow step html into its own template. This is currently being invoked in `tabbed-workflow.htm`, but NOT in `workflow.htm`. There is a very minor issue (<30min fix) with a containing div, and if we're not planning on officially supporting untabbed workflows then this a small amount of time saved :-) . What do you think @chiatt ?
#7007 
=> Create workflow-step.htm #7007

arches/app/templates/views/components/widgets/datepicker.htm, arches/app/templates/views/components/widgets/map.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> 182 1 alignment issue base from stable

arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js
workflows now clean their own localStorage namespaces
#7003 
=> Workflows clean localStorage behind themselves #7003

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/map-editor.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/map-editor.htm, arches/app/templates/views/components/map-widget-editor.htm, package.json, yarn.lock
=> Adds support for geojson & kml file drag and drop in map widget/card

arches/app/templates/views/components/widgets/datepicker.htm, arches/app/templates/views/components/widgets/map.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm
=> 181 2 alignment of null values

arches/app/views/api.py
=> fix missing import, re #7059

arches/app/media/js/views/components/plugins/manifest-manager.js, arches/app/views/manifest_manager.py
Check if the canvas is in used in annotation before deleting, #7031
#7031 
=> Prevent deletion of a canvas if in use, #7031 

arches/app/media/js/views/components/widgets/iiif.js, arches/app/templates/views/components/widgets/iiif.htm
The annotation card tree shows the number of annotations instead of [object Object] #7053 
#7053
=> Update annotation displayValue as the count, #7053

arches/app/media/css/arches.css, arches/app/media/js/bindings/scrollTo.js, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm
=> Tabbed workflow active tab horizontal scroll #7018

arches/app/media/css/arches.css, arches/app/templates/views/components/plugins/tabbed-workflow.htm
=> tabbed workflow save multi tile step 7065

arches/app/media/css/arches.css, arches/app/media/js/bindings/scrollTo.js, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm
=> tabbed workflow css fixes 7063

arches/app/datatypes/datatypes.py
Create the file record if the tile has a file id but no file record created yet #7038 
Fix the issue with file records not created when json package loading.
#7038 
=> Create file record if a tile has file id but no file record created, #7038

arches/app/media/js/views/components/workflows/new-tile-step.js
The check for necessary parameters in the new-tile-step, in case the call is not part of the workflow. #7052 
Fix the issue that resource-instance-selector is not working.
=> Add check for workflow for non workflow use, #7052

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/iiif-widget-annotation.htm, arches/app/templates/views/components/plugins/manifest-manager.htm
Fix some UI issues with iiif-viewer/manifest manager, #6557 
The issues include iiif-viewer not showing properly in the annotation widget or with long manifest title.
#6557 
=> Fix iif-viewer UI in widget or w/ long title #6557

arches/app/media/js/views/components/search/sort-results.js, arches/app/models/migrations/7043_sort_results.py, arches/app/search/components/sort_results.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/templates/views/components/search/sort-results.htm, arches/app/templates/views/search.htm
=> add the ability to sort search results, re #7043

arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/new-tile-step.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm, arches/app/templates/views/components/plugins/workflow.htm
=> general workflow fixes + more intuitive tab state behavior #7067

arches/app/media/js/viewmodels/widget.js
Update the displayValue for the EDTF datatype in search-result, #7006 
Fix the issue not showing the value in summary report which using search-result
#7006 
=> Update display value for edtf in search result, #7006

.github/workflows/main.yml, tests/test_settings.py
Adds a github action for continuous integration
=> Adds CI action

arches/app/media/js/viewmodels/card-component.js, arches/app/media/js/viewmodels/card.js, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/viewmodels/tile.js, arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/views/components/workflows/new-tile-step.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm
Clear button wiring + small bug fix with resource-instance-select
Clear ( now undo ) is _not_ perfect, but this should be a good foundation to build the final bits onto.
#7045 
=> Workflow clear button now works with new-tile-step #7045

arches/app/utils/data_management/resources/formats/format.py
Add to and from graphids to relations import. re #7099
=> Add to and from graphids to relations import. re #7099

arches/app/models/tile.py
Cherry picks bug fix from @ads04r, e23cad25fbf23011a3ad591c323126c5d5f5c6c4
=> Checks provisional edits for card constraint violations

arches/app/models/resource.py, arches/app/search/search.py
Add proper handling to 404 (index_not_found) error, #7092 
To avoid a raised exception (thus not deleted) when you try to delete more than two related resources.
#7092 
=> Add proper handling index_not_found error, #7092

arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/new-tile-step.js
Update the workflow to properly create the wastebin list when a user quit workflow, AfS 259
AfS 259
=> Update wastebin logic to properly remove, AfS 259

arches/app/datatypes/datatypes.py
Fixes bug preventing images from appearing in the report header when loaded during CSV import. re #7095
=> Fix missing images from csv import in report header

arches/app/models/tile.py
=> fix tile cardinality validation bug, re #7088

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/models/tile.py, arches/app/search/components/advanced_search.py, arches/settings.py
=> 7094 search nulls bug

arches/app/datatypes/base.py
Uncomments docstring, re #7094
=> Uncomments docstring, re #7094

arches/app/views/api.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py
Allow float values for cluster distance, re #7120
=> Allow float values for cluster distance, re #7120

arches/app/media/js/viewmodels/tile.js
=> Prevent tile from setting null defaults to widget

arches/app/media/css/arches.css
Fix the ui issues. Show the original buttons (in addition to workflow buttons) and fix windows size, #7105  
#7105 
=> Fix the UI issue with creating new resource instance type in workflow, #7105

README.md, arches/__init__.py, releases/5.1.0.md, releases/5.1.1.md
Updated version and started release note draft
=> Starting 5.1.1 release prep

releases/5.1.1.md
Renames 'Additional notes' to 'Important'
=> Renames 'Additional notes' to 'Important'

README.md, arches/__init__.py, arches/app/datatypes/datatypes.py, releases/5.1.0.md, releases/5.1.1.md
Updates stable/5.1.1 for release
=> Release updates

arches/install/requirements.txt, releases/5.1.1.md
Updates 5.1.1 with fix for Pillow install using Python 3.9.
=> Update 5.1.1 with fix for Pillow install using Python 3.9

README.md, arches/app/datatypes/datatypes.py, arches/install/requirements.txt, releases/5.1.0.md, releases/5.1.1.md
Updates 5.2.x with 5.1.1 release prep and bug fixes
=> Updates 5.2.x with 5.1.1 release prep and bug fixes

arches/app/media/css/arches.css, arches/app/templates/views/components/coordinate-editor.htm, arches/app/templates/views/components/map-editor.htm, arches/app/templates/views/components/map-widget-editor.htm, arches/app/templates/views/components/related-resources-map-editor.htm, arches/app/templates/views/map-layer-manager.htm, arches/app/templates/views/search.htm
=> re:#7148 small UI fixes

arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/component-based-step.js, arches/app/media/js/views/components/workflows/new-tile-step.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm
Updates workflow buttons and button logic.
Also solves issue with wastebin not correctly persisting to localStorage.
#7141 #7138 #7137
=> Omnibus workflow improvements

arches/app/models/migrations/7125_geometry_index_table.py, arches/app/models/migrations/7125_geometry_index_table_update.py
=> updates populate geom index for 3d

arches/app/views/resource.py
Cherry picks fix for #7162 from stable/5.2.x
=> Check if display_value is None before eval, #7162

.github/workflows/main.yml
Testing fix for libgconf2-4 install
=> Testing fix for libgconf2-4 install

arches/app/views/api.py
Ensures nodeid is in feature.properties regardless whether nodeId already exists, re #7167
=> Ensures nodeid in geojson api's feature.properties, re #7167

arches/app/media/js/views/components/workflows/new-tile-step.js
Ensures dirty state is activated in new tile step, re #7178
=> Ensures dirty state is activated in new tile step, re #7178

arches/app/media/css/arches.css
=> re:#7176 fix search result

arches/app/templates/views/components/search/search-export.htm
=> 7114 search export labeling issue

.github/workflows/main.yml, arches/app/templates/views/components/search/search-export.htm
=> Fix labeling issue in search export, re #7114

arches/app/media/css/arches.css, arches/app/templates/views/components/map-editor.htm, arches/app/templates/views/components/related-resources-map-editor.htm
Shows map editor buttons for related resource intersection panel and geojson editor. Also changes the order of the buffer and intersecting geom selection re #7184
=> Shows map editor buttons for rr intersection panel and geojson editor

arches/app/media/css/arches.css, arches/app/media/js/views/components/plugins/manifest-manager.js, arches/app/media/js/views/components/workbench.js, arches/app/models/migrations/6979_manifest_manager.py, arches/app/templates/views/components/plugins/manifest-manager.htm, arches/app/templates/views/components/workbench.htm
Updates manifest start page to reflect mockups and renames Manifest Manager, Image Service Manager, re #7108
=> Update manifest start page

arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/formats/excel.py, arches/install/requirements.txt, arches/management/commands/packages.py, arches/settings.py
Add ability to export tilecsv to multi-tabbed excel file
#
=> Add ability to export tilecsv to excel file, re #7192

arches/app/datatypes/base.py
=> only need to find the first null value in a tile, re #7194

.github/workflows/main.yml, arches/app/datatypes/base.py
Includes a fix for the CI build and a performance improvement from stable/5.2.x
=> Advance search performance improvement

arches/app/models/resource.py, arches/app/models/tile.py, arches/app/views/api.py, arches/urls.py
re #7171
example requests to test:
http://localhost:8000/validate/resource/{resource id}
http://localhost:8000/validate/tile/{tile id}
you can throw in a "raise" statement in any datatype "validate" function to see an example of output when valid is false
=> initial commit on an api to validate resource instance and tile objects in the system

arches/app/utils/response.py
=> jsonresponse will now cast the indent flag value to an int if possible, re #7170

arches/app/media/css/arches.css, arches/app/templates/views/components/photo-workbench.htm
Fixes positioning of gallery in photo gallery card in workflows and properly resizes gallery when workbench side panel is opened. re #7145
=> Photo gallery layout fixes

arches/app/media/js/views/components/cards/related-resources-map.js
Small changes to allow for external-resource-data-preview  component to control the map on load
#7221
=> Small changes  to RRmap card for external data preview map

arches/app/datatypes/url.py, arches/app/media/js/views/components/datatypes/url.js, arches/app/media/js/views/components/widgets/urldatatype.js, arches/app/models/migrations/7224_url_datatype.py, arches/app/templates/views/components/datatypes/url.htm, arches/app/templates/views/components/widgets/urldatatype.htm
=> 7224_url_datatype

arches/app/media/css/arches.css
Add space between info box and map card
=> Add space between info box and map card

arches/app/media/js/viewmodels/workflow-step.js
Show the workflow information box by default initially, if the user has had the selection, archesproject/arches-her#559
archesproject/arches-her#559
=> Show the workflow information box by default, arches-her#559

arches/app/media/css/arches.css, arches/app/templates/views/components/photo-workbench.htm, arches/app/templates/views/report-templates/default.htm, arches/app/templates/views/resource/report.htm
Removes double-scroll behavior in reports.
To test:
1. navigate to various report templates, notice the absence of double-scroll behavior.
2. navigate to a photo-gallery card. Notice the still-consistent behavior.
#7232 ( some )
=> removes double-scroll behavior from reports #7232

arches/app/templates/views/report-templates/default.htm
small changes to support https://github.com/archesproject/arches-for-science-prj/pull/332
#7234
=> add changes to support thematic report templating #7234

arches/app/media/css/arches.css, arches/app/templates/views/components/plugins/workflow-step.htm, arches/app/templates/views/components/workflows/component-based-step.htm, arches/app/templates/views/components/workflows/new-multi-tile-step.htm
=> re:#7236 workflow ccs fixes

arches/app/models/resource.py, arches/app/utils/label_based_graph.py, arches/app/views/api.py
Update the resources API endpoint to filter the tiles by nodegroup permission, #7229 
#7229 
=> Update resources endpoint to filter by perm, #7229

arches/app/media/js/viewmodels/resource-instance-select.js
Fix error when loading some workflows. re #7255
=> Fix error when loading some workflows. re #7255

arches/app/models/resource.py, arches/app/views/api.py, arches/urls.py
=> 7171 validation api

arches/app/templates/javascript.htm
Make validate url available in the browser, re #7171
=> Make validate url available in the browser, re #7171

arches/app/templates/views/components/photo-workbench.htm
In the photo gallery card show only widgets configured as visible, re #7247
=> In the photo gallery card show only widgets configured as visible, re #7247

arches/app/models/tile.py
Fix the error failing to create a geom node using node_value api by ArcGIS Pro addin
archesproject/arches-esri-add-in#141
archesproject/arches-esri-add-in#141
=> Create a new geom in a separate card, Esri#141 

arches/app/utils/data_management/resources/formats/rdffile.py
=> allow the domain node to be in a parent tile, re #7252

arches/app/models/resource.py, arches/app/utils/label_based_graph.py, arches/app/views/api.py
Update 5.1.x with api permissions filtering cherry picked from stable/5.2.x, re #7229
=> Update 5.1.x with api permissions filtering, re #7229

arches/__init__.py, arches/install/arches-project
Updates version number and fixes path to version branch re #7210
=> 5.1.2 release prep

arches/app/models/resource.py
cherry picked from stable/5.2.x,  re #7269
=> Fixes error in calling load_tiles without a user

arches/app/templates/views/components/workflows/component-based-step.htm
Show only visible widgets in multi-tile workflow step, re #7267
=> Show only visible widgets in multi-tile workflow step

.github/workflows/main.yml
apt update before installing system dependencies, re #7278
=> Fix failing CI build, re #7278

arches/app/media/js/views/components/workflows/final-step.js, arches/app/templates/views/components/workflows/final-step.htm
Remove final step cruft and support component based final step, re archesproject/arches-her#578
=> Remove final step cruft and support component based final step

.github/workflows/main.yml
Run apt update before installing system dependencies, re #7278
=> Fix CI build error

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/views/components/workflows/new-resource-instance.js, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/components/workflows/new-resource-instance.htm
Add a new feature: supporting multi card in the resource instance creation, #7250 
#7250 
=> 7250 new resource instance

arches/app/datatypes/url.py
=> fix bug where urls weren't getting imported during csv import, re #7243

README.md, releases/5.1.2.md
Adds release notes for v 5.1.2
=> Add 5.1.2 release notes

.github/workflows/main.yml, README.md, arches/app/models/resource.py, releases/5.1.2.md
Update 5.1.2 with release notes and minor bug fix
=> Update 5.1.2 with release notes and minor bug fix

README.md, arches/__init__.py, releases/5.1.3.md
Changes release version to 5.1.3
=> Changes release version to 5.1.3

arches/__init__.py
Sets 5.1.x version to 5.1.4 beta
=> Sets 5.1.x version to 5.1.4 beta

arches/app/datatypes/datatypes.py
Update FileList Datatype to return urls not file names as display value, #5617
#5617
=> Update FileList displayname as url not name, #5617

arches/app/templates/views/components/plugins/tabbed-workflow.htm
Hide the previous and next step buttons on 1st and last steps, respectively. re #7251
=> Hide prev and next step buttons on 1st and last steps

arches/app/media/js/views/components/workflows/component-based-step.js
component-based-step now passes workflow-step through its VM
#7299
=> passes externalStepData through component-based-step viewmodel #7299

arches/app/media/css/arches.css, arches/app/templates/views/components/plugins/tabbed-workflow.htm
Add button to allow user to navigate back to init workflow page, #7298
=> Add button to allow user to navigate back to init workflow page

arches/app/media/js/viewmodels/workflow.js, arches/app/templates/javascript.htm
Update the us when the user quits workflow including emptying wastebin, #7282 
Add the cancel button and message when nothing to delete.
related pr in archesproject/arches-her#593
#7282
=> The message on quit regarding wastebin, #7282

arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/views/components/workflows/component-based-step.js
Reproducible in the consultation workflow. Instead of creating many resources, it should now create 2. The 2nd resource is due to the final step of the workflow, and will be refactored in a later ticket.
#7307
=> Some workflows create multiple resources

arches/app/media/css/arches.css, arches/app/templates/views/components/search/saved-searches.htm, arches/app/templates/views/search.htm
#7304 and addresses #7130 
*   Sponsored by: Los Angeles City Planning - Historic Places LA (https://github.com/CityOfLosAngeles)
=> 7304 css fixes

arches/app/media/css/arches.css, arches/app/templates/views/graph-designer.htm, arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm, arches/app/templates/views/graph/graph-designer/card-tree.htm, arches/app/templates/views/graph/graph-designer/graph-settings.htm, arches/app/templates/views/graph/graph-designer/graph-tree.htm, arches/app/templates/views/graph/graph-designer/node-form.htm, arches/app/templates/views/graph/graph-designer/permission-settings-form.htm, arches/app/templates/views/graph/graph-settings.htm
CSS refactor of Graph Designer. All panels should scroll independently. 
To test: Thoroughly interact with the designer view.
#7292
=> 7292 cbyrd fix main content panel scroll

arches/app/models/resource.py, arches/app/search/base_index.py, arches/app/search/elasticsearch_dsl_builder.py
=> when deleting resources make sure documents in custom indexes are deleted as well, re #7290

arches/app/media/css/arches.css, arches/app/templates/views/components/plugins/tabbed-workflow.htm
Disable click on the workflow tab arrows, so now they only provide a visual guide, #7183 
#7183
=> Disable workflow tab arrows, #7183

arches/app/media/js/views/components/workflows/component-based-step.js
Update the logic to iterate through the data array when loading data.
Fix the issue of consultation map not saving properly. archesproject/arches-her#599
archesproject/arches-her#599
=> Fix component step load data, arches-her#599

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/models/resource.py, arches/app/models/tile.py, arches/app/views/api.py, arches/install/arches-templates/project_name/datatypes/sample_datatype.py, tests/fixtures/datatypes/color.py, tests/fixtures/datatypes/semantic_like.py
=> 7328_validation_api_bug_fix

arches/app/models/resource.py
=> 7334 fix related resource report section

arches/app/utils/label_based_graph.py, tests/utils/label_based_graph_test.py
Put cardinality n tiles in an array, even if there is only one tile, re #7303.
=> Put cardinality n tiles in an array, even if there is only one tile

arches/app/media/css/arches.css, arches/app/templates/views/resource/editor.htm
This changes the resource editor's CSS to allow for vertical scrolling. To review, thoroughly navigate the graph designer and resource manager to ensure proper scrolling throughout.
This partially solves #7344 , but we should not close the ticket until external developers report successful behavior.
=> resource manager scrolls y correctly #7344

arches/app/media/css/arches.css, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/plugins/manifest-manager.htm
=> re:#7337 image manager UI updates

arches/app/templates/views/components/plugins/tabbed-workflow.htm
Shows the 'Complete Workflow' button on any step once all required steps are completed. re #7327
=> Show 'Complete Workflow' link once required steps are complete

arches/app/media/js/bindings/cytoscape.js, arches/app/templates/javascript.htm, package.json, yarn.lock
Adds the Cytoscape.js library to the JS dependencies and creates a binding handler to support creating Cytoscape.js graph visualizations
re: #7353
=> adds cytoscape binding handler

arches/app/media/js/viewmodels/concept-select.js, arches/app/media/js/views/components/workflows/component-based-step.js, arches/app/templates/views/components/workflows/component-based-step.htm
Fix the issue with deleting tiles in the multi-tile component-based step, #7317
#7317
=> delete tile multi component step

arches/app/views/resource.py
Fix the logic to properly return json when query string includes json=True, #7322
Also, fix the issue with related resource info button not working
#7322
=> Fix the resource report logic when returning json, # 7322

arches/app/datatypes/datatypes.py
=> improve get_display_value method of resource instance datatype, re #7364

arches/app/media/js/views/components/plugins/manifest-manager.js, arches/app/templates/views/components/plugins/manifest-manager.htm
=> Disable editing of non-arches iiif manifests, re #7346

arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm, arches/app/templates/views/components/plugins/workflow-step.htm, arches/app/templates/views/components/plugins/workflow.htm
Update the infobox setting to remember user's selection, #7283
Once a user choose to display or hide, the selection is saved for the next new session.
#7283
=> persistent infobox status, #7283

arches/app/datatypes/datatypes.py
=> 7364 harden ri display name code, bug fix

README.md, arches/__init__.py, releases/5.1.4.md
Adds release notes and updates version.
=> 5.1.4 release prep

arches/app/media/css/arches.css, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/widgets/resource-instance-select.htm
Add style to new new-resource-instance creating ui to slide open, #7324 
#7324
=> Slide-open the related resource opening UI, #7324

arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
Update the other divs sharing the same class as the sliding opening container, #7324
eg. related resource info button (this will slide open)
#7324 
=> The related resource opening UI #7324

arches/app/media/js/views/components/search/advanced-search.js, arches/app/templates/views/components/search/advanced-search.htm
=> 7413 adv search collapse

arches/app/media/js/viewmodels/resource-instance-select.js
Apply term filter even if term is an empty string. re #7410
=> Apply term filter even if term is an empty string.

arches/app/media/css/arches.scss
=> updates sass with the latest CSS

arches/install/arches-templates/.gitignore, arches/install/arches-templates/project_name/settings.py-tpl
=> Configure template project to support sass compressor. 

arches/app/media/js/views/components/search/advanced-search.js, arches/app/media/js/views/search.js, arches/app/templates/views/components/search/advanced-search.htm
search page now has expected loading behavior. To reproduce, try to break the search page :-)
#7330 
=> Fixes loading state of search view #7330

arches/app/media/js/views/components/resource-summary.js
Fix the error in the resource instance widget including related resource summary, re #7438 
#7438 
=> The related resource instance widget, re #7438

arches/app/views/resource.py
=> 7394_fix_typos

arches/app/media/js/viewmodels/tile.js
Remove update of '_tileData' causing widget to lose focus, re #7352
=> Remove update of '_tileData' causing widget to lose focus

arches/app/models/system_settings.py
=> 7377 default settings bug

arches/app/media/css/arches.scss, arches/app/templates/views/components/photo-workbench.htm, arches/app/utils/data_management/resources/exporter.py
=> #7448 image gallery workbench css

arches/app/media/js/reports/image.js, arches/app/media/js/viewmodels/file-widget.js, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/views/components/search/saved-searches.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/file.htm, arches/app/templates/views/rdm/concept-report.htm, arches/app/utils/context_processors.py, arches/app/views/concept.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py
=> 7437 url pathing with subpaths

arches/app/media/css/arches.scss
Update css for the related resource instance creator button when started from the workbench, #7420
#7420
=> The related resource creator button in workbench, #7420

arches/app/media/js/views/components/workflows/component-based-step.js, arches/app/media/js/views/components/workflows/new-tile-step.js
Reset dirty state when revisiting a step. re #7362
=> Resets dirty state when revisiting a step

arches/app/models/models.py
=> 7459_fix_unique_together_bug

arches/app/media/js/viewmodels/resource-instance-select.js
Fix api call in resource instance selector, #7437 
#7437 
=> Fix api call in resource instance selector, #7437

arches/db/dml/db_data.sql
Updates the street layer and source so that when a user creates a new project or rebuilds their database, the new layer will load., re #7467
=> Update street layer in dml

arches/app/media/js/viewmodels/workflow-step.js
Update the reousrce id tracking logic, archesproject/arches-her#606
To take into account for various shapes of values from local storage.
archesproject/arches-her#606
=> Update resource id tracking logic, arches-her#606

arches/app/models/graph.py
=> 7428 adv styling geom clone

arches/app/datatypes/concept_types.py, arches/app/datatypes/url.py
Add missing **kwarg arg passed from the node_value endpoint, re #7496.
=> Add missing **kwarg passed from the node_value endpoint

arches/app/utils/index_database.py, arches/management/commands/es.py
=> adds mgmt cmd to index resources by type, re #7488

arches/app/media/css/arches.scss
Fix the ui when the workbench is used in the related resource creator, #7519 
#7519 
=> The related resource creator button position in a workbench

arches/app/media/css/arches.scss, arches/app/media/js/bindings/gallery.js, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm
Add arrows to scroll left and right in the workflow tabs, re #7358
#7358
=> Add scroll arrows in the workflow tab list, #7358

arches/app/media/js/views/components/workflows/component-based-step.js
=> fix bug where undo is incorrectly displayed, re #7526

arches/app/templates/views/components/plugins/tabbed-workflow.htm
Save dirty workflow step when a user clicks 'Complete Workflow', re #7387
=> Save dirty step when a user clicks 'Complete Workflow'

arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/templates/views/components/plugins/tabbed-workflow.htm
Add the function to save the unsaved data when the user click the complete button, archesproject/arches-for-science#358
To enhance the functionality to finish the remaining tile-savings after the step
archesproject/arches-for-science#358
=> Add the function to save the unsaved on completion

arches/app/templates/views/components/cards/file-renderers/imagereader.htm, arches/app/templates/views/components/cards/file-renderers/pdfreader.htm
Fix the ui (removing padding from image viewer and pdf viewer for the file widget), #7143 
#7143 
=> The file viewer padding, #7143

arches/app/media/js/viewmodels/concept-select.js
Ensure values passed in requests are valid, re #7566
=> Ensure values passed in requests are valid

arches/app/views/manifest_manager.py
=> Adds '@id' attribute to manifests #7539

.eslintrc.js
Modify .eslintrc file to permit ES 6 syntax, re #7537
=> Modify .eslintrc file to permit ES 6 syntax

arches/management/commands/developer.py
Adds livereload host argument - necessary to run livereload in a container.  Nonbreaking; defaults to localhost as usual.
#7577 
=> adds livereload host argument

arches/app/media/js/views/components/iiif-annotation.js
undoes breaking changes in https://github.com/archesproject/arches/pull/7570/files
#7579
=> Fix iiif annotation ux geometry table

arches/app/templates/views/components/widgets/concept-select.htm
Removes anchor tag from concept report - need guidance on what's desired on the node value anchor tags.  Testing with @robgaston those appear to work and link to other nodes within the report.  
Removes anchor tag from concept report, it isn't needed.
#7180 
=> remove anchor tag from concept report

arches/app/media/js/views/components/widgets/number.js, arches/app/media/js/views/components/widgets/text.js, arches/app/templates/views/components/widgets/number.htm, arches/app/templates/views/components/widgets/text.htm
determines whether field is disabled by checking for disabled and uneditable properties
When a user has read only permissions, the input for a field should be disabled.  Currently there's a conflict with the uneditable property.  Now there's a computed property that checks both of them (uneditable and disabled).  Naming is hard - I called new computed property "disable" (open to better ideas!).  At least now it's the only thing that needs to be checked.
#7571 
-   [ ] I have added tests that prove my fix is …
=> Adds computed property for text/number

arches/install/ubuntu_setup.sh
small updates to the ubuntu_setup.sh script.
#7562 
*   Sponsored by: GCI
*   Found by: @mradamcox
*   Tested by: @mradamcox
=> 7562 update ubuntu setup

arches/app/datatypes/url.py
=> fix strict parameter on url datatype, re #7583

arches/app/media/js/views/components/iiif-annotation.js
=> Core changes to support iiif annotation in workflows

arches/app/datatypes/datatypes.py
=> es mapping issue with annotation and geojson datatypes

arches/app/media/js/models/report.js
=> includes RR.resourceinstanceid in RR payload for report, re #7591

arches/app/datatypes/datatypes.py
Changes return from get_display_value for the boolean data type to return "True" or "False" or null if no value is specified.  Commented code can be used instead when v2 of the api is released.
closes #7581 
=> boolean datatype rework

arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/views/api.py
Adds a "cards" parameter to the graphs API endpoint.  If it's false, the endpoint won't load cards.  In my testing, the performance improvement when using the cards parameter is noticeable and measureable (without setting "cards" to false it was taking a little more than double the time - this will vary by resource and number of cards, most likely)
resolves #7598 
* …
=> graph api endpoint modification

arches/app/utils/decorators.py, arches/app/utils/permission_backend.py, arches/app/utils/transaction.py, arches/app/views/transaction.py, arches/management/commands/transaction.py, arches/urls.py
* Adds transaction rollback api endpoint
* Adds CLI management command for transaction rollback
* Adds utility function for transaction rollback
Adds utility functions, cli, and view/endpoint for rollback of a transaction, given a specific transaction ID
resolves #7588 
=> allows for transaction rollback

arches/app/media/js/views/components/workflows/component-based-step.js
Hide the selected node from component based workflow step, #7402 
The nodes that should be hidden can be specified in
`layoutSections > componentConfigs > parameters > hiddenNodes: ['node_id', ... ]`
#7402
=> hide nodes in a component based step, #7402

arches/app/media/js/views/components/workflows/component-based-step.js
Allows for use of the alertviewmodel at the step level.  
fixes #7604 
=> required content in workflow step

arches/app/tasks.py
Fixes issue that was causing celery export to fail for excel type export
fixes #7621 
=> tile excel search export celery error

arches/app/media/js/viewmodels/tile.js, arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/component-based-step.js, arches/app/templates/javascript.htm, arches/app/views/transaction.py
This change depends on PR #7595 and is branched off it.
Core changes to allow for workflow transaction deletion. 
* Adds transaction ID to tile viewmodel.  
* Adds workflow ID to component based step.
* Adds the transaction reversal endpoint to quitWorkflow in workflow.js
#7587 - makes it possible.  But individual workflows will need to be modified to pass the transaction ID/workflow ID over. …
=> core changes to allow for workflow transaction deletion

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/datatypes/url.py, arches/app/models/resource.py, arches/app/utils/label_based_graph_v2.py, arches/app/views/api.py
=> update disambiguated json output, version label based graph

tests/utils/label_based_graph_test_v2.py
Add label based graph v2 tests, re #7314
=> Add label based graph v2 tests, re #7314

arches/app/media/js/views/components/iiif-annotation.js, arches/app/templates/views/components/iiif-annotation.htm
adds classname to to iiif-workbench editor tab, to give the ability to hide it at the project level
#7629 
=> update editor iiif-workbench tab to have classname #7629

arches/app/media/css/arches.scss, arches/app/templates/views/components/plugins/manifest-manager.htm
Hide "create image service" label in the manager when running in a workflow, archesproject/arches-for-science#433
archesproject/arches-for-science#433
=> The image service manager in a workflow, afs#433 

arches/app/media/css/arches.scss, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
Update css for the resource editor related resource viewer selector tab, #7627 
#7627 
=> Update the css for related resource viewer selector, #7627

arches/app/views/tile.py
Core changes for afs #[455](https://github.com/archesproject/arches-for-science-prj/issues/455) - parses the transaction ID from the json body if form data isn't used
closes #7633 
=> core changes for afs #455

arches/app/media/js/viewmodels/resource-instance-select.js
UI fix to resolve an issue with improperly named variable
closes #7645
=> name of data has changed to "queryString"

arches/app/media/js/views/components/iiif-annotation.js
=> Core changes for afs 458

README.md
Updated Arches community forum link: removed Google Groups link and replaced with new link to forum hosted on Discourse
=> Updated community forum link

arches/app/media/js/viewmodels/card-component.js
Saves the workflow ID as the card component tile's transaction ID if it exists
#7623 
=> Saves the workflow ID as the card component tile's transaction ID

arches/app/models/tile.py, arches/app/views/api.py
updates tile model + api nodevalue endpoint to accept transaction IDs
resolves #7663 
=> nodevalue api endpoint changes

arches/app/models/tile.py
For tiles created through the API, not all node values are set by the user.  Because of this, dirty tile checks fail.  This PR adds missing node values as empty.  
fixes #7626 
=> adds missing nodes to to tiles created through the API

arches/app/media/js/models/abstract.js, arches/app/media/js/models/card.js, arches/app/media/js/models/concept.js, arches/app/media/js/models/graph.js, arches/app/media/js/models/mobile-survey.js, arches/app/media/js/models/node.js, arches/app/media/js/models/report.js, arches/app/media/js/models/tile.js
re #7668
I'm not sure how to test this as we currently don't expect a return from ajax calls when using the abstract.js model.
This shouldn't affect any currently running code because of that.
=> 7668 update models to return promises

arches/app/media/js/viewmodels/card.js, arches/app/media/js/viewmodels/provisional-tile.js, arches/app/media/js/viewmodels/tile.js, arches/app/templates/views/components/cards/default-card-report.htm, arches/app/templates/views/components/cards/grouping.htm
=> Safely unwraps provisionaledits observable

arches/app/media/js/views/components/resource-report-abstract.js
=> Fixes report double-refresh error

arches/app/media/js/views/components/resource-report-abstract.js, arches/app/templates/views/components/resource-report-abstract.htm
Remove footer in summary step and allow initialization of abstract-summary-report without the CardViewModel to support 
archesproject/arches-for-science#516.
=> Changes to support archesproject/arches-for-science-prj#516

arches/app/media/css/arches.scss, arches/app/media/js/views/components/related-resources-graph.js, arches/app/templates/views/components/related-resources-graph.htm
=> #7660 rr UI update

arches/app/media/css/arches.scss, arches/app/media/js/views/components/related-resources-graph.js, arches/app/media/js/views/components/resource-report-abstract.js, arches/app/templates/views/components/related-resources-graph.htm, arches/app/templates/views/components/resource-report-abstract.htm, arches/app/utils/data_management/resources/formats/rdffile.py, arches/app/views/api.py, arches/app/views/search.py
Updates workflows_dev branch with latest in stable/5.2.x
=> Update workflows_dev branch

arches/app/utils/data_management/resources/formats/csvfile.py
Prevents excessive logging during import. re #6960
=> Reduce missing display value warning to 'INFO' 

arches/app/datatypes/datatypes.py
Fix issue with resource instance datatype validation.
#
=> Fix issue with resource instance datatype validation, re #7704

arches/app/media/js/views/components/resource-report-abstract.js
=> 7689 cbyrd resource report abstract optional disambiguated fetch param

arches/app/views/api.py
Adds exclusions to bulk resource endpoint to improve performance
resolves #7711 
needed by AFS [534](https://github.com/archesproject/arches-for-science-prj/issues/534)
=> adds exclusions to bulk resource endpoint

arches/app/media/js/views/components/workflows/component-based-step.js
Update step saveOnQuit when step component initializes, re #7719
=> Allow custom steps to override step saveOnQuit method

arches/app/templates/views/components/cards/iiif-card.htm, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/plugins/manifest-manager.htm
Changes remaining references to 'Manifest' to 'Image Service'. re #7724
=> Change 'Manifest' to 'Image Service'

arches/app/media/js/views/components/resource-report-abstract.js
=> fix for broken report, re #7728

arches/app/utils/transaction.py
Instead of calling the queryset delete method (which only calls delete on the queryset itself, not on the proxy models) use the individual delete method on each returned proxy object - django does the cast
fixes #7714 
=> resource indices persist

arches/app/utils/forms.py, arches/app/utils/transaction.py
Update workflows_dev with latest in stable/5.2.x
=> Update workflows_dev with latest in stable/5.2.x

arches/app/media/js/views/components/resource-report-abstract.js, arches/app/templates/views/resource/editor.htm
Turns off caching for resource-component-abstract in the editor context
resolves #7740 
=> turns caching off for resource-component-abstract in the editor context

arches/app/media/js/views/components/resource-report-abstract.js, arches/app/templates/views/resource/editor.htm, arches/app/utils/transaction.py
Update workflows dev with recent 5.2.x changes
=> Update workflows dev with recent 5.2.x changes

arches/app/media/js/views/components/resource-report-abstract.js
Changes the resource component abstract component to use the 
#7742 
=> make resource report abstract use the beta bulk endpoint

arches/app/templates/views/report-templates/default.htm
Fix hide null values position, re #7758
=> Fix hide null values position

arches/app/utils/task_management.py
Added ConnectionResetError as a handled exception type.
#7768 
*   Tested by: @aj-he
=> handled ConnectionResetError

arches/app/utils/label_based_graph_v2.py, tests/utils/label_based_graph_test_v2.py
=> Fixes label based graph shape to be backwards-compatible

arches/app/media/js/views/components/related-resources-graph.js
=> make sure cytoscape graph has matching nodes for every edge, re #7681

arches/app/media/js/views/components/search/search-results.js
search result component should use label based graph v2 (beta) endpoint
#7777 
=> search result component should use label based graph v2

arches/app/media/js/viewmodels/workflow.js
Fix the issue with info-box status persistency, #7786 
#
=> Move the initialize() body to run after getting workflow name, #7786

arches/app/utils/data_management/resource_graphs/exporter.py
=> make sure graph data are sorted before export, re #7820

arches/app/models/concept.py
=> make sure concept ids are uuids

arches/app/media/js/views/components/iiif-viewer.js
Allows a user to replace the method which builds the node overlays by passing in a method with the same name to the iiif-viewer component param. re #7826
=> Allow user to replace method to create annotation node overlays

arches/app/media/css/arches.scss, arches/app/templates/views/components/plugins/workflow-step.htm, arches/app/templates/views/components/workflows/workflow-component-abstract.htm
=> re: #7843 update workflow css

arches/__init__.py, arches/management/commands/report.py
Adds functionality for update, unregister, and list report templates
The report management command had handles for four operations: register, update, unregister, and list, but only the register function had been written. This PR adds the missing update, unregister, and list functions, following the same pattern of similar management commands (e.g. widget).
#7374 
-   [X ] Unit tests pass locally with my changes
* …
=> 7374 report add missing commands

arches/app/datatypes/datatypes.py
Change date from csv to None if it is an empty string
#7932
Model and data for QA:
[date_testing.zip](https://github.com/archesproject/arches/files/7435436/date_testing.zip)
Command for QA:
`python3 manage.py packages -o import_business_data -s 'date_testing/Robot.csv' -c 'date_testing/Robot.mapping' -ow 'overwrite' -g 93d791e8-3781-11ec-8ea7-0242ac1a0007`
=> Change date from csv to None if it is an empty string, re #7932

arches/app/media/css/arches.scss, arches/app/templates/views/components/plugins/workflow.htm
=> #7946 update workflow footer style

arches/app/models/migrations/7794_i18n_string_datatype.py
=> Add defaultconfig from widgets table, re #7794

arches/app/models/fields/i18n.py, tests/localization/field_tests.py
=> fix save of non localized config properties, re #7971

arches/app/media/js/views/components/workflows/workflow-component-abstract.js, arches/app/templates/views/components/workflows/workflow-component-abstract.htm
Temporary fixes for undefined variables until multi-tile logic workflow component abstract is updated. re #7987
=> Fix undefined variables in workflow component abstract, re #7987

arches/app/media/js/views/components/workflows/final-step.js, arches/app/templates/views/components/workflows/final-step.htm
Remove HER specific code from default final step, re #7983
=> Replace final step with generic step, re #7983

arches/app/datatypes/url.py
Prevents Attribute error when saving URL nodes with no value
#7992
=> Handle for null value in URL datatype, re #7992

arches/app/media/js/views/components/workflows/workflow-component-abstract.js, arches/app/templates/views/components/workflows/workflow-component-abstract.htm
Update the multi-tile step to make it work with new workflow update, archesproject/arches-her#709
archesproject/arches-her#709
=> Update multi tile step, arches-her#709

arches/app/views/user.py
Refinement of email notification so that the message reads correctly irrespective of whether settings.ADMINS is set, or not. Provide logging when the email fails to send.
-   [X] Unit tests pass locally with my changes
*   Found by: @RobOatesHistoricEngland
*   Tested by: @RobOatesHistoricEngland
=> Refine email message and log when email exception

arches/app/templates/views/components/widgets/file.htm, arches/app/views/user.py
Update master with latest in dev/6.1.x
=> Update master with latest in dev/6.1.x

arches/app/media/js/views/components/search/search-export.js, arches/app/search/search_export.py, arches/app/tasks.py
Create a zip file with export name that the user entered, when create a zip file from search export results. #8014 
It does not apply to small zip file that does not use the celery because the option to enter the name is not given.
#8014 
=> Update search export zip file name, #8014

arches/app/models/migrations/7807_i18n_edtf_datatype.py
=> add edtf i18n migration, re #7807

arches/app/media/js/views/components/cards/grouping.js
Add the workflow id as a transaction id to the grouping card when saved in a workflow, #7991 
#7991 
=> Add transaction id to grouping card saving, #7991

arches/app/media/css/arches.scss
Fix the issue of not showing the text in the page properly when the text string is very long without any space. #8018
eg. saved search setting with long search url string.
#
=> Break long text string, eg saved search, #8018

arches/app/models/migrations/7802_i18n_ri_datatype.py
=> add i18n for resource instance widget, re #7802

arches/app/models/migrations/7803_i18n_ri_list_datatype.py
=> i18n ri list widget

arches/app/models/migrations/7810_i18n_url_datatype.py
=> i18n url widget

arches/app/media/js/views/components/cards/grouping.js
Update the grouping card to use params saving instead of its own, archesproject/arches-her#737
Fix the issue with local storage not updating in the workflow
archesproject/arches-her#737
=> Update grouping card to work with workflow local storage, arches-her#737

arches/app/media/css/arches.scss, arches/app/media/js/viewmodels/map.js, arches/app/templates/views/components/map-popup.htm
Show popup info for overlapping features
#5307
=> Show popup info for overlapping features, re #5307

arches/app/templates/views/components/cards/grouping.htm
Update the grouping card to fix a couple of ui issues, #7753, archesproject/arches-her#547
#7753, archesproject/arches-her#547
=> The grouping card UI issues, #7753

arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/workflow-component-abstract.js, arches/app/templates/views/components/plugins/workflow.htm
=> Updates workflow error handling

arches/app/models/tile.py
Cherry picks #8048 (add update_all to update_node_value) into 6.0.x
=> Cherry pick #8048 (add update_all to update_node_value) into 6.0.x

arches/app/media/plugins/leaflet-side-by-side/index.js
Leaflet side by side requires leaflet to load.  Encases the library in "define" and makes leaflet a dependency, which will generate a correct dependency graph.
#8059 
=> 8059 canvas slider unavailable

arches/app/models/card.py, arches/app/models/fields/i18n.py, arches/app/models/graph.py, arches/app/models/mobile_survey.py, arches/app/models/resource.py, arches/app/models/tile.py, arches/app/utils/betterJSONSerializer.py, arches/app/utils/data_management/resource_graphs/exporter.py, arches/app/utils/data_management/resources/formats/rdffile.py, arches/app/views/graph.py, arches/management/commands/packages.py
=> working version of graph export with i18n, re #7980

arches/app/views/concept.py
=> fix sparql endpoint to work with i18n, re #8062

arches/app/media/js/views/components/resource-report-abstract.js, arches/app/models/tile.py
Update 6.1.x with latest bug fix from 6.0.x
=> Update 6.1.x with latest bug fix from 6.0.x

arches/app/utils/label_based_graph.py, arches/app/utils/label_based_graph_v2.py, tests/utils/label_based_graph_test.py, tests/utils/label_based_graph_test_v2.py
this updates the disambiguated graphs to only associate nodes with a `parentnodegroup` lineage
#7616 
#7977
=> Updates the label-based-graph to associate parent nodegroups #7616
