arches/app/media/js/views/components/resource-report-abstract.js
fixes resource report abstract - brand new reports IDs weren't retrieved within the getjson call. Cherrypicked from 6.1.x, PR #8070
#8068
=> Cherrypick fix for #8068 from 6.1.x

arches/app/media/js/viewmodels/map.js, arches/app/templates/views/components/map-popup.htm
Improves the performance of the map popup when selecting multiple features.
#8064
=> Improve map popup performance, re #8064

arches/app/models/migrations/8085_relational_data_model_handle_dates.py
=> handles for date formatting in relational data model views

arches/app/media/js/viewmodels/workflow.js
Start the loading spinner right after the user click [delete workflow -> OK]
#8044
=> Add loading spinner when delete workflow, #8044

arches/app/templates/views/components/related-instance-creator.htm, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
Replace a close icon (x) with `return` button, #8043 
#8043 
=> Replace the resource instance return button, #8043

arches/app/media/js/bindings/ckeditor.js
Cherry pick for 6.0.0 branch for that resolves #8077 
#8077 
=> rich text disabling cherry pick

arches/app/models/resource.py
Moves datatype lookup inside already existing nullguard in Resource.get_documents_to_index
#8110 
=> moves datatype lookup into existing nullguard #8110

arches/app/media/css/arches.scss, arches/app/media/js/views/components/widgets/rich-text.js, arches/app/media/js/views/components/widgets/text.js, arches/app/models/system_settings.py, arches/app/templates/views/components/search/search-results.htm, arches/app/templates/views/components/widgets/rich-text.htm, arches/app/templates/views/components/widgets/text.htm, arches/app/utils/data_management/resources/formats/csvfile.py
=>  purge i8ln references

arches/app/models/resource.py
Pulls the changes from #8111 , which is 5.1.x based, into 6.1.x
#8110
=> Cherry pick 8111 (nullguard resource index datatype lookup) into 6.0.x , re #8110

releases/6.1.0.md
Adds in initial draft of the 6.1.0 release notes so that they can be maintained leading up to the 6.1 release rather than compiled just before the release.
#8115
=> Add draft release notes for 6.1.x, re #8115

tests/test_settings.py
Generates xml coverage information for unit tests (can be viewed in vscode with coverage gutters plugin)
#8122 
=> unit test coverage xml generation

arches/app/media/css/arches.scss
Removes opacity on selected load masks in order to avoid excessive browser paints.   Performance improvements are small, but noticeable.
#8096 
=> load mask opacity removal

arches/app/media/css/arches.scss
Arrow cursor makes it difficult to see when an element can be clicked on. As per issue raised... #7954 
Ensures the mouse pointer changes to a regular pointer when hovering over the circular plus icons
#
*   Found by: @rlwilliamss
*   Tested by: @rlwilliamss
=> 7954 - Added cursor styling to add icon hover

arches/app/media/js/viewmodels/concept-select.js
Default values for concept lists don't show up in the designer after a refresh - this fixes that.
resolves #7126 
=> Fixes issue with default concept values not showing up.

arches/app/media/js/viewmodels/concept-select.js
fixes concept list default values in arches designer
resolves #7126 
=> cherry pick fix for 7126

arches/app/models/resource.py, arches/app/utils/label_based_graph.py, arches/app/utils/label_based_graph_v2.py, arches/app/views/api.py, tests/utils/label_based_graph_test.py, tests/utils/label_based_graph_test_v2.py
Adds new feature to filter nodes based on card "visible" attribute.  
#7838 
=> filter hidden nodes

arches/app/media/js/viewmodels/workflow.js, arches/app/templates/javascript.htm
Address the issue with the arches instance with not init-workflow, #8125 
#8125 
=> Update the workflow quit url to search homepage

arches/app/media/js/viewmodels/resource-instance-select.js
Make all the functions available in `this` (viewmodel) context, archesproject/arches-for-science#833
In order to make a child context related to the afs workflows.
archesproject/arches-for-science#833
=> Update resource instance widget

releases/6.1.0_draft.md
=> Adds 6.1.0_draft.md

arches/app/models/resource.py, arches/app/tasks.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py, tests/fixtures/testing_prj/testing_prj/settings.py
…ync-update-custom-indices
Cherry picks 8144 into 5.1.x
#8147
=> Cherry picks 8144 into 5.1.x

arches/app/templates/views/components/cards/default.htm, arches/app/templates/views/graph/graph-designer/graph-tree.htm
Renders the card tree (and graph designer) on demand - avoids rendering the entire tree up front.  
resolves #8112 
=> render card tree on demand

arches/app/templates/views/components/cards/default.htm, arches/app/templates/views/graph/graph-designer/graph-tree.htm
Duplicate of #8113 which was mistakenly merged to dev/6.0.x
=> avoids recursive trees in advance of need/expansion

arches/app/utils/label_based_graph.py, arches/app/utils/label_based_graph_v2.py, tests/utils/label_based_graph_test.py, tests/utils/label_based_graph_test_v2.py
=> Updates LabelBasedGraph and LabelBasedGraphV2 to properly identify valid semantic nodes

arches/management/commands/add_test_users.py
Adds dev user to `add_test_users` command and subsequently on package load.
=> Add dev user #7818

arches/admin.py, arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/datatypes/url.py, arches/app/models/fields/i18n.py, arches/app/models/migrations/7805_i18n_domain_datatype.py, arches/app/models/migrations/8130_consolidate_languages.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/search/search_term.py, arches/app/templates/views/rdm/modals/add-child-form.htm, arches/app/templates/views/rdm/modals/add-collection-form.htm, arches/app/templates/views/rdm/modals/add-scheme-form.htm, arches/app/templates/views/rdm/modals/value-form.htm, arches/app/utils/context_processors.py, arches/app/utils/data_management/sparql_providers/abstract_provider.py, arches/app/utils/i18n.py, arches/app/utils/skos.py, arches/app/views/concept.py, arches/install/arches-templates/project_name/datatypes/sample_datatype.py, arches/management/commands/load_jsonld.py, tests/exporter/datatype_to_rdf_tests.py, tests/exporter/jsonld_export_tests.py, tests/fixtures/jsonld_base/models/test_2_complex_object.json, tests/importer/jsonld_import_tests.py
merge the d_languages into the language table and eliminate d_languages
tests still need work, pending fixes for the domain test failures and optional language export css feature.
=> consolidate languages into single table

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/skos.py, arches/management/commands/packages.py, tests/exporter/resource_export_tests.py, tests/localization/field_tests.py
Allows users to choose the language they'll export their CSVs in - defaults to all languages for compatibility
#8154 
=> csv export language choice

arches/app/models/graph.py, arches/app/views/resource.py
To reproduce:
Publish && unpublish a graph, then access the resource editor for a resource based on the graph via the search page.
#8212
-   [ x] Unit tests pass locally with my changes
=> Restabilize publication logic

arches/app/media/js/viewmodels/map.js
Name for features parameter was singularized in #8104 - now it's not found.  This restores the original name/fixes issue.
#8211 
=> fix for 8211, feature/s mismatch

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/functions/primary_descriptors.py, arches/app/models/system_settings.py, arches/app/utils/data_management/resources/formats/rdffile.py, tests/utils/label_based_graph_test.py, tests/utils/label_based_graph_test_v2.py
Fix for 8155 - removes direct checks for the string datatype and modifies the base datatype/string datatype accordingly.  Does not address resources.py - where @apeters addresses the issue checks in csvfile.py - which will be addressed in upcoming PR to address issue #8154 
resolves #8155 
=> remove direct string datatype checks

arches/app/media/css/arches.scss, arches/app/templates/views/components/map-popup.htm
=> #8229 map popup nav buttons

arches/app/search/search_export.py
Fixes bug detailed in Issue #8201 
@chiatt would you be happy to take a look at this?
=> Fix GeoJSON Export

arches/app/views/plugin.py
Fixes issue with plugins redirecting to home instead of the login view.
#8271 
=> unauthenticated plugins redirect to authenticate

arches/app/media/js/viewmodels/card-component.js
Fixes issue where missing required fields using the workflow default component cause the loading mask to cease to go away
#8268 
=> fix issue with default card component required fields in workflows

arches/app/media/css/arches.scss, arches/app/templates/base-manager.htm, arches/app/templates/views/components/plugins/workflow.htm
=> first attempt at responsive workflow design

arches/app/models/graph.py, arches/app/models/migrations/7784_add_serialized_graph_to_graph_publications.py, arches/app/views/graph.py, arches/app/views/tile.py
Fix for issue where a string based index was expected, but a string object was received.  This happened because the graph was saved to the db as a string instead of a JSON structure
Fixes #8172 
=> graph publication column save type should be json instead of string

arches/app/models/graph.py, arches/app/models/migrations/7783_add_graph_publications.py, arches/app/models/migrations/7783_make_settings_active.py, arches/app/models/migrations/7784_add_serialized_graph_to_graph_publications.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/utils/data_management/resource_graphs/importer.py, tests/exporter/resource_export_tests.py, tests/fixtures/jsonld_base/models/6235_parenttile_id.json, tests/models/graph_tests.py, tests/models/resource_test.py, tests/models/tile_model_tests.py, tests/views/search_tests.py
This is meant to supercede: https://github.com/archesproject/arches/pull/8191
=> 8186 publication id preservation

arches/app/media/js/viewmodels/card-component.js, arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/workflows/workflow-component-abstract.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/cards/default-card-report.htm, arches/app/templates/views/components/plugins/workflow.htm, arches/app/views/api.py, arches/urls.py
=> Handle tile data in workflows

arches/app/search/time_wheel.py
#8287 arches issue - timewheel range bug
Fix avoids processing dates not selected for display in TIMEWHEEL_DATE_TIERS range setting.
#8287 
#
*   Sponsored by: @HistoricEngland
*   Found by: @rlwilliamss
*   Tested by: @khodgkinson-he 
*   Designed by: @khodgkinson-he
=> 8287 Timewheel inefficiently handling range processing, causing timeouts, fix.

arches/app/media/js/viewmodels/resource-instance-select.js
Prevent error if iconclass not available, re #8311
=> Prevent error if iconclass not available, re #8311

arches/app/media/js/viewmodels/map.js, arches/app/media/js/views/components/cards/related-resources-map.js, arches/app/templates/views/components/cards/related-resources-map-popup.htm
Fixes a bug in the relate resources map card preventing the creation of resource relationships using the map popup.
=> Fix bug in relate resources map popup, re archesproject/arches_her#800

arches/app/media/css/arches.scss, arches/app/templates/views/map-layer-manager.htm
Allows map layer manager layer list and main panel to scroll vertically and removes some css cruft. re #8300.
=> Fix map layer manager scrolling, re #8300

arches/app/etl_modules/import_single_csv.py, arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/models/migrations/8009_etlmodule.py, arches/app/models/models.py
Add load_details to the load_event table in the db, #8291 
Update single csv importer to reload the import mapping by utilizing load_details
#8291 
=> Add load event details, #8291

arches/app/templates/views/resource/editor.htm
Remove hard-coded slash, re #7503
=> Remove hard-coded slash, re #7503

arches/app/datatypes/datatypes.py, arches/app/media/js/views/components/widgets/edtf.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/edtf.htm, arches/app/views/admin.py, arches/app/views/api.py, arches/urls.py
Update edtf widget to show the transformed value (the proper edtf format) and save the tile with the transformed value, #8282
(Edtf widget has a utility function to transform the non edtf format to edtf format if the date valid date format but it did not show the transformed value nor save it as transformed.)
#8282 
* …
=> 8282 edtf datatype widget

arches/app/media/css/arches.scss
=> fix switch widgets

arches/app/media/js/viewmodels/map-filter.js, arches/app/templates/views/components/related-resources-map-editor.htm
Adds coordinate editing to related resource map card
#8345
=> Related resource map card coords, #8345

arches/app/datatypes/datatypes.py
Adds a colon to a timezone to ensure elastic can index
#8328
=> Adds a colon to a timezone to ensure elastic can index, re #8328

arches/app/media/js/viewmodels/card-component.js
Allows user to override cardinality in workflows.
#8350 
=> adds cardinality overide to workflow #8350

arches/app/media/css/arches.scss, arches/app/media/css/rtl.scss
Fixes checkboxes and radios so that they mirror correctly
#8254 
=> 8254 checkboxes radios

arches/app/media/css/app.css, arches/app/media/css/arches.scss, arches/app/media/css/rtl.scss, arches/app/media/js/bindings/chosen.js, arches/app/templates/views/graph.htm, arches/app/templates/views/resource.htm
Fixes RTL for graph designer landing page
#8252 
=> RTL in graph designer landing page

arches/app/etl_modules/branch_csv_importer.py, arches/app/models/migrations/8009_etlmodule.py, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm
Add the error reporting to load staging table and retrieve the message when validating, #8380 
#8380
=> Update etl error reporting, #8380

arches/app/etl_modules/branch_csv_importer.py, arches/app/media/js/views/components/etl_modules/branch-csv-importer.js
Handle db writing error, #8386
#8386 
=> Handle writing db error, #8386

arches/app/etl_modules/branch_csv_importer.py, arches/app/media/css/arches.scss, arches/app/media/js/viewmodels/base-import-view-model.js, arches/app/media/js/views/components/etl_modules/branch-csv-importer.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm, arches/app/templates/views/components/plugins/etl-manager.htm, arches/app/views/etl_manager.py, arches/management/commands/etl_template.py
Improves validation reporting, Brings UI layout closer to mockup, and saves files to tmp/[loadid] rather than just /tmp
#8384
#8379
=> Improve branch csv UI #8379 

arches/app/views/concept.py
=> add exact match to top of concept search list, re #8355

arches/app/media/js/views/components/etl_modules/branch-csv-importer.js, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm, arches/app/views/etl_manager.py, arches/management/commands/etl_template.py, arches/urls.py
=> mvp for template download functionality

arches/app/functions/primary_descriptors.py, arches/app/media/js/views/resource/editor.js, arches/app/models/resource.py, arches/app/models/tile.py, arches/app/templates/javascript.htm, arches/app/utils/data_management/resources/formats/htmlfile.py, arches/app/utils/label_based_graph_v2.py, arches/app/views/api.py, arches/app/views/resource.py, arches/management/commands/load_jsonld.py, tests/utils/label_based_graph_test_v2.py
Passes copy context to functions on save so that functions can behave accordingly
re #8171
=> Pass copy context to functions, re #8171

arches/app/media/js/views/components/iiif-viewer.js, arches/app/media/plugins/leaflet-side-by-side/index.js, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/plugins/manifest-manager.htm
Image slider usability fixes/enhancements
#8367
#8368 
#8369 
#8370 
#8371
=> image slider usability fixes and enhancements

arches/app/media/js/bindings/ckeditor.js
Fixes issues with ckeditor/webpack
#8402 
=> ckeditor fix

arches/app/media/css/arches.scss, arches/app/templates/views/report-templates/default.htm
Fix RTL overlap issue with Hide Null Values switch in reports, re #8244
=> Fix RTL issues with hide null values switch in report, re #8244

arches/app/datatypes/datatypes.py, arches/app/models/resource.py, arches/app/views/resource.py
Ensures displayname is added to the resource as a string rather than a method.
=> Adds missing displayname to related resources request, re #8415

arches/app/media/js/views/components/iiif-viewer.js
The iiif layer adds its layers to the map asynchronously.  The side by side layer is expecting its layers to be _fully rendered_ before it actually uses them in comparison.  As a result, this PR attempts to leverage the "load" event of a leaflet layer (in which all tiles are fully rendered) in order to do the leaflet side by side operations.  Additionally, the zoom to bounds function is modified and only executed on manifest change.   …
=> fixes for asynchronous iiiflayer vs synchronous side by side layer

arches/app/views/search.py
Search Filters - look in request POST data for filter parameters
Allow search filters to be passed to the server in request POST data
#8412
=> 8412 - Check for search filter parameters in POST portion of request

arches/app/media/css/arches.scss, arches/app/media/css/rtl.scss, arches/app/templates/views/components/search/advanced-search.htm, arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm, arches/app/templates/views/mobile-survey-manager.htm, arches/app/templates/views/resource/permissions/permissions-manager.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> fix the location of the clear node search button, re #8417

arches/app/models/migrations/8247_update_primary_descriptors_config.py
Replaces instead of modifies primary descriptor default config
#8442
=> Replace instead of modify primary descriptor default config, re #8442

arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py, arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/plugins/etl-manager.htm
Update the status logics and available actions, #8423 
Also replace graph id with graph name in the status tab, #8421
Fix reverse transaction
Fix a server error
#8421 
#8423 
=> update status &. available actions, #8423

arches/app/datatypes/datatypes.py, arches/app/views/api.py
Update edtf transform value for tile to return just value not tuple, #8447
#8447
=> Update edtf transform value for tile, #8447

arches/app/datatypes/datatypes.py, arches/app/etl_modules/branch_csv_importer.py, arches/app/media/js/views/components/etl_modules/branch-csv-importer.js
Fix a couple of issue for etl from various datatypes, #8420 
Number: when the value is not number at all (since only happens during etl since ui does not allow this)
EDTF: accept only value from the tuple (value, validity) returned from the transfrom_value_for_tile
Also, fix the file extension of the generated templates
#8420 
*   Tested …
=> Fix various etl issues, #8420 

arches/app/media/js/views/graph/permission-manager/permission-settings-form.js, arches/app/templates/admin/change_form.html, arches/app/templates/javascript.htm
Add context root to clear-user-permission-cache URLs
#8424
=> 8424 hard coded permissions url

arches/app/models/migrations/8009_etlmodule.py
Check null for resource type before accessing json element during etl using db, #8454
#8454 
=> Check null for resource type during etl using db, #8454

arches/app/media/js/utils/map-popup-provider.js, arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/viewmodels/map.js
Fix the issue of popup appears while creating features
#8444
=> Disable popup when creating geometry, #8444

arches/app/etl_modules/branch_csv_importer.py, arches/app/tasks.py
Add support for celery to ETL Manager, #8461
#
=> Add support for celery to ETL Manager, #8461

arches/app/etl_modules/import_single_csv.py, arches/app/models/migrations/8009_etlmodule.py, arches/app/templates/views/components/etl_modules/import-single-csv.htm
Fix the errors from 1. missing node for csv columns, 2. handles null value when transform staging to tile table
#8484
=> Update single csv importer to handle missing values, #8484

arches/app/media/js/models/node.js
Prevent error if updated_values is undefined, re #8476
=> Prevent error if updated_values is undefined, re #8476

arches/app/media/js/views/components/plugins/etl-manager.js
Updates the details/stats of load if the state of the selected load changes. Previously a user would have to click on the selected load to see the data change.
#8501
=> Update details/stats when state of selected load changes, re #8501

arches/app/templates/views/components/related-instance-creator.htm
Add loading mask in the related resource creation panel, #8524
#8524 
=> Add loading mask in the related resource creation panel, #8524

arches/app/templates/views/components/plugins/etl-manager.htm
Stop Task is currently unavailable, so the button (kink) is removed from etl status, #8510 
#8510 
=> Remove the "stop task" button from etl status, #8510

arches/app/models/migrations/8009_etlmodule.py, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm
Change the label of "branch csv" to "branch excel", #8521 
#8521 
=> Change branch importer label, #8521

arches/app/etl_modules/branch_csv_importer.py, arches/app/models/migrations/8449_filter_warning_etl_module.py
Filter out validation warnings that were stopping ETL module data load, re #8449
#
=> Filter warnings that stopped load when using ETL manager, re #8449

arches/app/models/migrations/8502_loadevent_indexed_time.py
Fixes broken migration depenencies
=> Fix broken migration depenency

arches/app/etl_modules/branch_csv_importer.py, arches/app/templates/views/components/plugins/etl-manager.htm
Informs user that load failed because legacy ids in excel file already exist in the database., re #8513
=> Show legacy id error, re #8513

arches/app/media/css/arches.scss, arches/app/tasks.py, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/plugins/etl-manager.htm
=> RE; #8504 update etl manager UI

arches/admin.py, arches/app/models/migrations/8009_etlmodule.py, arches/app/views/etl_manager.py
Allows admin to control module access using either a 'show' property on the module's config field or guardian permissions
#8543
=> Allow admin to control module visibility and access, re #8543

arches/app/models/mobile_survey.py
Fix of the issue collector app does not take the updated descriptor function config, #8540 
A temporary fix to reshape the descriptor config to the old shape before send to the mobile device.
#8540 
=> Descriptors function in mobile project, #8540 

arches/admin.py, arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py, arches/app/media/css/arches.scss, arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/models/migrations/8009_etlmodule.py, arches/app/models/migrations/8528_bulk_load_performance_functions.py, arches/app/models/mobile_survey.py, arches/app/search/search_export.py, arches/app/tasks.py, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/plugins/etl-manager.htm, arches/app/templates/views/components/search/resource-type-filter.htm, arches/app/views/etl_manager.py, arches/app/views/transaction.py
Update dev/6.2.x with latest in 6.1.x
=> Update dev/6.2.x with latest in 6.1.x

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/datatypes/url.py, arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py, arches/app/models/tile.py, arches/app/utils/file_validator.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/install/requirements.txt, arches/settings.py, tests/fixtures/datatypes/color.py, tests/fixtures/datatypes/semantic_like.py
Allows for file type validation for a limited subset of files accepted into arches.  Defaults to being turned off. 
#
=> Allow for file type validation for a subset of files 

arches/__init__.py
Sets 6.1.x version to next beta patch release
=> Sets 6.1.x version to next beta patch release

arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/templates/views/components/plugins/etl-manager.htm, releases/6.1.0.md
Add confirmation dialog to etl manager when undoing a load, re #8550
=> Add confirmation dialog to undo etl manager load, re #8550

arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py, arches/app/tasks.py
Notify the user when the etl task using the celery is done, #8503 
#8503
=> Notify when the import using celery is done, #8503

arches/app/media/css/arches.scss
Adjust the width of control panel to show the images consistently, #8174 
#8174 
=> Image service minor UI update, #8174

arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/utils/data_management/resources/formats/csvfile.py
Moves some of the concept and domain specific logic into their respective datatype methods and fixes import of the domain and domain-list values. 
#8594
=> Moves datatype code to datatype/fixes domain value import, re #8594

arches/app/utils/data_management/resources/formats/rdffile.py, arches/management/commands/load_jsonld.py
=> allow users to print detailed logging information to the screen, re #8623

arches/app/media/css/arches.scss, arches/app/templates/base-manager.htm, arches/app/utils/context_processors.py
Adds a debug indicator and arches version
#7517
=> Add debug indicator and arches version, re #7517

arches/app/models/fields/i18n.py
=> fix JSONField errors with i18n

arches/app/models/migrations/8220_node_hascustomalias.py
Fixes order of migration dependencies following merge of custom aliases migration.
=> Fix migration dependency order, re #8220

arches/app/utils/data_management/resources/formats/rdffile.py, arches/management/commands/load_jsonld.py
=> notify when json-ld loader fails to load, allow ignore-errors flag

arches/app/media/js/views/components/widgets/map/bin-feature-collection.js, arches/app/templates/views/graph.htm, arches/app/templates/views/graph/graph-designer/graph-tree.htm
Ensure underscore imported in bin-feature-collection.js
#8631
=> Ensure underscore imported in bin-feature-collection.js re #8631

arches/app/utils/data_management/resource_graphs/importer.py, arches/app/views/graph.py
Ensure imported graphs use i18n_String field before publishing.
#8676
=> Ensure imported graphs use i18n_String field before publishing, re #8676

arches/app/media/js/views/graph/graph-manager/branch-list.js
Updates 7.0.x with bug fix in 6.2.x related to underscore.js upgrade
#8631
=> Updates 7.0.x with bug fix in 6.2.x

arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm
=> Fix single csv trans strings

arches/app/templates/base-manager.htm
removed click binding on <li> element
#8687
=> fixes sidenav resource link behavior #8687

arches/app/media/js/views/components/related-instance-creator.js
Sort the cards from card api response to show the top cards in the original order, #8686
#8686
=> Sort cards for related resource creation, #8686

arches/app/templates/views/components/cards/default-card-report.htm, arches/app/templates/views/components/search/term-filter.htm, arches/app/views/tile.py
Prevents error when deleting tiles. Also removes some cruft and unnecessary db queries.
#8685
=> Prevent error when deleting tiles, re #8685

arches/app/search/search.py
To reproduce:
Load arches-HER v7
navigate to the graph designer
navigate to the application area resource model
navigate to the cards tab, then the descriptions card
notice the error described in the ticket has no longer appears
#8708
=> updates kwargs logic in search.py #8708

arches/install/requirements.txt
Upgrades django celery results to more secure version #8704
=> Upgrade django-celery-results re #8704

releases/7.0.0_draft.md
Update release doc with first draft of enhancement list
=> Add first draft of enhancement list

releases/6.2.0.md
Updates 6.2.x release notes with enhancements and dependency changes
=> Updates release notes with enhancements and dependency changes

arches/install/arches-templates/project_name/package.json
=> updates generated package.json dependency #8782

arches/app/models/migrations/7794_i18n_string_datatype.py
Makes default string widget value an object with empty string
#8769
=> Makes default string widget value an object with empty string, re #8769

arches/app/templates/javascript.htm, arches/app/templates/views/components/language-switcher.htm, arches/app/views/main.py, arches/templatetags/template_tags.py, arches/urls.py
fixes language switcher, also adds a new django tag to escape js strings.  
#8791 
=> fix language switcher

arches/app/utils/data_management/resource_graphs/exporter.py
Fix issue where mapping files could not be exported in some cases, re #8723
=> Fix issue where mapping files were not able to be exported, re #8723

arches/app/media/js/viewmodels/tile.js
Allows card to update with provisional edits
#8744
=> Fixes provisional editing bug

arches/app/templates/views/components/iiif-annotation.htm, arches/app/templates/views/components/iiif-widget-annotation.htm, arches/app/templates/views/components/plugins/manifest-manager.htm
=> resolve  iiif annotation dropdown not showing features

arches/app/media/js/viewmodels/card.js, arches/app/media/js/viewmodels/tile.js, arches/app/media/js/views/resource/editor.js, arches/app/templates/views/components/cards/default.htm
Updates frontend files to handle for missing nodegroup. The only change of significance is in `arches/app/media/js/views/resource/editor.js`
#8779
=> fix nodegroup restrictions resource editor cause page break

arches/management/commands/updateproject.py, releases/7.0.0_draft.md
Updates the `updateproject` management command to copy the webpack config files from arches-core to the project
#8792
=> Copy webpack config files to project in `updateproject` management command re #8792

arches/app/media/js/viewmodels/tile.js
Makes tile data is a koMapping object
#8744
=> Make tile data is komapping object, re #8744

arches/app/media/js/rdm.js, arches/app/media/js/viewmodels/file-widget.js, arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/views/components/iiif-annotation.js, arches/app/media/js/views/components/widgets/rich-text.js, arches/app/media/js/views/components/widgets/text.js, arches/app/media/js/views/rdm/concept-report.js, arches/app/templates/javascript.htm
Reverses pattern change that unblocked early webpack development
#8811 #8810
=> fixes tile-reset form listener pattern #8811

arches/app/templates/views/components/file-workbench.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> updates egText placeholder pattern #8745

arches/app/models/graph.py
Fix issue where graphs could not be deleted in the graph manager, re #8725 
-   [x]Bugfix (non-breaking change which fixes an issue)
#
=> 8725 delete model bug

arches/app/media/css/arches.scss, arches/app/templates/views/graph/graph-designer/card-tree-permissions.htm, arches/app/templates/views/graph/graph-designer/card-tree.htm, arches/app/templates/views/graph/graph-designer/graph-tree.htm
=> fix arches designer tree scroll height

arches/app/models/migrations/8813_resource_model_view_defaults.py
We elected to hardcode "en" as the language we're looking for by default in the __arches_create_resource_model_views - for all other needs, the user can pass in a schema_name manually. 
#8813 
=> fixes the defaults for resource model creation 

arches/app/templates/views/graph/function-manager.htm, arches/app/templates/views/graph/graph-base.htm
Fixes function button alignment; also RTL for function buttons.
closes #8793 
=> function button alignment fix

arches/app/search/components/sort_results.py
display name is now a nested type; prior to this change it was a flat string.  This allows us to sort based on language
closes #8775 
=> i18n search results ordering

arches/app/media/js/views/user-profile-manager.js
Added throttle to `updateNotifTypes` onload trigger
#8717
=> throttles POST to create user notification #8717

arches/install/arches-templates/project_name/package.json, arches/install/arches-templates/project_name/webpack/webpack.common.js, package.json, webpack/webpack.common.js
General webpack Quality of Life updates: explicitly sets 8GB memory in webpack processes to prevent heaperror, colors warnings/errors of build process, and handles for errant .DS_Store files
#8826
=> webpack QoL updates #8826

arches/app/media/css/arches.scss
Hide buttons from the widget in the workflows, #8683 
#8683 
=> Hide widget button workflow, #8683

arches/app/media/js/views/components/widgets/rich-text.js, arches/app/templates/views/components/widgets/rich-text.htm
Update rich text widget to work properly (edit, undo, save...) for i18n.
#8828
=> Update rich text widget for i18n, #8828

arches/app/utils/permission_backend.py
Hides manage link on index page if user is not in resource editor group
#8780
=> Hide manage link if user is not in resource editor group, re #8780

arches/app/media/css/arches.scss, arches/app/tasks.py
=> Update css in search result notification download button, #8777

arches/app/media/css/arches.scss
Fix the simple switch ui for rtl, #8830 
#8830
=> Simple switch ui fix for rtl in the graph designer, #8830

arches/app/datatypes/base.py, arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py, arches/app/datatypes/url.py, arches/app/functions/primary_descriptors.py, arches/app/models/migrations/8838_descriptors_update.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/search/mappings.py, tests/fixtures/data/json/resource_export_business_data_truth.json, tests/views/search_tests.py
Changes the descriptor name field to be i18njson - to support multiple values for different languages.  Changes how indexing happens - to minimize issues with things that depend on the display_descriptors fields, it just keeps an array of values with a language key.  Changes when descriptor name is saved and allows you to request language specific versions of a string based primary descriptor.  
closes #8838  …
=> descriptor changes for i18n

arches/app/models/migrations/8009_etlmodule.py
Rename the etl manager to bulk data manager, #8473 
#8473
=> Rename etl manager to bulk data manager, #8473

arches/app/templates/admin/change_form.html
updates modal css to be legible
#8695
=> updates user permission cache modal CSS

arches/app/views/resource.py
Update the logic to get cardwidgets when serialized graph isn't available. #8861 
#8861
=> Update the logic to get cardwidgets for editor, #8861

.gitignore, arches/app/media/build/.gitignore, arches/install/arches-templates/.gitignore, arches/install/arches-templates/project_name/webpack/webpack.common.js, releases/7.0.0_draft.md, webpack/webpack.common.js
=> webpack qol updates re #8881

arches/install/requirements.txt
https://github.com/advisories/GHSA-8x94-hmjh-97hq/dependabot
=> update Django to 3.2.15 to fix high severity bug, re #8882

CONTRIBUTING.md, contributing/css-styleguide.md
=> adds CSS styleguide to contributing documentation

arches/app/media/js/views/resource/edit-log.js, arches/app/templates/views/resource/edit-log.htm
makes edit log card handling recursive to allow for any depth of tiles
fixes #8879
=> fixes edit log for nested tiles

releases/7.0.0_draft.md
Adds documentation on es 8 security
#8900 
=> 8900 es security documentation

arches/app/media/css/arches.scss, arches/app/templates/views/components/language-switcher.htm
=> #8894 update header button css

arches/db/system_settings/Arches_System_Settings.json, arches/db/system_settings/Arches_System_Settings_Model.json
Update system settings graph and resource, #8888 
#8888
=> Update the system setting graph and the resource, #8888

arches/app/media/css/arches.scss
Fixes profiles for RTL 
fixes #8608 
=> profile fix for RTL

arches/install/arches-templates/project_name/urls.py-tpl
Disable i18n url patterns (which includes the language code in the url) temporarily to fix the issue with language switcher. #8831
It is desirable to make both the language switcher and i18n url working in the future.
#8831
=> Comment out the i18n url patterns, #8831

arches/app/media/css/arches.scss, arches/app/media/css/rtl.scss, arches/app/media/css/tree.scss, arches/app/media/js/bindings/term-search.js, arches/app/templates/views/components/cards/default.htm, arches/app/templates/views/components/cards/grouping.htm, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/map.htm, arches/app/templates/views/components/search/search-results.htm, arches/app/templates/views/components/search/time-filter.htm, arches/app/templates/views/map-layer-manager.htm
=> 8871 rtl padding fixes

arches/app/models/resource.py
Uses the most suitable language for a related resource if a descriptor is not available in the current language.
#8910
=> Use best descriptor string in related resources, re #8910

arches/app/media/css/arches.scss
Fixes saved search overlap
#8924 
=> Fix issue with saved search overlap

releases/6.2.0.md, releases/7.0.0_draft.md
=> updates release docs re #8920

arches/app/media/css/arches.scss
=> fixes overlap issue in RTL as well as placement of tools, re #8926

arches/install/arches-templates/project_name/package.json
=> updates project package.json re #8932

arches/app/media/css/arches.scss
fixes tree filter css re: #8911
=> 8911_tree_filter_css

arches/app/models/resource.py
Update how to get paginated response of related resource response, #8916 
Fix the issue not loading the 2nd page or higher.
#8916 
=> Update related resource pagination, #8916 

arches/install/requirements.txt, releases/7.0.0.md
=>  update requirements to use arches revproxy re 8941

arches/app/models/migrations/6837_add_annotations_view.py
Cast feature column in annotation view as jsonb to support django 3.2
#8935
=> Cast feature column in annotation view as jsonb to support django 3.2, re #8935

arches/app/media/js/views/resource/edit-log.js, arches/app/templates/views/resource/edit-log.htm
cherrypick makes edit log card handling recursive, re: #8879
#8879
=> cherrypick makes edit log card handling recursive, re: #8879

arches/app/media/css/arches.scss
ensures search sidebar appears over workbench components
fixes #8952
=> updates search sidebar z-index, re: #8952

arches/app/datatypes/concept_types.py, arches/app/datatypes/datatypes.py
Fixes issues with csv importer improperly interpreting some csv values
#8956
=> Improve csv value interpretation, re #8956

arches/app/models/migrations/7131_update_annotations_view.py, arches/app/models/migrations/7442_move_data_from_manifest_images_table_to_files_table.py
Fix migration annotation by casting feature to jsonb, #8935 
#8935 
=> Fix migration of annotation (for Django 3), #8935

arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py
=> update error message when Celery isn't running, re #8963

arches/app/models/migrations/8974_rr_load_performance_v2.py
=> fix sql error in __arches_create_resource_x_resource_relationships, re #8974

arches/install/arches-templates/project_name/settings.py-tpl, arches/install/arches-templates/project_name/webpack/webpack.common.js, arches/webpack/webpack.common.js
=> updates webpack config to be docker compatible #8978

arches/app/media/js/views/components/iiif-viewer.js, arches/app/media/js/views/components/plugins/manifest-manager.js, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/plugins/manifest-manager.htm, arches/app/views/manifest_manager.py
Update images service manager archesproject/arches-for-science#942
1. Add placeholder for attribution logo and update the logic to get logo from url
2. Update the metadata when it is not added but filled and allow to delete metadata when deleted
3. Use the first image name as a service title by default
#8973
*   Designed …
=> Afs942 update manifest manager

arches/app/models/graph.py
Prevent alias from getting recalculated on graph import
#8983
=> Do not overwrite alias on import if it already exists, re #8983

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/models/system_settings.py
=> fix issue with configurable system settings not working as expected

releases/7.1.1.md
=> adds 7.1.1 release notes #8990

arches/app/media/js/viewmodels/card.js
Add the incoming parameters to add the current card so that they can be used outside of card vm.
This addition is needed to archesproject/arches-for-science#972 to work.
#
=> Add all the params to card viewmodel, afs#972

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
=> updates card adapter #9005

arches/app/models/resource.py
Fix the related resource paging issue in the editor related resource page, #8916
#8916 
=> Fix the related resource paging, #8916

arches/app/media/css/arches.scss, arches/app/templates/views/components/iiif-viewer.htm
=> 8998 css updates

releases/6.2.0.md
=> updates 6.2.0.md

arches/app/media/js/bindings/ckeditor.js
=> fix rich text editor readonly bug

arches/app/models/concept.py
Solution based from: https://docs.djangoproject.com/en/4.1/topics/db/sql/#executing-custom-sql-directly
#9019
=> protects concept.py get_e55_domain from sql injection #9019

arches/app/media/js/views/components/datatypes/string.js
Select the default language automatically in the string widget in the advanced search., #9028 
#9028
=> Select the default language in advanced search, #9028

arches/app/media/js/bindings/datatable.js
=> Fix conditional detecting when serverSide is true, re #9030

arches/app/media/js/views/components/datatypes/domain-value.js
Add upderscore (_)  in the dependency in the domain widget vm, #9026
#9036 
=> Add dependnecy domain widget, #9036 

arches/app/media/js/views/user-profile-manager.js, arches/urls.py, releases/6.2.0.md
=> cherry-pick fixes from later versions into 6.2

arches/install/supervisor_celery_setup/my_proj_name-celeryd.conf, releases/6.2.0.md
Updates celery config for new version
#9031
=> 9031 cbyrd update celery config

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
=> updates workflow to handle cards without resourceinstance_id #9061

arches/app/utils/data_management/resources/formats/rdffile.py
In response to the feedback from : https://github.com/archesproject/arches/pull/8967
=> Check bnodeid exists in tile data

arches/app/models/concept.py, arches/app/views/concept.py
fixes #9019, #9021, #9026 in stable/6.1.0
=> fixes #9019, #9021, #9026 in stable/6.1.0

arches/app/models/concept.py, arches/app/views/concept.py
fixes #9019, #9021, #9026 in stable/7.1.1
=> fixes #9019, #9021, #9026 in stable/7.1.1

arches/install/arches-templates/project_name/webpack/webpack.config.prod.js, arches/webpack/webpack.config.prod.js
Updates webpack production config to handle Prototype calls
#9012
=> updates webpack prod config #9012

arches/locale/fr/LC_MESSAGES/django.po, arches/locale/ur/LC_MESSAGES/django.po
=> adds updated French and Urdu languages from Transifex, re #9063

arches/app/views/auth.py
Fix for #8753, ported to 6.2.x
=> import validationError, fixes issue #8753

arches/app/etl_modules/import_single_csv.py, arches/app/templates/views/components/datatypes/number.htm
Add the config to properly transform data for concept datatype, #9078 
Also check if the value is empty string before try to transform, if the value is "" turn it into None.
Fix the issue the single csv importer for the concept and resource instance datatype
#9078 
=> Fix concept import in the single csv importer, #9078

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
=> updates workflow card adapter

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
updates card adapter to handle cardinality n
=> updates card adapter to handle cardinality n

arches/app/utils/data_management/resources/formats/rdffile.py
=> no need to check for nodeid in @id field, re #9098

arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/media/js/views/components/widgets/edtf.js
Update single csv importer to return viewmodel, so that a custom module can extend it.
Also, fix a small issue with edtf, in case the value is not an observable.
#9103
=> Update single csv impoter to return vm, #9103

arches/app/models/graph.py
=> lang delete bug

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/search/components/term_filter.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/templates/views/components/datatypes/string.htm
Add some new search capability in the term search and advanced search, #8994, #9000, #9001, #9002
- Resource ID search capability in the term search
- Exact String Match Search (full text or partial match in the term search and the advanced search (eg. "exact match", 'exact match')
- Empty String ("") Search is working as a part of the Exact String Search
- Wild card search capability with wild card in a single word in the term search and the advanced search (eg. wildcard, *card, ?ildcard ,etc)
#8994, #9000, #9001, #9002
-   [ ] Unit tests pass locally with my …
=> Update search filters, #8994, #9000, #9001, #9002

arches/app/search/mappings.py
=> limit length of keyword strings that can be indexed

arches/app/utils/data_management/resources/formats/rdffile.py
re #8800 
This is cherry picked from @aarongundel work done here: https://github.com/archesproject/arches/pull/8801
=> don't add child tiles that don't point to parent tiles during jsonld import

arches/app/models/graph.py, arches/app/models/migrations/9053_add_future_graphs.py, arches/app/models/models.py, arches/app/views/graph.py
Add columns to reference source records for cards, nodes, and edges.   Resolves #9116 
=> create references to source record

arches/app/media/js/bindings/ckeditor.js, arches/app/media/js/views/components/widgets/rich-text.js, arches/app/media/js/views/components/widgets/text.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/widgets/rich-text.htm, arches/webpack/webpack-node-modules-aliases.js, package.json, yarn.lock
Updates the CKEditor package and adds placeholder for rich-text-widget
#9125
=> create rich text widget placeholder

arches/app/media/js/views/components/resource-report-abstract.js
Removes param to exclude related resources on report load, re #9131
=> Remove call to exclude related resources, re #9131

arches/app/media/js/views/components/widgets/rich-text.js, arches/app/media/js/views/components/widgets/text.js
Rich Text widget fix for null currentValue JSON value
#9101 
=> 9101 - Check for null currentValue before trying to set i18n value

package.json
=> updates jquery to 3.6.2

arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm, arches/app/templates/views/components/plugins/etl-manager.htm
=> Refactor etl modules for bulk editing. #9122

README.md, arches/__init__.py, package.json, releases/7.2.1.md
=> Updates dev/7.2.x with info for 7.2.1

arches/app/utils/external_oauth_backend.py, arches/app/views/auth.py, arches/settings.py
improves local application URL handling in our oAuth logic/views
re: #9075
=> improves application url handling in SSO re: #9075

arches/app/datatypes/datatypes.py, tests/views/api_tests.py
=> fixes null search bug, re #9173

arches/app/etl_modules/bulk_data_editor.py, arches/app/media/js/views/components/etl_modules/bulk-data-editor.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/models/migrations/9141_bulk_editing_module.py, arches/app/tasks.py, arches/app/templates/views/components/etl_modules/bulk-data-editor.htm, arches/app/templates/views/components/plugins/etl-manager.htm, arches/app/utils/index_database.py
Add bulk data editing module, #9141
#9141
=> Bulk data editor ETL module, #9141

arches/app/models/migrations/9141_bulk_editing_module.py
Fix migration conflicts for bulk editor, #9141
#9141 
=> Bulk editor - Fix migration conflicts, #9141

arches/app/views/auth.py, arches/settings.py
=> adds support for multiple sso domains

.stickler.yml
Updates stickler config to re-enable check
#9182
=> restabilizes stickler for 7.0+ branches

arches/install/requirements.txt, releases/7.3.0.md
=> 7.3.x release prep

arches/__init__.py
=> Set version to 730 final

arches/app/media/js/utils/resource.js, arches/app/media/js/viewmodels/card.js, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/viewmodels/tile.js, arches/app/models/migrations/9188_feature_annotation_type.py
There's an issue with the lookupResourceInstanceData where tile data isn't loaded.  
It seems like it should be loaded by default when a specific resource id is given in this utility function.  
#
=> tile loading issue in resource.js utility

arches/app/utils/data_management/resource_graphs/exporter.py, arches/app/utils/data_management/resource_graphs/importer.py
Update import / export logics to create the editable version of the graph when the graph is imported and export the correct original graph, #9210
#9120 
=> Import/export to handle editable version, #9120

arches/app/media/js/views/base-manager.js, arches/app/media/js/views/components/search/advanced-search.js, arches/app/media/js/views/graph.js
-   [X] New feature: hide futures graphs in graph designer index, resource manager index, and advanced search pages
- #9118
=> 9118 hide future graphs in graph designer

arches/app/templates/views/components/widgets/rich-text.htm, arches/app/templates/views/components/widgets/text.htm
=> 9142 - Fix bug causing empty text nodes to display when Hide Null Values selected

arches/install/requirements.txt
Upgrades psycopg2 to latest feature release. Replaces PR #7552
=> Upgrades psycopg2 to v2.9.5

arches/app/models/migrations/9165_error_reporting.py
Fixes migration dependency order, re #9165
=> Fixes migration dependency order, re #9165

arches/app/templates/views/graph-designer.htm
Update the button labels in the graph designer to reflect the change which allows the users to edit the published graph
#9121 
=> Rename the button labels in the designer, #9121

arches/app/datatypes/datatypes.py
Ensure resource instance datatype reports errors for bulk loader, re #9165
=> Improve resource instance error reporting

arches/app/models/migrations/9147_get_tile_cardinality_violations_i18n.py
=> fixes migration issue, re #9215

arches/app/etl_modules/import_single_csv.py, arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/tasks.py, arches/app/templates/views/components/etl_modules/import-single-csv.htm
Update Single CSV Importer to support i18n string, #9163 
#9163 
=> Update single csv importer to support i18n, #9163

arches/app/media/js/views/components/search/advanced-search.js
Fixes sort order of widgets in advanced search
#9217
=> Sort nodes in search facets, re #9217

arches/__init__.py
Update version number to correct version.
=> Updates version number to 7.4

arches/app/media/js/viewmodels/card.js, arches/app/models/card.py, arches/app/models/graph.py
Prevents the automatic creation of card constraints without associated nodeids reducing the number of unneeded constraint validation queries.
#7181
=> Prevent unnecessary card constraint queries, re #7181

arches/app/media/js/viewmodels/file-widget.js
=> fix relative/absolute file path issue, re #9228

arches/app/models/resource.py
Reduces queries to the function table get primary descriptors.
#9232
=> Use descriptor from resource instance if available, re #9232

arches/app/datatypes/concept_types.py
Corrects invalid concept id property.
=> Concept id prop is concept_id, not conceptid

arches/app/utils/data_management/resources/formats/rdffile.py, tests/fixtures/jsonld_base/models/required_ambiguous_nodes.json, tests/importer/jsonld_import_tests.py
=> 9223 jsonld parser fixes

arches/app/media/js/viewmodels/card.js, arches/app/models/card.py, arches/app/models/graph.py
Cherry picks fix for extra card constraints from 7.4.x
#7181, re #9231
=> Cherry pick card constraint fix from v7, re #7181

arches/app/functions/primary_descriptors.py, arches/app/models/resource.py
Ensures changes to descriptors are reflected in the indexed instance
re #9232
=> Ensure descriptors are updated in indexed resource instance, re #9232

arches/app/models/graph.py
Allows user to change alias and other node properties when the corresponding card has data
#8748
=> Allow users to edit graph/nodes when model/nodegroup has corresponding data

arches/__init__.py, package.json, releases/6.2.2.md
Updates version number and adds release notes
=> Updates version number and adds release notes

arches/install/requirements.txt
Upgrades django from 3.2.15 to 3.2.18, re #9244
=> Upgrade django to from 3.2.15 to 3.2.18, re #9244

arches/app/media/js/viewmodels/file-widget.js, arches/app/media/js/views/components/search/advanced-search.js, arches/app/models/models.py, arches/app/views/resource.py, arches/install/requirements.txt, releases/6.2.2.md
#9217, #9228, #7181, #9209, #9244, #9251
=> Update v74x with 62x bug fixes

arches/management/commands/packages.py
Combines logic from duplicate functions
#9261
=> Load card comp from 'cards' and 'card_components' dir, re #9261

arches/install/requirements.txt, arches/management/commands/packages.py
Updates 7.4 with fix for #9261
=> Update 7.4 with fix for #9261

arches/app/media/js/views/components/widgets/rich-text.js, arches/app/media/js/views/components/widgets/text.js
Do not reset widget if self.value is falsy
#9273
=> Handle for falsy self.value in text widgets

arches/app/datatypes/datatypes.py
Minor feature allowing for preloading files/bypassing django storage for files chunked and uploaded via client side methods.
#8712 
=> allows for preloaded suffix on uploaded files

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
=> updates workflow multi tile save #9283

arches/app/etl_modules/branch_csv_importer.py, arches/app/media/js/views/components/etl_modules/branch-csv-importer.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm
Adapts the branch excel loader to work with recent changes in the bulk loader to improve error reporting.
re #9285
=> 9285 fix branch excel loader

arches/app/utils/data_management/resources/importer.py, arches/management/commands/packages.py
=> Update dev/7.4.x with bug fix in 6.2.x

arches/app/media/js/views/components/datatypes/resource-instance.js
Fix the issue with not showing the existing choice of the relationship method (concept or ontology)
#9247 
=> Honor the existing method choice, #9247

arches/app/media/js/views/map-layer-manager.js, arches/app/models/migrations/8928_map_layer_sort_order.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/templates/javascript.htm, arches/app/templates/views/map-layer-manager.htm, arches/app/utils/data_management/resources/importer.py, arches/app/views/map.py, arches/management/commands/packages.py, tests/fixtures/datatypes/extended_string_datatype.py, tests/models/relational_data_model_tests.py
Made order of map layers well defined by:
- adding sortorder column to map_layers table and 
- sorting map layers by sort order, and then layer name.
Added config parameter to basemap/overlay manager
#8928 
#8929
*   Tested by: @bferguso 
=> 8928,8929 - Implement well defined map layer sort order, fully config map layer in JSON file

arches/app/media/js/views/components/search/search-result-details.js, arches/app/media/js/views/components/search/search-results.js
Fixes the application getting stuck in an infinite loop when accessing search results details for items that have related resources.
#9307
=> fixes search results loop for v6 #9307

arches/management/commands/packages.py
Prevents errors in load_package if a package has no graphs
#9305
QA can be done using this graph-less package:
[map_pkg.zip](https://github.com/archesproject/arches/files/10909347/map_pkg.zip)
=> Skip import_graphs if no graphs to import, re #9305

.github/workflows/add-new-issue-to-pipeline.yml
Adds a github action to automatically add new issues to the pipeline github project
=> Adds action to update pipeline project

arches/app/media/js/views/components/search/search-result-details.js, arches/app/media/js/views/components/search/search-results.js
Update 7.4 with fix #9307 fix in 6.2
#9307
=> Update 7.4 with fix #9307 fix in 6.2

arches/app/media/js/views/components/etl_modules/branch-csv-importer.js, arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/templates/views/components/etl_modules/base-import.htm, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm, arches/app/templates/views/components/plugins/etl-manager.htm
These changes provide a default error report for the bulk data loader. In the future, this default can be overridden based on the bulk loader module's schema. 
#9294
=> 9294 individualized bulk loader error reporting

README.md
Makes the road map available in the Arches readme.md file.
#9315
=> Add road map to readme.md

arches/app/datatypes/datatypes.py, arches/app/models/migrations/9165_error_reporting.py, arches/app/templates/views/components/etl_modules/base-import.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/plugins/etl-manager.htm
Minor updates on etl error report, #9165
Also fix the migration conflicts.
#9165
=> Minor changes in etl error report, #9165

arches/app/media/css/arches.scss, arches/app/media/js/views/components/datatypes/resource-instance.js, arches/app/templates/views/components/datatypes/resource-instance.htm
Add node-config for the relationship collection so that the user can choose the collection for the relationship, #9324
#9324
=> Add node-config for the relationship collection, #9324

arches/app/views/tile.py
=> fixes tile file download issue that can cause arches crash per #9319

arches/db/system_settings/Arches_System_Settings_Model.json
Ensure system settings graph has publication information before saving system settings instance
#9374
=> Fixes system settings import error, re #9374

arches/app/etl_modules/base_data_editor.py, arches/app/media/js/views/components/etl_modules/base-editor.js
Replace the node name / node alias with widget label and card name for the label in the node selector dropdown 
#9369 
=> Add card/widget name to node selector, #9369

arches/app/etl_modules/base_data_editor.py, arches/app/media/js/views/components/etl_modules/base-editor.js, arches/app/templates/views/components/etl_modules/base-editor.htm
Update the sql to get example data for preview using search url if available, #9367 
#9367 
=> Preview using the data from search url, #9367

arches/app/media/js/models/card.js, arches/app/media/js/models/node.js, arches/app/media/js/views/graph-designer.js, arches/app/media/js/views/graph.js, arches/app/media/js/views/graph/graph-designer/card-tree.js, arches/app/models/graph.py, arches/app/models/migrations/9053_add_future_graphs.py, arches/app/models/models.py, arches/app/templates/javascript.htm, arches/app/templates/views/graph-designer.htm, arches/app/templates/views/graph.htm, arches/app/views/api.py, arches/app/views/graph.py, arches/urls.py
=> updates dirty state logic in graphs view and graph designer view #9269

arches/webpack/webpack-node-modules-aliases.js
Updated webpack togeojson import to use the es version of the library rather than the UMD version
#9393 
=> 9393 kml import bug fix

arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py, arches/app/tasks.py, arches/app/views/etl_manager.py
Fix the issue with celery process keeping going even when there are errors. (when the etl is supposed to stop)
#9363
=> Fix the issue with the ETL process not stop when there are errors, #9363

arches/app/media/css/accessibility.scss, arches/app/media/css/accessibility/base/_elements.scss, arches/app/media/css/accessibility/base/_index.scss, arches/app/media/css/accessibility/base/_landingpage.scss, arches/app/media/css/accessibility/base/_search.scss, arches/app/media/css/accessibility/breakpoints/_bp-max915.scss, arches/app/media/css/accessibility/breakpoints/_index.scss, arches/app/media/css/accessibility/components/_buttons.scss, arches/app/media/css/accessibility/components/_index.scss, arches/app/media/css/accessibility/components/_links.scss, arches/app/templates/base.htm, arches/app/templates/index.htm, arches/install/arches-templates/project_name/templates/index.htm
Changes include the conversion of accessibility.css to .scss. Also included a skeleton sass structure to aid future accessibility changes.
#9376 
*   Found by: @phudson-he
*   Tested by: @phudson-he
=> 9376 Make accessibility css use SASS

arches/app/media/js/viewmodels/card.js
Update the issue with saving tile that has a parent but not parent.expanded.
Fix the issue with saving tiles in the provenance custom editor
#
=> Check parent.expanded before setting value

arches/app/templates/views/components/datatypes/number.htm
These changes make the number datatype accessible in search. The chosen dropdown will be addressed in another PR.
#9359
=> 9359 Make number datatype accessible

arches/app/utils/label_based_graph_v2.py, tests/utils/label_based_graph_test_v2.py
Updates LabelBasedGraphV2 to use serialized_graphs
#9446
=> 9446 cbyrd update label based graph to use serialized graphs

arches/install/requirements.txt
Bump pyscopg-binary to resolve apple silicon issue fixes #9422
=> Bump psycopg-binary version, fixes #9422

tests/models/resource_test.py, tests/views/auth_tests.py
Fixes failing tests on dev/7.4.x
=> Fix dev 7.4.x failing tests

arches/app/media/css/arches.scss, arches/app/templates/views/search.htm
Make top level search view template have semantic markup, to include article and sections.
#9362 
*   Found by: @phudson-he
*   Tested by: @phudson-he
=> 9362 Make top level search template accessible

arches/app/utils/index_database.py
Prevents index from failing if resources exist that belong to inactive resource models
#9453
=> Only index resources of active graphs

README.md, arches/__init__.py, package.json, releases/6.2.3.md
Updates version numbers and adds release notes, re #9456
=> Prepare 6.2.3 release, #9456

arches/install/requirements.txt, releases/6.2.3.md
Replaces psycopg2-binary with psycopg2 and upgrades to 2.9.6
=> Replace psycopg2-binary with psycopg2, re #9481

arches/app/templates/base-manager.htm
Fixes styling for manage button in header
#9491
=> 9491 fix header button styling

releases/6.2.3.md
Updates release notes with latest bug fix, re #9456
=> Updates release notes with latest bug fix, re #9456

arches/app/media/js/views/components/datatypes/geojson-feature-collection.js, arches/app/media/js/views/components/search/resource-type-filter.js, arches/install/requirements.txt, releases/6.2.3.md
Updates dev/7.4.x with bug fixes in dev/6.2.x
=> Update 7.4.x with 6.2.x

releases/7.4.0.md
Adds draft release notes for v7.4.0
=> Add draft 7.4.0 release notes

arches/app/templates/index.htm
Improve index page accessibility & fix missing translation tags.
#9490
=> 9490 Make index page accessible

arches/app/templates/views/components/widgets/concept-select.htm
These changes make the concept-select widget accessible in search and the graph designer. The select2 and chosen dropdowns will be addressed in another PR.
#9338
=> 9338 Make concept select widget accessible

package.json
updates pattern to upgrade jquery versions on `yarn install` through patch releases and minor releases.
#9527
=> updates jquery minor version #9527

package.json
Updates `jquery` reference in `package.json` to install the latest minor and patch releases
#9527
=> updates jquery to track minor/patch versions #9527

arches/app/templates/base-manager.htm
Replaced next={{ home }} with next={{ request.get_full_path }} in base-manager.htm - this is what is was in V6.
#9325
*   Sponsored by: Knowledge Integration 
*   Found by: @SDScandrettKint  
*   Tested by: @SDScandrettKint  
*   Designed by: @SDScandrettKint
=> 9325 Login redirect page fix

arches/app/media/css/arches.scss, arches/app/templates/views/components/widgets/rich-text.htm, arches/app/templates/views/components/widgets/text.htm
=> fix asterisk not showing up for required string nodes, re #9546

arches/app/utils/data_management/resources/formats/csvfile.py
Fixes error when instance in csv has no tile data
#9548
=> Fixes error when instance in csv has no tile data

arches/app/models/migrations/9395_iiifmanifest_transaction.py, arches/app/models/models.py
=> Allow null transactionids in manifests table, re #9552

arches/app/media/js/views/components/notification.js, arches/app/templates/email/download_ready_email_notification.htm, arches/app/templates/javascript.htm, arches/app/templates/views/components/notification.htm, arches/app/views/notifications.py
Modify the download notification to support https://github.com/archesproject/arches-for-science-prj/pull/1152 and to allow multiple files can be downloaded, https://github.com/archesproject/arches-for-science-prj/issues/1136
https://github.com/archesproject/arches-for-science-prj/issues/1136
=> Add file dowload links to notification, afs#1136

README.md
Update master with latest in 7.4.x
=> Update master with latest in 7.4.x

arches/install/requirements.txt
Upgrades django to 3.2.19 re #9568
=> Upgrades django to 3.2.19 re #9568

arches/app/utils/label_based_graph_v2.py
Fixes LabelBasedGraphV2 to handle Graphs with multiple publications
#9551
=> Fix labelbasedgraph for multiple publications re #9551

arches/app/views/graph.py
Prevent node deletion in published graphs
#9575
=> Prevent node deletion in published graph, re #9575

arches/app/search/components/term_filter.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/search/mappings.py
=> reserved character search

releases/7.4.0.md
Informs admins that they will need to reindex their database following upgrade to 7.4.x
=> Update upgrade instructions

arches/app/models/migrations/9437_include_map_source_and_map_layer_permissions.py, arches/app/utils/permission_backend.py
Changes default behaviour so map layers without explicit permissions are visible not hidden
#9582 
This is just a slight tweak of the map layer permissions functionality
=> 9582 map layers visible by default

arches/app/media/css/accessibility.scss, arches/app/media/css/core.scss, arches/app/templates/base.htm
=> add a stylesheet that can be optionally added via a setting, re #9592

arches/app/models/fields/i18n.py, arches/app/utils/betterJSONSerializer.py
=> 9365 fix i18n string json encoding bug

arches/app/models/graph.py, arches/app/models/resource.py
Removes `topnode` from graph serialize since `root` already exists
#9597
=> removes topnode from graph serialize #9597

arches/app/models/graph.py, arches/app/models/models.py, arches/app/models/resource.py, arches/app/models/tile.py, arches/app/utils/i18n.py, arches/app/utils/index_database.py, arches/app/views/api.py, arches/app/views/resource.py
=> Creates `get_published_graph` method and replaces all calls  #9599

arches/app/templates/base-manager.htm
Add a link to the top of the site nav to allow the user to return to the home page.
#9560
=> Add Home Link to side navigation menu re. issue  #9560

arches/app/models/migrations/9604_fix_inefficient_trigger.py
=> fix inefficient trigger function

arches/app/models/migrations/9477_fix_for_spatial_view_dbf_function_table_alias_error.py
fixes migration dependency, re #9477
=> fix migration dependency, re #9477

releases/7.5.0.md
Add draft release notes for 7.5.x
=> Add draft release notes for 7.5.x

arches/app/media/js/utils/resource.js
Add lookup resource instance by query method re #9632 .
=> Add lookup resource instance by ES query, re #9632

arches/app/utils/data_management/resource_graphs/exporter.py, arches/app/utils/data_management/resource_graphs/importer.py, arches/app/views/graph.py
=> Fix graph import and export when not admin re #9550

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
=> fixes AbstractCardAdapter #9629

arches/app/utils/permission_backend.py
=> updates CachedUserPermissionChecker re #9627

arches/app/etl_modules/base_import_module.py, arches/app/utils/index_database.py, arches/management/commands/es.py
Added an argument to the `es` management command to force refresh of resource primary descriptors when reindexing
The arguments used are either `-rd` or `--recalculate-descriptors`
#9579 
=> 9579 - First cut of es refresh descriptors argument

arches/app/models/models.py
Change the default value of MapLayer.ispublic in the model from False to True
#9651 
Set dev/7.4.x as target as we probably want to either add this to the 7.4.0 if possible or include it in the next patch release. Should be applied to dev/7.5.x too.
=> 9651 map layer default public

arches/app/templates/views/search.htm
Improve keyboard accessibility for search toolbar
#9541
=> 9541 Make search toolbar accessible

arches/install/arches-templates/project_name/settings.py-tpl
=> adds ARCHES_NAMESPACE_FOR_DATA_EXPORT to settings.py-tpl #9656

releases/7.4.0.md
=> Update 7.4 release notes

arches/app/templates/views/components/plugins/workflow-step.htm
=> updates workflow to handle newlines in information box #9644

arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_csv_importer.py, arches/app/templates/javascript.htm
Fix the single csv importer reporting an error if there is no value in the column for a file-list, #9652
Also, fix the issue with the branch excel importer not importing the child tiles, #9653
#9652, #9653
=> Fix minor bugs in the bulk data manager, #9652, #9653 

arches/app/models/models.py
Minor fix to allow for a functioning temp table model
=> fixes temp files models not working

arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/widgets/resource-instance-select.htm
fixes null check errors in the resource instance select widget.
=> fixes null check errors in the resource instance select widget

arches/app/templates/javascript.htm, arches/app/templates/views/components/search/search-export.htm
Fix non-translated string
#9520
=> 9520 Fix celery warning translation for search export

arches/management/commands/packages.py
changes load templates call to use yaml configuration files
=> yaml templating for template configuration

arches/app/media/js/viewmodels/card-component.js, arches/app/media/js/views/components/workflows/workflow-component-abstract.js
=> updates AbstractCardAdapter #9721

arches/install/requirements.txt
Upgrade django to 3.2.20
re https://docs.djangoproject.com/en/4.2/releases/3.2.20/
=> Upgrade django to 3.2.20

arches/install/requirements.txt
Patch upgrade for django. Moves django from 3.2.18 -> 3.2.20
=> Patch upgrade for django

arches/app/etl_modules/branch_csv_importer.py, arches/app/etl_modules/import_single_csv.py
Update bulk importer to check the file type using extension not the mime type.
Fix the issue with the zip file uploaded from a Windows system which has the mime type application/x-zip-compressed instead of application/zip.
#9693 
=> Check the file type using extension, #9693

arches/app/utils/label_based_graph_v2.py
=> updates labelbasedgraph to handle provisional edits #9715

arches/app/etl_modules/branch_csv_importer.py
Handles for blank lines in branch excel
#9750
=> Handles for blank lines in branch excel, re #9750

arches/app/templates/base-manager.htm, arches/app/templates/javascript.htm
Makes logo in left nav accessible
#9710
=> 9710 Make left nav logo accessible

arches/app/media/css/arches.scss
Ensures min width of iiif widget in default report
#8419
=> Sets default width, re #8419

arches/app/media/js/views/page-view.js
=> 9752 delete duplicate help content from help panel

arches/app/views/api.py
Ensures all necessary arguments are passed to BulkDisambiguatedResourceInstance endpoint
=> Pass missing args to bulk disambiguated resource endpoint

arches/app/media/css/sidenav.scss, arches/app/templates/base-manager.htm, arches/app/templates/javascript.htm
Improves accessibility of left nav - screen reader is alerted to hierarchy of navigation items and links are given proper labels.
#9391
=> 9391 Make left nav accessible

arches/app/templates/views/search.htm
Announces total number of search results
#9726
=> 9726 Announce number search results

arches/app/models/migrations/9670_improve_bulk_load_performance.py, arches/app/models/migrations/9746_related_resource_post_save_bug.py
=> fix migration order

arches/app/etl_modules/base_data_editor.py
Update the logic to send request using search url, #9806 
Fix the issue with the search url in bulk editor is not working in the docker setting.
#9806 
=> Fix logic to use search url in bulk editor, #9806

arches/app/etl_modules/branch_csv_importer.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm
Update the branch excel importer to accept the excel itself as well as zip files, #8469 
#8469
=> Add support for xlsx file, #8469

package.json
Reverts knockout because 3.5.1 breaks card tree in designer
#9805
=> fixes broken card tree #9805

arches/app/media/js/views/search.js, arches/app/templates/javascript.htm, arches/app/templates/views/search.htm
Screen readers need context for how many results are show, not just total number of results. 
Resolves #9726
=>  9726 Give screen reader context for how many results are shown

arches/app/templates/views/graph/graph-designer/node-form.htm
Prevents error during cardinality check when a user clicks on a node
#9803
=> Fixes 'missing nodegroup' error when selecting a node in graph tree re #9803

arches/app/views/api.py, package.json
Updates 7.4.x with latest in 6.2.x
=> Updates 7.4.x with latest in 6.2.x

README.md, arches/__init__.py, releases/6.2.4.md
Adds release notes and updates version for 6.2.4 patch release
=> 6.2.4 Release preperation

package.json
Update arches version in package.json to version 6.2.4
=> Update arches version in package.json

releases/6.2.4.md
=> Merge 6.2.x into 7.4.x

arches/app/etl_modules/base_data_editor.py
Fix the issue of the preview being slow by updating the query to count the resources, #9837 
#9837 
=> Fix the preview in the string bulk editor, #9837

arches/app/media/js/views/components/etl_modules/branch-csv-importer.js
Filters branches from branch excel templates
#9811
=> Filter branches from branch excel templates

README.md, arches/__init__.py, package.json, releases/7.4.1.md
Updates version and release notes for 7.4.1 release
=> v741 release preparation

arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm
Add spinner to preview button while it is getting a sample data and disable the button. #9845 
Also, refresh the data in the beginning when preview button is clicked.
#9845
=> spinner on preview button, #9845 

arches/app/models/graph.py, tests/models/graph_tests.py
As of #9575, deleting nodes from published graphs is already prohibited. Extend this prohibition to adding nodes/branches.
Fixes #9864
=> Prevent adding nodes or branches to published graphs #9864

arches/app/views/concept.py, tests/views/concept_tests.py
Previously, completing this form raised TypeErrors on the backend:
Closes #9884 
=> Fix TypeError when creating new collection from RDM

arches/app/etl_modules/import_single_csv.py
This will prevent the empty tile (string object with no value) from creating when there is no value for the csv column/cell, #9872
#9872
=> Skip the empty value from reading csv, #9749

arches/app/media/js/views/components/etl_modules/branch-csv-importer.js, arches/app/media/js/views/components/etl_modules/branch-excel-exporter.js, arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/templates/views/components/etl_modules/branch-csv-importer.htm, arches/app/templates/views/components/etl_modules/branch-excel-exporter.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/plugins/etl-manager.htm
Moves import details from the base etl component to module so that they can be tailored to the module, re #9749
=> Move import details to module, re #9749

arches/app/models/migrations/9744_add_tile_excel_importer.py
Add migration for tile excel importer, re #9886
=> Add migration for tile excel importer, re #9886

arches/app/etl_modules/tile_excel.py, arches/app/models/migrations/9744_add_tile_excel_importer.py
Fix typos and remove config from python file, re #9886
=> Fix typos and remove config from python file, re #9886

arches/app/templates/views/components/etl_modules/import-single-csv.htm
=> Add missing space to row count footer

arches/app/models/migrations/9744_add_tile_excel_importer.py
Remove load errors in reverse migration of tile excel importer, re #9908
=> Remove load_errors on reverse migration of tile excel importer, re #9908

arches/app/etl_modules/base_data_editor.py, arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_excel_exporter.py, arches/app/etl_modules/branch_excel_importer.py, arches/app/etl_modules/decorators.py, arches/app/etl_modules/import_single_csv.py, arches/app/etl_modules/save.py, arches/app/etl_modules/tile_excel_importer.py, arches/app/views/etl_manager.py
The ancestors of the ETL modules did not lend themselves to future extension, see remarks in #9900.
Now, shared functionality is maintained without having exporters inherit from importers, etc.
Commits:
[Remove object orientation from save_to_tiles()](https://github.com/archesproject/arches/pull/9911/commits/428c3017a6cdef1080697e313dd0c14c8b6b2f33)
[Refactor load_data_async() as a decorator](https://github.com/archesproject/arches/pull/9911/commits/c65b9d411ee55c736c8ac298559b2fcd1cd45e2d)
[Remove ancestor from …
=> Refactor inheritance structure of ETL modules #9900

arches/app/search/search.py, arches/app/search/search_engine_factory.py, arches/app/utils/betterJSONSerializer.py
The search engine factory was changed to supply either the `cloud_id` or `hosts` to the constructor. These settings are mutually exclusive and if both are supplied, an error results. If the `cloud_id` is present - that will be used, otherwise it will fallback to use `hosts`.
Elastic Cloud requires the serialized query object to be UTF-8 encoded. To implement this, a `utf_encode` variable is added to the JSONSerializer instance and a check is made within the serialize() method and encodes when present.
#9850 
-   [ ] …
=> Add support for Elastic Cloud #9850 AB#57245

arches/app/media/css/arches.scss, arches/app/templates/views/components/iiif-viewer.htm, arches/app/templates/views/components/plugins/manifest-manager.htm
Fixes styling for IIIF Gallery filter
#9890 
https://github.com/archesproject/arches-for-science-prj/issues/1250
=> 9890 Fix wrap of iiif gallery filter

.github/workflows/main.yml
Forwardport of #9929 from 7.4.x
Refs #9931
=> Remove editable flag on CI #9931

arches/app/views/concept.py
Allows searching for concept labels using uppercase and lowercase characters.
#9786
=> Fix search on uppercase concept labels, re #9786

arches/app/models/migrations/6020_bi_directional_node_to_resource.py, arches/app/models/migrations/6481_add_resourceinstance_graphid.py
#9779 
*   Tested by: @khodgkinson-he 
*   Designed by: @aj-he
=> Fixes out of memory issue migrating from 5.2 to 6.2

arches/app/models/migrations/6020_bi_directional_node_to_resource.py, arches/app/models/migrations/6481_add_resourceinstance_graphid.py
Updates 7.4.x with bug fixes in 6.2.x
=> Updates 7.4.x with bug fixes in 6.2.x

arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_excel_exporter.py, arches/app/etl_modules/branch_excel_importer.py, arches/app/etl_modules/tile_excel_importer.py, arches/app/tasks.py, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/etl_modules/tile-excel-importer.htm, arches/management/commands/etl_template.py
Improve the tile excel importer, #9920 
Support update/insert when the tileids are specified.
Create a template from the graph
#9920
=> Improve the tile excel importer, #9920 

.github/workflows/main.yml
Add a step to fail PRs that having missing migrations.
Closes #9917
*   Sponsored by: Farallon Geographics
Until Django 4.2, you would have needed to also add the `--dry-run` flag to avoid actually making the migration, but we're about to upgrade to 4.2 anyway, and the action filesystem is …
=> Add workflow step to check for missing migrations #9917

arches/app/views/graph.py
=> enforces datatype immutability #9875

arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/branch_excel_importer.py, arches/app/etl_modules/tile_excel_importer.py, arches/app/media/js/viewmodels/base-import-view-model.js, arches/app/media/js/viewmodels/excel-file-import.js, arches/app/media/js/views/components/etl_modules/branch-excel-exporter.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm, arches/app/templates/views/components/etl_modules/base-import.htm, arches/app/templates/views/components/etl_modules/branch-excel-importer.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/etl_modules/tile-excel-importer.htm
Add a validation step when reading the file to check the excel file from the wrong template, #9925
Fix the issue of failing when the branch excel file was added to tile excel importer vice versa.
#9925 
=> The excel template validation, #9925

arches/app/media/css/arches.scss, arches/app/templates/base-manager.htm
See [afs #1260](https://github.com/archesproject/arches-for-science-prj/issues/1260) for explanation
Resolves #9909
=> 9909 Prevent notifications circle from rendering above expandable content

arches/app/templates/javascript.htm, arches/app/templates/views/components/search/map-filter.htm
Fixes a few missing button aria-labels, shifts focus from those buttons, and alerts users to GeoJSON editor errors via aria-live.
Resolves #9881
=> 9881 map filter accessibility cleanup

arches/app/views/api.py
fixes bug where not supplying a graphid or slug to the json-ld api would delete the resource but not save the new one, re #9968
see this thread for more context:
https://community.archesproject.org/t/api-for-update-resource/2094/1
=> fixes bug where not supplying a graphid or slug to the json-ld api would delete the resource but not save the new one, re #9968

arches/install/arches-templates/project_name/webpack/webpack.common.js, arches/webpack/webpack.common.js
=> update webpack config 9992

arches/app/templates/views/components/plugins/workflow.htm
=> removes workflow hardcoding in workflow banner #10014

arches/settings.py
=> re-adds OVERRIDE_RESOURCE_MODEL_LOCK #10030

arches/__init__.py
=> Sets release to alpha

arches/app/etl_modules/base_data_editor.py, arches/app/models/migrations/9979_update_stage_for_bulk_edit.py
Update the function to stage only relevant tiles for bulk edit, #9979 
#9979
=> Update staging data for bulk edit, #9979 

arches/app/media/js/views/components/etl_modules/import-single-csv.js, arches/app/templates/views/components/etl_modules/base-import.htm, arches/app/templates/views/components/etl_modules/branch-excel-importer.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/etl_modules/tile-excel-importer.htm
Moves resource count into base-import, re #9975
=> Move resource count into base-import, re #9975

arches/app/etl_modules/save.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm, arches/app/templates/views/components/etl_modules/branch-excel-importer.htm, arches/app/templates/views/components/etl_modules/import-single-csv.htm, arches/app/templates/views/components/etl_modules/tile-excel-importer.htm
Add the count of resources/tiles imported in the etl-manager status summary page, #9975 
Single CSV, Branch Excel, Tile Excel, String Editor were all updated.
#9975
=> Add the count of resources/tiles imported, #9975 

arches/app/media/js/card-components.js, arches/app/media/js/datatype-config-components.js, arches/app/media/js/file-renderers.js, arches/app/media/js/function-templates.js, arches/app/media/js/geocoder-templates.js, arches/app/media/js/plugins.js, arches/app/media/js/report-templates.js, arches/app/media/js/resource-types.js, arches/app/media/js/search-components.js, arches/app/media/js/view-data.js, arches/app/media/js/views/graph-designer-data.js, arches/app/media/js/views/graph-manager-data.js, arches/app/media/js/views/graph/graph-base-data.js, arches/app/media/js/views/graph/graph-functions-data.js, arches/app/media/js/views/graph/graph-settings-data.js, arches/app/media/js/views/map-layer-manager-data.js, arches/app/media/js/views/plugin-data.js, arches/app/media/js/views/profile-manager-data.js, arches/app/media/js/views/resource/resource-edit-history-data.js, arches/app/media/js/views/resource/resource-editor-data.js, arches/app/media/js/widgets.js
=> updates interactions to fail loudly #10016

arches/app/etl_modules/base_excel_exporter.py, arches/app/etl_modules/branch_excel_exporter.py, arches/app/etl_modules/tile_excel_exporter.py, arches/app/media/js/viewmodels/excel-file-export.js, arches/app/tasks.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/branch-excel-exporter.htm, arches/app/templates/views/components/etl_modules/tile-excel-exporter.htm
=> allows naming of exported files from bulk_data_manager #9974

arches/app/etl_modules/base_excel_exporter.py, arches/app/etl_modules/branch_excel_exporter.py, arches/app/etl_modules/tile_excel_exporter.py, arches/app/media/js/viewmodels/excel-file-export.js, arches/app/tasks.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/tile-excel-exporter.htm
=> adds option for users to export concepts as UUIDS when using bulk tile exporter #9987

arches/app/templates/views/components/plugins/manifest-manager.htm, arches/app/views/manifest_manager.py
Fix the issue of not being able to delete a canvas, #10029
#10029
=> Fix canvas delete function, #10029

releases/7.5.0.md
Documentation update for settings deprecations in Django 4.2.
=> Add note about settings deprecations

arches/app/templates/views/report-templates/default.htm
Headers shouldn't skip levels, just use header tags for styling
#9882
=> 9882 fix missing headers in default resource report

arches/app/media/js/bindings/select2-query.js
Fixes issue with select2 not disabling itself to respect observable value.
=> fixes #10002

arches/app/templates/javascript.htm, arches/app/templates/views/components/search/sort-results.htm
Gives select element in sort results an accessible label
#9996
=> Give result sorter select an accessible label #9996

arches/app/media/css/accessibility.scss
Adds focus indicator to select2 and chosen results
Resolves #9898, Resolves #9994
=> 9994 fix focus indicator for chosen

arches/app/etl_modules/base_data_editor.py, arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/models/migrations/10041_limit_number_of_bulk_edit.py, arches/app/tasks.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm
Limit the number of edits for the bulk editor that the user can edit at one time, #10041
To prevent that the user start a long process.
#10041
=> Limit the number of bulk edits, #10041

arches/app/media/css/accessibility.scss, arches/app/media/css/components/_map.scss, arches/app/media/css/components/search/_index.scss, arches/app/media/css/components/search/_search-results.scss, arches/app/media/css/pages/_index.scss, arches/app/media/css/pages/_report.scss
Bring small text into compliance with accessibility standards 
Resolves #9964
=> Size up small text in accessibility mode #9964

arches/app/models/tile.py
Fixes broken file uploads in 7.4.x after tile performance fix.
=> 10072 file upload

arches/app/templates/views/report-templates/default.htm
Replace one of duplicates of date with Report Date text, #10081 
#10081 
=> Fix duplicate dates, #10081

arches/app/tasks.py
Ensure link property is a string not a uuid, re #10084
=> Ensure link property is a string not a uuid, re #10084

arches/app/models/migrations/10041_limit_number_of_bulk_edit.py
=> conflicting migrations fix

README.md, arches/__init__.py, arches/install/requirements.txt, package.json, releases/6.2.5.md
Initial prep for 6.2.5 release
=> Prep 6.2.5 release

arches/app/etl_modules/tile_excel_importer.py
Allow uploading a tile excel file with an empty worksheet (no tiles for that nodegroup).
Closes #9990
=> Allow importing empty worksheets #9990

arches/app/tasks.py, arches/app/utils/index_database.py, arches/install/requirements.txt, releases/6.2.0.md, releases/6.2.1.md, releases/6.2.5.md
Updates dev/7.4.x with changes in dev/6.2.x
=> Reconcile 625 and 741

arches/app/models/models.py
=> Check 'to' type and add better error logging

arches/app/utils/skos.py
=> enforce that skos file uses hasTopConcept

README.md, arches/__init__.py, package.json, releases/7.4.2.md
Update readme and version number for 7.4.2 release
=> Prep 742 release

arches/app/media/css/abstracts/_breakpoint-settings.scss, arches/app/media/css/components/search/_search-results.scss, arches/app/media/css/pages/_search.scss, arches/app/templates/views/search.htm
Makes search toolbar buttons more responsive at smaller screen sizes.
Resolves #9984
=> Improve responsiveness for search toolbar items #9984

arches/app/etl_modules/base_data_editor.py, arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/models/migrations/10120_replace_whole_word_bulk_edit.py, arches/app/search/elasticsearch_dsl_builder.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm
Update the bilk string editor to add the capability of replacing when only whole word matches, #10120
#10120
=> [bulk editor] Add the capability of replacing the whole word only, #10120

arches/app/templates/views/components/search/term-filter.htm
=> fix label issue with term search, re #9822

arches/app/media/js/bindings/datepicker.js, arches/app/media/js/views/components/widgets/datepicker.js
Fix the issue with the dirty state if the user cancels the date picked and picks the same day again, #10125
#10125
=> The value in the date picker widget, #10125

README.md, arches/app/datatypes/datatypes.py, arches/app/media/css/arches.scss, arches/app/media/js/bindings/select2-query.js, arches/app/media/js/views/components/resource-report-abstract.js, arches/app/models/models.py, arches/app/models/tile.py, arches/app/tasks.py, arches/app/templates/base-manager.htm, arches/app/templates/views/components/plugins/manifest-manager.htm, arches/app/templates/views/report-templates/default.htm, arches/app/utils/index_database.py, arches/app/views/api.py, arches/app/views/manifest_manager.py, arches/install/ubuntu_setup.sh, releases/6.2.0.md, releases/6.2.1.md, releases/6.2.5.md, releases/7.0.0.md, releases/7.4.2.md
Updates 7.5.x with latest bug fixes in 7.4.x
=> Updates 7.5.x with latest bug fixes in 7.4.x

arches/app/datatypes/datatypes.py, arches/app/models/tile.py, tests/models/tile_model_tests.py
Previously, required nodes having list datatypes such as file-list escaped validation for missing values.
Closes #10077
*   Sponsored by: GCI
=> Fix validation of required list nodes #10077

arches/app/media/js/viewmodels/resource-instance-select.js
Prevents undefined graph error, re #10151
#10151
=> Prevents undefined graph error, re #10151

arches/app/etl_modules/base_data_editor.py
Fix the issue with string bulk editor failing, #10155 
#10155 
=> Assign value to missing parameter, #10155

arches/app/templates/views/components/search/search-export.htm
If the export-warning was not shown, the download button had a broken aria-description
Resolves #10142
=> 10142 fix search export broken aria describedby

arches/app/etl_modules/bulk_data_deletion.py
Fix indexing issue with bulk deletion, #10173
#10173
=> Fix bulk deletion indexing, #10173

arches/app/media/js/views/components/datatypes/boolean.js, arches/app/media/js/views/components/datatypes/date.js, arches/app/media/js/views/components/datatypes/domain-value.js, arches/app/media/js/views/components/datatypes/edtf.js, arches/app/media/js/views/components/datatypes/number.js, arches/app/media/js/views/components/datatypes/string.js, arches/app/media/js/views/components/datatypes/url.js, arches/app/templates/views/components/datatypes/boolean.htm, arches/app/templates/views/components/datatypes/concept.htm, arches/app/templates/views/components/datatypes/date.htm, arches/app/templates/views/components/datatypes/domain-value.htm, arches/app/templates/views/components/datatypes/edtf.htm, arches/app/templates/views/components/datatypes/number.htm, arches/app/templates/views/components/datatypes/resource-instance.htm, arches/app/templates/views/components/datatypes/string.htm, arches/app/templates/views/components/datatypes/url.htm
=> 10190 adv search labels

arches/__init__.py
Update alpha version to 7.5.0.a1
=> Update alpha version to 7.5.0.a1

arches/app/media/js/views/page-view.js
Fixes double VO/NVDA readout when expanding slideout panels. 
Resolves #9902
=> Wait for panel to be fully expanded before shifting focus #9902

arches/app/media/js/viewmodels/card-component.js
User Verification alert added to prevent the user accidentally deleting a card.
#9091
=> Handle deletion verify at card component level #9091

arches/app/models/graph.py, arches/management/commands/graph.py
Adds `--update` flag to graph publish management command
#9625
=> adds update flag to graph publish command #9625

arches/app/templates/index.htm, arches/install/arches-templates/project_name/templates/index.htm
=> 10226 Add translation tags for aria-labels in index page

arches/app/templates/views/components/iiif-viewer.htm
Support HTML in metadata attribution field in IIIF viewer (prevent unrendered HTML).
Closes #10208
=> Support HTML in manifest attribution field #10208

arches/app/media/js/viewmodels/file-widget.js, arches/app/templates/views/components/widgets/file.htm
Makes the file widget easier to inherit from, for example, for the purpose of adding additional file metadata fields.
Refs #9333
*   Sponsored by: Max Planck Institute
*   Tested by: @jacobtylerwalls 
=> Make file-widget easier to inherit from #9333

arches/app/media/js/views/components/search/sort-results.js
Fix the issue of search result indicating sort in "ascending" order, when in fact is unsorted. #10128 
Now it will say unsorted.
#10128
=> Remove initial sort, #10128

arches/app/media/js/views/components/datatypes/file-list.js
Found in review of #9333, tabled until @njkim solved the related issue in #10229.
Re #9333
=> Make image only toggle respect Discard Edits button re #9333

arches/app/media/js/views/components/datatypes/file-list.js
Fix the issue with resetting (undo) the max files (maximum number of files), #10059 
#10059 
=> Fix reset maxfiles in graph designer, #10059

arches/settings_utils.py
Force full real path of ROOT_DIR and APP_ROOT directories to fix path mismatch in webpack
#10234
=> 10234 - Fix webpack symlink mismatch

arches/app/templates/base-manager.htm
New button was added and used old, non-accessible pattern.
Resolves #10228
=> 10228 make new base manager button accessible

arches/app/templates/views/search.htm
Follows tool-tip pattern of base manager top-nav
Resolves #10251
=> Add search toolbar btn tooltips #10251

arches/app/views/api.py, arches/app/views/workflow_history.py
=> superusers can finish workflows of other users #10153

arches/app/media/css/accessibility.scss
Fixes a contrast issue with inactive options for map filters - basemaps, overlays and legends. This is only relevant when in accessibility mode.
#9903 
*   Found by: @phudson-he
*   Tested by: @phudson-he
=> 9903 Map filter contrast issue

arches/app/media/css/arches.scss, arches/app/media/css/pages/_report.scss
Fixes reflow issues for report title and tools, on smaller screen widths or zoom 400%.
#9761 
*   Found by: @phudson-he
*   Tested by: @phudson-he
=> 9761 Ensure reflow of report title and tools

arches/app/media/js/views/graph/function-manager.js
Fixes bug which does not allow a primary descriptor function to be saved in the function manager unless its configuration is changed (causing it to be dirty).  
#10252 
*   Found by: @bferguso 
=> 10252 - Check if function is new in save logic

README.md
=> Update to roadmap

arches/app/etl_modules/base_import_module.py, arches/app/etl_modules/import_single_csv.py
Fix database function name in the single csv importer, #10269
#10269
=> Fix db func error single csv, #10269

arches/app/etl_modules/base_excel_exporter.py, arches/app/etl_modules/branch_excel_exporter.py, arches/app/etl_modules/tile_excel_exporter.py, arches/app/templates/views/components/etl_modules/branch-excel-exporter.htm, arches/app/templates/views/components/etl_modules/tile-excel-exporter.htm
=> fixes bulk export failure when file not found #10258

arches/app/models/tile.py
Ensures all nodes are returned so that update_after_all is performed on each of them.
#10287
=> Ensure all nodes in nodegroup are returned, re #10287

arches/app/search/search_export.py
Update 7.4.x with fixes in 6.2.x
=> Update 7.4.x with fixes in 6.2.x

arches/app/media/css/arches.scss, arches/app/templates/base-manager.htm
Fixes reflow issues for login, logout and welcome user message. These changes work at 400% zoom.
From a UX point of view, I've hidden the Welcome user message from mobile screen widths due to the fact that it links to the users profile and there is already a link to that in the left nav. Also, the top right logout button also serves as a login button when not logged in (with appropriate tooltips), instead of using the Login text which was situated in the same place as the welcome user text when logged in.
#9839 
- …
=> 9839 Login/logout/welcome message fixes

README.md, arches/__init__.py, package.json, releases/6.2.6.md
Add release notes and update versions for 6.2.6 release
=> Add release notes and update versions for 6.2.6 release

README.md, arches/__init__.py, package.json, releases/6.2.6.md, releases/7.4.3.md
Add release notes and update versions for 7.4.3 release
=> Add release notes and update versions for 7.4.3 release

releases/6.2.6.md
Update release notes with latest bug fixes
=> Update release notes with latest bug fixes

arches/app/datatypes/datatypes.py, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/media/js/views/search.js, arches/app/models/concept.py, arches/app/views/concept.py, arches/app/views/search.py, releases/6.2.6.md, releases/7.4.3.md
Updates 7.4.x with the following fixes:
- Fixes edtf advanced search error message #10309
- Disallows selection of concepts outside of a collection in concept widget #10308
- Sorts resources in resource instance dropdown, #10305
=> Update 74x with latest bug fixes in 62x 

yarn.lock
Refs #9814
Refs #10265
Needed to do this to get going on updating arches for science work after the selectWoo changes. A knockout downgrade from #9814 also involved here.
=> Remake yarn lockfile

releases/6.2.6.md
Adds latest changes to release notes
=> Updates bug fix list with latest changes

arches/install/requirements.txt
Somehow updating requirements.txt got lost in the shuffle of #10327, sorry!
=> Bump Django to 4.2.8

arches/app/media/css/arches.scss, arches/app/media/js/views/components/iiif-viewer.js, arches/app/media/js/views/components/plugins/manifest-manager.js, arches/app/templates/views/components/plugins/manifest-manager.htm
Fix the missing canvas label issue, #10279
Also update the ui including buttons
#10279 
=> Fix the missing canvas label, #10279

arches/app/views/auth.py
rate limit for 7.x arches - doubling for the log in view.
=> updates rate limit to multiply by 2 for new auth frontend

README.md
=> Remove cruft

releases/7.4.3.md
Add note re rate limiting and caching
=> Add note re rate limiting and caching

arches/app/media/css/arches.scss, arches/app/templates/views/components/widgets/resource-instance-select.htm, arches/app/templates/views/resource/related-resources/related-resources-manager.htm
=> fix css nits, re #10331

arches/app/models/graph.py, arches/app/utils/i18n.py
=> updates language synchronizer to serialize graph proxy model #10371

arches/app/media/js/utils/map-configurator.js, arches/app/media/js/viewmodels/map.js
Adds a hook to perform configuration of the map at the beginning and end of the map.on('load') event.
#10353 
=> 10353 add map config hook

arches/app/media/css/arches.scss, arches/app/media/css/pages/_report.scss
=> 10351 fix report no scroll

arches/app/media/css/arches.scss, arches/app/templates/views/components/search/search-results.htm
=> 10375 improve position of search image

arches/app/datatypes/datatypes.py
A fix for the pathing issue that comes about when using non local file system storages.  
Also some black auto-formatting.
=> fixes issue with django_storage path not implemented

arches/app/media/js/views/components/widgets/text.js
Fix the issue with placeholder is not properly displayed in the form, #8832
#8832
=> Fix string widget placeholder, #8832

arches/app/functions/primary_descriptors.py, tests/fixtures/data/json/resource_export_business_data_truth.json
Update the missing descriptor
Fix the missing descriptor in the arches-for-science workflows, archesproject/arches-for-science#1495
archesproject/arches-for-science#1495
=> The missing descriptor, afs#1495 

arches/app/etl_modules/branch_excel_exporter.py, arches/app/etl_modules/tile_excel_exporter.py
Fix the issue if the file list node does not have node value (no file), #10417 
#10417 
=> The exporters handle the None value in the file-list node, #10417

arches/app/utils/thumbnail_generator.py
this causes an error when trying to import this class
=> remove unused imports, re #10434

arches/app/etl_modules/bulk_data_deletion.py, arches/app/templates/javascript.htm, arches/app/templates/views/components/etl_modules/bulk-data-deletion.htm
Fix the preview to handle the different shapes of label based graph data, #10428
Also, handle missing preview to allow the deletion as long as there are tiles to delete.
#10428
=> Update the bulk deletion preview, #10428

README.md, arches/app/utils/data_management/resources/formats/archesfile.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/management/commands/packages.py
Resource descriptors weren't being saved when importing business data after changes in #9758.
*   Tested by: @jacobtylerwalls 
=> Recalculate descriptors when loading business data re #9758

arches/app/search/search_export.py, arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/formats/excel.py, arches/app/utils/data_management/resources/formats/format.py
Filter out restricted nodes when exporting to tile excel from search
Closes #10425
We should follow-up with PRs for other export formats.
=> Observe nodegroup permissions in tile excel export #10425

releases/7.5.0.md
Adds list of breaking changes to release notes
=> Add list of breaking changes

arches/app/media/css/components/search/_time-filter.scss
Fix the issue with disappearing the selection (calendar) when year month selector is selected, #9060 
#9060 
=> Fix datepicker time wheel, #9060

arches/app/utils/forms.py, arches/app/views/user.py
Prevent username already exists error when updating user profile
#10430
=> Prevent username already exists error when updating user profile

arches/app/media/css/arches.scss
Adjust default body font size to be closer to the size in v7.4
=> Adjust default body font size

package.json, releases/7.6.0.md
Add draft release notes for 7.6.0
=> Add draft 7.6.0 release notes

CONTRIBUTING.md
This solves issue  #10393
This fixes the broken link in the contributing guidelines for setting up a development environment.
broken link: https://arches.readthedocs.io/en/latest/creating-a-development-environment/
new link: https://arches.readthedocs.io/en/stable/developing/getting-started/creating-a-development-environment/
#
*   Tested …
=> fix broken link contributing guideline

arches/app/media/css/arches.scss
Fix the issue with datepicker not showing selections, #9060
#9060 
=> Update selector to hide clock button, #9060

README.md, arches/__init__.py, package.json, releases/6.2.7.md
Add draft 6.2.7 release notes and update version number
=> Add draft 6.2.7 release notes and update version number

arches/app/search/search_export.py, arches/app/utils/data_management/resources/exporter.py, arches/app/utils/data_management/resources/formats/csvfile.py, arches/app/utils/data_management/resources/formats/excel.py, arches/app/utils/data_management/resources/formats/format.py
Cherry picked from #10441 
#10425
=> Observe nodegroup permissions in tile excel export #10425 (#10441)

arches/app/media/js/reports/map-header.js, arches/app/media/js/viewmodels/map-report.js
Handles null values in the map header report template
Resolves #10429
=> Handle empty node values in map report #10429

arches/app/models/tile.py, tests/models/tile_model_tests.py
Fix deletion of empty tiles.
Closes #10480
=> Fix deletion of empty tile #10480

arches/app/utils/message_contexts.py
Fixes failures importing business data with celery enabled.
=> Fix notification failures when importing business data #10479

arches/webpack/webpack.common.js, releases/7.6.0.md
=> updates webpack to handle multiple build calls #10490

.github/workflows/main.yml, arches/app/models/concept.py
Fixes #10466
Issue is that the comparison to offset 0 results in a falsy value, which causes the pagination limit to not be applied to the query.  Comparing with "None" instead resolves the issue. - L511/512
Other changes are black styleguide based formatting mostly based on arches predefined line width.
=> fix issue with concept pagination for offset 0

.github/workflows/main.yml, arches/install/requirements.txt, package.json, releases/7.6.0.md, setup.py, yarn.lock
Add python 3.11 and 3.12 to CI matrix. Get a passing CI run on 3.12 before declaring support.
`node-gyp` pin is due to https://github.com/nodejs/node-gyp/issues/2869.
=> Declare support for Python 3.12

releases/6.2.7.md
=> Update 6.2.7 release notes

.github/workflows/main.yml, arches/app/models/concept.py, releases/6.2.7.md
Updates 7.4 with bug fixes in 6.2. Fixes duplicate concepts in concept dropdown, #10482 and fixes issue in ci action.
=> Update 74x w 62x

.github/workflows/main.yml, arches/app/media/css/arches.scss, arches/app/media/js/reports/map-header.js, arches/app/media/js/viewmodels/map-report.js, arches/app/media/js/views/components/widgets/rich-text.js, arches/app/models/concept.py, arches/app/templates/views/components/file-workbench.htm, arches/app/templates/views/components/photo-workbench.htm, releases/6.2.7.md, releases/7.5.1.md
Updates 75x with bug fixes in 74x
=> Updates 75x with bug fixes in 74x

arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm, releases/7.5.1.md
Fix some small issues with bulk editor, #10464 
Also fix the issue with the status detail spinning wheel and the issue with selecting the current edit in the status tab.
Update to select the active language by default. 
#10464 
=> Fix minor issue with the bulk editor, #10464 

.github/workflows/main.yml, arches/app/media/css/arches.scss, arches/app/media/js/reports/map-header.js, arches/app/media/js/viewmodels/map-report.js, arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/media/js/views/components/widgets/rich-text.js, arches/app/models/concept.py, arches/app/models/tile.py, arches/app/search/time_wheel.py, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm, arches/app/templates/views/components/file-workbench.htm, arches/app/templates/views/components/photo-workbench.htm, arches/app/utils/message_contexts.py, arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py, releases/6.2.7.md, releases/7.5.1.md, tests/models/tile_model_tests.py
Updates 76x with latest fixes in 75x
=> Update 76x with 75x 

arches/app/media/css/components/_map.scss, arches/app/templates/views/components/map.htm
=> fix map being overlaped by side bar, re #10315

arches/management/commands/packages.py
Various black fixes, fixes package function load - if it's an application, it does not copy the function to the project but it still registers the function.  
Expects that the application's function location is registered in settings.
=> fix function load

arches/app/media/css/arches.scss
CSS changes to fix the edit coordinates bug.
CSS fixes for the bug that caused the Edit Coordinates panel to be crammed with coordinates for a polygon with many coordinates.
#9145 
*   Found by: @SDScandrettKint 
*   Tested by: @SDScandrettKint 
*   Designed by: @SDScandrettKint 
`map-coordinate-editor-crs-selector` change from fixed …
=> 9145 Fix for the visual edit coordinates bug with multiple coordinates in a polygon (dev/7.4.x)

arches/app/media/css/components/search/_advanced-search.scss, arches/app/media/js/views/components/search/advanced-search.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/search/advanced-search.htm, arches/app/views/api.py, arches/urls.py
Add card path to advanced search facets archesproject/arches-for-science#1488
=> Add path to advanced search facets archesproject/arches-for-science#1488

arches/app/views/api.py, arches/install/arches-templates/project_name/install/requirements.txt
Replace workflow slug with workflow name in incomplete workflow modal #10496
=> Replace workflow slugs with workflow names in incomplete workflows modal #10496

arches/app/media/js/viewmodels/workflow-step.js
Fixes issue where "locked" value would not be respected in workflow step, then would immediately reset the "locked" value in the database.
=> fixes workflow steps not respecting 'locked' value

arches/app/media/css/arches.scss, arches/app/templates/views/components/coordinate-editor.htm, arches/app/templates/views/components/map-editor.htm, arches/app/templates/views/components/map-widget-editor.htm
Fix display of map coord editor #9145
#9145
To test this you'll need to verify that scrolling works properly in both the map widget and the map card.
=> Fix display of map coord editor #9145

arches/management/commands/load_ontology.py, tests/base_test.py, tests/exporter/datatype_to_rdf_tests.py, tests/exporter/jsonld_export_tests.py, tests/exporter/resource_export_tests.py, tests/importer/concept_import_tests.py, tests/importer/datatype_from_rdf_tests.py, tests/importer/ontology_import_tests.py, tests/localization/field_tests.py, tests/models/graph_tests.py, tests/models/mapped_archesjson_import_tests.py, tests/models/mapped_csv_import_tests.py, tests/models/relational_data_model_tests.py, tests/models/resource_test.py, tests/models/tile_model_tests.py, tests/permissions/permission_tests.py, tests/search/search_tests.py, tests/utils/activitystream.py, tests/utils/datatype_tests.py, tests/v3migration/v3_migration_cli_tests.py, tests/views/api_tests.py, tests/views/command_line_tests.py, tests/views/graph_manager_tests.py, tests/views/resource_tests.py, tests/views/search_tests.py
=> Add missing super() calls #10525

arches/app/media/css/components/_map.scss, arches/app/media/css/components/search/_advanced-search.scss, arches/app/media/js/views/components/search/advanced-search.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/map.htm, arches/app/templates/views/components/search/advanced-search.htm, arches/app/views/api.py, arches/urls.py
Merge 7.5.x into 7.6.x for alpha 1 release
=> 76x 75x merge

arches/__init__.py
=> Update version to 7.6.0a1

arches/app/media/css/arches.scss, arches/app/templates/views/components/coordinate-editor.htm, arches/app/templates/views/components/map-editor.htm, arches/app/templates/views/components/map-widget-editor.htm
Update dev/7.5.x with fix in dev/7.4
=> Update v75 with fix in v74

arches/management/commands/packages.py
Sorts the SQL files in the pre, post and resource view parts of the package load so they are not executed in arbitrary order
#10394
I didn't have time to run test against this change as I didn't want to change my dev core version from 7.5 to 7.6 as I'm pushing towards …
=> 10394 order sql executions

arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, tests/views/workflow_tests.py
Description included in issue.
#10538 
*   Found by: @teenorth
*   Tested by: @teenorth
=> Workflow History doesn't reload every tile #10538

arches/app/etl_modules/base_data_editor.py, arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/models/migrations/9219_divide_individual_editors.py, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm
=> adds the ability to change the preview limit for the bulk data editor

arches/app/media/js/utils/create-vue-application.js
=> updates i18n call in create-vue-application component #10566

arches/app/media/js/views/components/widgets/text.js
Fix issue where text widget would sometimes display [object object] re #10542
=> Fix issue where text box would sometimes show [object object] re #10542

arches/install/requirements.txt, releases/6.2.7.md
Updates django to latest patch release and adds fix for related resources to Bug Fixes list
=> Upgrade Django and release notes

.github/workflows/main.yml, arches/app/models/concept.py
Update 7.4.x with latest in 6.2.x
=> Update 7.4.x with latest in 6.2.x

README.md, arches/__init__.py, package.json, releases/7.4.4.md
Updates version number and adds release notes for 7.4.4
=> Updates version number and adds release notes for 7.4.4

README.md, arches/__init__.py, package.json, releases/6.2.7.md, releases/7.4.4.md, releases/7.5.1.md
Updates 7.5.x  with latest changes in 7.4.x. 
Updates version number to 7.5.1
=> Updates 7.5.x  with latest changes in 7.4.x

README.md, arches/app/etl_modules/base_data_editor.py, arches/app/media/css/arches.scss, arches/app/media/js/viewmodels/file-widget.js, arches/app/media/js/viewmodels/workflow-step.js, arches/app/media/js/viewmodels/workflow.js, arches/app/media/js/views/components/cards/photo-gallery-card.js, arches/app/media/js/views/components/etl_modules/base-bulk-string-editor.js, arches/app/media/js/views/components/widgets/text.js, arches/app/models/migrations/9219_divide_individual_editors.py, arches/app/templates/views/components/coordinate-editor.htm, arches/app/templates/views/components/etl_modules/base-bulk-string-editor.htm, arches/app/templates/views/components/map-editor.htm, arches/app/templates/views/components/map-widget-editor.htm, arches/install/requirements.txt, releases/6.2.7.md, releases/7.4.4.md, tests/views/workflow_tests.py
Updates 7.6 with latest in dev/7.5.x
=> Update 7.6 with latest in dev/7.5.x

arches/app/media/css/arches.scss
=> 10605 Fix long titles being hidden in resource editor

arches/app/tasks.py
=> Add a generic etl celery task for custom module, #10573

arches/app/templates/base.htm
Add PrimeVue stylesheet to base.htm
=> Add PrimeVue stylesheet to base.htm

arches/install/requirements.txt, releases/6.2.8.md
https://www.djangoproject.com/weblog/2024/mar/04/security-releases/
=> Bump Django to 3.2.25

arches/install/requirements.txt, releases/7.5.2.md
https://www.djangoproject.com/weblog/2024/mar/04/security-releases/
=> Bump Django to 4.2.11

arches/app/models/graph.py
on import of a graph from a json file, the sortorder of nodes is not persisted to the db
*   Found by: @apeters 
*   Tested by: @apeters
=> fix node sortoder on graph import, re #10668

package.json, releases/7.6.0.md, yarn.lock
Enables using `defineModel()` and shortcut `v-bind` syntax.
`vue-tsc` updated in https://github.com/archesproject/arches-dev-dependencies/pull/14; mentioning in release notes here.
=> Bump vue to 3.4.21

arches/install/arches-templates/project_name/webpack/webpack-utils/build-css-filepath-lookup.js, arches/install/arches-templates/project_name/webpack/webpack.common.js, arches/webpack/webpack-utils/build-css-filepath-lookup.js, arches/webpack/webpack.common.js
=> updates webpack CSS #10679

README.md
=> Update arches roadmap

arches/app/views/user.py, releases/7.5.2.md
A small change to fix a logical issue that causes #10702 in specific cases. The diff should illustrate the issue clearly (it is localized to a single for loop)
#10702 
*   Sponsored by: FPAN - HMS
*   Found by: @mradamcox 
I am unable to attempt a test suite run on the master branch at this time.
=> fix logic within identity list creation

arches/app/search/search_export.py, releases/7.6.0.md
#10699 
One way to test this PR is to override `views/search.py` in a project by simply copy/pasting everything from that view into your project view, as well as adding a new url to your project `urls.py` file like so:
```
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from my_prj.views import search
urlpatterns = [
...
re_path(r"^search$", search.SearchView.as_view(), name="search_home"),
re_path(r"^search/resources$", …
```
=> 10699 circular search

arches/install/arches-admin, arches/install/arches-project
[see this](https://community.archesproject.org/t/multipass-ubuntu-on-mac-issue-with-starting-the-first-project-archescommand-object-has-no-attribute-a-or-an/2346?u=ivancov_catalin)
#10759
*   Found by: the community
*   Tested by: @apeters
=> fix a_or_an error when creating a project or app, re #10759

arches/app/media/js/views/graph-designer.js
=> filter root ontology class by selected ontology, re #10624

.github/PULL_REQUEST_TEMPLATE.md
Per discussion at 2024 Developer Meeting.
=> Update PR template with target branch, accessibility, testing advice

.github/PULL_REQUEST_TEMPLATE.md, README.md, arches/app/datatypes/datatypes.py, arches/app/datatypes/url.py, arches/app/media/css/tree.scss, arches/app/media/js/viewmodels/node-value-select.js, arches/app/media/js/views/components/cards/photo-gallery-card.js, arches/app/media/js/views/components/widgets/text.js, arches/app/media/js/views/components/widgets/urldatatype.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/photo-workbench.htm, arches/app/templates/views/components/widgets/text.htm, arches/app/views/user.py, arches/install/requirements.txt, package.json, releases/7.5.2.md, tests/localization/field_tests.py, tests/utils/datatype_tests.py, yarn.lock
Updates 7.6.x with the latest changes in dev/7.5.x
=> Update 76 with 75

arches/app/models/migrations/9191_string_nonlocalized.py
forgot to allow for the widget placeholder to be localized, re #9191
=> allow non-localized-string widget placeholder to be localized, re #9191

arches/app/media/css/arches.scss, arches/app/templates/views/components/search/search-results.htm
Fix display of search footer when the provisional edit banner and map button are present. re #10812
=> Fix display of search results footer when buttons get crowded, re Provisional edit flag breaks search result layout  #10812

arches/app/models/concept.py, releases/7.5.2.md, releases/7.5.3.md
The query that builds the concept hierarchy was being constructed to contain an incorrect where clause (formatted with extra apostrophes). This fixes the construction of that clause so a valid hierarchy is returned. 
#9444 
*   Sponsored by: Getty Digital 
=> Fix query parameter issue preventing return of concept hierarchy #9444

arches/management/commands/updateproject.py
Ensure `gettext.config.js` is correctly interpolated with project's name on `python manage.py updateproject` command
#10849
=> adds gettext.config.js interpolation on updateproject command #10849

arches/install/requirements.txt, releases/7.6.0.md
Follow-up to ab6e009cd43c8a9fbc7856fcc85dbd050a92cf5a.
=> Remove `django-libsass` dependency

releases/7.6.0.md
=> updates 7.6.0.md for upgrading Node.js #10853

arches/app/media/js/views/rdm/modals/import-concept-form.js, arches/app/templates/views/rdm/modals/import-concept-form.htm, releases/7.5.3.md
=> update dropdown to selectwoo to fix import of sparql import of concepts

releases/7.5.2.md
=> Add changelogs for #10581

arches/app/templates/navbar/graph-designer-menu.htm, releases/7.6.0.md
Adds a space before the text of all graph Manage list entries that include span.  
Those which do not include a span tag just use html trans % which has a space before e.g. 
`<div class="menu-item-title"><i class="fa fa-trash"></i> {% trans "Delete Associated Instances" %}</div>`  includes a space between `</i>` and `{%`.
#10911 
* …
=> Add space between icon and text in graph Manage list for items that use span tag.

arches/app/utils/data_management/resources/formats/archesfile.py, releases/6.2.8.md, releases/7.5.3.md
6.2.x is sleepy these days, so just getting a headstart on getting this useful change pulled up into the more active branches.
=> 6.2.x -> 7.5.x

arches/app/etl_modules/import_single_csv.py, arches/settings.py
copy of #10382 but into `dev/7.6.x`
#10381
=> 10381 celery file size threshold

arches/app/views/graph.py, tests/views/graph_manager_tests.py
=> Fix clone published graph bug #10839

postcss.config.js, releases/7.6.0.md, yarn.lock
=> removes postcss.config.js #10902

arches/app/views/graph.py, releases/7.5.3.md, tests/views/graph_manager_tests.py
=> cherry pick fix clone graph bug #10839

arches/app/datatypes/base.py, arches/app/datatypes/datatypes.py, arches/app/media/js/viewmodels/reference-select.js, arches/app/media/js/views/components/datatypes/reference.js, arches/app/models/graph.py
Cleanup in response to @chrabyrd comments on #10569
=> Refinements to reference datatype

arches/install/arches-templates/webpack/webpack-utils/find-file.js, arches/install/arches-templates/webpack/webpack.common.js, webpack/webpack-utils/find-file.js, webpack/webpack.common.js
=> hardens webpack when finding settings.py #10970

arches/app/media/js/utils/create-vue-application.js, arches/app/templates/javascript.htm
…e archesproject#10974
To test this PR you'll have to run a project that has some string value for the setting `FORCE_SCRIPT_NAME` in `settings.py`. I have such a project that led me to this bug and although I am the PR author, I can say this fixes the bug.
#10974
*   Sponsored by: @scholiumtech
*   Found by: @whatisgalen 
*   Designed by: @whatisgalen
=> replace i18n hard-coded url with arches.urls variable

arches/app/utils/string_utils.py, tests/utils/datatype_tests.py
…0934
#10934
*   Sponsored by: @scholiumtech
*   Found by: @whatisgalen 
*   Designed by: @whatisgalen
=> Fix for boolean datatype validation

arches/app/media/js/views/graph-designer.js, arches/app/templates/javascript.htm, arches/app/views/graph.py, tests/views/graph_manager_tests.py
=> adds redirect for editable_future_graph access to graph_designer #10967

arches/app/views/api.py, releases/6.2.8.md, tests/search/search_export_tests.py
Fix basic HTTP authorization via search export GET #10986
- Fix attribute error
- Return 401 if bad creds used
Closes #10986
Feel free to cherry-pick this onto 7.6 if easier to test.
=> Fix basic HTTP authorization via search export GET #10986

arches/install/arches-templates/project_name/settings.py-tpl, releases/7.6.0.md
Update the order of the items in the LOCALE_PATHS list.
Fix the issue with creating .po files in the core arches.
#10960 
=> Update locale paths, #10960

.pre-commit-config.yaml, arches/install/arches-templates/.pre-commit-config.yaml, arches/install/arches-templates/eslint.config.mjs, eslint.config.mjs
Reduces drift in configuration of precommit and package.json scripts
Closes #
| …
=> Only check project src directory on precommit

arches/app/media/css/accessibility.scss
When accessibility mode is on, and any left nav item that has subitems, extra arrows are displayed.
Closes #11031 
*   Tested by: @phudson-he 
=> Fix extra subitem arrows

arches/app/models/resource.py
`get_nodegroups_by_perm` now returns IDs, so filter tiles by nodegroup_id, not nodegroup when loading.
Closes #
| …
=> Update tile filtering for nodegroup ID

package-lock.json, package.json
see conversation in https://github.com/archesproject/arches/issues/10828
Closes #11039
| ---------------- | ------- | …
=> reverts ckeditor dependency #11039

arches/__init__.py, package.json
Updates version number for 6.2.8 patch release
=> Update version number to 6.2.8

arches/app/templates/email/download_ready_email_notification.htm, arches/install/arches-templates/project_name/templates/email/download_ready_email_notification.htm
Move the {% if link =! "" %} section outside of the {% if files %} section so that this part of the template works whether or not files are within the context
#11099 
Also related to https://github.com/archesproject/arches-her/issues/1233
*   Sponsored by: …
=> 11099 download ready email

arches/app/models/resource.py, tests/models/resource_test.py
Fix issue where provisional editor id is null
=> Catch error when creatorid is ''

arches/app/media/js/views/components/workflows/workflow-component-abstract.js
In multi card step, the re-population now handles non-observables (as produced with regard to the internationalized structure of the string node)
#10861 
*   Found by: @csmith-he
*   Tested by: @csmith-he
This was going to …
=> #10861 Multi Card Workflow Component and String Structure

arches/install/arches-templates/tests/search_indexes/sample_index_tests.py-tpl, arches/install/arches-templates/tests/test_settings.py-tpl
fixes some discrepancies when running the python test runner in a project.
Closes #11115 
| ---------------- | ------- | …
=> fixes project tests #11115

arches/app/datatypes/datatypes.py, arches/app/utils/geo_utils.py, releases/7.6.0.md, tests/utils/datatype_tests.py
This allows geometries to be created if they are larger than the 32k Lucene index document limit.
Closes #11080 
| …
=> 11080 chunk es geometries

arches/app/media/js/models/card-widget.js
Handle for empty widget object in workflows
Closes #11111
=> Handle for empty widget object in workflows #11111

arches/app/media/js/utils/load-component-dependencies.js, arches/settings_utils.py
Fixes staticfile dependency order
Closes #11146 
| Color contrast   |         | …
=> fixes staticfile dependency order #11146

arches/app/media/js/models/card-widget.js, arches/app/media/js/utils/load-component-dependencies.js, arches/settings_utils.py
=> Update 7.6.x with 7.5.x

arches/settings_utils.py, releases/7.6.0.md
=> Hardens build_staticfiles_dirs #11149

arches/settings_utils.py
Reverts `build_staticfiles_dirs` hardening
Closes #
| Color contrast   | …
=> reverts `build_staticfiles_dirs`  hardening #11151

arches/install/requirements.txt
=> Raise lower bound on Django to 4.2.14

arches/app/etl_modules/bulk_edit_concept.py, arches/app/media/js/views/components/etl_modules/bulk_edit_concept.js, arches/app/tasks.py, arches/app/templates/views/components/etl_modules/bulk_edit_concept.htm
incorporation of bulk concept edit script
A bulk edit script for concept was created. Initially the script finds all the concepts from each model. Then the user chooses which concept he wants to replace and with which one. Also in the front-end a new function was added if a resource does not need a concept change the user can remove it in so that the concept for that resource is not changed.
Closes #
- [x ] dev/7.6.x (under development): features, bugfixes not covered below
-   [ …
=> incorporation of bulk concept edit script

arches/app/media/js/views/components/widgets/urldatatype.js, releases/7.5.3.md
- also handles preview when url is falsey
When a UrlDatatype widget is part of a multi-card step of a workflow, the `url` and `url_label` input boxes don't clear when adding and editing the data.
This lead to confusion when trying to create an edit data in the workflows.
Closes #11136 
-   [ ] My …
=> Fixes bug stopping Url datatype widget input boxes updating when adding and editing in multi-card workflow step

arches/app/media/js/utils/load-component-dependencies.js
Fixes load-component-dependencies
Closes #11163
| Color contrast   |         | …
=> Fixes load component dependencies #11163

arches/app/media/css/arches.scss, arches/app/media/css/components/_buttons.scss, arches/app/media/js/utils/load-component-dependencies.js, arches/app/media/js/views/components/widgets/urldatatype.js, arches/app/search/search_export.py, releases/7.5.3.md
=> Updates dev/7.6.x with dev/7.5.x

arches/install/arches-templates/webpack/webpack.common.js, webpack/webpack.common.js
=> hardens webpack messaging #11169

arches/app/media/js/viewmodels/map.js, releases/7.6.0.md
Fixes issue where geocoder placeholder translation in javascript.htm was not being populated in the mapbox geocoder text box 
Closes #11173 
-   I targeted one of these branches: (This should also probably go into dev/7.5.x)
n/a
| ---------------- | …
=> 11173 - Fix geocoder placeholder value

arches/app/media/js/viewmodels/map.js, releases/7.5.3.md
Fixes geocoder placeholder string. Cherry pick from #11174
Closes #11173 
=> Fixes geocoder placeholder string - cherry pick from #11174

README.md, arches/__init__.py, package.json, releases/7.5.3.md
Update version number to latest patch release (7.5.3). Also corrects the release cadence in README.md from 6 to 9 months.
=> Update 7.5.3 version number

README.md, arches/__init__.py, package.json, releases/7.5.4.md
=> Update to 7.5.x beta version

arches/management/commands/updateproject.py
=> hardens updateproject #11181

arches/app/media/css/arches.scss
=> fixes sass deprecation warnings #11183

arches/webpack/webpack-utils/build-filepath-lookup.js
Follow-up to 37cd4c3.
I only fixed the app template, not core 😓
=> Also ignore dotfiles in core arches webpack config #11094

README.md, arches/install/arches-templates/webpack/webpack-utils/build-filepath-lookup.js, releases/7.5.4.md, webpack/webpack-utils/build-filepath-lookup.js
Updates 7.6.x with latest fixes in 7.5.x
=> Update 76x with 75x 20240718 1022

arches/app/permissions/arches_standard.py, arches/app/views/search.py
Displays edit link in search results if user has edit permissions on an instance.
Closes #11213
| ---------------- | …
=> Fix logic that sets edit link visibility #11213

arches/app/models/models.py, arches/app/models/utils.py, arches/app/permissions/arches_standard.py, arches/app/views/search.py, releases/7.6.0.md
=> Cbyrd update 8.0.x with 7.6

arches/app/views/api.py
Not cast uuid to str to check nodegroup permission, #11126
Closes #11126 
| …
=> Not cast uuid to str to check nodegroup permission, #11126

arches/install/arches-templates/tests/test_settings.py-tpl
The template for project test settings was importing from core arches settings, thus skipping project-level settings e.g. INSTALLED_APPS and (project) settings_local.py
Suggest testing a project with the project's own settings to reduce surprises during deployment, and only apply minimal test settings overrides mostly for dealing with the file system.
Closes #11229
-   [ ] I …
=> Reduce drift between test settings and project settings #11229

arches/app/templates/base-root.htm, arches/app/templates/base.htm
=> Fixes double body tag render #11237

arches/app/media/js/views/search.js, releases/6.2.9.md
Cleans markup from search query strings
=> Clean markup from filter strings

arches/app/media/css/sidenav.scss
Fixes an issue where using a device with a smaller screen height, the expanded left nav cannot be scrolled to all menu items.
Was looking like this...
...now looks like this...
Closes #11185 
* …
=> Fix for left nav scrolling

arches/app/media/css/components/_buttons.scss
Fix ensures that the map filter buttons do not appear over the top of the dropdown selection boxes.
Fix works as expected...
Closes #11187 
*   Tested by: @phudson-he 
=> Fix overlapping issues

arches/app/media/css/arches.scss
When viewing the search results on devices with a smaller screen height, the pagination links were not visible and cant be scrolled to. This was due to a css flex value which wouldn't allow the container to shrink. This fix allows the container to shrink if needed. The other cross browser flex values were also changed accordingly to match.
Was looking like this...
...and now looks like this...
Closes #10994 
-   [ ] Unit …
=> Allow search control container to shrink if needed on smaller devices

arches/management/commands/updateproject.py
=> Fix typo that prevents project_name from interpolating

releases/7.5.4.md
Updates changelog with recent merges
=> Add release note entries for recent PRs

.github/actions/build-and-test-branch/action.yml, .github/workflows/main.yml
=> fixes GH test runner branch pollution #11251

README.md, arches/__init__.py, package.json
Update version number to 6.2.9
=> Update version number to 6.2.9

arches/app/templates/arches_urls.htm
=> fixes arches_urls update from previous merge

arches/app/utils/geo_utils.py, releases/7.6.0.md, tests/utils/test_geo_utils.py
Fixes hard coded geom type in geo_utils.convert_multipart_to_singlepart
Closes #11218
| ---------------- | ------- | …
=> Fix hard coded geom type in multipart to single part util, #11218

arches/install/arches-templates/.coveragerc, releases/7.6.0.md
Polish 7.6 app template for coverage ignores and upgrade instructions.
=> Advise on order of `INSTALLED_APPS`

arches/management/commands/updateproject.py
=> Fix updateproject after declarations.d.ts template moved

arches/app/templates/arches_urls.htm
=> updates arches_urls to remove pollution from dirty merge #11280

arches/settings_utils.py
=> report creation of files in `generate_frontend_configuration` #11286

arches/management/commands/packages.py, releases/8.0.0.md
=> [8.0] Remove `-o install` operation

arches/apps.py, arches/install/arches-templates/project_name/apps.py-tpl, arches/install/arches-templates/webpack/webpack.common.js, webpack/webpack.common.js
=> updates webpack to manually point to tsconfig file #11295

arches/settings_utils.py
=> removes _move_to_end_of_sys_path #11297

arches/app/models/migrations/0005_4_0_1.py, arches/app/models/migrations/0010_4_1_0.py, tests/search/search_tests.py
-   [x] Unit test
Adds a unit test for testing terms
Closes #11301
=> Add test for term search

releases/7.6.0.md
Release notes update to mention file permissions on new frontend files.
=> include note about file permissions needed for frontend build

arches/install/arches-templates/vitest.setup.mts, arches/install/arches_admin.py, arches/install/arches_project.py, arches/management/commands/updateproject.py
=> Namespace declarations import in project vitest config #11292

arches/install/arches-templates/vitest.config.mts, arches/install/arches_admin.py, arches/install/arches_project.py, arches/management/commands/updateproject.py
=> fixes project frontend test coverage #11328

arches/app/templates/arches_urls.htm, arches/app/views/api/user.py, arches/urls.py, tests/views/api/test_user.py
Follow-up to #11284. Allow retrieving the current user so that page refreshes or redirects (e.g. from the arches login form for multi-factor authentication) don't unnecessarily route to a login page.
Refs #11261 …
=> Add `UserView.get()` to retrieve logged-in user details re #11261

arches/app/media/js/viewmodels/map-editor.js, arches/app/templates/javascript.htm, arches/app/templates/views/components/map-widget-editor.htm, package.json, releases/7.6.0.md
Adds support for Shapefile import in map editor widget
Adds the ShpJS library and uses it to support importing of geometries in Shapefile. Supports import of .shp and .zip files.
Closes #11339
[Developer …
=> 11339 import shapefile

arches/app/templates/base-root.htm, arches/app/templates/base.htm
=> removes scroll-y-auto from base-root #11344

arches/install/arches-templates/vitest.config.mts, vitest.config.mts
See passing [run](https://github.com/archesproject/arches/actions/runs/10458675867/job/28961020491)
=> Exclude theme files from vitest coverage

arches/app/templates/base-root.htm, package-lock.json, package.json, releases/7.6.0.md
=> adds normalize.css for standalone Vue components #11338

arches/app/media/css/arches.scss, arches/app/templates/base-root.htm, package-lock.json, package.json, releases/8.0.0.md
This adds support for primeicons
To test:
1. Checkout this branch
2. In a project, either point to this branch in `package.json` for the arches dependency, or manually the the `primeicons` dependency.
3. Set up a Vue application, or use an already-existing one
4. Render an icon with `<i class="pi pi-${something}></i>`
5. Notice the icon renders
=> adds primeicons #11356

tests/models/spatialview_model_tests.py, tests/views/spatialview_api_tests.py
=> need to index required concepts in spatial tests, re #11354

arches/management/commands/updateproject.py
Fixes test discovery
Closes #11388
=> Remove outermost `__init__.py` #11388

arches/app/search/components/base_search_view.py, arches/app/search/components/standard_search_view.py, arches/app/views/search.py, tests/views/search_tests.py
=> return dsl unserialized, re #11386

arches/install/arches-templates/vitest.config.mts, arches/install/arches-templates/vitest.setup.mts, vitest.config.mts, vitest.setup.mts
=> updates vitest to handle arches mock #11373

arches/management/commands/updateproject.py
=> reconcile placeholder args in apps.py when running the `updateproject` command, re #11304

arches/install/arches-templates/project_name/settings.py-tpl, arches/settings.py, releases/7.6.0.md
Enable clickjacking protection from Django.
=> Enable clickjacking protection middleware

releases/7.6.0.md
=> Flesh out release note re #11305

.github/workflows/main.yml, arches/app/models/migrations/11042_add_resource_instance_lifecycle.py, arches/app/models/models.py, arches/app/permissions/arches_standard.py, arches/app/views/workflow_history.py, arches/apps.py, arches/install/arches-templates/.github/workflows/main.yml, arches/install/arches-templates/pyproject.toml, arches/management/commands/load_jsonld.py, pyproject.toml, releases/8.0.0.md
Require Django 5.1.x and Python 3.11+.
[5.0 release notes](https://docs.djangoproject.com/en/5.0/releases/5.0/)
[5.1 release notes](https://docs.djangoproject.com/en/5.1/releases/5.1/)
We don't appear to be impacted by any breaking changes. I replaced one deprecated argument name in `CheckConstraint`, that's all. (I also took the opportunity to rewrite a `get_or_create()` as `update_or_create()` with `create_defaults` as I'd been waiting to do.)
Closes #
-   [ ] I submitted a PR …
=> Require Python 3.11+ and Django 5.1

arches/app/search/components/base_search_view.py, arches/app/search/components/standard_search_view.py
=> 11409 base search refactor

arches/app/utils/date_utils.py, releases/7.5.4.md
Prevents search from failing on dates before -9999 or after 9999.
Closes #11419
=> Search on years before -9999 and after 9999

arches/install/arches-templates/webpack/webpack.common.js, webpack/webpack.common.js
=> updates webpack to handle external library css #11433

arches/app/models/models.py, tests/models/spatialview_model_tests.py
Adds a error handling to spatialviews model clean() for the attributenodes value.
Closes #11429
| ---------------- | …
=> Fix spatialview django validation error when attributenodes is not a list of node objects

arches/app/media/css/arches.scss, arches/app/templates/base-root.htm, package-lock.json, package.json
=> adds primeicons #11436

arches/app/src/arches/declarations.d.ts, arches/settings_utils.py
=> loosens tsconfig pathing #11422

arches/install/arches_admin.py, arches/install/arches_project.py, arches/settings.py, tests/fixtures/testing_prj/testing_prj/settings.py, tests/search/search_export_tests.py
Since Django 3.2, Django will attempt to detect insecure SECRET_KEY values, by sniffing for whether they start with `django-insecure-` and thus have never been rotated.
This check is already part of the system checks for security we recently documented in the docs repo and the upgrade instructions:
https://github.com/archesproject/arches/blob/c6b043ae0357892f25f1c143daadde1162ff4e19/releases/7.6.0.md?plain=1#L392-L396
With this change:
>  ?: (security.W009) Your SECRET_KEY has less than 50 characters, less than 5 unique characters, or it's prefixed with …
=> Mark `SECRET_KEY` templates as insecure

arches/management/commands/updateproject.py
Follow-up to 10b90d5. Creates the missing files on an `updateproject` call identified in #11285.
Closes #11285
*   Found by: @apeters
=> Fix updateproject check for existing TS declarations #11285

arches/app/media/js/bindings/term-search.js
When the `term-filter` is used to include search terms, the ko.observableArray `terms` gets a new `term` object but the ko.observableArray `tags` does not. The logic in the term-search binding only updates the selectWoo UI when `tags` gets updated, not `terms` (unless a user individually clicks "x" on the term, or the ensuing query updates the term-filter state). This PR adds a subscription to `terms` to update (empty) the selectWoo if there are neither tags nor terms.
Closes #11443 
-   [ ] I added a changelog in …
=> Fix term-filter.clear method #11443

arches/app/media/css/arches.scss
Prevents CKEditor warning from appearing over rich-text editor input. Stop-gap measure until CKEditor is replaced per #10828
=> Prevent ckeditor message from blocking input

arches/app/utils/data_management/resources/formats/rdffile.py
Fixes issue with missing gettext import in rdffile.py
=> Add missing import

arches/app/search/components/term_filter.py
This fixes a default value for querystring in the term filter. It gets json decoded and an empty string returns an error.
However there's likely also an issue somewhere in a test. There shouldn't be a term filter instance without that querystring parameter -- somehow a query object in a search test is getting something like: `"term-filter": None` which should not be happening (unless we're explicitly testing for a negative case but I don't think we are)
Closes #11475 
-   [ ] I …
=> 11475 term filter q string

arches/app/media/js/views/components/plugins/etl-manager.js, arches/app/templates/views/components/plugins/etl-manager.htm, arches/app/views/etl_manager.py, releases/7.6.0.md, tests/views/etl_manager_tests.py
Calculate user display name on backend.
Return 302 Forbidden instead of 403 redirect to auth page, as this view is called by an AJAX client.
-   [x] I submitted a PR to arches-docs (if appropriate)
=> Avoid serializing user information in ETLManagerView.get()

arches/app/search/components/standard_search_view.py, tests/views/search_tests.py
Ensures total hits are included in resource search results #11466
Closes #11466 …
=> Ensure total is included in resource search results

arches/app/media/js/views/graph-designer.js, releases/7.6.0.md
Prevent broken requests to the help template view from adding 500 responses to error logs.
Closes #11478
=> Fix nuisance failing requests to help template view #11478

arches/app/models/tile.py, releases/7.5.5.md
Closes archesproject/arches-her#1343
| …
=> Cast nodegroupid to string for check w/ serialized graph

arches/app/media/css/arches.scss, arches/app/media/css/components/_buttons.scss, arches/app/media/css/sidenav.scss, arches/app/templates/views/components/widgets/file.htm, arches/app/utils/date_utils.py, releases/7.5.5.md
Updates 7.6 with recent changes in 7.5
=> Updates 7.6 with recent changes in 7.5

README.md, arches/__init__.py, package.json
=> Update version to 7.5.5

arches/app/models/resource.py, releases/7.6.0.md, tests/models/resource_test.py
Resources weren't being deleted from custom indexes when operating in bulk.
Closes #10872
*   Sponsored by: GCI
=> Delete from custom indexes when bulk deleting resources #10872

arches/install/arches_project.py, releases/7.6.0.md
Start on a path to removing duplication between `arches-project` (deprecated) and `arches-admin` (survivor).
Closes #11038
-   [x] I submitted a PR to arches-docs (if appropriate)
*   Found by: @chrabyrd
Expected to slightly degrade test coverage, but it would be very cumbersome and low …
=> Deprecate `arches-project create` #11038

arches/__init__.py, releases/7.6.0.md
Prepares 7.6.0 for release - updates version number, formats release notes
=> 760 release prep

README.md, arches/__init__.py, package.json
Updates version number and removes outdated roadmap entry in prep for 7.6.1 release
=> 761 release prep

releases/7.6.1.md
Revise upgrade instructions to minimum steps
=> Simplfy upgrade instructions

arches/app/datatypes/datatypes.py, arches/app/models/tile.py, arches/app/views/api/__init__.py, releases/8.0.0.md
UserProfiles always exist since #8022.
1ca5c32 removed some cruft guards for missing profiles. This removes the rest, which makes it more clear that these GETs do not have side-effects (and thus CSRF attack vectors).
Closes #10664
=> Remove (hypothetical) side effects from GET calls #10664

.github/actions/build-and-test-branch/action.yml, arches/app/models/models.py, arches/app/utils/index_database.py, arches/install/arches-templates/.github/actions/build-and-test-branch/action.yml, arches/management/commands/graph.py, arches/management/commands/setup_db.py, releases/8.0.0.md, tests/utils/test_checks.py
Helpfully fail with a system check and a hint if adding system languages without having republished graphs yet.
Closes #10079
=> Add check for published graph in every system language #10079
